#
# Autogenerated by generate-bytecode-expectations.
#

---
wrap: no
test function name: f

---
snippet: "
  async function* f() { }
  f();
"
frame size: 9
parameter count: 1
bytecode array length: 131
bytecodes: [
                B(SwitchOnGeneratorState), R(0), U8(0), U8(1),
                B(Mov), R(closure), R(1),
                B(Mov), R(this), R(2),
  /*   17 E> */ B(InvokeIntrinsic), U8(Runtime::k_CreateJSGeneratorObject), R(1), U8(2),
                B(Star0),
                B(LdaTheHole),
                B(Star3),
                B(Mov), R(context), R(4),
                B(Mov), R(context), R(5),
                B(Ldar), R(0),
  /*   17 E> */ B(SuspendGenerator), R(0), R(0), U8(6), U8(0),
                B(ResumeGenerator), R(0), R(0), U8(6),
                B(Star6),
                B(InvokeIntrinsic), U8(Runtime::k_GeneratorGetResumeMode), R(0), U8(1),
                B(SwitchOnSmiNoFeedback), U8(1), U8(3), I8(0),
                B(Ldar), R(6),
  /*   17 E> */ B(ReThrow),
                B(Ldar), R(6),
  /*   17 E> */ B(Throw),
                B(LdaSmi), I8(1),
                B(Star1),
                B(Mov), R(6), R(2),
                B(Jump), U8(44),
                B(LdaUndefined),
                B(Star2),
                B(LdaSmi), I8(1),
                B(Star1),
                B(Jump), U8(37),
                B(Star6),
                B(CreateCatchContext), R(6), U8(4),
                B(Star5),
                B(LdaTheHole),
                B(SetPendingMessage),
                B(Ldar), R(5),
                B(PushContext), R(6),
                B(LdaImmutableCurrentContextSlot), U8(2),
                B(Star8),
                B(Mov), R(0), R(7),
                B(InvokeIntrinsic), U8(Runtime::k_AsyncGeneratorReject), R(7), U8(2),
                B(PopContext), R(6),
                B(Star2),
                B(LdaSmi), I8(2),
                B(Star1),
                B(Jump), U8(8),
                B(Star2),
                B(LdaZero),
                B(Star1),
                B(LdaTheHole),
                B(SetPendingMessage),
                B(Star3),
                B(InvokeIntrinsic), U8(Runtime::k_GeneratorClose), R(0), U8(1),
                B(Ldar), R(1),
                B(SwitchOnSmiNoFeedback), U8(5), U8(3), I8(0),
                B(Ldar), R(3),
                B(SetPendingMessage),
                B(Ldar), R(2),
                B(ReThrow),
                B(LdaTrue),
                B(Star7),
                B(Mov), R(0), R(5),
                B(Mov), R(2), R(6),
                B(InvokeIntrinsic), U8(Runtime::k_AsyncGeneratorResolve), R(5), U8(3),
                B(Return),
                B(Ldar), R(2),
                B(Return),
]
constant pool: [
  Smi [30],
  Smi [18],
  Smi [10],
  Smi [7],
  SCOPE_INFO_TYPE,
  Smi [4],
  Smi [10],
  Smi [23],
]
handlers: [
  [20, 93, 93],
  [23, 64, 64],
]

---
snippet: "
  async function* f() { yield 42 }
  f();
"
frame size: 9
parameter count: 1
bytecode array length: 173
bytecodes: [
                B(SwitchOnGeneratorState), R(0), U8(0), U8(2),
                B(Mov), R(closure), R(1),
                B(Mov), R(this), R(2),
  /*   17 E> */ B(InvokeIntrinsic), U8(Runtime::k_CreateJSGeneratorObject), R(1), U8(2),
                B(Star0),
                B(LdaTheHole),
                B(Star3),
                B(Mov), R(context), R(4),
                B(Mov), R(context), R(5),
                B(Ldar), R(0),
  /*   17 E> */ B(SuspendGenerator), R(0), R(0), U8(6), U8(0),
                B(ResumeGenerator), R(0), R(0), U8(6),
                B(Star6),
                B(InvokeIntrinsic), U8(Runtime::k_GeneratorGetResumeMode), R(0), U8(1),
                B(SwitchOnSmiNoFeedback), U8(2), U8(3), I8(0),
                B(Ldar), R(6),
  /*   17 E> */ B(ReThrow),
                B(Ldar), R(6),
  /*   17 E> */ B(Throw),
                B(LdaSmi), I8(1),
                B(Star1),
                B(Mov), R(6), R(2),
                B(Jump), U8(86),
  /*   22 S> */ B(LdaSmi), I8(42),
                B(Star7),
                B(Mov), R(0), R(6),
                B(InvokeIntrinsic), U8(Runtime::k_AsyncGeneratorYieldWithAwait), R(6), U8(2),
  /*   22 E> */ B(SuspendGenerator), R(0), R(0), U8(6), U8(1),
                B(ResumeGenerator), R(0), R(0), U8(6),
                B(Star6),
                B(InvokeIntrinsic), U8(Runtime::k_GeneratorGetResumeMode), R(0), U8(1),
                B(SwitchOnSmiNoFeedback), U8(5), U8(3), I8(0),
                B(Ldar), R(6),
  /*   22 E> */ B(ReThrow),
                B(Ldar), R(6),
  /*   22 E> */ B(Throw),
                B(LdaSmi), I8(1),
                B(Star1),
                B(Mov), R(6), R(2),
                B(Jump), U8(44),
                B(LdaUndefined),
                B(Star2),
                B(LdaSmi), I8(1),
                B(Star1),
                B(Jump), U8(37),
                B(Star6),
                B(CreateCatchContext), R(6), U8(8),
                B(Star5),
                B(LdaTheHole),
                B(SetPendingMessage),
                B(Ldar), R(5),
                B(PushContext), R(6),
                B(LdaImmutableCurrentContextSlot), U8(2),
                B(Star8),
                B(Mov), R(0), R(7),
                B(InvokeIntrinsic), U8(Runtime::k_AsyncGeneratorReject), R(7), U8(2),
                B(PopContext), R(6),
                B(Star2),
                B(LdaSmi), I8(2),
                B(Star1),
                B(Jump), U8(8),
                B(Star2),
                B(LdaZero),
                B(Star1),
                B(LdaTheHole),
                B(SetPendingMessage),
                B(Star3),
                B(InvokeIntrinsic), U8(Runtime::k_GeneratorClose), R(0), U8(1),
                B(Ldar), R(1),
                B(SwitchOnSmiNoFeedback), U8(9), U8(3), I8(0),
                B(Ldar), R(3),
                B(SetPendingMessage),
                B(Ldar), R(2),
                B(ReThrow),
                B(LdaTrue),
                B(Star7),
                B(Mov), R(0), R(5),
                B(Mov), R(2), R(6),
                B(InvokeIntrinsic), U8(Runtime::k_AsyncGeneratorResolve), R(5), U8(3),
                B(Return),
                B(Ldar), R(2),
                B(Return),
]
constant pool: [
  Smi [30],
  Smi [72],
  Smi [18],
  Smi [10],
  Smi [7],
  Smi [18],
  Smi [10],
  Smi [7],
  SCOPE_INFO_TYPE,
  Smi [4],
  Smi [10],
  Smi [23],
]
handlers: [
  [20, 135, 135],
  [23, 106, 106],
]

---
snippet: "
  async function* f() { for (let x of [42]) yield x }
  f();
"
frame size: 19
parameter count: 1
bytecode array length: 311
bytecodes: [
                B(SwitchOnGeneratorState), R(0), U8(0), U8(2),
                B(Mov), R(closure), R(4),
                B(Mov), R(this), R(5),
  /*   17 E> */ B(InvokeIntrinsic), U8(Runtime::k_CreateJSGeneratorObject), R(4), U8(2),
                B(Star0),
                B(LdaTheHole),
                B(Star6),
                B(Mov), R(context), R(7),
                B(Mov), R(context), R(8),
                B(Ldar), R(0),
  /*   17 E> */ B(SuspendGenerator), R(0), R(0), U8(9), U8(0),
                B(ResumeGenerator), R(0), R(0), U8(9),
                B(Star9),
                B(InvokeIntrinsic), U8(Runtime::k_GeneratorGetResumeMode), R(0), U8(1),
                B(SwitchOnSmiNoFeedback), U8(2), U8(3), I8(0),
                B(Ldar), R(9),
  /*   17 E> */ B(ReThrow),
                B(Ldar), R(9),
  /*   17 E> */ B(Throw),
                B(LdaSmi), I8(1),
                B(Star4),
                B(Mov), R(9), R(5),
                B(Jump), U8(224),
  /*   36 S> */ B(CreateArrayLiteral), U8(5), U8(0), U8(37),
                B(Star11),
                B(GetIterator), R(11), U8(1), U8(3),
                B(Star10),
                B(GetNamedProperty), R(10), U8(6), U8(5),
                B(Star9),
                B(LdaFalse),
                B(Star11),
                B(LdaTheHole),
                B(Star14),
                B(Mov), R(context), R(15),
                B(LdaTrue),
                B(Star11),
  /*   31 S> */ B(CallProperty0), R(9), R(10), U8(7),
                B(Star), R(16),
                B(JumpIfJSReceiver), U8(7),
                B(CallRuntime), U16(Runtime::kThrowIteratorResultNotAnObject), R(16), U8(1),
                B(GetNamedProperty), R(16), U8(7), U8(9),
                B(JumpIfToBooleanTrue), U8(65),
                B(GetNamedProperty), R(16), U8(8), U8(11),
                B(Star), R(16),
                B(LdaFalse),
                B(Star11),
                B(Mov), R(16), R(1),
  /*   31 S> */ B(Mov), R(1), R(3),
  /*   42 S> */ B(Mov), R(0), R(16),
                B(Mov), R(3), R(17),
                B(InvokeIntrinsic), U8(Runtime::k_AsyncGeneratorYieldWithAwait), R(16), U8(2),
  /*   42 E> */ B(SuspendGenerator), R(0), R(0), U8(16), U8(1),
                B(ResumeGenerator), R(0), R(0), U8(16),
                B(Star), R(16),
                B(InvokeIntrinsic), U8(Runtime::k_GeneratorGetResumeMode), R(0), U8(1),
                B(SwitchOnSmiNoFeedback), U8(9), U8(3), I8(0),
                B(Ldar), R(16),
  /*   42 E> */ B(ReThrow),
                B(Ldar), R(16),
  /*   42 E> */ B(Throw),
                B(LdaSmi), I8(1),
                B(Star12),
                B(Mov), R(16), R(13),
                B(Jump), U8(20),
                B(Ldar), R(16),
  /*   22 E> */ B(JumpLoop), U8(80), I8(0), U8(13),
                B(LdaSmi), I8(-1),
                B(Star13),
                B(Star12),
                B(Jump), U8(8),
                B(Star13),
                B(LdaZero),
                B(Star12),
                B(LdaTheHole),
                B(SetPendingMessage),
                B(Star14),
                B(Ldar), R(11),
                B(JumpIfToBooleanTrue), U8(38),
                B(Mov), R(context), R(16),
                B(GetNamedProperty), R(10), U8(12), U8(14),
                B(JumpIfUndefinedOrNull), U8(29),
                B(Star), R(17),
                B(CallProperty0), R(17), R(10), U8(16),
                B(JumpIfJSReceiver), U8(21),
                B(Star), R(18),
                B(CallRuntime), U16(Runtime::kThrowIteratorResultNotAnObject), R(18), U8(1),
                B(Jump), U8(12),
                B(Star), R(16),
                B(LdaZero),
                B(TestReferenceEqual), R(12),
                B(JumpIfTrue), U8(5),
                B(Ldar), R(16),
                B(ReThrow),
                B(Ldar), R(12),
                B(SwitchOnSmiNoFeedback), U8(13), U8(2), I8(0),
                B(Jump), U8(16),
                B(Ldar), R(14),
                B(SetPendingMessage),
                B(Ldar), R(13),
                B(ReThrow),
                B(LdaSmi), I8(1),
                B(Star4),
                B(Mov), R(13), R(5),
                B(Jump), U8(44),
                B(LdaUndefined),
                B(Star5),
                B(LdaSmi), I8(1),
                B(Star4),
                B(Jump), U8(37),
                B(Star9),
                B(CreateCatchContext), R(9), U8(15),
                B(Star8),
                B(LdaTheHole),
                B(SetPendingMessage),
                B(Ldar), R(8),
                B(PushContext), R(9),
                B(LdaImmutableCurrentContextSlot), U8(2),
                B(Star11),
                B(Mov), R(0), R(10),
                B(InvokeIntrinsic), U8(Runtime::k_AsyncGeneratorReject), R(10), U8(2),
                B(PopContext), R(9),
                B(Star5),
                B(LdaSmi), I8(2),
                B(Star4),
                B(Jump), U8(8),
                B(Star5),
                B(LdaZero),
                B(Star4),
                B(LdaTheHole),
                B(SetPendingMessage),
                B(Star6),
                B(InvokeIntrinsic), U8(Runtime::k_GeneratorClose), R(0), U8(1),
                B(Ldar), R(4),
                B(SwitchOnSmiNoFeedback), U8(16), U8(3), I8(0),
                B(Ldar), R(6),
                B(SetPendingMessage),
                B(Ldar), R(5),
                B(ReThrow),
                B(LdaTrue),
                B(Star10),
                B(Mov), R(0), R(8),
                B(Mov), R(5), R(9),
                B(InvokeIntrinsic), U8(Runtime::k_AsyncGeneratorResolve), R(8), U8(3),
                B(Return),
                B(Ldar), R(5),
                B(Return),
]
constant pool: [
  Smi [30],
  Smi [129],
  Smi [18],
  Smi [10],
  Smi [7],
  ARRAY_BOILERPLATE_DESCRIPTION_TYPE,
  INTERNALIZED_ONE_BYTE_STRING_TYPE ["next"],
  INTERNALIZED_ONE_BYTE_STRING_TYPE ["done"],
  INTERNALIZED_ONE_BYTE_STRING_TYPE ["value"],
  Smi [18],
  Smi [10],
  Smi [7],
  INTERNALIZED_ONE_BYTE_STRING_TYPE ["return"],
  Smi [6],
  Smi [12],
  SCOPE_INFO_TYPE,
  Smi [4],
  Smi [10],
  Smi [23],
]
handlers: [
  [20, 273, 273],
  [23, 244, 244],
  [79, 163, 169],
  [182, 203, 205],
]

---
snippet: "
  function* g() { yield 42 }
  async function* f() { yield* g() }
  f();
"
frame size: 18
parameter count: 1
bytecode array length: 425
bytecodes: [
                B(SwitchOnGeneratorState), R(0), U8(0), U8(5),
                B(Mov), R(closure), R(1),
                B(Mov), R(this), R(2),
  /*   44 E> */ B(InvokeIntrinsic), U8(Runtime::k_CreateJSGeneratorObject), R(1), U8(2),
                B(Star0),
                B(LdaTheHole),
                B(Star3),
                B(Mov), R(context), R(4),
                B(Mov), R(context), R(5),
                B(Ldar), R(0),
  /*   44 E> */ B(SuspendGenerator), R(0), R(0), U8(6), U8(0),
                B(ResumeGenerator), R(0), R(0), U8(6),
                B(Star6),
                B(InvokeIntrinsic), U8(Runtime::k_GeneratorGetResumeMode), R(0), U8(1),
                B(SwitchOnSmiNoFeedback), U8(5), U8(3), I8(0),
                B(Ldar), R(6),
  /*   44 E> */ B(ReThrow),
                B(Ldar), R(6),
  /*   44 E> */ B(Throw),
                B(LdaSmi), I8(1),
                B(Star1),
                B(Mov), R(6), R(2),
                B(JumpConstant), U8(19),
  /*   49 S> */ B(LdaGlobal), U8(8), U8(0),
                B(Star10),
  /*   56 E> */ B(CallUndefinedReceiver0), R(10), U8(2),
                B(Star11),
                B(GetNamedProperty), R(11), U8(9), U8(4),
                B(JumpIfUndefinedOrNull), U8(14),
                B(Star12),
                B(CallProperty0), R(12), R(11), U8(6),
                B(JumpIfJSReceiver), U8(21),
                B(CallRuntime), U16(Runtime::kThrowSymbolAsyncIteratorInvalid), R(0), U8(0),
                B(GetNamedProperty), R(11), U8(10), U8(8),
                B(Star12),
                B(CallProperty0), R(12), R(11), U8(10),
                B(Star12),
                B(InvokeIntrinsic), U8(Runtime::k_CreateAsyncFromSyncIterator), R(12), U8(1),
                B(Star8),
                B(GetNamedProperty), R(8), U8(11), U8(12),
                B(Star10),
                B(LdaUndefined),
                B(Star9),
                B(LdaZero),
                B(Star7),
                B(Ldar), R(7),
                B(SwitchOnSmiNoFeedback), U8(12), U8(2), I8(1),
                B(CallProperty1), R(10), R(8), R(9), U8(14),
                B(Jump), U8(130),
                B(GetNamedProperty), R(8), U8(14), U8(16),
                B(JumpIfUndefinedOrNull), U8(10),
                B(Star11),
                B(CallProperty1), R(11), R(8), R(9), U8(18),
                B(Jump), U8(116),
                B(Mov), R(0), R(11),
                B(Mov), R(9), R(12),
                B(InvokeIntrinsic), U8(Runtime::k_AsyncGeneratorAwait), R(11), U8(2),
  /*   49 E> */ B(SuspendGenerator), R(0), R(0), U8(11), U8(1),
                B(ResumeGenerator), R(0), R(0), U8(11),
                B(Star11),
                B(InvokeIntrinsic), U8(Runtime::k_GeneratorGetResumeMode), R(0), U8(1),
                B(Star12),
                B(LdaZero),
                B(TestReferenceEqual), R(12),
                B(JumpIfTrue), U8(5),
                B(Ldar), R(11),
                B(ReThrow),
                B(LdaSmi), I8(1),
                B(Star1),
                B(Mov), R(11), R(2),
                B(Jump), U8(220),
                B(GetNamedProperty), R(8), U8(15), U8(20),
                B(JumpIfUndefinedOrNull), U8(10),
                B(Star13),
                B(CallProperty1), R(13), R(8), R(9), U8(22),
                B(Jump), U8(61),
                B(GetNamedProperty), R(8), U8(14), U8(24),
                B(JumpIfUndefinedOrNull), U8(50),
                B(Star13),
                B(CallProperty0), R(13), R(8), U8(26),
                B(Jump), U8(2),
                B(Star14),
                B(Mov), R(0), R(13),
                B(InvokeIntrinsic), U8(Runtime::k_AsyncGeneratorAwait), R(13), U8(2),
  /*   49 E> */ B(SuspendGenerator), R(0), R(0), U8(13), U8(2),
                B(ResumeGenerator), R(0), R(0), U8(13),
                B(Star13),
                B(InvokeIntrinsic), U8(Runtime::k_GeneratorGetResumeMode), R(0), U8(1),
                B(Star14),
                B(LdaZero),
                B(TestReferenceEqual), R(14),
                B(JumpIfTrue), U8(5),
                B(Ldar), R(13),
                B(ReThrow),
                B(Ldar), R(13),
                B(JumpIfJSReceiver), U8(8),
                B(Star15),
                B(CallRuntime), U16(Runtime::kThrowIteratorResultNotAnObject), R(15), U8(1),
                B(CallRuntime), U16(Runtime::kThrowThrowMethodMissing), R(0), U8(0),
                B(Star14),
                B(Mov), R(0), R(13),
                B(InvokeIntrinsic), U8(Runtime::k_AsyncGeneratorAwait), R(13), U8(2),
  /*   49 E> */ B(SuspendGenerator), R(0), R(0), U8(13), U8(3),
                B(ResumeGenerator), R(0), R(0), U8(13),
                B(Star13),
                B(InvokeIntrinsic), U8(Runtime::k_GeneratorGetResumeMode), R(0), U8(1),
                B(Star14),
                B(LdaZero),
                B(TestReferenceEqual), R(14),
                B(JumpIfTrue), U8(5),
                B(Ldar), R(13),
                B(ReThrow),
                B(Ldar), R(13),
                B(Mov), R(13), R(6),
                B(JumpIfJSReceiver), U8(7),
                B(CallRuntime), U16(Runtime::kThrowIteratorResultNotAnObject), R(6), U8(1),
                B(GetNamedProperty), R(6), U8(16), U8(28),
                B(JumpIfToBooleanTrue), U8(37),
                B(GetNamedProperty), R(6), U8(17), U8(30),
                B(Star), R(16),
                B(LdaFalse),
                B(Star), R(17),
                B(Mov), R(0), R(15),
                B(InvokeIntrinsic), U8(Runtime::k_AsyncGeneratorResolve), R(15), U8(3),
  /*   49 E> */ B(SuspendGenerator), R(0), R(0), U8(15), U8(4),
                B(ResumeGenerator), R(0), R(0), U8(15),
                B(Star9),
                B(InvokeIntrinsic), U8(Runtime::k_GeneratorGetResumeMode), R(0), U8(1),
                B(Star7),
                B(JumpLoop), U8(221), I8(0), U8(32),
                B(GetNamedProperty), R(6), U8(17), U8(33),
                B(Star8),
                B(LdaSmi), I8(1),
                B(TestReferenceEqual), R(7),
                B(JumpIfFalse), U8(10),
                B(LdaSmi), I8(1),
                B(Star1),
                B(Mov), R(8), R(2),
                B(Jump), U8(44),
                B(LdaUndefined),
                B(Star2),
                B(LdaSmi), I8(1),
                B(Star1),
                B(Jump), U8(37),
                B(Star6),
                B(CreateCatchContext), R(6), U8(18),
                B(Star5),
                B(LdaTheHole),
                B(SetPendingMessage),
                B(Ldar), R(5),
                B(PushContext), R(6),
                B(LdaImmutableCurrentContextSlot), U8(2),
                B(Star8),
                B(Mov), R(0), R(7),
                B(InvokeIntrinsic), U8(Runtime::k_AsyncGeneratorReject), R(7), U8(2),
                B(PopContext), R(6),
                B(Star2),
                B(LdaSmi), I8(2),
                B(Star1),
                B(Jump), U8(8),
                B(Star2),
                B(LdaZero),
                B(Star1),
                B(LdaTheHole),
                B(SetPendingMessage),
                B(Star3),
                B(InvokeIntrinsic), U8(Runtime::k_GeneratorClose), R(0), U8(1),
                B(Ldar), R(1),
                B(SwitchOnSmiNoFeedback), U8(20), U8(3), I8(0),
                B(Ldar), R(3),
                B(SetPendingMessage),
                B(Ldar), R(2),
                B(ReThrow),
                B(LdaTrue),
                B(Star7),
                B(Mov), R(0), R(5),
                B(Mov), R(2), R(6),
                B(InvokeIntrinsic), U8(Runtime::k_AsyncGeneratorResolve), R(5), U8(3),
                B(Return),
                B(Ldar), R(2),
                B(Return),
]
constant pool: [
  Smi [30],
  Smi [149],
  Smi [215],
  Smi [261],
  Smi [318],
  Smi [18],
  Smi [10],
  Smi [7],
  INTERNALIZED_ONE_BYTE_STRING_TYPE ["g"],
  SYMBOL_TYPE,
  SYMBOL_TYPE,
  INTERNALIZED_ONE_BYTE_STRING_TYPE ["next"],
  Smi [11],
  Smi [66],
  INTERNALIZED_ONE_BYTE_STRING_TYPE ["return"],
  INTERNALIZED_ONE_BYTE_STRING_TYPE ["throw"],
  INTERNALIZED_ONE_BYTE_STRING_TYPE ["done"],
  INTERNALIZED_ONE_BYTE_STRING_TYPE ["value"],
  SCOPE_INFO_TYPE,
  Smi [338],
  Smi [4],
  Smi [10],
  Smi [23],
]
handlers: [
  [20, 387, 387],
  [23, 358, 358],
]

