#
# Autogenerated by generate-bytecode-expectations.
#

---
wrap: yes

---
snippet: "
  var a = 1; a += 2;
"
frame size: 1
parameter count: 1
bytecode array length: 9
bytecodes: [
  /*   42 S> */ B(LdaSmi), I8(1),
                B(Star0),
  /*   45 S> */ B(AddSmi), I8(2), U8(0),
                B(Star0),
                B(LdaUndefined),
  /*   53 S> */ B(Return),
]
constant pool: [
]
handlers: [
]

---
snippet: "
  var a = 1; a /= 2;
"
frame size: 1
parameter count: 1
bytecode array length: 9
bytecodes: [
  /*   42 S> */ B(LdaSmi), I8(1),
                B(Star0),
  /*   45 S> */ B(DivSmi), I8(2), U8(0),
                B(Star0),
                B(LdaUndefined),
  /*   53 S> */ B(Return),
]
constant pool: [
]
handlers: [
]

---
snippet: "
  var a = { val: 2 }; a.name *= 2;
"
frame size: 1
parameter count: 1
bytecode array length: 18
bytecodes: [
  /*   42 S> */ B(CreateObjectLiteral), U8(0), U8(0), U8(41),
                B(Star0),
  /*   54 S> */ B(GetNamedProperty), R(0), U8(1), U8(1),
                B(MulSmi), I8(2), U8(3),
  /*   61 E> */ B(SetNamedProperty), R(0), U8(1), U8(4),
                B(LdaUndefined),
  /*   67 S> */ B(Return),
]
constant pool: [
  OBJECT_BOILERPLATE_DESCRIPTION_TYPE,
  INTERNALIZED_ONE_BYTE_STRING_TYPE ["name"],
]
handlers: [
]

---
snippet: "
  var a = { 1: 2 }; a[1] ^= 2;
"
frame size: 3
parameter count: 1
bytecode array length: 20
bytecodes: [
  /*   42 S> */ B(CreateObjectLiteral), U8(0), U8(0), U8(41),
                B(Star0),
  /*   52 S> */ B(LdaSmi), I8(1),
                B(Star2),
                B(GetKeyedProperty), R(0), U8(1),
                B(BitwiseXorSmi), I8(2), U8(3),
  /*   57 E> */ B(SetKeyedProperty), R(0), R(2), U8(4),
                B(LdaUndefined),
  /*   63 S> */ B(Return),
]
constant pool: [
  OBJECT_BOILERPLATE_DESCRIPTION_TYPE,
]
handlers: [
]

---
snippet: "
  var a = 1; (function f() { return a; }); a |= 24;
"
frame size: 1
parameter count: 1
bytecode array length: 22
bytecodes: [
  /*   30 E> */ B(CreateFunctionContextWithCells), U8(0), U8(1),
                B(PushContext), R(0),
  /*   42 S> */ B(LdaSmi), I8(1),
  /*   42 E> */ B(StaCurrentContextSlot), U8(2),
  /*   45 S> */ B(CreateClosure), U8(1), U8(0), U8(2),
  /*   75 S> */ B(LdaCurrentContextSlot), U8(2),
                B(BitwiseOrSmi), I8(24), U8(0),
  /*   77 E> */ B(StaCurrentContextSlot), U8(2),
                B(LdaUndefined),
  /*   84 S> */ B(Return),
]
constant pool: [
  SCOPE_INFO_TYPE,
  SHARED_FUNCTION_INFO_TYPE,
]
handlers: [
]

