#
# Autogenerated by generate-bytecode-expectations.
#

---
wrap: yes

---
snippet: "
  const x = 10; function f1() {return x;}
"
frame size: 1
parameter count: 1
bytecode array length: 14
bytecodes: [
  /*   30 E> */ B(CreateFunctionContextWithCells), U8(0), U8(1),
                B(PushContext), R(0),
                B(LdaTheHole),
                B(StaCurrentContextSlotNoCell), U8(2),
  /*   44 S> */ B(LdaSmi), I8(10),
  /*   44 E> */ B(StaCurrentContextSlotNoCell), U8(2),
                B(LdaUndefined),
  /*   74 S> */ B(Return),
]
constant pool: [
  SCOPE_INFO_TYPE,
]
handlers: [
]

---
snippet: "
  const x = 10; function f1() {return x;} return x;
"
frame size: 1
parameter count: 1
bytecode array length: 15
bytecodes: [
  /*   30 E> */ B(CreateFunctionContextWithCells), U8(0), U8(1),
                B(PushContext), R(0),
                B(LdaTheHole),
                B(StaCurrentContextSlotNoCell), U8(2),
  /*   44 S> */ B(LdaSmi), I8(10),
  /*   44 E> */ B(StaCurrentContextSlotNoCell), U8(2),
  /*   74 S> */ B(LdaImmutableCurrentContextSlot), U8(2),
  /*   83 S> */ B(Return),
]
constant pool: [
  SCOPE_INFO_TYPE,
]
handlers: [
]

---
snippet: "
  const x = (x = 20); function f1() {return x;}
"
frame size: 2
parameter count: 1
bytecode array length: 24
bytecodes: [
  /*   30 E> */ B(CreateFunctionContextWithCells), U8(0), U8(1),
                B(PushContext), R(0),
                B(LdaTheHole),
                B(StaCurrentContextSlotNoCell), U8(2),
  /*   44 S> */ B(LdaSmi), I8(20),
                B(Star1),
                B(LdaCurrentContextSlot), U8(2),
  /*   47 E> */ B(ThrowReferenceErrorIfHole), U8(1),
                B(CallRuntime), U16(Runtime::kThrowConstAssignError), R(0), U8(0),
  /*   44 E> */ B(StaCurrentContextSlotNoCell), U8(2),
                B(LdaUndefined),
  /*   80 S> */ B(Return),
]
constant pool: [
  SCOPE_INFO_TYPE,
  INTERNALIZED_ONE_BYTE_STRING_TYPE ["x"],
]
handlers: [
]

---
snippet: "
  const x = 10; x = 20; function f1() {return x;}
"
frame size: 1
parameter count: 1
bytecode array length: 21
bytecodes: [
  /*   30 E> */ B(CreateFunctionContextWithCells), U8(0), U8(1),
                B(PushContext), R(0),
                B(LdaTheHole),
                B(StaCurrentContextSlotNoCell), U8(2),
  /*   44 S> */ B(LdaSmi), I8(10),
  /*   44 E> */ B(StaCurrentContextSlotNoCell), U8(2),
  /*   48 S> */ B(LdaSmi), I8(20),
  /*   50 E> */ B(CallRuntime), U16(Runtime::kThrowConstAssignError), R(0), U8(0),
                B(LdaUndefined),
  /*   82 S> */ B(Return),
]
constant pool: [
  SCOPE_INFO_TYPE,
]
handlers: [
]

