#
# Autogenerated by generate-bytecode-expectations.
#

---
wrap: yes

---
snippet: "
  var a; return function() { a = 1; };
"
frame size: 1
parameter count: 1
bytecode array length: 10
bytecodes: [
  /*   30 E> */ B(CreateFunctionContextWithCells), U8(0), U8(1),
                B(PushContext), R(0),
  /*   41 S> */ B(CreateClosure), U8(1), U8(0), U8(2),
  /*   70 S> */ B(Return),
]
constant pool: [
  SCOPE_INFO_TYPE,
  SHARED_FUNCTION_INFO_TYPE,
]
handlers: [
]

---
snippet: "
  var a = 1; return function() { a = 2; };
"
frame size: 1
parameter count: 1
bytecode array length: 14
bytecodes: [
  /*   30 E> */ B(CreateFunctionContextWithCells), U8(0), U8(1),
                B(PushContext), R(0),
  /*   42 S> */ B(LdaSmi), I8(1),
  /*   42 E> */ B(StaCurrentContextSlot), U8(2),
  /*   45 S> */ B(CreateClosure), U8(1), U8(0), U8(2),
  /*   74 S> */ B(Return),
]
constant pool: [
  SCOPE_INFO_TYPE,
  SHARED_FUNCTION_INFO_TYPE,
]
handlers: [
]

---
snippet: "
  var a = 1; var b = 2; return function() { a = 2; b = 3 };
"
frame size: 1
parameter count: 1
bytecode array length: 18
bytecodes: [
  /*   30 E> */ B(CreateFunctionContextWithCells), U8(0), U8(2),
                B(PushContext), R(0),
  /*   42 S> */ B(LdaSmi), I8(1),
  /*   42 E> */ B(StaCurrentContextSlot), U8(2),
  /*   53 S> */ B(LdaSmi), I8(2),
  /*   53 E> */ B(StaCurrentContextSlot), U8(3),
  /*   56 S> */ B(CreateClosure), U8(1), U8(0), U8(2),
  /*   91 S> */ B(Return),
]
constant pool: [
  SCOPE_INFO_TYPE,
  SHARED_FUNCTION_INFO_TYPE,
]
handlers: [
]

---
snippet: "
  var a; (function() { a = 2; })(); return a;
"
frame size: 2
parameter count: 1
bytecode array length: 16
bytecodes: [
  /*   30 E> */ B(CreateFunctionContextWithCells), U8(0), U8(1),
                B(PushContext), R(0),
  /*   41 S> */ B(CreateClosure), U8(1), U8(0), U8(2),
                B(Star1),
  /*   64 E> */ B(CallUndefinedReceiver0), R(1), U8(0),
  /*   68 S> */ B(LdaCurrentContextSlot), U8(2),
  /*   77 S> */ B(Return),
]
constant pool: [
  SCOPE_INFO_TYPE,
  SHARED_FUNCTION_INFO_TYPE,
]
handlers: [
]

---
snippet: "
  'use strict';
  let a = 1;
  { let b = 2; return function() { a + b; }; }
"
frame size: 2
parameter count: 1
bytecode array length: 28
bytecodes: [
  /*   30 E> */ B(CreateFunctionContextWithCells), U8(0), U8(1),
                B(PushContext), R(0),
                B(LdaTheHole),
                B(StaCurrentContextSlotNoCell), U8(2),
  /*   56 S> */ B(LdaSmi), I8(1),
  /*   56 E> */ B(StaCurrentContextSlotNoCell), U8(2),
                B(CreateBlockContext), U8(1),
                B(PushContext), R(1),
                B(LdaTheHole),
                B(StaCurrentContextSlotNoCell), U8(2),
  /*   69 S> */ B(LdaSmi), I8(2),
  /*   69 E> */ B(StaCurrentContextSlotNoCell), U8(2),
  /*   72 S> */ B(CreateClosure), U8(2), U8(0), U8(2),
  /*  101 S> */ B(Return),
]
constant pool: [
  SCOPE_INFO_TYPE,
  SCOPE_INFO_TYPE,
  SHARED_FUNCTION_INFO_TYPE,
]
handlers: [
]

---
snippet: "
  'use strict';
  var a896 = 0;
  var a897 = 0;
  var a898 = 0;
  var a899 = 0;
  var a900 = 0;
  var a901 = 0;
  var a902 = 0;
  var a903 = 0;
  var a904 = 0;
  var a905 = 0;
  var a906 = 0;
  var a907 = 0;
  var a908 = 0;
  var a909 = 0;
  var a910 = 0;
  var a911 = 0;
  var a912 = 0;
  var a913 = 0;
  var a914 = 0;
  var a915 = 0;
  var a916 = 0;
  var a917 = 0;
  var a918 = 0;
  var a919 = 0;
  var a920 = 0;
  var a921 = 0;
  var a922 = 0;
  var a923 = 0;
  var a924 = 0;
  var a925 = 0;
  var a926 = 0;
  var a927 = 0;
  var a928 = 0;
  var a929 = 0;
  var a930 = 0;
  var a931 = 0;
  var a932 = 0;
  var a933 = 0;
  var a934 = 0;
  var a935 = 0;
  var a936 = 0;
  var a937 = 0;
  var a938 = 0;
  var a939 = 0;
  var a940 = 0;
  var a941 = 0;
  var a942 = 0;
  var a943 = 0;
  var a944 = 0;
  var a945 = 0;
  var a946 = 0;
  var a947 = 0;
  var a948 = 0;
  var a949 = 0;
  var a950 = 0;
  var a951 = 0;
  var a952 = 0;
  var a953 = 0;
  var a954 = 0;
  var a955 = 0;
  var a956 = 0;
  var a957 = 0;
  var a958 = 0;
  var a959 = 0;
  var a960 = 0;
  var a961 = 0;
  var a962 = 0;
  var a963 = 0;
  var a964 = 0;
  var a965 = 0;
  var a966 = 0;
  var a967 = 0;
  var a968 = 0;
  var a969 = 0;
  var a970 = 0;
  var a971 = 0;
  var a972 = 0;
  var a973 = 0;
  var a974 = 0;
  var a975 = 0;
  var a976 = 0;
  var a977 = 0;
  var a978 = 0;
  var a979 = 0;
  var a980 = 0;
  var a981 = 0;
  var a982 = 0;
  var a983 = 0;
  var a984 = 0;
  var a985 = 0;
  var a986 = 0;
  var a987 = 0;
  var a988 = 0;
  var a989 = 0;
  var a990 = 0;
  var a991 = 0;
  var a992 = 0;
  var a993 = 0;
  var a994 = 0;
  var a995 = 0;
  var a996 = 0;
  var a997 = 0;
  var a998 = 0;
  var a999 = 0;
  var a1000 = 0;
  var a1001 = 0;
  var a1002 = 0;
  var a1003 = 0;
  var a1004 = 0;
  var a1005 = 0;
  var a1006 = 0;
  var a1007 = 0;
  var a1008 = 0;
  var a1009 = 0;
  var a1010 = 0;
  var a1011 = 0;
  var a1012 = 0;
  var a1013 = 0;
  var a1014 = 0;
  var a1015 = 0;
  var a1016 = 0;
  var a1017 = 0;
  var a1018 = 0;
  var a1019 = 0;
  var a1020 = 0;
  var a1021 = 0;
  var a1022 = 0;
  var a1023 = 0;
  var a1024 = 0;
  var a1025 = 0;
  var a1026 = 0;
  var a1027 = 0;
  var a1028 = 0;
  var a1029 = 0;
  var a1030 = 0;
  var a1031 = 0;
  var a1032 = 0;
  var a1033 = 0;
  var a1034 = 0;
  var a1035 = 0;
  var a1036 = 0;
  var a1037 = 0;
  var a1038 = 0;
  var a1039 = 0;
  var a1040 = 0;
  var a1041 = 0;
  var a1042 = 0;
  var a1043 = 0;
  var a1044 = 0;
  var a1045 = 0;
  var a1046 = 0;
  var a1047 = 0;
  var a1048 = 0;
  var a1049 = 0;
  var a1050 = 0;
  var a1051 = 0;
  var a1052 = 0;
  var a1053 = 0;
  var a1054 = 0;
  var a1055 = 0;
  var a1056 = 0;
  var a1057 = 0;
  var a1058 = 0;
  var a1059 = 0;
  var a1060 = 0;
  var a1061 = 0;
  var a1062 = 0;
  var a1063 = 0;
  var a1064 = 0;
  var a1065 = 0;
  var a1066 = 0;
  var a1067 = 0;
  var a1068 = 0;
  var a1069 = 0;
  var a1070 = 0;
  var a1071 = 0;
  var a1072 = 0;
  var a1073 = 0;
  var a1074 = 0;
  var a1075 = 0;
  var a1076 = 0;
  var a1077 = 0;
  var a1078 = 0;
  var a1079 = 0;
  var a1080 = 0;
  var a1081 = 0;
  var a1082 = 0;
  var a1083 = 0;
  var a1084 = 0;
  var a1085 = 0;
  var a1086 = 0;
  var a1087 = 0;
  var a1088 = 0;
  var a1089 = 0;
  var a1090 = 0;
  var a1091 = 0;
  var a1092 = 0;
  var a1093 = 0;
  var a1094 = 0;
  var a1095 = 0;
  var a1096 = 0;
  var a1097 = 0;
  var a1098 = 0;
  var a1099 = 0;
  var a1100 = 0;
  var a1101 = 0;
  var a1102 = 0;
  var a1103 = 0;
  var a1104 = 0;
  var a1105 = 0;
  var a1106 = 0;
  var a1107 = 0;
  var a1108 = 0;
  var a1109 = 0;
  var a1110 = 0;
  var a1111 = 0;
  var a1112 = 0;
  var a1113 = 0;
  var a1114 = 0;
  var a1115 = 0;
  var a1116 = 0;
  var a1117 = 0;
  var a1118 = 0;
  var a1119 = 0;
  var a1120 = 0;
  var a1121 = 0;
  var a1122 = 0;
  var a1123 = 0;
  var a1124 = 0;
  var a1125 = 0;
  var a1126 = 0;
  var a1127 = 0;
  var a1128 = 0;
  var a1129 = 0;
  var a1130 = 0;
  var a1131 = 0;
  var a1132 = 0;
  var a1133 = 0;
  var a1134 = 0;
  var a1135 = 0;
  var a1136 = 0;
  var a1137 = 0;
  var a1138 = 0;
  var a1139 = 0;
  var a1140 = 0;
  var a1141 = 0;
  var a1142 = 0;
  var a1143 = 0;
  var a1144 = 0;
  var a1145 = 0;
  var a1146 = 0;
  var a1147 = 0;
  eval();
  var b = 100;
  return b
"
frame size: 3
parameter count: 1
bytecode array length: 795
bytecodes: [
  /*   30 E> */ B(Wide), B(CreateFunctionContext), U16(0), U16(256),
                B(PushContext), R(1),
                B(Ldar), R(this),
                B(StaCurrentContextSlotNoCell), U8(2),
                B(CreateUnmappedArguments),
                B(Wide), B(StaCurrentContextSlotNoCell), U16(257),
                B(Ldar), R(0),
                B(StaCurrentContextSlotNoCell), U8(3),
  /*   59 S> */ B(LdaZero),
  /*   59 E> */ B(StaCurrentContextSlotNoCell), U8(4),
  /*   73 S> */ B(LdaZero),
  /*   73 E> */ B(StaCurrentContextSlotNoCell), U8(5),
  /*   87 S> */ B(LdaZero),
  /*   87 E> */ B(StaCurrentContextSlotNoCell), U8(6),
  /*  101 S> */ B(LdaZero),
  /*  101 E> */ B(StaCurrentContextSlotNoCell), U8(7),
  /*  115 S> */ B(LdaZero),
  /*  115 E> */ B(StaCurrentContextSlotNoCell), U8(8),
  /*  129 S> */ B(LdaZero),
  /*  129 E> */ B(StaCurrentContextSlotNoCell), U8(9),
  /*  143 S> */ B(LdaZero),
  /*  143 E> */ B(StaCurrentContextSlotNoCell), U8(10),
  /*  157 S> */ B(LdaZero),
  /*  157 E> */ B(StaCurrentContextSlotNoCell), U8(11),
  /*  171 S> */ B(LdaZero),
  /*  171 E> */ B(StaCurrentContextSlotNoCell), U8(12),
  /*  185 S> */ B(LdaZero),
  /*  185 E> */ B(StaCurrentContextSlotNoCell), U8(13),
  /*  199 S> */ B(LdaZero),
  /*  199 E> */ B(StaCurrentContextSlotNoCell), U8(14),
  /*  213 S> */ B(LdaZero),
  /*  213 E> */ B(StaCurrentContextSlotNoCell), U8(15),
  /*  227 S> */ B(LdaZero),
  /*  227 E> */ B(StaCurrentContextSlotNoCell), U8(16),
  /*  241 S> */ B(LdaZero),
  /*  241 E> */ B(StaCurrentContextSlotNoCell), U8(17),
  /*  255 S> */ B(LdaZero),
  /*  255 E> */ B(StaCurrentContextSlotNoCell), U8(18),
  /*  269 S> */ B(LdaZero),
  /*  269 E> */ B(StaCurrentContextSlotNoCell), U8(19),
  /*  283 S> */ B(LdaZero),
  /*  283 E> */ B(StaCurrentContextSlotNoCell), U8(20),
  /*  297 S> */ B(LdaZero),
  /*  297 E> */ B(StaCurrentContextSlotNoCell), U8(21),
  /*  311 S> */ B(LdaZero),
  /*  311 E> */ B(StaCurrentContextSlotNoCell), U8(22),
  /*  325 S> */ B(LdaZero),
  /*  325 E> */ B(StaCurrentContextSlotNoCell), U8(23),
  /*  339 S> */ B(LdaZero),
  /*  339 E> */ B(StaCurrentContextSlotNoCell), U8(24),
  /*  353 S> */ B(LdaZero),
  /*  353 E> */ B(StaCurrentContextSlotNoCell), U8(25),
  /*  367 S> */ B(LdaZero),
  /*  367 E> */ B(StaCurrentContextSlotNoCell), U8(26),
  /*  381 S> */ B(LdaZero),
  /*  381 E> */ B(StaCurrentContextSlotNoCell), U8(27),
  /*  395 S> */ B(LdaZero),
  /*  395 E> */ B(StaCurrentContextSlotNoCell), U8(28),
  /*  409 S> */ B(LdaZero),
  /*  409 E> */ B(StaCurrentContextSlotNoCell), U8(29),
  /*  423 S> */ B(LdaZero),
  /*  423 E> */ B(StaCurrentContextSlotNoCell), U8(30),
  /*  437 S> */ B(LdaZero),
  /*  437 E> */ B(StaCurrentContextSlotNoCell), U8(31),
  /*  451 S> */ B(LdaZero),
  /*  451 E> */ B(StaCurrentContextSlotNoCell), U8(32),
  /*  465 S> */ B(LdaZero),
  /*  465 E> */ B(StaCurrentContextSlotNoCell), U8(33),
  /*  479 S> */ B(LdaZero),
  /*  479 E> */ B(StaCurrentContextSlotNoCell), U8(34),
  /*  493 S> */ B(LdaZero),
  /*  493 E> */ B(StaCurrentContextSlotNoCell), U8(35),
  /*  507 S> */ B(LdaZero),
  /*  507 E> */ B(StaCurrentContextSlotNoCell), U8(36),
  /*  521 S> */ B(LdaZero),
  /*  521 E> */ B(StaCurrentContextSlotNoCell), U8(37),
  /*  535 S> */ B(LdaZero),
  /*  535 E> */ B(StaCurrentContextSlotNoCell), U8(38),
  /*  549 S> */ B(LdaZero),
  /*  549 E> */ B(StaCurrentContextSlotNoCell), U8(39),
  /*  563 S> */ B(LdaZero),
  /*  563 E> */ B(StaCurrentContextSlotNoCell), U8(40),
  /*  577 S> */ B(LdaZero),
  /*  577 E> */ B(StaCurrentContextSlotNoCell), U8(41),
  /*  591 S> */ B(LdaZero),
  /*  591 E> */ B(StaCurrentContextSlotNoCell), U8(42),
  /*  605 S> */ B(LdaZero),
  /*  605 E> */ B(StaCurrentContextSlotNoCell), U8(43),
  /*  619 S> */ B(LdaZero),
  /*  619 E> */ B(StaCurrentContextSlotNoCell), U8(44),
  /*  633 S> */ B(LdaZero),
  /*  633 E> */ B(StaCurrentContextSlotNoCell), U8(45),
  /*  647 S> */ B(LdaZero),
  /*  647 E> */ B(StaCurrentContextSlotNoCell), U8(46),
  /*  661 S> */ B(LdaZero),
  /*  661 E> */ B(StaCurrentContextSlotNoCell), U8(47),
  /*  675 S> */ B(LdaZero),
  /*  675 E> */ B(StaCurrentContextSlotNoCell), U8(48),
  /*  689 S> */ B(LdaZero),
  /*  689 E> */ B(StaCurrentContextSlotNoCell), U8(49),
  /*  703 S> */ B(LdaZero),
  /*  703 E> */ B(StaCurrentContextSlotNoCell), U8(50),
  /*  717 S> */ B(LdaZero),
  /*  717 E> */ B(StaCurrentContextSlotNoCell), U8(51),
  /*  731 S> */ B(LdaZero),
  /*  731 E> */ B(StaCurrentContextSlotNoCell), U8(52),
  /*  745 S> */ B(LdaZero),
  /*  745 E> */ B(StaCurrentContextSlotNoCell), U8(53),
  /*  759 S> */ B(LdaZero),
  /*  759 E> */ B(StaCurrentContextSlotNoCell), U8(54),
  /*  773 S> */ B(LdaZero),
  /*  773 E> */ B(StaCurrentContextSlotNoCell), U8(55),
  /*  787 S> */ B(LdaZero),
  /*  787 E> */ B(StaCurrentContextSlotNoCell), U8(56),
  /*  801 S> */ B(LdaZero),
  /*  801 E> */ B(StaCurrentContextSlotNoCell), U8(57),
  /*  815 S> */ B(LdaZero),
  /*  815 E> */ B(StaCurrentContextSlotNoCell), U8(58),
  /*  829 S> */ B(LdaZero),
  /*  829 E> */ B(StaCurrentContextSlotNoCell), U8(59),
  /*  843 S> */ B(LdaZero),
  /*  843 E> */ B(StaCurrentContextSlotNoCell), U8(60),
  /*  857 S> */ B(LdaZero),
  /*  857 E> */ B(StaCurrentContextSlotNoCell), U8(61),
  /*  871 S> */ B(LdaZero),
  /*  871 E> */ B(StaCurrentContextSlotNoCell), U8(62),
  /*  885 S> */ B(LdaZero),
  /*  885 E> */ B(StaCurrentContextSlotNoCell), U8(63),
  /*  899 S> */ B(LdaZero),
  /*  899 E> */ B(StaCurrentContextSlotNoCell), U8(64),
  /*  913 S> */ B(LdaZero),
  /*  913 E> */ B(StaCurrentContextSlotNoCell), U8(65),
  /*  927 S> */ B(LdaZero),
  /*  927 E> */ B(StaCurrentContextSlotNoCell), U8(66),
  /*  941 S> */ B(LdaZero),
  /*  941 E> */ B(StaCurrentContextSlotNoCell), U8(67),
  /*  955 S> */ B(LdaZero),
  /*  955 E> */ B(StaCurrentContextSlotNoCell), U8(68),
  /*  969 S> */ B(LdaZero),
  /*  969 E> */ B(StaCurrentContextSlotNoCell), U8(69),
  /*  983 S> */ B(LdaZero),
  /*  983 E> */ B(StaCurrentContextSlotNoCell), U8(70),
  /*  997 S> */ B(LdaZero),
  /*  997 E> */ B(StaCurrentContextSlotNoCell), U8(71),
  /* 1011 S> */ B(LdaZero),
  /* 1011 E> */ B(StaCurrentContextSlotNoCell), U8(72),
  /* 1025 S> */ B(LdaZero),
  /* 1025 E> */ B(StaCurrentContextSlotNoCell), U8(73),
  /* 1039 S> */ B(LdaZero),
  /* 1039 E> */ B(StaCurrentContextSlotNoCell), U8(74),
  /* 1053 S> */ B(LdaZero),
  /* 1053 E> */ B(StaCurrentContextSlotNoCell), U8(75),
  /* 1067 S> */ B(LdaZero),
  /* 1067 E> */ B(StaCurrentContextSlotNoCell), U8(76),
  /* 1081 S> */ B(LdaZero),
  /* 1081 E> */ B(StaCurrentContextSlotNoCell), U8(77),
  /* 1095 S> */ B(LdaZero),
  /* 1095 E> */ B(StaCurrentContextSlotNoCell), U8(78),
  /* 1109 S> */ B(LdaZero),
  /* 1109 E> */ B(StaCurrentContextSlotNoCell), U8(79),
  /* 1123 S> */ B(LdaZero),
  /* 1123 E> */ B(StaCurrentContextSlotNoCell), U8(80),
  /* 1137 S> */ B(LdaZero),
  /* 1137 E> */ B(StaCurrentContextSlotNoCell), U8(81),
  /* 1151 S> */ B(LdaZero),
  /* 1151 E> */ B(StaCurrentContextSlotNoCell), U8(82),
  /* 1165 S> */ B(LdaZero),
  /* 1165 E> */ B(StaCurrentContextSlotNoCell), U8(83),
  /* 1179 S> */ B(LdaZero),
  /* 1179 E> */ B(StaCurrentContextSlotNoCell), U8(84),
  /* 1193 S> */ B(LdaZero),
  /* 1193 E> */ B(StaCurrentContextSlotNoCell), U8(85),
  /* 1207 S> */ B(LdaZero),
  /* 1207 E> */ B(StaCurrentContextSlotNoCell), U8(86),
  /* 1221 S> */ B(LdaZero),
  /* 1221 E> */ B(StaCurrentContextSlotNoCell), U8(87),
  /* 1235 S> */ B(LdaZero),
  /* 1235 E> */ B(StaCurrentContextSlotNoCell), U8(88),
  /* 1249 S> */ B(LdaZero),
  /* 1249 E> */ B(StaCurrentContextSlotNoCell), U8(89),
  /* 1263 S> */ B(LdaZero),
  /* 1263 E> */ B(StaCurrentContextSlotNoCell), U8(90),
  /* 1277 S> */ B(LdaZero),
  /* 1277 E> */ B(StaCurrentContextSlotNoCell), U8(91),
  /* 1291 S> */ B(LdaZero),
  /* 1291 E> */ B(StaCurrentContextSlotNoCell), U8(92),
  /* 1305 S> */ B(LdaZero),
  /* 1305 E> */ B(StaCurrentContextSlotNoCell), U8(93),
  /* 1319 S> */ B(LdaZero),
  /* 1319 E> */ B(StaCurrentContextSlotNoCell), U8(94),
  /* 1333 S> */ B(LdaZero),
  /* 1333 E> */ B(StaCurrentContextSlotNoCell), U8(95),
  /* 1347 S> */ B(LdaZero),
  /* 1347 E> */ B(StaCurrentContextSlotNoCell), U8(96),
  /* 1361 S> */ B(LdaZero),
  /* 1361 E> */ B(StaCurrentContextSlotNoCell), U8(97),
  /* 1375 S> */ B(LdaZero),
  /* 1375 E> */ B(StaCurrentContextSlotNoCell), U8(98),
  /* 1389 S> */ B(LdaZero),
  /* 1389 E> */ B(StaCurrentContextSlotNoCell), U8(99),
  /* 1403 S> */ B(LdaZero),
  /* 1403 E> */ B(StaCurrentContextSlotNoCell), U8(100),
  /* 1417 S> */ B(LdaZero),
  /* 1417 E> */ B(StaCurrentContextSlotNoCell), U8(101),
  /* 1431 S> */ B(LdaZero),
  /* 1431 E> */ B(StaCurrentContextSlotNoCell), U8(102),
  /* 1445 S> */ B(LdaZero),
  /* 1445 E> */ B(StaCurrentContextSlotNoCell), U8(103),
  /* 1459 S> */ B(LdaZero),
  /* 1459 E> */ B(StaCurrentContextSlotNoCell), U8(104),
  /* 1473 S> */ B(LdaZero),
  /* 1473 E> */ B(StaCurrentContextSlotNoCell), U8(105),
  /* 1487 S> */ B(LdaZero),
  /* 1487 E> */ B(StaCurrentContextSlotNoCell), U8(106),
  /* 1501 S> */ B(LdaZero),
  /* 1501 E> */ B(StaCurrentContextSlotNoCell), U8(107),
  /* 1516 S> */ B(LdaZero),
  /* 1516 E> */ B(StaCurrentContextSlotNoCell), U8(108),
  /* 1531 S> */ B(LdaZero),
  /* 1531 E> */ B(StaCurrentContextSlotNoCell), U8(109),
  /* 1546 S> */ B(LdaZero),
  /* 1546 E> */ B(StaCurrentContextSlotNoCell), U8(110),
  /* 1561 S> */ B(LdaZero),
  /* 1561 E> */ B(StaCurrentContextSlotNoCell), U8(111),
  /* 1576 S> */ B(LdaZero),
  /* 1576 E> */ B(StaCurrentContextSlotNoCell), U8(112),
  /* 1591 S> */ B(LdaZero),
  /* 1591 E> */ B(StaCurrentContextSlotNoCell), U8(113),
  /* 1606 S> */ B(LdaZero),
  /* 1606 E> */ B(StaCurrentContextSlotNoCell), U8(114),
  /* 1621 S> */ B(LdaZero),
  /* 1621 E> */ B(StaCurrentContextSlotNoCell), U8(115),
  /* 1636 S> */ B(LdaZero),
  /* 1636 E> */ B(StaCurrentContextSlotNoCell), U8(116),
  /* 1651 S> */ B(LdaZero),
  /* 1651 E> */ B(StaCurrentContextSlotNoCell), U8(117),
  /* 1666 S> */ B(LdaZero),
  /* 1666 E> */ B(StaCurrentContextSlotNoCell), U8(118),
  /* 1681 S> */ B(LdaZero),
  /* 1681 E> */ B(StaCurrentContextSlotNoCell), U8(119),
  /* 1696 S> */ B(LdaZero),
  /* 1696 E> */ B(StaCurrentContextSlotNoCell), U8(120),
  /* 1711 S> */ B(LdaZero),
  /* 1711 E> */ B(StaCurrentContextSlotNoCell), U8(121),
  /* 1726 S> */ B(LdaZero),
  /* 1726 E> */ B(StaCurrentContextSlotNoCell), U8(122),
  /* 1741 S> */ B(LdaZero),
  /* 1741 E> */ B(StaCurrentContextSlotNoCell), U8(123),
  /* 1756 S> */ B(LdaZero),
  /* 1756 E> */ B(StaCurrentContextSlotNoCell), U8(124),
  /* 1771 S> */ B(LdaZero),
  /* 1771 E> */ B(StaCurrentContextSlotNoCell), U8(125),
  /* 1786 S> */ B(LdaZero),
  /* 1786 E> */ B(StaCurrentContextSlotNoCell), U8(126),
  /* 1801 S> */ B(LdaZero),
  /* 1801 E> */ B(StaCurrentContextSlotNoCell), U8(127),
  /* 1816 S> */ B(LdaZero),
  /* 1816 E> */ B(StaCurrentContextSlotNoCell), U8(128),
  /* 1831 S> */ B(LdaZero),
  /* 1831 E> */ B(StaCurrentContextSlotNoCell), U8(129),
  /* 1846 S> */ B(LdaZero),
  /* 1846 E> */ B(StaCurrentContextSlotNoCell), U8(130),
  /* 1861 S> */ B(LdaZero),
  /* 1861 E> */ B(StaCurrentContextSlotNoCell), U8(131),
  /* 1876 S> */ B(LdaZero),
  /* 1876 E> */ B(StaCurrentContextSlotNoCell), U8(132),
  /* 1891 S> */ B(LdaZero),
  /* 1891 E> */ B(StaCurrentContextSlotNoCell), U8(133),
  /* 1906 S> */ B(LdaZero),
  /* 1906 E> */ B(StaCurrentContextSlotNoCell), U8(134),
  /* 1921 S> */ B(LdaZero),
  /* 1921 E> */ B(StaCurrentContextSlotNoCell), U8(135),
  /* 1936 S> */ B(LdaZero),
  /* 1936 E> */ B(StaCurrentContextSlotNoCell), U8(136),
  /* 1951 S> */ B(LdaZero),
  /* 1951 E> */ B(StaCurrentContextSlotNoCell), U8(137),
  /* 1966 S> */ B(LdaZero),
  /* 1966 E> */ B(StaCurrentContextSlotNoCell), U8(138),
  /* 1981 S> */ B(LdaZero),
  /* 1981 E> */ B(StaCurrentContextSlotNoCell), U8(139),
  /* 1996 S> */ B(LdaZero),
  /* 1996 E> */ B(StaCurrentContextSlotNoCell), U8(140),
  /* 2011 S> */ B(LdaZero),
  /* 2011 E> */ B(StaCurrentContextSlotNoCell), U8(141),
  /* 2026 S> */ B(LdaZero),
  /* 2026 E> */ B(StaCurrentContextSlotNoCell), U8(142),
  /* 2041 S> */ B(LdaZero),
  /* 2041 E> */ B(StaCurrentContextSlotNoCell), U8(143),
  /* 2056 S> */ B(LdaZero),
  /* 2056 E> */ B(StaCurrentContextSlotNoCell), U8(144),
  /* 2071 S> */ B(LdaZero),
  /* 2071 E> */ B(StaCurrentContextSlotNoCell), U8(145),
  /* 2086 S> */ B(LdaZero),
  /* 2086 E> */ B(StaCurrentContextSlotNoCell), U8(146),
  /* 2101 S> */ B(LdaZero),
  /* 2101 E> */ B(StaCurrentContextSlotNoCell), U8(147),
  /* 2116 S> */ B(LdaZero),
  /* 2116 E> */ B(StaCurrentContextSlotNoCell), U8(148),
  /* 2131 S> */ B(LdaZero),
  /* 2131 E> */ B(StaCurrentContextSlotNoCell), U8(149),
  /* 2146 S> */ B(LdaZero),
  /* 2146 E> */ B(StaCurrentContextSlotNoCell), U8(150),
  /* 2161 S> */ B(LdaZero),
  /* 2161 E> */ B(StaCurrentContextSlotNoCell), U8(151),
  /* 2176 S> */ B(LdaZero),
  /* 2176 E> */ B(StaCurrentContextSlotNoCell), U8(152),
  /* 2191 S> */ B(LdaZero),
  /* 2191 E> */ B(StaCurrentContextSlotNoCell), U8(153),
  /* 2206 S> */ B(LdaZero),
  /* 2206 E> */ B(StaCurrentContextSlotNoCell), U8(154),
  /* 2221 S> */ B(LdaZero),
  /* 2221 E> */ B(StaCurrentContextSlotNoCell), U8(155),
  /* 2236 S> */ B(LdaZero),
  /* 2236 E> */ B(StaCurrentContextSlotNoCell), U8(156),
  /* 2251 S> */ B(LdaZero),
  /* 2251 E> */ B(StaCurrentContextSlotNoCell), U8(157),
  /* 2266 S> */ B(LdaZero),
  /* 2266 E> */ B(StaCurrentContextSlotNoCell), U8(158),
  /* 2281 S> */ B(LdaZero),
  /* 2281 E> */ B(StaCurrentContextSlotNoCell), U8(159),
  /* 2296 S> */ B(LdaZero),
  /* 2296 E> */ B(StaCurrentContextSlotNoCell), U8(160),
  /* 2311 S> */ B(LdaZero),
  /* 2311 E> */ B(StaCurrentContextSlotNoCell), U8(161),
  /* 2326 S> */ B(LdaZero),
  /* 2326 E> */ B(StaCurrentContextSlotNoCell), U8(162),
  /* 2341 S> */ B(LdaZero),
  /* 2341 E> */ B(StaCurrentContextSlotNoCell), U8(163),
  /* 2356 S> */ B(LdaZero),
  /* 2356 E> */ B(StaCurrentContextSlotNoCell), U8(164),
  /* 2371 S> */ B(LdaZero),
  /* 2371 E> */ B(StaCurrentContextSlotNoCell), U8(165),
  /* 2386 S> */ B(LdaZero),
  /* 2386 E> */ B(StaCurrentContextSlotNoCell), U8(166),
  /* 2401 S> */ B(LdaZero),
  /* 2401 E> */ B(StaCurrentContextSlotNoCell), U8(167),
  /* 2416 S> */ B(LdaZero),
  /* 2416 E> */ B(StaCurrentContextSlotNoCell), U8(168),
  /* 2431 S> */ B(LdaZero),
  /* 2431 E> */ B(StaCurrentContextSlotNoCell), U8(169),
  /* 2446 S> */ B(LdaZero),
  /* 2446 E> */ B(StaCurrentContextSlotNoCell), U8(170),
  /* 2461 S> */ B(LdaZero),
  /* 2461 E> */ B(StaCurrentContextSlotNoCell), U8(171),
  /* 2476 S> */ B(LdaZero),
  /* 2476 E> */ B(StaCurrentContextSlotNoCell), U8(172),
  /* 2491 S> */ B(LdaZero),
  /* 2491 E> */ B(StaCurrentContextSlotNoCell), U8(173),
  /* 2506 S> */ B(LdaZero),
  /* 2506 E> */ B(StaCurrentContextSlotNoCell), U8(174),
  /* 2521 S> */ B(LdaZero),
  /* 2521 E> */ B(StaCurrentContextSlotNoCell), U8(175),
  /* 2536 S> */ B(LdaZero),
  /* 2536 E> */ B(StaCurrentContextSlotNoCell), U8(176),
  /* 2551 S> */ B(LdaZero),
  /* 2551 E> */ B(StaCurrentContextSlotNoCell), U8(177),
  /* 2566 S> */ B(LdaZero),
  /* 2566 E> */ B(StaCurrentContextSlotNoCell), U8(178),
  /* 2581 S> */ B(LdaZero),
  /* 2581 E> */ B(StaCurrentContextSlotNoCell), U8(179),
  /* 2596 S> */ B(LdaZero),
  /* 2596 E> */ B(StaCurrentContextSlotNoCell), U8(180),
  /* 2611 S> */ B(LdaZero),
  /* 2611 E> */ B(StaCurrentContextSlotNoCell), U8(181),
  /* 2626 S> */ B(LdaZero),
  /* 2626 E> */ B(StaCurrentContextSlotNoCell), U8(182),
  /* 2641 S> */ B(LdaZero),
  /* 2641 E> */ B(StaCurrentContextSlotNoCell), U8(183),
  /* 2656 S> */ B(LdaZero),
  /* 2656 E> */ B(StaCurrentContextSlotNoCell), U8(184),
  /* 2671 S> */ B(LdaZero),
  /* 2671 E> */ B(StaCurrentContextSlotNoCell), U8(185),
  /* 2686 S> */ B(LdaZero),
  /* 2686 E> */ B(StaCurrentContextSlotNoCell), U8(186),
  /* 2701 S> */ B(LdaZero),
  /* 2701 E> */ B(StaCurrentContextSlotNoCell), U8(187),
  /* 2716 S> */ B(LdaZero),
  /* 2716 E> */ B(StaCurrentContextSlotNoCell), U8(188),
  /* 2731 S> */ B(LdaZero),
  /* 2731 E> */ B(StaCurrentContextSlotNoCell), U8(189),
  /* 2746 S> */ B(LdaZero),
  /* 2746 E> */ B(StaCurrentContextSlotNoCell), U8(190),
  /* 2761 S> */ B(LdaZero),
  /* 2761 E> */ B(StaCurrentContextSlotNoCell), U8(191),
  /* 2776 S> */ B(LdaZero),
  /* 2776 E> */ B(StaCurrentContextSlotNoCell), U8(192),
  /* 2791 S> */ B(LdaZero),
  /* 2791 E> */ B(StaCurrentContextSlotNoCell), U8(193),
  /* 2806 S> */ B(LdaZero),
  /* 2806 E> */ B(StaCurrentContextSlotNoCell), U8(194),
  /* 2821 S> */ B(LdaZero),
  /* 2821 E> */ B(StaCurrentContextSlotNoCell), U8(195),
  /* 2836 S> */ B(LdaZero),
  /* 2836 E> */ B(StaCurrentContextSlotNoCell), U8(196),
  /* 2851 S> */ B(LdaZero),
  /* 2851 E> */ B(StaCurrentContextSlotNoCell), U8(197),
  /* 2866 S> */ B(LdaZero),
  /* 2866 E> */ B(StaCurrentContextSlotNoCell), U8(198),
  /* 2881 S> */ B(LdaZero),
  /* 2881 E> */ B(StaCurrentContextSlotNoCell), U8(199),
  /* 2896 S> */ B(LdaZero),
  /* 2896 E> */ B(StaCurrentContextSlotNoCell), U8(200),
  /* 2911 S> */ B(LdaZero),
  /* 2911 E> */ B(StaCurrentContextSlotNoCell), U8(201),
  /* 2926 S> */ B(LdaZero),
  /* 2926 E> */ B(StaCurrentContextSlotNoCell), U8(202),
  /* 2941 S> */ B(LdaZero),
  /* 2941 E> */ B(StaCurrentContextSlotNoCell), U8(203),
  /* 2956 S> */ B(LdaZero),
  /* 2956 E> */ B(StaCurrentContextSlotNoCell), U8(204),
  /* 2971 S> */ B(LdaZero),
  /* 2971 E> */ B(StaCurrentContextSlotNoCell), U8(205),
  /* 2986 S> */ B(LdaZero),
  /* 2986 E> */ B(StaCurrentContextSlotNoCell), U8(206),
  /* 3001 S> */ B(LdaZero),
  /* 3001 E> */ B(StaCurrentContextSlotNoCell), U8(207),
  /* 3016 S> */ B(LdaZero),
  /* 3016 E> */ B(StaCurrentContextSlotNoCell), U8(208),
  /* 3031 S> */ B(LdaZero),
  /* 3031 E> */ B(StaCurrentContextSlotNoCell), U8(209),
  /* 3046 S> */ B(LdaZero),
  /* 3046 E> */ B(StaCurrentContextSlotNoCell), U8(210),
  /* 3061 S> */ B(LdaZero),
  /* 3061 E> */ B(StaCurrentContextSlotNoCell), U8(211),
  /* 3076 S> */ B(LdaZero),
  /* 3076 E> */ B(StaCurrentContextSlotNoCell), U8(212),
  /* 3091 S> */ B(LdaZero),
  /* 3091 E> */ B(StaCurrentContextSlotNoCell), U8(213),
  /* 3106 S> */ B(LdaZero),
  /* 3106 E> */ B(StaCurrentContextSlotNoCell), U8(214),
  /* 3121 S> */ B(LdaZero),
  /* 3121 E> */ B(StaCurrentContextSlotNoCell), U8(215),
  /* 3136 S> */ B(LdaZero),
  /* 3136 E> */ B(StaCurrentContextSlotNoCell), U8(216),
  /* 3151 S> */ B(LdaZero),
  /* 3151 E> */ B(StaCurrentContextSlotNoCell), U8(217),
  /* 3166 S> */ B(LdaZero),
  /* 3166 E> */ B(StaCurrentContextSlotNoCell), U8(218),
  /* 3181 S> */ B(LdaZero),
  /* 3181 E> */ B(StaCurrentContextSlotNoCell), U8(219),
  /* 3196 S> */ B(LdaZero),
  /* 3196 E> */ B(StaCurrentContextSlotNoCell), U8(220),
  /* 3211 S> */ B(LdaZero),
  /* 3211 E> */ B(StaCurrentContextSlotNoCell), U8(221),
  /* 3226 S> */ B(LdaZero),
  /* 3226 E> */ B(StaCurrentContextSlotNoCell), U8(222),
  /* 3241 S> */ B(LdaZero),
  /* 3241 E> */ B(StaCurrentContextSlotNoCell), U8(223),
  /* 3256 S> */ B(LdaZero),
  /* 3256 E> */ B(StaCurrentContextSlotNoCell), U8(224),
  /* 3271 S> */ B(LdaZero),
  /* 3271 E> */ B(StaCurrentContextSlotNoCell), U8(225),
  /* 3286 S> */ B(LdaZero),
  /* 3286 E> */ B(StaCurrentContextSlotNoCell), U8(226),
  /* 3301 S> */ B(LdaZero),
  /* 3301 E> */ B(StaCurrentContextSlotNoCell), U8(227),
  /* 3316 S> */ B(LdaZero),
  /* 3316 E> */ B(StaCurrentContextSlotNoCell), U8(228),
  /* 3331 S> */ B(LdaZero),
  /* 3331 E> */ B(StaCurrentContextSlotNoCell), U8(229),
  /* 3346 S> */ B(LdaZero),
  /* 3346 E> */ B(StaCurrentContextSlotNoCell), U8(230),
  /* 3361 S> */ B(LdaZero),
  /* 3361 E> */ B(StaCurrentContextSlotNoCell), U8(231),
  /* 3376 S> */ B(LdaZero),
  /* 3376 E> */ B(StaCurrentContextSlotNoCell), U8(232),
  /* 3391 S> */ B(LdaZero),
  /* 3391 E> */ B(StaCurrentContextSlotNoCell), U8(233),
  /* 3406 S> */ B(LdaZero),
  /* 3406 E> */ B(StaCurrentContextSlotNoCell), U8(234),
  /* 3421 S> */ B(LdaZero),
  /* 3421 E> */ B(StaCurrentContextSlotNoCell), U8(235),
  /* 3436 S> */ B(LdaZero),
  /* 3436 E> */ B(StaCurrentContextSlotNoCell), U8(236),
  /* 3451 S> */ B(LdaZero),
  /* 3451 E> */ B(StaCurrentContextSlotNoCell), U8(237),
  /* 3466 S> */ B(LdaZero),
  /* 3466 E> */ B(StaCurrentContextSlotNoCell), U8(238),
  /* 3481 S> */ B(LdaZero),
  /* 3481 E> */ B(StaCurrentContextSlotNoCell), U8(239),
  /* 3496 S> */ B(LdaZero),
  /* 3496 E> */ B(StaCurrentContextSlotNoCell), U8(240),
  /* 3511 S> */ B(LdaZero),
  /* 3511 E> */ B(StaCurrentContextSlotNoCell), U8(241),
  /* 3526 S> */ B(LdaZero),
  /* 3526 E> */ B(StaCurrentContextSlotNoCell), U8(242),
  /* 3541 S> */ B(LdaZero),
  /* 3541 E> */ B(StaCurrentContextSlotNoCell), U8(243),
  /* 3556 S> */ B(LdaZero),
  /* 3556 E> */ B(StaCurrentContextSlotNoCell), U8(244),
  /* 3571 S> */ B(LdaZero),
  /* 3571 E> */ B(StaCurrentContextSlotNoCell), U8(245),
  /* 3586 S> */ B(LdaZero),
  /* 3586 E> */ B(StaCurrentContextSlotNoCell), U8(246),
  /* 3601 S> */ B(LdaZero),
  /* 3601 E> */ B(StaCurrentContextSlotNoCell), U8(247),
  /* 3616 S> */ B(LdaZero),
  /* 3616 E> */ B(StaCurrentContextSlotNoCell), U8(248),
  /* 3631 S> */ B(LdaZero),
  /* 3631 E> */ B(StaCurrentContextSlotNoCell), U8(249),
  /* 3646 S> */ B(LdaZero),
  /* 3646 E> */ B(StaCurrentContextSlotNoCell), U8(250),
  /* 3661 S> */ B(LdaZero),
  /* 3661 E> */ B(StaCurrentContextSlotNoCell), U8(251),
  /* 3676 S> */ B(LdaZero),
  /* 3676 E> */ B(StaCurrentContextSlotNoCell), U8(252),
  /* 3691 S> */ B(LdaZero),
  /* 3691 E> */ B(StaCurrentContextSlotNoCell), U8(253),
  /* 3706 S> */ B(LdaZero),
  /* 3706 E> */ B(StaCurrentContextSlotNoCell), U8(254),
  /* 3721 S> */ B(LdaZero),
  /* 3721 E> */ B(StaCurrentContextSlotNoCell), U8(255),
  /* 3724 S> */ B(LdaGlobal), U8(1), U8(0),
                B(Star2),
  /* 3724 E> */ B(CallUndefinedReceiver0), R(2), U8(2),
  /* 3740 S> */ B(LdaSmi), I8(100),
  /* 3740 E> */ B(Wide), B(StaCurrentContextSlotNoCell), U16(256),
  /* 3745 S> */ B(Wide), B(LdaCurrentContextSlotNoCell), U16(256),
  /* 3753 S> */ B(Return),
]
constant pool: [
  SCOPE_INFO_TYPE,
  INTERNALIZED_ONE_BYTE_STRING_TYPE ["eval"],
]
handlers: [
]

