#
# Autogenerated by generate-bytecode-expectations.
#

---
wrap: yes

---
snippet: "
  var a = 1; return ++a;
"
frame size: 1
parameter count: 1
bytecode array length: 7
bytecodes: [
  /*   42 S> */ B(LdaSmi), I8(1),
                B(Star0),
  /*   45 S> */ B(Inc), U8(0),
                B(Star0),
  /*   56 S> */ B(Return),
]
constant pool: [
]
handlers: [
]

---
snippet: "
  var a = 1; return a++;
"
frame size: 2
parameter count: 1
bytecode array length: 12
bytecodes: [
  /*   42 S> */ B(LdaSmi), I8(1),
                B(Star0),
  /*   45 S> */ B(ToNumeric), U8(0),
                B(Star1),
                B(Inc), U8(0),
                B(Star0),
                B(Ldar), R(1),
  /*   56 S> */ B(Return),
]
constant pool: [
]
handlers: [
]

---
snippet: "
  var a = 1; return --a;
"
frame size: 1
parameter count: 1
bytecode array length: 7
bytecodes: [
  /*   42 S> */ B(LdaSmi), I8(1),
                B(Star0),
  /*   45 S> */ B(Dec), U8(0),
                B(Star0),
  /*   56 S> */ B(Return),
]
constant pool: [
]
handlers: [
]

---
snippet: "
  var a = 1; return a--;
"
frame size: 2
parameter count: 1
bytecode array length: 12
bytecodes: [
  /*   42 S> */ B(LdaSmi), I8(1),
                B(Star0),
  /*   45 S> */ B(ToNumeric), U8(0),
                B(Star1),
                B(Dec), U8(0),
                B(Star0),
                B(Ldar), R(1),
  /*   56 S> */ B(Return),
]
constant pool: [
]
handlers: [
]

---
snippet: "
  var a = { val: 1 }; return a.val++;
"
frame size: 4
parameter count: 1
bytecode array length: 22
bytecodes: [
  /*   42 S> */ B(CreateObjectLiteral), U8(0), U8(0), U8(41),
                B(Star0),
  /*   54 S> */ B(GetNamedProperty), R(0), U8(1), U8(1),
                B(ToNumeric), U8(3),
                B(Star2),
                B(Inc), U8(3),
                B(Star3),
  /*   66 E> */ B(SetNamedProperty), R(0), U8(1), U8(4),
                B(Ldar), R(2),
  /*   69 S> */ B(Return),
]
constant pool: [
  OBJECT_BOILERPLATE_DESCRIPTION_TYPE,
  INTERNALIZED_ONE_BYTE_STRING_TYPE ["val"],
]
handlers: [
]

---
snippet: "
  var a = { val: 1 }; return --a.val;
"
frame size: 3
parameter count: 1
bytecode array length: 19
bytecodes: [
  /*   42 S> */ B(CreateObjectLiteral), U8(0), U8(0), U8(41),
                B(Star0),
  /*   54 S> */ B(GetNamedProperty), R(0), U8(1), U8(1),
                B(Dec), U8(3),
                B(Star2),
  /*   65 E> */ B(SetNamedProperty), R(0), U8(1), U8(4),
                B(Ldar), R(2),
  /*   69 S> */ B(Return),
]
constant pool: [
  OBJECT_BOILERPLATE_DESCRIPTION_TYPE,
  INTERNALIZED_ONE_BYTE_STRING_TYPE ["val"],
]
handlers: [
]

---
snippet: "
  var name = 'var'; var a = { val: 1 }; return a[name]--;
"
frame size: 6
parameter count: 1
bytecode array length: 26
bytecodes: [
  /*   45 S> */ B(LdaConstant), U8(0),
                B(Star0),
  /*   60 S> */ B(CreateObjectLiteral), U8(1), U8(0), U8(41),
                B(Star1),
  /*   72 S> */ B(Ldar), R(0),
  /*   81 E> */ B(GetKeyedProperty), R(1), U8(1),
                B(ToNumeric), U8(3),
                B(Star4),
                B(Dec), U8(3),
                B(Star5),
  /*   86 E> */ B(SetKeyedProperty), R(1), R(0), U8(4),
                B(Ldar), R(4),
  /*   89 S> */ B(Return),
]
constant pool: [
  INTERNALIZED_ONE_BYTE_STRING_TYPE ["var"],
  OBJECT_BOILERPLATE_DESCRIPTION_TYPE,
]
handlers: [
]

---
snippet: "
  var name = 'var'; var a = { val: 1 }; return ++a[name];
"
frame size: 5
parameter count: 1
bytecode array length: 23
bytecodes: [
  /*   45 S> */ B(LdaConstant), U8(0),
                B(Star0),
  /*   60 S> */ B(CreateObjectLiteral), U8(1), U8(0), U8(41),
                B(Star1),
  /*   72 S> */ B(Ldar), R(0),
  /*   83 E> */ B(GetKeyedProperty), R(1), U8(1),
                B(Inc), U8(3),
                B(Star4),
  /*   87 E> */ B(SetKeyedProperty), R(1), R(0), U8(4),
                B(Ldar), R(4),
  /*   89 S> */ B(Return),
]
constant pool: [
  INTERNALIZED_ONE_BYTE_STRING_TYPE ["var"],
  OBJECT_BOILERPLATE_DESCRIPTION_TYPE,
]
handlers: [
]

---
snippet: "
  var a = 1; var b = function() { return a }; return ++a;
"
frame size: 2
parameter count: 1
bytecode array length: 21
bytecodes: [
  /*   30 E> */ B(CreateFunctionContextWithCells), U8(0), U8(1),
                B(PushContext), R(1),
  /*   42 S> */ B(LdaSmi), I8(1),
  /*   42 E> */ B(StaCurrentContextSlot), U8(2),
  /*   53 S> */ B(CreateClosure), U8(1), U8(0), U8(2),
                B(Star0),
  /*   78 S> */ B(LdaCurrentContextSlot), U8(2),
                B(Inc), U8(0),
  /*   87 E> */ B(StaCurrentContextSlot), U8(2),
  /*   89 S> */ B(Return),
]
constant pool: [
  SCOPE_INFO_TYPE,
  SHARED_FUNCTION_INFO_TYPE,
]
handlers: [
]

---
snippet: "
  var a = 1; var b = function() { return a }; return a--;
"
frame size: 3
parameter count: 1
bytecode array length: 26
bytecodes: [
  /*   30 E> */ B(CreateFunctionContextWithCells), U8(0), U8(1),
                B(PushContext), R(1),
  /*   42 S> */ B(LdaSmi), I8(1),
  /*   42 E> */ B(StaCurrentContextSlot), U8(2),
  /*   53 S> */ B(CreateClosure), U8(1), U8(0), U8(2),
                B(Star0),
  /*   78 S> */ B(LdaCurrentContextSlot), U8(2),
                B(ToNumeric), U8(0),
                B(Star2),
                B(Dec), U8(0),
  /*   86 E> */ B(StaCurrentContextSlot), U8(2),
                B(Ldar), R(2),
  /*   89 S> */ B(Return),
]
constant pool: [
  SCOPE_INFO_TYPE,
  SHARED_FUNCTION_INFO_TYPE,
]
handlers: [
]

---
snippet: "
  var idx = 1; var a = [1, 2]; return a[idx++] = 2;
"
frame size: 5
parameter count: 1
bytecode array length: 26
bytecodes: [
  /*   44 S> */ B(LdaSmi), I8(1),
                B(Star0),
  /*   55 S> */ B(CreateArrayLiteral), U8(0), U8(0), U8(37),
                B(Star1),
  /*   63 S> */ B(Ldar), R(0),
                B(ToNumeric), U8(1),
                B(Star3),
                B(Inc), U8(1),
                B(Star0),
                B(LdaSmi), I8(2),
                B(Star4),
  /*   79 E> */ B(SetKeyedProperty), R(1), R(3), U8(2),
                B(Ldar), R(4),
  /*   83 S> */ B(Return),
]
constant pool: [
  ARRAY_BOILERPLATE_DESCRIPTION_TYPE,
]
handlers: [
]

