#
# Autogenerated by generate-bytecode-expectations.
#

---
wrap: yes

---
snippet: "
  var a = {x:13, y:14}; return delete a.x;
"
frame size: 1
parameter count: 1
bytecode array length: 10
bytecodes: [
  /*   42 S> */ B(CreateObjectLiteral), U8(0), U8(0), U8(41),
                B(Star0),
  /*   56 S> */ B(LdaConstant), U8(1),
                B(DeletePropertySloppy), R(0),
  /*   74 S> */ B(Return),
]
constant pool: [
  OBJECT_BOILERPLATE_DESCRIPTION_TYPE,
  INTERNALIZED_ONE_BYTE_STRING_TYPE ["x"],
]
handlers: [
]

---
snippet: "
  'use strict'; var a = {x:13, y:14}; return delete a.x;
"
frame size: 1
parameter count: 1
bytecode array length: 10
bytecodes: [
  /*   56 S> */ B(CreateObjectLiteral), U8(0), U8(0), U8(41),
                B(Star0),
  /*   70 S> */ B(LdaConstant), U8(1),
                B(DeletePropertyStrict), R(0),
  /*   88 S> */ B(Return),
]
constant pool: [
  OBJECT_BOILERPLATE_DESCRIPTION_TYPE,
  INTERNALIZED_ONE_BYTE_STRING_TYPE ["x"],
]
handlers: [
]

---
snippet: "
  var a = {1:13, 2:14}; return delete a[2];
"
frame size: 1
parameter count: 1
bytecode array length: 10
bytecodes: [
  /*   42 S> */ B(CreateObjectLiteral), U8(0), U8(0), U8(41),
                B(Star0),
  /*   56 S> */ B(LdaSmi), I8(2),
                B(DeletePropertySloppy), R(0),
  /*   75 S> */ B(Return),
]
constant pool: [
  OBJECT_BOILERPLATE_DESCRIPTION_TYPE,
]
handlers: [
]

---
snippet: "
  var a = 10; return delete a;
"
frame size: 1
parameter count: 1
bytecode array length: 5
bytecodes: [
  /*   42 S> */ B(LdaSmi), I8(10),
                B(Star0),
  /*   46 S> */ B(LdaFalse),
  /*   62 S> */ B(Return),
]
constant pool: [
]
handlers: [
]

---
snippet: "
  'use strict';
  var a = {1:10};
  (function f1() {return a;});
  return delete a[1];
"
frame size: 2
parameter count: 1
bytecode array length: 23
bytecodes: [
  /*   30 E> */ B(CreateFunctionContextWithCells), U8(0), U8(1),
                B(PushContext), R(0),
  /*   56 S> */ B(CreateObjectLiteral), U8(1), U8(0), U8(41),
  /*   56 E> */ B(StaCurrentContextSlotNoCell), U8(2),
  /*   64 S> */ B(CreateClosure), U8(2), U8(0), U8(2),
  /*   93 S> */ B(LdaImmutableCurrentContextSlot), U8(2),
                B(Star1),
                B(LdaSmi), I8(1),
                B(DeletePropertyStrict), R(1),
  /*  112 S> */ B(Return),
]
constant pool: [
  SCOPE_INFO_TYPE,
  OBJECT_BOILERPLATE_DESCRIPTION_TYPE,
  SHARED_FUNCTION_INFO_TYPE,
]
handlers: [
]

---
snippet: "
  return delete 'test';
"
frame size: 0
parameter count: 1
bytecode array length: 2
bytecodes: [
  /*   34 S> */ B(LdaTrue),
  /*   55 S> */ B(Return),
]
constant pool: [
]
handlers: [
]

---
snippet: "
  return delete this;
"
frame size: 0
parameter count: 1
bytecode array length: 2
bytecodes: [
  /*   34 S> */ B(LdaTrue),
  /*   53 S> */ B(Return),
]
constant pool: [
]
handlers: [
]

