#
# Autogenerated by generate-bytecode-expectations.
#

---
wrap: yes

---
snippet: "
  var x, a = [0,1,2,3];
  [x] = a;
"
frame size: 14
parameter count: 1
bytecode array length: 122
bytecodes: [
  /*   45 S> */ B(CreateArrayLiteral), U8(0), U8(0), U8(37),
                B(Star1),
  /*   60 S> */ B(GetIterator), R(1), U8(1), U8(3),
                B(Star4),
                B(GetNamedProperty), R(4), U8(1), U8(5),
                B(Star3),
                B(LdaFalse),
                B(Mov), R(1), R(2),
                B(Star5),
                B(Mov), R(context), R(9),
                B(Ldar), R(5),
  /*   57 E> */ B(JumpIfToBooleanTrue), U8(33),
                B(LdaTrue),
                B(Star5),
                B(CallProperty0), R(3), R(4), U8(11),
                B(Star10),
                B(JumpIfJSReceiver), U8(7),
                B(CallRuntime), U16(Runtime::kThrowIteratorResultNotAnObject), R(10), U8(1),
                B(GetNamedProperty), R(10), U8(2), U8(9),
                B(JumpIfToBooleanTrue), U8(13),
                B(GetNamedProperty), R(10), U8(3), U8(7),
                B(Star10),
                B(LdaFalse),
                B(Star5),
                B(Ldar), R(10),
                B(Jump), U8(3),
                B(LdaUndefined),
                B(Star0),
                B(LdaSmi), I8(-1),
                B(Star7),
                B(Star6),
                B(Jump), U8(8),
                B(Star7),
                B(LdaZero),
                B(Star6),
                B(LdaTheHole),
                B(SetPendingMessage),
                B(Star8),
                B(Ldar), R(5),
                B(JumpIfToBooleanTrue), U8(35),
                B(Mov), R(context), R(11),
                B(GetNamedProperty), R(4), U8(4), U8(13),
                B(JumpIfUndefinedOrNull), U8(26),
                B(Star12),
                B(CallProperty0), R(12), R(4), U8(15),
                B(JumpIfJSReceiver), U8(19),
                B(Star13),
                B(CallRuntime), U16(Runtime::kThrowIteratorResultNotAnObject), R(13), U8(1),
                B(Jump), U8(11),
                B(Star11),
                B(LdaZero),
                B(TestReferenceEqual), R(6),
                B(JumpIfTrue), U8(5),
                B(Ldar), R(11),
                B(ReThrow),
                B(LdaZero),
                B(TestReferenceEqual), R(6),
                B(JumpIfFalse), U8(8),
                B(Ldar), R(8),
                B(SetPendingMessage),
                B(Ldar), R(7),
                B(ReThrow),
                B(LdaUndefined),
  /*   65 S> */ B(Return),
]
constant pool: [
  ARRAY_BOILERPLATE_DESCRIPTION_TYPE,
  INTERNALIZED_ONE_BYTE_STRING_TYPE ["next"],
  INTERNALIZED_ONE_BYTE_STRING_TYPE ["done"],
  INTERNALIZED_ONE_BYTE_STRING_TYPE ["value"],
  INTERNALIZED_ONE_BYTE_STRING_TYPE ["return"],
]
handlers: [
  [23, 60, 66],
  [79, 98, 100],
]

---
snippet: "
  var x, y, a = [0,1,2,3];
  [,x,...y] = a;
"
frame size: 15
parameter count: 1
bytecode array length: 197
bytecodes: [
  /*   48 S> */ B(CreateArrayLiteral), U8(0), U8(0), U8(37),
                B(Star2),
  /*   69 S> */ B(GetIterator), R(2), U8(1), U8(3),
                B(Star5),
                B(GetNamedProperty), R(5), U8(1), U8(5),
                B(Star4),
                B(LdaFalse),
                B(Mov), R(2), R(3),
                B(Star6),
                B(Mov), R(context), R(10),
                B(Ldar), R(6),
                B(JumpIfToBooleanTrue), U8(24),
                B(LdaTrue),
                B(Star6),
                B(CallProperty0), R(4), R(5), U8(11),
                B(Star11),
                B(JumpIfJSReceiver), U8(7),
                B(CallRuntime), U16(Runtime::kThrowIteratorResultNotAnObject), R(11), U8(1),
                B(GetNamedProperty), R(11), U8(2), U8(9),
                B(JumpIfToBooleanTrue), U8(4),
                B(LdaFalse),
                B(Star6),
                B(Ldar), R(6),
  /*   61 E> */ B(JumpIfToBooleanTrue), U8(33),
                B(LdaTrue),
                B(Star6),
                B(CallProperty0), R(4), R(5), U8(13),
                B(Star11),
                B(JumpIfJSReceiver), U8(7),
                B(CallRuntime), U16(Runtime::kThrowIteratorResultNotAnObject), R(11), U8(1),
                B(GetNamedProperty), R(11), U8(2), U8(9),
                B(JumpIfToBooleanTrue), U8(13),
                B(GetNamedProperty), R(11), U8(3), U8(7),
                B(Star11),
                B(LdaFalse),
                B(Star6),
                B(Ldar), R(11),
                B(Jump), U8(3),
                B(LdaUndefined),
                B(Star0),
  /*   63 E> */ B(CreateEmptyArrayLiteral), U8(15),
                B(Star12),
                B(Ldar), R(6),
                B(JumpIfToBooleanTrue), U8(41),
                B(LdaZero),
                B(Star13),
                B(LdaTrue),
                B(Star6),
                B(CallProperty0), R(4), R(5), U8(19),
                B(Star11),
                B(JumpIfJSReceiver), U8(7),
                B(CallRuntime), U16(Runtime::kThrowIteratorResultNotAnObject), R(11), U8(1),
                B(GetNamedProperty), R(11), U8(2), U8(21),
                B(JumpIfToBooleanTrue), U8(19),
                B(GetNamedProperty), R(11), U8(3), U8(7),
                B(StaInArrayLiteral), R(12), R(13), U8(16),
                B(Ldar), R(13),
                B(Inc), U8(18),
                B(Star13),
                B(JumpLoop), U8(31), I8(0), U8(23),
                B(Mov), R(12), R(1),
                B(LdaSmi), I8(-1),
                B(Star8),
                B(Star7),
                B(Jump), U8(8),
                B(Star8),
                B(LdaZero),
                B(Star7),
                B(LdaTheHole),
                B(SetPendingMessage),
                B(Star9),
                B(Ldar), R(6),
                B(JumpIfToBooleanTrue), U8(35),
                B(Mov), R(context), R(12),
                B(GetNamedProperty), R(5), U8(4), U8(24),
                B(JumpIfUndefinedOrNull), U8(26),
                B(Star13),
                B(CallProperty0), R(13), R(5), U8(26),
                B(JumpIfJSReceiver), U8(19),
                B(Star14),
                B(CallRuntime), U16(Runtime::kThrowIteratorResultNotAnObject), R(14), U8(1),
                B(Jump), U8(11),
                B(Star12),
                B(LdaZero),
                B(TestReferenceEqual), R(7),
                B(JumpIfTrue), U8(5),
                B(Ldar), R(12),
                B(ReThrow),
                B(LdaZero),
                B(TestReferenceEqual), R(7),
                B(JumpIfFalse), U8(8),
                B(Ldar), R(9),
                B(SetPendingMessage),
                B(Ldar), R(8),
                B(ReThrow),
                B(LdaUndefined),
  /*   74 S> */ B(Return),
]
constant pool: [
  ARRAY_BOILERPLATE_DESCRIPTION_TYPE,
  INTERNALIZED_ONE_BYTE_STRING_TYPE ["next"],
  INTERNALIZED_ONE_BYTE_STRING_TYPE ["done"],
  INTERNALIZED_ONE_BYTE_STRING_TYPE ["value"],
  INTERNALIZED_ONE_BYTE_STRING_TYPE ["return"],
]
handlers: [
  [23, 135, 141],
  [154, 173, 175],
]

---
snippet: "
  var x={}, y, a = [0];
  [x.foo,y=4] = a;
"
frame size: 16
parameter count: 1
bytecode array length: 168
bytecodes: [
  /*   40 S> */ B(CreateEmptyObjectLiteral),
                B(Star0),
  /*   51 S> */ B(CreateArrayLiteral), U8(0), U8(0), U8(37),
                B(Star2),
  /*   68 S> */ B(GetIterator), R(2), U8(1), U8(3),
                B(Star5),
                B(GetNamedProperty), R(5), U8(1), U8(5),
                B(Star4),
                B(LdaFalse),
                B(Mov), R(2), R(3),
                B(Star6),
                B(Mov), R(context), R(10),
                B(Ldar), R(6),
                B(Mov), R(0), R(12),
  /*   57 E> */ B(JumpIfToBooleanTrue), U8(33),
                B(LdaTrue),
                B(Star6),
                B(CallProperty0), R(4), R(5), U8(11),
                B(Star11),
                B(JumpIfJSReceiver), U8(7),
                B(CallRuntime), U16(Runtime::kThrowIteratorResultNotAnObject), R(11), U8(1),
                B(GetNamedProperty), R(11), U8(2), U8(9),
                B(JumpIfToBooleanTrue), U8(13),
                B(GetNamedProperty), R(11), U8(3), U8(7),
                B(Star11),
                B(LdaFalse),
                B(Star6),
                B(Ldar), R(11),
                B(Jump), U8(3),
                B(LdaUndefined),
                B(SetNamedProperty), R(12), U8(4), U8(13),
                B(Ldar), R(6),
  /*   63 E> */ B(JumpIfToBooleanTrue), U8(33),
                B(LdaTrue),
                B(Star6),
                B(CallProperty0), R(4), R(5), U8(15),
                B(Star11),
                B(JumpIfJSReceiver), U8(7),
                B(CallRuntime), U16(Runtime::kThrowIteratorResultNotAnObject), R(11), U8(1),
                B(GetNamedProperty), R(11), U8(2), U8(9),
                B(JumpIfToBooleanTrue), U8(13),
                B(GetNamedProperty), R(11), U8(3), U8(7),
                B(Star11),
                B(LdaFalse),
                B(Star6),
                B(Ldar), R(11),
                B(JumpIfNotUndefined), U8(4),
                B(LdaSmi), I8(4),
                B(Star1),
                B(LdaSmi), I8(-1),
                B(Star8),
                B(Star7),
                B(Jump), U8(8),
                B(Star8),
                B(LdaZero),
                B(Star7),
                B(LdaTheHole),
                B(SetPendingMessage),
                B(Star9),
                B(Ldar), R(6),
                B(JumpIfToBooleanTrue), U8(35),
                B(Mov), R(context), R(13),
                B(GetNamedProperty), R(5), U8(5), U8(17),
                B(JumpIfUndefinedOrNull), U8(26),
                B(Star14),
                B(CallProperty0), R(14), R(5), U8(19),
                B(JumpIfJSReceiver), U8(19),
                B(Star15),
                B(CallRuntime), U16(Runtime::kThrowIteratorResultNotAnObject), R(15), U8(1),
                B(Jump), U8(11),
                B(Star13),
                B(LdaZero),
                B(TestReferenceEqual), R(7),
                B(JumpIfTrue), U8(5),
                B(Ldar), R(13),
                B(ReThrow),
                B(LdaZero),
                B(TestReferenceEqual), R(7),
                B(JumpIfFalse), U8(8),
                B(Ldar), R(9),
                B(SetPendingMessage),
                B(Ldar), R(8),
                B(ReThrow),
                B(LdaUndefined),
  /*   73 S> */ B(Return),
]
constant pool: [
  ARRAY_BOILERPLATE_DESCRIPTION_TYPE,
  INTERNALIZED_ONE_BYTE_STRING_TYPE ["next"],
  INTERNALIZED_ONE_BYTE_STRING_TYPE ["done"],
  INTERNALIZED_ONE_BYTE_STRING_TYPE ["value"],
  INTERNALIZED_ONE_BYTE_STRING_TYPE ["foo"],
  INTERNALIZED_ONE_BYTE_STRING_TYPE ["return"],
]
handlers: [
  [25, 106, 112],
  [125, 144, 146],
]

---
snippet: "
  var x, a = {x:1};
  ({x} = a);
"
frame size: 2
parameter count: 1
bytecode array length: 12
bytecodes: [
  /*   45 S> */ B(CreateObjectLiteral), U8(0), U8(0), U8(41),
                B(Star1),
  /*   54 S> */ B(GetNamedProperty), R(1), U8(1), U8(1),
                B(Star0),
                B(LdaUndefined),
  /*   63 S> */ B(Return),
]
constant pool: [
  OBJECT_BOILERPLATE_DESCRIPTION_TYPE,
  INTERNALIZED_ONE_BYTE_STRING_TYPE ["x"],
]
handlers: [
]

---
snippet: "
  var x={}, a = {y:1};
  ({y:x.foo} = a);
"
frame size: 2
parameter count: 1
bytecode array length: 17
bytecodes: [
  /*   40 S> */ B(CreateEmptyObjectLiteral),
                B(Star0),
  /*   48 S> */ B(CreateObjectLiteral), U8(0), U8(0), U8(41),
                B(Star1),
  /*   59 S> */ B(GetNamedProperty), R(1), U8(1), U8(1),
                B(SetNamedProperty), R(0), U8(2), U8(3),
                B(LdaUndefined),
  /*   72 S> */ B(Return),
]
constant pool: [
  OBJECT_BOILERPLATE_DESCRIPTION_TYPE,
  INTERNALIZED_ONE_BYTE_STRING_TYPE ["y"],
  INTERNALIZED_ONE_BYTE_STRING_TYPE ["foo"],
]
handlers: [
]

---
snippet: "
  var x, a = {y:1, w:2, v:3};
  ({x=0,...y} = a);
"
frame size: 4
parameter count: 1
bytecode array length: 28
bytecodes: [
  /*   45 S> */ B(CreateObjectLiteral), U8(0), U8(0), U8(41),
                B(Star1),
  /*   62 S> */ B(LdaConstant), U8(1),
                B(Star3),
  /*   64 E> */ B(GetNamedProperty), R(1), U8(1), U8(1),
                B(Mov), R(1), R(2),
                B(JumpIfNotUndefined), U8(3),
                B(LdaZero),
                B(Star0),
  /*   71 E> */ B(InvokeIntrinsic), U8(Runtime::k_CopyDataPropertiesWithExcludedPropertiesOnStack), R(2), U8(2),
                B(StaGlobal), U8(2), U8(3),
                B(LdaUndefined),
  /*   80 S> */ B(Return),
]
constant pool: [
  OBJECT_BOILERPLATE_DESCRIPTION_TYPE,
  INTERNALIZED_ONE_BYTE_STRING_TYPE ["x"],
  INTERNALIZED_ONE_BYTE_STRING_TYPE ["y"],
]
handlers: [
]

