#
# Autogenerated by generate-bytecode-expectations.
#

---
wrap: no
test function name: f
extra flags: --ignition-elide-redundant-tdz-checks

---
snippet: "
  {
    f = function f(a) {
  x; x;
    }
    let w, x, y, z;
    f();
  }
"
frame size: 0
parameter count: 2
bytecode array length: 6
bytecodes: [
  /*   24 S> */ B(LdaImmutableCurrentContextSlot), C8(2),
                B(ThrowReferenceErrorIfHole), U8(0:"x"),
  /*   27 S> */ B(LdaUndefined),
  /*   32 S> */ B(Return),
]
constant pool: [
  INTERNALIZED_ONE_BYTE_STRING_TYPE ["x"],
]
handlers: [
]

---
snippet: "
  {
    f = function f(a) {
  if (x) { y; }
  x + y;
    }
    let w, x, y, z;
    f();
  }
"
frame size: 1
parameter count: 2
bytecode array length: 22
bytecodes: [
  /*   24 S> */ B(LdaImmutableCurrentContextSlot), C8(2),
                B(ThrowReferenceErrorIfHole), U8(0:"x"),
                B(JumpIfToBooleanFalse), U8(6),
  /*   33 S> */ B(LdaImmutableCurrentContextSlot), C8(3),
                B(ThrowReferenceErrorIfHole), U8(1:"y"),
  /*   38 S> */ B(LdaImmutableCurrentContextSlot), C8(2),
                B(Star0),
                B(LdaImmutableCurrentContextSlot), C8(3),
  /*   42 E> */ B(ThrowReferenceErrorIfHole), U8(1:"y"),
  /*   40 E> */ B(Add), R(0), FBV(0),
                B(LdaUndefined),
  /*   47 S> */ B(Return),
]
constant pool: [
  INTERNALIZED_ONE_BYTE_STRING_TYPE ["x"],
  INTERNALIZED_ONE_BYTE_STRING_TYPE ["y"],
]
handlers: [
]

---
snippet: "
  {
    f = function f(a) {
  if (a) { x; y; } else { x; z; }
  x; y; z;
    }
    let w, x, y, z;
    f();
  }
"
frame size: 0
parameter count: 2
bytecode array length: 34
bytecodes: [
  /*   24 S> */ B(Ldar), R(arg0),
                B(JumpIfToBooleanFalse), U8(12),
  /*   33 S> */ B(LdaImmutableCurrentContextSlot), C8(2),
                B(ThrowReferenceErrorIfHole), U8(0:"x"),
  /*   36 S> */ B(LdaImmutableCurrentContextSlot), C8(3),
                B(ThrowReferenceErrorIfHole), U8(1:"y"),
                B(Jump), U8(10),
  /*   48 S> */ B(LdaImmutableCurrentContextSlot), C8(2),
                B(ThrowReferenceErrorIfHole), U8(0:"x"),
  /*   51 S> */ B(LdaImmutableCurrentContextSlot), C8(4),
                B(ThrowReferenceErrorIfHole), U8(2:"z"),
  /*   56 S> */ B(LdaImmutableCurrentContextSlot), C8(2),
  /*   59 S> */ B(LdaImmutableCurrentContextSlot), C8(3),
                B(ThrowReferenceErrorIfHole), U8(1:"y"),
  /*   62 S> */ B(LdaImmutableCurrentContextSlot), C8(4),
                B(ThrowReferenceErrorIfHole), U8(2:"z"),
                B(LdaUndefined),
  /*   67 S> */ B(Return),
]
constant pool: [
  INTERNALIZED_ONE_BYTE_STRING_TYPE ["x"],
  INTERNALIZED_ONE_BYTE_STRING_TYPE ["y"],
  INTERNALIZED_ONE_BYTE_STRING_TYPE ["z"],
]
handlers: [
]

---
snippet: "
  {
    f = function f(a) {
  while (x) { y; }
  x; y;
    }
    let w, x, y, z;
    f();
  }
"
frame size: 0
parameter count: 2
bytecode array length: 22
bytecodes: [
  /*   31 S> */ B(LdaImmutableCurrentContextSlot), C8(2),
                B(ThrowReferenceErrorIfHole), U8(0:"x"),
                B(JumpIfToBooleanFalse), U8(10),
  /*   36 S> */ B(LdaImmutableCurrentContextSlot), C8(3),
                B(ThrowReferenceErrorIfHole), U8(1:"y"),
  /*   24 E> */ B(JumpLoop), U8(10), I8(0), FBV(0),
  /*   41 S> */ B(LdaImmutableCurrentContextSlot), C8(2),
  /*   44 S> */ B(LdaImmutableCurrentContextSlot), C8(3),
                B(ThrowReferenceErrorIfHole), U8(1:"y"),
                B(LdaUndefined),
  /*   49 S> */ B(Return),
]
constant pool: [
  INTERNALIZED_ONE_BYTE_STRING_TYPE ["x"],
  INTERNALIZED_ONE_BYTE_STRING_TYPE ["y"],
]
handlers: [
]

---
snippet: "
  {
    f = function f(a) {
  do { x; } while (y);
  x; y;
    }
    let w, x, y, z;
    f();
  }
"
frame size: 0
parameter count: 2
bytecode array length: 20
bytecodes: [
  /*   29 S> */ B(LdaImmutableCurrentContextSlot), C8(2),
                B(ThrowReferenceErrorIfHole), U8(0:"x"),
  /*   41 S> */ B(LdaImmutableCurrentContextSlot), C8(3),
                B(ThrowReferenceErrorIfHole), U8(1:"y"),
                B(JumpIfToBooleanFalse), U8(6),
  /*   24 E> */ B(JumpLoop), U8(10), I8(0), FBV(0),
  /*   45 S> */ B(LdaImmutableCurrentContextSlot), C8(2),
                B(ThrowReferenceErrorIfHole), U8(0:"x"),
  /*   48 S> */ B(LdaUndefined),
  /*   53 S> */ B(Return),
]
constant pool: [
  INTERNALIZED_ONE_BYTE_STRING_TYPE ["x"],
  INTERNALIZED_ONE_BYTE_STRING_TYPE ["y"],
]
handlers: [
]

---
snippet: "
  {
    f = function f(a) {
  do { x; break; } while (y);
  x; y;
    }
    let w, x, y, z;
    f();
  }
"
frame size: 0
parameter count: 2
bytecode array length: 16
bytecodes: [
  /*   29 S> */ B(LdaImmutableCurrentContextSlot), C8(2),
                B(ThrowReferenceErrorIfHole), U8(0:"x"),
  /*   32 S> */ B(Jump), U8(2),
  /*   52 S> */ B(LdaImmutableCurrentContextSlot), C8(2),
                B(ThrowReferenceErrorIfHole), U8(0:"x"),
  /*   55 S> */ B(LdaImmutableCurrentContextSlot), C8(3),
                B(ThrowReferenceErrorIfHole), U8(1:"y"),
                B(LdaUndefined),
  /*   60 S> */ B(Return),
]
constant pool: [
  INTERNALIZED_ONE_BYTE_STRING_TYPE ["x"],
  INTERNALIZED_ONE_BYTE_STRING_TYPE ["y"],
]
handlers: [
]

---
snippet: "
  {
    f = function f(a) {
  for (x; y; z) { w; }
  x; y; z; w;
    }
    let w, x, y, z;
    f();
  }
"
frame size: 0
parameter count: 2
bytecode array length: 36
bytecodes: [
  /*   29 S> */ B(LdaImmutableCurrentContextSlot), C8(3),
                B(ThrowReferenceErrorIfHole), U8(0:"x"),
  /*   32 S> */ B(LdaImmutableCurrentContextSlot), C8(4),
                B(ThrowReferenceErrorIfHole), U8(1:"y"),
                B(JumpIfToBooleanFalse), U8(14),
  /*   40 S> */ B(LdaImmutableCurrentContextSlot), C8(2),
                B(ThrowReferenceErrorIfHole), U8(2:"w"),
  /*   35 S> */ B(LdaImmutableCurrentContextSlot), C8(5),
                B(ThrowReferenceErrorIfHole), U8(3:"z"),
  /*   24 E> */ B(JumpLoop), U8(14), I8(0), FBV(0),
  /*   45 S> */ B(LdaImmutableCurrentContextSlot), C8(3),
  /*   48 S> */ B(LdaImmutableCurrentContextSlot), C8(4),
  /*   51 S> */ B(LdaImmutableCurrentContextSlot), C8(5),
                B(ThrowReferenceErrorIfHole), U8(3:"z"),
  /*   54 S> */ B(LdaImmutableCurrentContextSlot), C8(2),
                B(ThrowReferenceErrorIfHole), U8(2:"w"),
                B(LdaUndefined),
  /*   59 S> */ B(Return),
]
constant pool: [
  INTERNALIZED_ONE_BYTE_STRING_TYPE ["x"],
  INTERNALIZED_ONE_BYTE_STRING_TYPE ["y"],
  INTERNALIZED_ONE_BYTE_STRING_TYPE ["w"],
  INTERNALIZED_ONE_BYTE_STRING_TYPE ["z"],
]
handlers: [
]

---
snippet: "
  {
    f = function f(a) {
  for (x in [y]) { z; }
  x; y; z;
    }
    let w, x, y, z;
    f();
  }
"
frame size: 6
parameter count: 2
bytecode array length: 70
bytecodes: [
  /*   34 S> */ B(CreateArrayLiteral), U8(0:ARRAY_BOILERPLATE_DESCRIPTION_TYPE), FBV(1), Flag8(0x25),
                B(Star0),
                B(LdaZero),
                B(Star1),
                B(LdaImmutableCurrentContextSlot), C8(3),
  /*   35 E> */ B(ThrowReferenceErrorIfHole), U8(1:"y"),
                B(StaInArrayLiteral), R(0), R(1), FBV(2),
                B(Ldar), R(0),
                B(JumpIfUndefinedOrNull), U8(41),
                B(ToObject), R(0),
                B(ForInEnumerate), R(0),
                B(ForInPrepare), R(1), FBV(0),
                B(LdaZero),
                B(Star4),
  /*   29 s> */ B(JumpIfForInDone), U8(30), R(4), R(3),
                B(ForInNext), R(0), R(4), R(1), FBV(0),
                B(JumpIfUndefined), U8(15),
  /*   29 S> */ B(Star5),
                B(LdaCurrentContextSlotNoCell), C8(2),
                B(ThrowReferenceErrorIfHole), U8(2:"x"),
                B(Ldar), R(5),
                B(StaCurrentContextSlotNoCell), C8(2),
  /*   41 S> */ B(LdaImmutableCurrentContextSlot), C8(4),
                B(ThrowReferenceErrorIfHole), U8(3:"z"),
                B(ForInStep), R(4),
  /*   24 E> */ B(JumpLoop), U8(26), I8(0), FBV(4),
  /*   46 S> */ B(LdaCurrentContextSlotNoCell), C8(2),
                B(ThrowReferenceErrorIfHole), U8(2:"x"),
  /*   49 S> */ B(LdaImmutableCurrentContextSlot), C8(3),
  /*   52 S> */ B(LdaImmutableCurrentContextSlot), C8(4),
                B(ThrowReferenceErrorIfHole), U8(3:"z"),
                B(LdaUndefined),
  /*   57 S> */ B(Return),
]
constant pool: [
  ARRAY_BOILERPLATE_DESCRIPTION_TYPE,
  INTERNALIZED_ONE_BYTE_STRING_TYPE ["y"],
  INTERNALIZED_ONE_BYTE_STRING_TYPE ["x"],
  INTERNALIZED_ONE_BYTE_STRING_TYPE ["z"],
]
handlers: [
]

---
snippet: "
  {
    f = function f(a) {
  for (x of [y]) { z; }
  x; y; z;
    }
    let w, x, y, z;
    f();
  }
"
frame size: 11
parameter count: 2
bytecode array length: 147
bytecodes: [
  /*   34 S> */ B(CreateArrayLiteral), U8(0:ARRAY_BOILERPLATE_DESCRIPTION_TYPE), FBV(0), Flag8(0x25),
                B(Star0),
                B(LdaZero),
                B(Star1),
                B(LdaImmutableCurrentContextSlot), C8(3),
  /*   35 E> */ B(ThrowReferenceErrorIfHole), U8(1:"y"),
                B(StaInArrayLiteral), R(0), R(1), FBV(1),
                B(GetIterator), R(0), FBV(3), FBV(5),
                B(Star1),
                B(GetNamedProperty), R(1), U8(2:"next"), FBV(7),
                B(Star0),
                B(LdaFalse),
                B(Star3),
                B(LdaTheHole),
                B(Star6),
                B(Mov), R(context), R(7),
                B(LdaTrue),
                B(Star3),
  /*   29 s> */ B(CallProperty0), R(0), R(1), FBV(9),
                B(Star2),
                B(JumpIfJSReceiver), U8(7),
                B(CallRuntime), U16(Runtime::kThrowIteratorResultNotAnObject), R(2), RegCount8(1),
                B(GetNamedProperty), R(2), U8(3:"done"), FBV(11),
                B(JumpIfToBooleanTrue), U8(25),
                B(GetNamedProperty), R(2), U8(4:"value"), FBV(13),
                B(Star2),
                B(LdaFalse),
  /*   29 S> */ B(Star3),
                B(LdaCurrentContextSlotNoCell), C8(2),
                B(ThrowReferenceErrorIfHole), U8(5:"x"),
                B(Ldar), R(2),
                B(StaCurrentContextSlotNoCell), C8(2),
  /*   41 S> */ B(LdaImmutableCurrentContextSlot), C8(4),
                B(ThrowReferenceErrorIfHole), U8(6:"z"),
  /*   24 E> */ B(JumpLoop), U8(39), I8(0), FBV(15),
                B(LdaSmi), I8(-1),
                B(Star5),
                B(Star4),
                B(Jump), U8(8),
                B(Star5),
                B(LdaZero),
                B(Star4),
                B(LdaTheHole),
                B(SetPendingMessage),
                B(Star6),
                B(Ldar), R(3),
                B(JumpIfToBooleanTrue), U8(35),
                B(Mov), R(context), R(8),
                B(GetNamedProperty), R(1), U8(7:"return"), FBV(16),
                B(JumpIfUndefinedOrNull), U8(26),
                B(Star9),
                B(CallProperty0), R(9), R(1), FBV(18),
                B(JumpIfJSReceiver), U8(19),
                B(Star10),
                B(CallRuntime), U16(Runtime::kThrowIteratorResultNotAnObject), R(10), RegCount8(1),
                B(Jump), U8(11),
                B(Star8),
                B(LdaZero),
                B(TestReferenceEqual), R(4),
                B(JumpIfTrue), U8(5),
                B(Ldar), R(8),
                B(ReThrow),
                B(LdaZero),
                B(TestReferenceEqual), R(4),
                B(JumpIfFalse), U8(8),
                B(Ldar), R(6),
                B(SetPendingMessage),
                B(Ldar), R(5),
                B(ReThrow),
  /*   46 S> */ B(LdaCurrentContextSlotNoCell), C8(2),
                B(ThrowReferenceErrorIfHole), U8(5:"x"),
  /*   49 S> */ B(LdaImmutableCurrentContextSlot), C8(3),
  /*   52 S> */ B(LdaImmutableCurrentContextSlot), C8(4),
                B(ThrowReferenceErrorIfHole), U8(6:"z"),
                B(LdaUndefined),
  /*   57 S> */ B(Return),
]
constant pool: [
  ARRAY_BOILERPLATE_DESCRIPTION_TYPE,
  INTERNALIZED_ONE_BYTE_STRING_TYPE ["y"],
  INTERNALIZED_ONE_BYTE_STRING_TYPE ["next"],
  INTERNALIZED_ONE_BYTE_STRING_TYPE ["done"],
  INTERNALIZED_ONE_BYTE_STRING_TYPE ["value"],
  INTERNALIZED_ONE_BYTE_STRING_TYPE ["x"],
  INTERNALIZED_ONE_BYTE_STRING_TYPE ["z"],
  INTERNALIZED_ONE_BYTE_STRING_TYPE ["return"],
]
handlers: [
  [32, 75, 81],
  [94, 113, 115],
]

---
snippet: "
  {
    f = function f(a) {
  try { x; } catch (y) { y; z; } finally { w; }
  x; y; z; w;
    }
    let w, x, y, z;
    f();
  }
"
frame size: 6
parameter count: 2
bytecode array length: 76
bytecodes: [
                B(LdaTheHole),
                B(Star2),
                B(Mov), R(context), R(3),
                B(Mov), R(context), R(4),
  /*   30 S> */ B(LdaImmutableCurrentContextSlot), C8(3),
                B(ThrowReferenceErrorIfHole), U8(0:"x"),
                B(Jump), U8(23),
                B(Star5),
                B(CreateCatchContext), R(5), U8(1:SCOPE_INFO_TYPE),
                B(Star4),
                B(LdaTheHole),
                B(SetPendingMessage),
                B(Ldar), R(4),
                B(PushContext), R(5),
  /*   47 S> */ B(LdaImmutableCurrentContextSlot), C8(2),
  /*   50 S> */ B(LdaImmutableContextSlot), R(5), C8(5), U8(0),
                B(ThrowReferenceErrorIfHole), U8(2:"z"),
                B(PopContext), R(5),
                B(LdaSmi), I8(-1),
                B(Star1),
                B(Star0),
                B(Jump), U8(8),
                B(Star1),
                B(LdaZero),
                B(Star0),
                B(LdaTheHole),
                B(SetPendingMessage),
                B(Star2),
  /*   65 S> */ B(LdaImmutableCurrentContextSlot), C8(2),
                B(ThrowReferenceErrorIfHole), U8(3:"w"),
                B(LdaZero),
                B(TestReferenceEqual), R(0),
                B(JumpIfFalse), U8(8),
                B(Ldar), R(2),
                B(SetPendingMessage),
                B(Ldar), R(1),
                B(ReThrow),
  /*   70 S> */ B(LdaImmutableCurrentContextSlot), C8(3),
                B(ThrowReferenceErrorIfHole), U8(0:"x"),
  /*   73 S> */ B(LdaImmutableCurrentContextSlot), C8(4),
                B(ThrowReferenceErrorIfHole), U8(4:"y"),
  /*   76 S> */ B(LdaImmutableCurrentContextSlot), C8(5),
                B(ThrowReferenceErrorIfHole), U8(2:"z"),
  /*   79 S> */ B(LdaUndefined),
  /*   84 S> */ B(Return),
]
constant pool: [
  INTERNALIZED_ONE_BYTE_STRING_TYPE ["x"],
  SCOPE_INFO_TYPE,
  INTERNALIZED_ONE_BYTE_STRING_TYPE ["z"],
  INTERNALIZED_ONE_BYTE_STRING_TYPE ["w"],
  INTERNALIZED_ONE_BYTE_STRING_TYPE ["y"],
]
handlers: [
  [5, 35, 41],
  [8, 12, 14],
]

---
snippet: "
  {
    f = function f(a) {
  let { p = x } = { p: 42 }
  x;
    }
    let w, x, y, z;
    f();
  }
"
frame size: 2
parameter count: 2
bytecode array length: 22
bytecodes: [
  /*   40 S> */ B(CreateObjectLiteral), U8(0:OBJECT_BOILERPLATE_DESCRIPTION_TYPE), FBV(0), Flag8(0x29),
                B(Star1),
  /*   30 E> */ B(GetNamedProperty), R(1), U8(1:"p"), FBV(1),
                B(JumpIfNotUndefined), U8(6),
                B(LdaImmutableCurrentContextSlot), C8(2),
  /*   34 E> */ B(ThrowReferenceErrorIfHole), U8(2:"x"),
                B(Star0),
  /*   50 S> */ B(LdaImmutableCurrentContextSlot), C8(2),
                B(ThrowReferenceErrorIfHole), U8(2:"x"),
                B(LdaUndefined),
  /*   55 S> */ B(Return),
]
constant pool: [
  OBJECT_BOILERPLATE_DESCRIPTION_TYPE,
  INTERNALIZED_ONE_BYTE_STRING_TYPE ["p"],
  INTERNALIZED_ONE_BYTE_STRING_TYPE ["x"],
]
handlers: [
]

---
snippet: "
  {
    f = function f(a) {
  let res = x && y && z
  x; y; z;
    }
    let w, x, y, z;
    f();
  }
"
frame size: 1
parameter count: 2
bytecode array length: 29
bytecodes: [
  /*   34 S> */ B(LdaImmutableCurrentContextSlot), C8(2),
                B(ThrowReferenceErrorIfHole), U8(0:"x"),
                B(JumpIfToBooleanFalse), U8(12),
                B(LdaImmutableCurrentContextSlot), C8(3),
  /*   39 E> */ B(ThrowReferenceErrorIfHole), U8(1:"y"),
                B(JumpIfToBooleanFalse), U8(6),
                B(LdaImmutableCurrentContextSlot), C8(4),
  /*   44 E> */ B(ThrowReferenceErrorIfHole), U8(2:"z"),
                B(Star0),
  /*   46 S> */ B(LdaImmutableCurrentContextSlot), C8(2),
  /*   49 S> */ B(LdaImmutableCurrentContextSlot), C8(3),
                B(ThrowReferenceErrorIfHole), U8(1:"y"),
  /*   52 S> */ B(LdaImmutableCurrentContextSlot), C8(4),
                B(ThrowReferenceErrorIfHole), U8(2:"z"),
                B(LdaUndefined),
  /*   57 S> */ B(Return),
]
constant pool: [
  INTERNALIZED_ONE_BYTE_STRING_TYPE ["x"],
  INTERNALIZED_ONE_BYTE_STRING_TYPE ["y"],
  INTERNALIZED_ONE_BYTE_STRING_TYPE ["z"],
]
handlers: [
]

---
snippet: "
  {
    f = function f(a) {
  let res = x || y || z
  x; y; z;
    }
    let w, x, y, z;
    f();
  }
"
frame size: 1
parameter count: 2
bytecode array length: 29
bytecodes: [
  /*   34 S> */ B(LdaImmutableCurrentContextSlot), C8(2),
                B(ThrowReferenceErrorIfHole), U8(0:"x"),
                B(JumpIfToBooleanTrue), U8(12),
                B(LdaImmutableCurrentContextSlot), C8(3),
  /*   39 E> */ B(ThrowReferenceErrorIfHole), U8(1:"y"),
                B(JumpIfToBooleanTrue), U8(6),
                B(LdaImmutableCurrentContextSlot), C8(4),
  /*   44 E> */ B(ThrowReferenceErrorIfHole), U8(2:"z"),
                B(Star0),
  /*   46 S> */ B(LdaImmutableCurrentContextSlot), C8(2),
  /*   49 S> */ B(LdaImmutableCurrentContextSlot), C8(3),
                B(ThrowReferenceErrorIfHole), U8(1:"y"),
  /*   52 S> */ B(LdaImmutableCurrentContextSlot), C8(4),
                B(ThrowReferenceErrorIfHole), U8(2:"z"),
                B(LdaUndefined),
  /*   57 S> */ B(Return),
]
constant pool: [
  INTERNALIZED_ONE_BYTE_STRING_TYPE ["x"],
  INTERNALIZED_ONE_BYTE_STRING_TYPE ["y"],
  INTERNALIZED_ONE_BYTE_STRING_TYPE ["z"],
]
handlers: [
]

---
snippet: "
  {
    f = function f(a) {
  let res = x ?? y ?? z
  x; y; z;
    }
    let w, x, y, z;
    f();
  }
"
frame size: 1
parameter count: 2
bytecode array length: 33
bytecodes: [
  /*   34 S> */ B(LdaImmutableCurrentContextSlot), C8(2),
                B(ThrowReferenceErrorIfHole), U8(0:"x"),
                B(JumpIfUndefinedOrNull), U8(4),
                B(Jump), U8(14),
                B(LdaImmutableCurrentContextSlot), C8(3),
  /*   39 E> */ B(ThrowReferenceErrorIfHole), U8(1:"y"),
                B(JumpIfUndefinedOrNull), U8(4),
                B(Jump), U8(6),
                B(LdaImmutableCurrentContextSlot), C8(4),
  /*   44 E> */ B(ThrowReferenceErrorIfHole), U8(2:"z"),
                B(Star0),
  /*   46 S> */ B(LdaImmutableCurrentContextSlot), C8(2),
  /*   49 S> */ B(LdaImmutableCurrentContextSlot), C8(3),
                B(ThrowReferenceErrorIfHole), U8(1:"y"),
  /*   52 S> */ B(LdaImmutableCurrentContextSlot), C8(4),
                B(ThrowReferenceErrorIfHole), U8(2:"z"),
                B(LdaUndefined),
  /*   57 S> */ B(Return),
]
constant pool: [
  INTERNALIZED_ONE_BYTE_STRING_TYPE ["x"],
  INTERNALIZED_ONE_BYTE_STRING_TYPE ["y"],
  INTERNALIZED_ONE_BYTE_STRING_TYPE ["z"],
]
handlers: [
]

---
snippet: "
  {
    f = function f(a) {
  ({p:42})?.[x]?.[x]?.[y];
  x; y;
    }
    let w, x, y, z;
    f();
  }
"
frame size: 1
parameter count: 2
bytecode array length: 45
bytecodes: [
  /*   24 S> */ B(CreateObjectLiteral), U8(0:OBJECT_BOILERPLATE_DESCRIPTION_TYPE), FBV(0), Flag8(0x29),
                B(Star0),
                B(JumpIfUndefinedOrNull), U8(29),
                B(LdaImmutableCurrentContextSlot), C8(2),
  /*   35 E> */ B(ThrowReferenceErrorIfHole), U8(1:"x"),
  /*   34 E> */ B(GetKeyedProperty), R(0), FBV(1),
                B(Star0),
                B(JumpIfUndefinedOrNull), U8(19),
                B(LdaImmutableCurrentContextSlot), C8(2),
  /*   39 E> */ B(GetKeyedProperty), R(0), FBV(3),
                B(Star0),
                B(JumpIfUndefinedOrNull), U8(11),
                B(LdaImmutableCurrentContextSlot), C8(3),
  /*   45 E> */ B(ThrowReferenceErrorIfHole), U8(2:"y"),
  /*   44 E> */ B(GetKeyedProperty), R(0), FBV(5),
                B(Jump), U8(3),
                B(LdaUndefined),
  /*   49 S> */ B(LdaImmutableCurrentContextSlot), C8(2),
                B(ThrowReferenceErrorIfHole), U8(1:"x"),
  /*   52 S> */ B(LdaImmutableCurrentContextSlot), C8(3),
                B(ThrowReferenceErrorIfHole), U8(2:"y"),
                B(LdaUndefined),
  /*   57 S> */ B(Return),
]
constant pool: [
  OBJECT_BOILERPLATE_DESCRIPTION_TYPE,
  INTERNALIZED_ONE_BYTE_STRING_TYPE ["x"],
  INTERNALIZED_ONE_BYTE_STRING_TYPE ["y"],
]
handlers: [
]

---
snippet: "
  {
    f = function f(a) {
  x &&= y;
  x; y;
    }
    let w, x, y, z;
    f();
  }
"
frame size: 0
parameter count: 2
bytecode array length: 20
bytecodes: [
  /*   24 S> */ B(LdaCurrentContextSlotNoCell), C8(2),
                B(ThrowReferenceErrorIfHole), U8(0:"x"),
                B(JumpIfToBooleanFalse), U8(8),
                B(LdaImmutableCurrentContextSlot), C8(3),
  /*   30 E> */ B(ThrowReferenceErrorIfHole), U8(1:"y"),
  /*   26 E> */ B(StaCurrentContextSlotNoCell), C8(2),
  /*   33 S> */ B(LdaCurrentContextSlotNoCell), C8(2),
  /*   36 S> */ B(LdaImmutableCurrentContextSlot), C8(3),
                B(ThrowReferenceErrorIfHole), U8(1:"y"),
                B(LdaUndefined),
  /*   41 S> */ B(Return),
]
constant pool: [
  INTERNALIZED_ONE_BYTE_STRING_TYPE ["x"],
  INTERNALIZED_ONE_BYTE_STRING_TYPE ["y"],
]
handlers: [
]

---
snippet: "
  {
    f = function f(a) {
  x ||= y;
  x; y;
    }
    let w, x, y, z;
    f();
  }
"
frame size: 0
parameter count: 2
bytecode array length: 20
bytecodes: [
  /*   24 S> */ B(LdaCurrentContextSlotNoCell), C8(2),
                B(ThrowReferenceErrorIfHole), U8(0:"x"),
                B(JumpIfToBooleanTrue), U8(8),
                B(LdaImmutableCurrentContextSlot), C8(3),
  /*   30 E> */ B(ThrowReferenceErrorIfHole), U8(1:"y"),
  /*   26 E> */ B(StaCurrentContextSlotNoCell), C8(2),
  /*   33 S> */ B(LdaCurrentContextSlotNoCell), C8(2),
  /*   36 S> */ B(LdaImmutableCurrentContextSlot), C8(3),
                B(ThrowReferenceErrorIfHole), U8(1:"y"),
                B(LdaUndefined),
  /*   41 S> */ B(Return),
]
constant pool: [
  INTERNALIZED_ONE_BYTE_STRING_TYPE ["x"],
  INTERNALIZED_ONE_BYTE_STRING_TYPE ["y"],
]
handlers: [
]

---
snippet: "
  {
    f = function f(a) {
  x ??= y;
  x; y;
    }
    let w, x, y, z;
    f();
  }
"
frame size: 0
parameter count: 2
bytecode array length: 22
bytecodes: [
  /*   24 S> */ B(LdaCurrentContextSlotNoCell), C8(2),
                B(ThrowReferenceErrorIfHole), U8(0:"x"),
                B(JumpIfUndefinedOrNull), U8(4),
                B(Jump), U8(8),
                B(LdaImmutableCurrentContextSlot), C8(3),
  /*   30 E> */ B(ThrowReferenceErrorIfHole), U8(1:"y"),
  /*   26 E> */ B(StaCurrentContextSlotNoCell), C8(2),
  /*   33 S> */ B(LdaCurrentContextSlotNoCell), C8(2),
  /*   36 S> */ B(LdaImmutableCurrentContextSlot), C8(3),
                B(ThrowReferenceErrorIfHole), U8(1:"y"),
                B(LdaUndefined),
  /*   41 S> */ B(Return),
]
constant pool: [
  INTERNALIZED_ONE_BYTE_STRING_TYPE ["x"],
  INTERNALIZED_ONE_BYTE_STRING_TYPE ["y"],
]
handlers: [
]

---
snippet: "
  {
    f = function f(a) {
  switch (a) {
    case x: if (a) break; y; break;
    case 42: y; z;
    default: y; w;
  }
  x; y; z; w;
    }
    let w, x, y, z;
    f();
  }
"
frame size: 1
parameter count: 2
bytecode array length: 67
bytecodes: [
  /*   24 S> */ B(LdaImmutableCurrentContextSlot), C8(3),
  /*   44 E> */ B(ThrowReferenceErrorIfHole), U8(0:"x"),
                B(TestEqualStrict), R(arg0), Flag16(0x0),
                B(Mov), R(arg0), R(0),
                B(JumpIfTrue), U8(12),
                B(LdaSmi), I8(42),
                B(TestEqualStrict), R(0), Flag16(0x0),
                B(JumpIfTrue), U8(16),
                B(Jump), U8(22),
  /*   47 S> */ B(Ldar), R(arg0),
                B(JumpIfToBooleanFalse), U8(4),
  /*   54 S> */ B(Jump), U8(24),
  /*   61 S> */ B(LdaImmutableCurrentContextSlot), C8(4),
                B(ThrowReferenceErrorIfHole), U8(1:"y"),
  /*   64 S> */ B(Jump), U8(18),
  /*   82 S> */ B(LdaImmutableCurrentContextSlot), C8(4),
                B(ThrowReferenceErrorIfHole), U8(1:"y"),
  /*   85 S> */ B(LdaImmutableCurrentContextSlot), C8(5),
                B(ThrowReferenceErrorIfHole), U8(2:"z"),
  /*   99 S> */ B(LdaImmutableCurrentContextSlot), C8(4),
                B(ThrowReferenceErrorIfHole), U8(1:"y"),
  /*  102 S> */ B(LdaImmutableCurrentContextSlot), C8(2),
                B(ThrowReferenceErrorIfHole), U8(3:"w"),
  /*  107 S> */ B(LdaImmutableCurrentContextSlot), C8(3),
  /*  110 S> */ B(LdaImmutableCurrentContextSlot), C8(4),
                B(ThrowReferenceErrorIfHole), U8(1:"y"),
  /*  113 S> */ B(LdaImmutableCurrentContextSlot), C8(5),
                B(ThrowReferenceErrorIfHole), U8(2:"z"),
  /*  116 S> */ B(LdaImmutableCurrentContextSlot), C8(2),
                B(ThrowReferenceErrorIfHole), U8(3:"w"),
                B(LdaUndefined),
  /*  121 S> */ B(Return),
]
constant pool: [
  INTERNALIZED_ONE_BYTE_STRING_TYPE ["x"],
  INTERNALIZED_ONE_BYTE_STRING_TYPE ["y"],
  INTERNALIZED_ONE_BYTE_STRING_TYPE ["z"],
  INTERNALIZED_ONE_BYTE_STRING_TYPE ["w"],
]
handlers: [
]

---
snippet: "
  {
    f = function f(a) {
  lbl: {
    x;
    if (a) break lbl;
    y;
  }
  x; y;
    }
    let w, x, y, z;
    f();
  }
"
frame size: 0
parameter count: 2
bytecode array length: 22
bytecodes: [
  /*   33 S> */ B(LdaImmutableCurrentContextSlot), C8(2),
                B(ThrowReferenceErrorIfHole), U8(0:"x"),
  /*   38 S> */ B(Ldar), R(arg0),
                B(JumpIfToBooleanFalse), U8(4),
  /*   45 S> */ B(Jump), U8(6),
  /*   58 S> */ B(LdaImmutableCurrentContextSlot), C8(3),
                B(ThrowReferenceErrorIfHole), U8(1:"y"),
  /*   63 S> */ B(LdaImmutableCurrentContextSlot), C8(2),
  /*   66 S> */ B(LdaImmutableCurrentContextSlot), C8(3),
                B(ThrowReferenceErrorIfHole), U8(1:"y"),
                B(LdaUndefined),
  /*   71 S> */ B(Return),
]
constant pool: [
  INTERNALIZED_ONE_BYTE_STRING_TYPE ["x"],
  INTERNALIZED_ONE_BYTE_STRING_TYPE ["y"],
]
handlers: [
]

---
snippet: "
  {
    f = function f(a) {
  {
    x;
    y;
  }
  x; y;
    }
    let w, x, y, z;
    f();
  }
"
frame size: 0
parameter count: 2
bytecode array length: 12
bytecodes: [
  /*   28 S> */ B(LdaImmutableCurrentContextSlot), C8(2),
                B(ThrowReferenceErrorIfHole), U8(0:"x"),
  /*   33 S> */ B(LdaImmutableCurrentContextSlot), C8(3),
                B(ThrowReferenceErrorIfHole), U8(1:"y"),
  /*   38 S> */ B(LdaImmutableCurrentContextSlot), C8(2),
  /*   41 S> */ B(LdaUndefined),
  /*   46 S> */ B(Return),
]
constant pool: [
  INTERNALIZED_ONE_BYTE_STRING_TYPE ["x"],
  INTERNALIZED_ONE_BYTE_STRING_TYPE ["y"],
]
handlers: [
]

---
snippet: "
  {
    f = function f(a) {
  try {
    x;
  } catch (e) {}
  x;
    }
    let w, x, y, z;
    f();
  }
"
frame size: 2
parameter count: 2
bytecode array length: 28
bytecodes: [
                B(Mov), R(context), R(0),
  /*   32 S> */ B(LdaImmutableCurrentContextSlot), C8(2),
                B(ThrowReferenceErrorIfHole), U8(0:"x"),
                B(Jump), U8(15),
                B(Star1),
                B(CreateCatchContext), R(1), U8(1:SCOPE_INFO_TYPE),
                B(Star0),
                B(LdaTheHole),
                B(SetPendingMessage),
                B(Ldar), R(0),
                B(PushContext), R(1),
                B(PopContext), R(1),
  /*   50 S> */ B(LdaImmutableCurrentContextSlot), C8(2),
                B(ThrowReferenceErrorIfHole), U8(0:"x"),
                B(LdaUndefined),
  /*   55 S> */ B(Return),
]
constant pool: [
  INTERNALIZED_ONE_BYTE_STRING_TYPE ["x"],
  SCOPE_INFO_TYPE,
]
handlers: [
  [3, 7, 9],
]

---
snippet: "
  {
    f = function f(a) {
  try {
    x;
  } catch (e) { x; }
  x;
    }
    let w, x, y, z;
    f();
  }
"
frame size: 2
parameter count: 2
bytecode array length: 30
bytecodes: [
                B(Mov), R(context), R(0),
  /*   32 S> */ B(LdaImmutableCurrentContextSlot), C8(2),
                B(ThrowReferenceErrorIfHole), U8(0:"x"),
                B(Jump), U8(21),
                B(Star1),
                B(CreateCatchContext), R(1), U8(1:SCOPE_INFO_TYPE),
                B(Star0),
                B(LdaTheHole),
                B(SetPendingMessage),
                B(Ldar), R(0),
                B(PushContext), R(1),
  /*   49 S> */ B(LdaImmutableContextSlot), R(1), C8(2), U8(0),
                B(ThrowReferenceErrorIfHole), U8(0:"x"),
                B(PopContext), R(1),
  /*   54 S> */ B(LdaUndefined),
  /*   59 S> */ B(Return),
]
constant pool: [
  INTERNALIZED_ONE_BYTE_STRING_TYPE ["x"],
  SCOPE_INFO_TYPE,
]
handlers: [
  [3, 7, 9],
]

---
snippet: "
  {
    f = function f(a) {
  try {
    x;
  } finally { y; }
  x; y;
    }
    let w, x, y, z;
    f();
  }
"
frame size: 4
parameter count: 2
bytecode array length: 42
bytecodes: [
                B(LdaTheHole),
                B(Star2),
                B(Mov), R(context), R(3),
  /*   32 S> */ B(LdaImmutableCurrentContextSlot), C8(2),
                B(ThrowReferenceErrorIfHole), U8(0:"x"),
                B(LdaSmi), I8(-1),
                B(Star1),
                B(Star0),
                B(Jump), U8(8),
                B(Star1),
                B(LdaZero),
                B(Star0),
                B(LdaTheHole),
                B(SetPendingMessage),
                B(Star2),
  /*   47 S> */ B(LdaImmutableCurrentContextSlot), C8(3),
                B(ThrowReferenceErrorIfHole), U8(1:"y"),
                B(LdaZero),
                B(TestReferenceEqual), R(0),
                B(JumpIfFalse), U8(8),
                B(Ldar), R(2),
                B(SetPendingMessage),
                B(Ldar), R(1),
                B(ReThrow),
  /*   52 S> */ B(LdaImmutableCurrentContextSlot), C8(2),
                B(ThrowReferenceErrorIfHole), U8(0:"x"),
  /*   55 S> */ B(LdaUndefined),
  /*   60 S> */ B(Return),
]
constant pool: [
  INTERNALIZED_ONE_BYTE_STRING_TYPE ["x"],
  INTERNALIZED_ONE_BYTE_STRING_TYPE ["y"],
]
handlers: [
  [5, 9, 15],
]

