#
# Autogenerated by generate-bytecode-expectations.
#

---
wrap: yes
extra flags: --for-of-optimization

---
snippet: "
  for (var p of [0, 1, 2]) {}
"
frame size: 13
parameter count: 1
bytecode array length: 107
bytecodes: [
  /*   48 S> */ B(CreateArrayLiteral), U8(0), U8(0), U8(37),
                B(Star4),
                B(GetIterator), R(4), U8(1), U8(3),
                B(Star3),
                B(GetNamedProperty), R(3), U8(1), U8(5),
                B(Star2),
                B(LdaFalse),
                B(Star5),
                B(LdaTheHole),
                B(Star8),
                B(Mov), R(context), R(9),
                B(LdaTrue),
                B(Star5),
  /*   43 s> */ B(ForOfNext), R(3), R(2), R(4), U8(7),
                B(Ldar), R(5),
                B(JumpIfToBooleanTrue), U8(14),
  /*   43 S> */ B(Mov), R(4), R(1),
  /*   43 S> */ B(Mov), R(1), R(0),
                B(Ldar), R(0),
  /*   34 E> */ B(JumpLoop), U8(19), I8(0), U8(13),
                B(LdaSmi), I8(-1),
                B(Star7),
                B(Star6),
                B(Jump), U8(8),
                B(Star7),
                B(LdaZero),
                B(Star6),
                B(LdaTheHole),
                B(SetPendingMessage),
                B(Star8),
                B(Ldar), R(5),
                B(JumpIfToBooleanTrue), U8(35),
                B(Mov), R(context), R(10),
                B(GetNamedProperty), R(3), U8(2), U8(14),
                B(JumpIfUndefinedOrNull), U8(26),
                B(Star11),
                B(CallProperty0), R(11), R(3), U8(16),
                B(JumpIfJSReceiver), U8(19),
                B(Star12),
                B(CallRuntime), U16(Runtime::kThrowIteratorResultNotAnObject), R(12), U8(1),
                B(Jump), U8(11),
                B(Star10),
                B(LdaZero),
                B(TestReferenceEqual), R(6),
                B(JumpIfTrue), U8(5),
                B(Ldar), R(10),
                B(ReThrow),
                B(LdaZero),
                B(TestReferenceEqual), R(6),
                B(JumpIfFalse), U8(8),
                B(Ldar), R(8),
                B(SetPendingMessage),
                B(Ldar), R(7),
                B(ReThrow),
                B(LdaUndefined),
  /*   62 S> */ B(Return),
]
constant pool: [
  ARRAY_BOILERPLATE_DESCRIPTION_TYPE,
  INTERNALIZED_ONE_BYTE_STRING_TYPE ["next"],
  INTERNALIZED_ONE_BYTE_STRING_TYPE ["return"],
]
handlers: [
  [22, 45, 51],
  [64, 83, 85],
]

---
snippet: "
  for (var p of [0, 1, 2].keys()) {}
"
frame size: 13
parameter count: 1
bytecode array length: 117
bytecodes: [
  /*   58 S> */ B(CreateArrayLiteral), U8(0), U8(0), U8(37),
                B(Star3),
  /*   58 E> */ B(GetNamedProperty), R(3), U8(1), U8(1),
                B(Star2),
  /*   58 E> */ B(CallProperty0), R(2), R(3), U8(3),
                B(Star4),
                B(GetIterator), R(4), U8(5), U8(7),
                B(Star3),
                B(GetNamedProperty), R(3), U8(2), U8(9),
                B(Star2),
                B(LdaFalse),
                B(Star5),
                B(LdaTheHole),
                B(Star8),
                B(Mov), R(context), R(9),
                B(LdaTrue),
                B(Star5),
  /*   43 s> */ B(ForOfNext), R(3), R(2), R(4), U8(11),
                B(Ldar), R(5),
                B(JumpIfToBooleanTrue), U8(14),
  /*   43 S> */ B(Mov), R(4), R(1),
  /*   43 S> */ B(Mov), R(1), R(0),
                B(Ldar), R(0),
  /*   34 E> */ B(JumpLoop), U8(19), I8(0), U8(17),
                B(LdaSmi), I8(-1),
                B(Star7),
                B(Star6),
                B(Jump), U8(8),
                B(Star7),
                B(LdaZero),
                B(Star6),
                B(LdaTheHole),
                B(SetPendingMessage),
                B(Star8),
                B(Ldar), R(5),
                B(JumpIfToBooleanTrue), U8(35),
                B(Mov), R(context), R(10),
                B(GetNamedProperty), R(3), U8(3), U8(18),
                B(JumpIfUndefinedOrNull), U8(26),
                B(Star11),
                B(CallProperty0), R(11), R(3), U8(20),
                B(JumpIfJSReceiver), U8(19),
                B(Star12),
                B(CallRuntime), U16(Runtime::kThrowIteratorResultNotAnObject), R(12), U8(1),
                B(Jump), U8(11),
                B(Star10),
                B(LdaZero),
                B(TestReferenceEqual), R(6),
                B(JumpIfTrue), U8(5),
                B(Ldar), R(10),
                B(ReThrow),
                B(LdaZero),
                B(TestReferenceEqual), R(6),
                B(JumpIfFalse), U8(8),
                B(Ldar), R(8),
                B(SetPendingMessage),
                B(Ldar), R(7),
                B(ReThrow),
                B(LdaUndefined),
  /*   69 S> */ B(Return),
]
constant pool: [
  ARRAY_BOILERPLATE_DESCRIPTION_TYPE,
  INTERNALIZED_ONE_BYTE_STRING_TYPE ["keys"],
  INTERNALIZED_ONE_BYTE_STRING_TYPE ["next"],
  INTERNALIZED_ONE_BYTE_STRING_TYPE ["return"],
]
handlers: [
  [32, 55, 61],
  [74, 93, 95],
]

---
snippet: "
  for (var p of [0, 1, 2].entries()) {}
"
frame size: 13
parameter count: 1
bytecode array length: 117
bytecodes: [
  /*   58 S> */ B(CreateArrayLiteral), U8(0), U8(0), U8(37),
                B(Star3),
  /*   58 E> */ B(GetNamedProperty), R(3), U8(1), U8(1),
                B(Star2),
  /*   58 E> */ B(CallProperty0), R(2), R(3), U8(3),
                B(Star4),
                B(GetIterator), R(4), U8(5), U8(7),
                B(Star3),
                B(GetNamedProperty), R(3), U8(2), U8(9),
                B(Star2),
                B(LdaFalse),
                B(Star5),
                B(LdaTheHole),
                B(Star8),
                B(Mov), R(context), R(9),
                B(LdaTrue),
                B(Star5),
  /*   43 s> */ B(ForOfNext), R(3), R(2), R(4), U8(11),
                B(Ldar), R(5),
                B(JumpIfToBooleanTrue), U8(14),
  /*   43 S> */ B(Mov), R(4), R(1),
  /*   43 S> */ B(Mov), R(1), R(0),
                B(Ldar), R(0),
  /*   34 E> */ B(JumpLoop), U8(19), I8(0), U8(17),
                B(LdaSmi), I8(-1),
                B(Star7),
                B(Star6),
                B(Jump), U8(8),
                B(Star7),
                B(LdaZero),
                B(Star6),
                B(LdaTheHole),
                B(SetPendingMessage),
                B(Star8),
                B(Ldar), R(5),
                B(JumpIfToBooleanTrue), U8(35),
                B(Mov), R(context), R(10),
                B(GetNamedProperty), R(3), U8(3), U8(18),
                B(JumpIfUndefinedOrNull), U8(26),
                B(Star11),
                B(CallProperty0), R(11), R(3), U8(20),
                B(JumpIfJSReceiver), U8(19),
                B(Star12),
                B(CallRuntime), U16(Runtime::kThrowIteratorResultNotAnObject), R(12), U8(1),
                B(Jump), U8(11),
                B(Star10),
                B(LdaZero),
                B(TestReferenceEqual), R(6),
                B(JumpIfTrue), U8(5),
                B(Ldar), R(10),
                B(ReThrow),
                B(LdaZero),
                B(TestReferenceEqual), R(6),
                B(JumpIfFalse), U8(8),
                B(Ldar), R(8),
                B(SetPendingMessage),
                B(Ldar), R(7),
                B(ReThrow),
                B(LdaUndefined),
  /*   72 S> */ B(Return),
]
constant pool: [
  ARRAY_BOILERPLATE_DESCRIPTION_TYPE,
  INTERNALIZED_ONE_BYTE_STRING_TYPE ["entries"],
  INTERNALIZED_ONE_BYTE_STRING_TYPE ["next"],
  INTERNALIZED_ONE_BYTE_STRING_TYPE ["return"],
]
handlers: [
  [32, 55, 61],
  [74, 93, 95],
]

