#
# Autogenerated by generate-bytecode-expectations.
#

---
wrap: no
test function name: f
extra flags: --proto-assign-seq-opt

---
snippet: "
  function f() {
    // Local definition of MyClass.
    function MyClass() {}
    MyClass.prototype.foo = function() {};
    MyClass.prototype.bar = function() {};
    MyClass.prototype.baz = function() {};
  }
"
frame size: 1
parameter count: 1
bytecode array length: 9
bytecodes: [
  /*   10 E> */ B(CreateClosure), U8(0), U8(0), U8(2),
                B(Star0),
                B(SetPrototypeProperties), U8(1),
                B(LdaUndefined),
  /*  196 S> */ B(Return),
]
constant pool: [
  SHARED_FUNCTION_INFO_TYPE,
  OBJECT_BOILERPLATE_DESCRIPTION_TYPE,
]
handlers: [
]

---
snippet: "
  // Context, non-assigned definition of MyClass.
  function bar() {
    const MyClass = function() {}
    function f() {
      MyClass.prototype.foo = function() {};
      MyClass.prototype.bar = function() {};
      MyClass.prototype.baz = function() {};
    }
    return f;
  }
  f = bar();
"
frame size: 0
parameter count: 1
bytecode array length: 6
bytecodes: [
                B(LdaImmutableCurrentContextSlot), U8(2),
  /*  109 E> */ B(SetPrototypeProperties), U8(0),
                B(LdaUndefined),
  /*  245 S> */ B(Return),
]
constant pool: [
  OBJECT_BOILERPLATE_DESCRIPTION_TYPE,
]
handlers: [
]

---
snippet: "
  // Parameter definition of MyClass.
  function f(MyClass) {
    MyClass.prototype.foo = function() {};
    MyClass.prototype.bar = function() {};
    MyClass.prototype.baz = function() {};
  }
"
frame size: 0
parameter count: 2
bytecode array length: 6
bytecodes: [
                B(Ldar), R(arg0),
  /*   46 E> */ B(SetPrototypeProperties), U8(0),
                B(LdaUndefined),
  /*  181 S> */ B(Return),
]
constant pool: [
  OBJECT_BOILERPLATE_DESCRIPTION_TYPE,
]
handlers: [
]

---
snippet: "
  // Global definition of MyClass (should not optimize, because a prototype
  // accessor could change the global).
  function MyClass() {}
  function f() {
    MyClass.prototype.foo = function() {};
    MyClass.prototype.bar = function() {};
    MyClass.prototype.baz = function() {};
  }
"
frame size: 1
parameter count: 1
bytecode array length: 53
bytecodes: [
  /*  151 S> */ B(LdaGlobal), U8(0), U8(0),
                B(Star0),
  /*  159 E> */ B(GetNamedProperty), R(0), U8(1), U8(2),
                B(Star0),
                B(CreateClosure), U8(2), U8(0), U8(1),
  /*  173 E> */ B(SetNamedProperty), R(0), U8(3), U8(4),
  /*  192 S> */ B(LdaGlobal), U8(0), U8(0),
                B(Star0),
  /*  200 E> */ B(GetNamedProperty), R(0), U8(1), U8(2),
                B(Star0),
                B(CreateClosure), U8(4), U8(1), U8(1),
  /*  214 E> */ B(SetNamedProperty), R(0), U8(5), U8(6),
  /*  233 S> */ B(LdaGlobal), U8(0), U8(0),
                B(Star0),
  /*  241 E> */ B(GetNamedProperty), R(0), U8(1), U8(2),
                B(Star0),
                B(CreateClosure), U8(6), U8(2), U8(1),
  /*  255 E> */ B(SetNamedProperty), R(0), U8(7), U8(8),
                B(LdaUndefined),
  /*  272 S> */ B(Return),
]
constant pool: [
  INTERNALIZED_ONE_BYTE_STRING_TYPE ["MyClass"],
  INTERNALIZED_ONE_BYTE_STRING_TYPE ["prototype"],
  SHARED_FUNCTION_INFO_TYPE,
  INTERNALIZED_ONE_BYTE_STRING_TYPE ["foo"],
  SHARED_FUNCTION_INFO_TYPE,
  INTERNALIZED_ONE_BYTE_STRING_TYPE ["bar"],
  SHARED_FUNCTION_INFO_TYPE,
  INTERNALIZED_ONE_BYTE_STRING_TYPE ["baz"],
]
handlers: [
]

---
snippet: "
  // Dynamic definition of MyClass (should not optimize, because an eval
  // could change or shadow the variable).
  function f() {
    eval(\"var MyClass = function() {}\");
    MyClass.prototype.foo = function() {};
    MyClass.prototype.bar = function() {};
    MyClass.prototype.baz = function() {};
  }
"
frame size: 10
parameter count: 1
bytecode array length: 109
bytecodes: [
  /*  122 E> */ B(CreateFunctionContext), U8(0), U8(4),
                B(PushContext), R(1),
                B(Ldar), R(this),
                B(StaCurrentContextSlotNoCell), U8(3),
                B(CreateMappedArguments),
                B(StaCurrentContextSlotNoCell), U8(5),
                B(Ldar), R(0),
                B(StaCurrentContextSlotNoCell), U8(4),
  /*  129 S> */ B(LdaLookupGlobalSlot), U8(1), U8(0), U8(1),
                B(Star2),
                B(LdaConstant), U8(2),
                B(Star3),
                B(LdaZero),
                B(Star7),
                B(LdaSmi), I8(2),
                B(Star8),
                B(Wide), B(LdaSmi), I16(129),
                B(Star9),
                B(Mov), R(2), R(4),
                B(Mov), R(3), R(5),
                B(Mov), R(closure), R(6),
                B(CallRuntime), U16(Runtime::kResolvePossiblyDirectEval), R(4), U8(6),
                B(Star2),
  /*  129 E> */ B(CallUndefinedReceiver1), R(2), R(3), U8(2),
  /*  168 S> */ B(LdaLookupGlobalSlot), U8(3), U8(4), U8(1),
                B(Star2),
  /*  176 E> */ B(GetNamedProperty), R(2), U8(4), U8(6),
                B(Star2),
                B(CreateClosure), U8(5), U8(0), U8(1),
  /*  190 E> */ B(SetNamedProperty), R(2), U8(6), U8(8),
  /*  209 S> */ B(LdaLookupGlobalSlot), U8(3), U8(10), U8(1),
                B(Star2),
  /*  217 E> */ B(GetNamedProperty), R(2), U8(4), U8(6),
                B(Star2),
                B(CreateClosure), U8(7), U8(1), U8(1),
  /*  231 E> */ B(SetNamedProperty), R(2), U8(8), U8(12),
  /*  250 S> */ B(LdaLookupGlobalSlot), U8(3), U8(14), U8(1),
                B(Star2),
  /*  258 E> */ B(GetNamedProperty), R(2), U8(4), U8(6),
                B(Star2),
                B(CreateClosure), U8(9), U8(2), U8(1),
  /*  272 E> */ B(SetNamedProperty), R(2), U8(10), U8(16),
                B(LdaUndefined),
  /*  289 S> */ B(Return),
]
constant pool: [
  SCOPE_INFO_TYPE,
  INTERNALIZED_ONE_BYTE_STRING_TYPE ["eval"],
  INTERNALIZED_ONE_BYTE_STRING_TYPE ["var MyClass = function() {}"],
  INTERNALIZED_ONE_BYTE_STRING_TYPE ["MyClass"],
  INTERNALIZED_ONE_BYTE_STRING_TYPE ["prototype"],
  SHARED_FUNCTION_INFO_TYPE,
  INTERNALIZED_ONE_BYTE_STRING_TYPE ["foo"],
  SHARED_FUNCTION_INFO_TYPE,
  INTERNALIZED_ONE_BYTE_STRING_TYPE ["bar"],
  SHARED_FUNCTION_INFO_TYPE,
  INTERNALIZED_ONE_BYTE_STRING_TYPE ["baz"],
]
handlers: [
]

