#
# Autogenerated by generate-bytecode-expectations.
#

---
wrap: yes

---
snippet: "
  {
    class A {
      a;
      ['b'];
      static c;
      static ['d'];
    }
  
    class B {
      a = 1;
      ['b'] = this.a;
      static c = 3;
      static ['d'] = this.c;
    }
    new A;
    new B;
  }
"
frame size: 9
parameter count: 1
bytecode array length: 166
bytecodes: [
  /*   30 E> */ B(CreateBlockContext), U8(0:SCOPE_INFO_TYPE),
                B(PushContext), R(2),
                B(LdaTheHole),
                B(StaCurrentContextSlotNoCell), C8(2),
                B(LdaTheHole),
                B(StaCurrentContextSlotNoCell), C8(3),
                B(LdaTheHole),
                B(Star6),
                B(CreateClosure), U8(2:SHARED_FUNCTION_INFO_TYPE), FBV(0), Flag8(0x2),
                B(Star3),
                B(LdaConstant), U8(1:CLASS_BOILERPLATE_TYPE),
                B(Star4),
  /*   60 S> */ B(LdaConstant), U8(3:"b"),
                B(StaCurrentContextSlotNoCell), C8(2),
                B(Star7),
  /*   92 S> */ B(LdaConstant), U8(4:"d"),
                B(Star8),
                B(LdaConstant), U8(5:"prototype"),
                B(TestEqualStrict), R(8), Flag16(0x0),
                B(Mov), R(3), R(5),
                B(JumpIfFalse), U8(7),
                B(CallRuntime), U16(Runtime::kThrowStaticPrototypeError), R(0), RegCount8(0),
                B(Ldar), R(8),
                B(StaCurrentContextSlotNoCell), C8(3),
                B(CallRuntime), U16(Runtime::kDefineClass), R(4), RegCount8(5),
                B(CreateClosure), U8(6:SHARED_FUNCTION_INFO_TYPE), FBV(1), Flag8(0x2),
                B(SetNamedProperty), R(3), U8(7:SYMBOL_TYPE), FBV(0),
                B(CreateClosure), U8(8:SHARED_FUNCTION_INFO_TYPE), FBV(2), Flag8(0x2),
                B(Star5),
                B(CallProperty0), R(5), R(3), FBV(2),
                B(PopContext), R(2),
                B(Mov), R(3), R(0),
  /*   38 E> */ B(CreateBlockContext), U8(9:SCOPE_INFO_TYPE),
                B(PushContext), R(2),
                B(LdaTheHole),
                B(StaCurrentContextSlotNoCell), C8(2),
                B(LdaTheHole),
                B(StaCurrentContextSlotNoCell), C8(3),
                B(LdaTheHole),
                B(Star6),
                B(CreateClosure), U8(11:SHARED_FUNCTION_INFO_TYPE), FBV(3), Flag8(0x2),
                B(Star3),
                B(LdaConstant), U8(10:CLASS_BOILERPLATE_TYPE),
                B(Star4),
  /*  131 S> */ B(LdaConstant), U8(3:"b"),
                B(StaCurrentContextSlotNoCell), C8(2),
                B(Star7),
  /*  176 S> */ B(LdaConstant), U8(4:"d"),
                B(Star8),
                B(LdaConstant), U8(5:"prototype"),
                B(TestEqualStrict), R(8), Flag16(0x0),
                B(Mov), R(3), R(5),
                B(JumpIfFalse), U8(7),
                B(CallRuntime), U16(Runtime::kThrowStaticPrototypeError), R(0), RegCount8(0),
                B(Ldar), R(8),
                B(StaCurrentContextSlotNoCell), C8(3),
                B(CallRuntime), U16(Runtime::kDefineClass), R(4), RegCount8(5),
                B(CreateClosure), U8(12:SHARED_FUNCTION_INFO_TYPE), FBV(4), Flag8(0x2),
                B(SetNamedProperty), R(3), U8(7:SYMBOL_TYPE), FBV(4),
                B(CreateClosure), U8(13:SHARED_FUNCTION_INFO_TYPE), FBV(5), Flag8(0x2),
                B(Star5),
                B(CallProperty0), R(5), R(3), FBV(6),
                B(PopContext), R(2),
                B(Mov), R(3), R(1),
  /*  197 S> */ B(Ldar), R(0),
  /*  197 E> */ B(Construct), R(0), R(0), RegCount8(0), FBV(8),
  /*  206 S> */ B(Ldar), R(1),
  /*  206 E> */ B(Construct), R(1), R(0), RegCount8(0), FBV(10),
                B(LdaUndefined),
  /*  215 S> */ B(Return),
]
constant pool: [
  SCOPE_INFO_TYPE,
  CLASS_BOILERPLATE_TYPE,
  SHARED_FUNCTION_INFO_TYPE,
  INTERNALIZED_ONE_BYTE_STRING_TYPE ["b"],
  INTERNALIZED_ONE_BYTE_STRING_TYPE ["d"],
  INTERNALIZED_ONE_BYTE_STRING_TYPE ["prototype"],
  SHARED_FUNCTION_INFO_TYPE,
  SYMBOL_TYPE,
  SHARED_FUNCTION_INFO_TYPE,
  SCOPE_INFO_TYPE,
  CLASS_BOILERPLATE_TYPE,
  SHARED_FUNCTION_INFO_TYPE,
  SHARED_FUNCTION_INFO_TYPE,
  SHARED_FUNCTION_INFO_TYPE,
]
handlers: [
]

---
snippet: "
  {
    class A extends class {} {
      a;
      ['b'];
      static c;
      static ['d'];
    }
  
    class B extends class {} {
      a = 1;
      ['b'] = this.a;
      static c = 3;
      static ['d'] = this.c;
      foo() { return 1; }
      constructor() {
        super();
      }
    }
  
    class C extends B {
      a = 1;
      ['b'] = this.a;
      static c = 3;
      static ['d'] = super.foo();
      constructor() {
        (() => super())();
      }
    }
  
    new A;
    new B;
    new C;
  }
"
frame size: 12
parameter count: 1
bytecode array length: 298
bytecodes: [
  /*   30 E> */ B(CreateBlockContext), U8(0:SCOPE_INFO_TYPE),
                B(PushContext), R(3),
                B(LdaTheHole),
                B(StaCurrentContextSlotNoCell), C8(2),
                B(LdaTheHole),
                B(StaCurrentContextSlotNoCell), C8(3),
                B(LdaTheHole),
                B(Star11),
                B(CreateClosure), U8(3:SHARED_FUNCTION_INFO_TYPE), FBV(0), Flag8(0x2),
                B(Star8),
                B(LdaConstant), U8(2:CLASS_BOILERPLATE_TYPE),
                B(Star9),
                B(Mov), R(8), R(10),
                B(CallRuntime), U16(Runtime::kDefineClass), R(9), RegCount8(3),
                B(CreateClosure), U8(4:SHARED_FUNCTION_INFO_TYPE), FBV(1), Flag8(0x2),
                B(Star4),
                B(LdaConstant), U8(1:CLASS_BOILERPLATE_TYPE),
                B(Star5),
  /*   77 S> */ B(LdaConstant), U8(5:"b"),
                B(StaCurrentContextSlotNoCell), C8(2),
                B(Star8),
  /*  109 S> */ B(LdaConstant), U8(6:"d"),
                B(Star9),
                B(LdaConstant), U8(7:"prototype"),
                B(TestEqualStrict), R(9), Flag16(0x0),
                B(Mov), R(10), R(7),
                B(Mov), R(4), R(6),
                B(JumpIfFalse), U8(7),
                B(CallRuntime), U16(Runtime::kThrowStaticPrototypeError), R(0), RegCount8(0),
                B(Ldar), R(9),
                B(StaCurrentContextSlotNoCell), C8(3),
                B(CallRuntime), U16(Runtime::kDefineClass), R(5), RegCount8(5),
                B(CreateClosure), U8(8:SHARED_FUNCTION_INFO_TYPE), FBV(2), Flag8(0x2),
                B(SetNamedProperty), R(4), U8(9:SYMBOL_TYPE), FBV(0),
                B(CreateClosure), U8(10:SHARED_FUNCTION_INFO_TYPE), FBV(3), Flag8(0x2),
                B(Star6),
                B(CallProperty0), R(6), R(4), FBV(2),
                B(PopContext), R(3),
                B(Mov), R(4), R(0),
  /*   38 E> */ B(CreateBlockContext), U8(11:SCOPE_INFO_TYPE),
                B(PushContext), R(3),
                B(LdaTheHole),
                B(StaCurrentContextSlotNoCell), C8(2),
                B(LdaTheHole),
                B(StaCurrentContextSlotNoCell), C8(3),
                B(LdaTheHole),
                B(Star11),
                B(CreateClosure), U8(14:SHARED_FUNCTION_INFO_TYPE), FBV(4), Flag8(0x2),
                B(Star8),
                B(LdaConstant), U8(13:CLASS_BOILERPLATE_TYPE),
                B(Star9),
                B(Mov), R(8), R(10),
                B(CallRuntime), U16(Runtime::kDefineClass), R(9), RegCount8(3),
                B(CreateClosure), U8(15:SHARED_FUNCTION_INFO_TYPE), FBV(5), Flag8(0x2),
                B(Star4),
                B(LdaConstant), U8(12:CLASS_BOILERPLATE_TYPE),
                B(Star5),
  /*  165 S> */ B(LdaConstant), U8(5:"b"),
                B(StaCurrentContextSlotNoCell), C8(2),
                B(Star8),
  /*  210 S> */ B(LdaConstant), U8(6:"d"),
                B(Star9),
                B(LdaConstant), U8(7:"prototype"),
                B(TestEqualStrict), R(9), Flag16(0x0),
                B(Mov), R(4), R(6),
                B(Mov), R(10), R(7),
                B(JumpIfFalse), U8(7),
                B(CallRuntime), U16(Runtime::kThrowStaticPrototypeError), R(0), RegCount8(0),
                B(Ldar), R(9),
                B(StaCurrentContextSlotNoCell), C8(3),
                B(CreateClosure), U8(16:SHARED_FUNCTION_INFO_TYPE), FBV(6), Flag8(0x2),
                B(Star10),
                B(CallRuntime), U16(Runtime::kDefineClass), R(5), RegCount8(6),
                B(CreateClosure), U8(17:SHARED_FUNCTION_INFO_TYPE), FBV(7), Flag8(0x2),
                B(SetNamedProperty), R(4), U8(9:SYMBOL_TYPE), FBV(4),
                B(CreateClosure), U8(18:SHARED_FUNCTION_INFO_TYPE), FBV(8), Flag8(0x2),
                B(Star6),
                B(CallProperty0), R(6), R(4), FBV(6),
                B(PopContext), R(3),
                B(Mov), R(4), R(1),
  /*  122 E> */ B(CreateBlockContext), U8(19:SCOPE_INFO_TYPE),
                B(PushContext), R(3),
                B(LdaTheHole),
                B(StaCurrentContextSlotNoCell), C8(2),
                B(LdaTheHole),
                B(StaCurrentContextSlotNoCell), C8(3),
  /*  313 E> */ B(CreateClosure), U8(21:SHARED_FUNCTION_INFO_TYPE), FBV(9), Flag8(0x2),
                B(Star4),
                B(LdaConstant), U8(20:CLASS_BOILERPLATE_TYPE),
                B(Star5),
  /*  333 S> */ B(LdaConstant), U8(5:"b"),
                B(StaCurrentContextSlotNoCell), C8(2),
                B(Star8),
  /*  378 S> */ B(LdaConstant), U8(6:"d"),
                B(Star9),
                B(LdaConstant), U8(7:"prototype"),
                B(TestEqualStrict), R(9), Flag16(0x0),
                B(Mov), R(4), R(6),
                B(Mov), R(1), R(7),
                B(JumpIfFalse), U8(7),
                B(CallRuntime), U16(Runtime::kThrowStaticPrototypeError), R(0), RegCount8(0),
                B(Ldar), R(9),
                B(StaCurrentContextSlotNoCell), C8(3),
                B(CallRuntime), U16(Runtime::kDefineClass), R(5), RegCount8(5),
                B(StaCurrentContextSlotNoCell), C8(4),
                B(Ldar), R(4),
                B(StaCurrentContextSlotNoCell), C8(5),
                B(CreateClosure), U8(22:SHARED_FUNCTION_INFO_TYPE), FBV(10), Flag8(0x2),
                B(SetNamedProperty), R(4), U8(9:SYMBOL_TYPE), FBV(8),
                B(CreateClosure), U8(23:SHARED_FUNCTION_INFO_TYPE), FBV(11), Flag8(0x2),
                B(Star6),
                B(CallProperty0), R(6), R(4), FBV(10),
                B(PopContext), R(3),
                B(Mov), R(4), R(2),
  /*  456 S> */ B(Ldar), R(0),
  /*  456 E> */ B(Construct), R(0), R(0), RegCount8(0), FBV(12),
  /*  465 S> */ B(Ldar), R(1),
  /*  465 E> */ B(Construct), R(1), R(0), RegCount8(0), FBV(14),
  /*  474 S> */ B(Ldar), R(2),
  /*  474 E> */ B(Construct), R(2), R(0), RegCount8(0), FBV(16),
                B(LdaUndefined),
  /*  483 S> */ B(Return),
]
constant pool: [
  SCOPE_INFO_TYPE,
  CLASS_BOILERPLATE_TYPE,
  CLASS_BOILERPLATE_TYPE,
  SHARED_FUNCTION_INFO_TYPE,
  SHARED_FUNCTION_INFO_TYPE,
  INTERNALIZED_ONE_BYTE_STRING_TYPE ["b"],
  INTERNALIZED_ONE_BYTE_STRING_TYPE ["d"],
  INTERNALIZED_ONE_BYTE_STRING_TYPE ["prototype"],
  SHARED_FUNCTION_INFO_TYPE,
  SYMBOL_TYPE,
  SHARED_FUNCTION_INFO_TYPE,
  SCOPE_INFO_TYPE,
  CLASS_BOILERPLATE_TYPE,
  CLASS_BOILERPLATE_TYPE,
  SHARED_FUNCTION_INFO_TYPE,
  SHARED_FUNCTION_INFO_TYPE,
  SHARED_FUNCTION_INFO_TYPE,
  SHARED_FUNCTION_INFO_TYPE,
  SHARED_FUNCTION_INFO_TYPE,
  SCOPE_INFO_TYPE,
  CLASS_BOILERPLATE_TYPE,
  SHARED_FUNCTION_INFO_TYPE,
  SHARED_FUNCTION_INFO_TYPE,
  SHARED_FUNCTION_INFO_TYPE,
]
handlers: [
]

