#
# Autogenerated by generate-bytecode-expectations.
#

---
wrap: no
test function name: test

---
snippet: "
  var test;
  (function () {
      function foo() {
          let a = typeof('str'); if (a === 'string') {}
          let b = typeof('str'); if (b === 1) {}
          let c = typeof('str'); c = 1; if (c === 'string') {}
          let d = typeof('str');
          if (d === 'string' || d === 'number') {}
          let e = 'hello world';
          if (e == 'string' || e == 'number') {}
          let f = 'hi';
          for (let i = 0; i < 2; ++i) {
              if (f === 'hi') {}
          }
          let g = true;
          if (g === 's') {}
          let j = true;
          let k = j || 's';
          if (k === 's') {}
      }
      foo();
      test = foo;
  })();
"
frame size: 10
parameter count: 1
bytecode array length: 131
bytecodes: [
  /*   62 S> */ B(LdaConstant), U8(0:"str"),
                B(TypeOf), FBV(0),
                B(Star0),
  /*   77 S> */ B(LdaConstant), U8(1:"string"),
                B(TestReferenceEqual), R(0),
                B(JumpIfFalse), U8(2),
  /*  116 S> */ B(LdaConstant), U8(0:"str"),
                B(TypeOf), FBV(1),
                B(Star1),
  /*  131 S> */ B(LdaSmi), I8(1),
  /*  137 E> */ B(TestEqualStrict), R(1), Flag16(0x0),
                B(JumpIfFalse), U8(2),
  /*  163 S> */ B(LdaConstant), U8(0:"str"),
                B(TypeOf), FBV(2),
                B(Star2),
  /*  178 S> */ B(LdaSmi), I8(1),
                B(Star2),
  /*  185 S> */ B(LdaConstant), U8(1:"string"),
  /*  191 E> */ B(TestEqualStrict), R(2), Flag16(0x0),
                B(JumpIfFalse), U8(2),
  /*  224 S> */ B(LdaConstant), U8(0:"str"),
                B(TypeOf), FBV(3),
                B(Star3),
  /*  247 S> */ B(LdaConstant), U8(1:"string"),
                B(TestReferenceEqual), R(3),
                B(JumpIfTrue), U8(10),
                B(LdaConstant), U8(2:"number"),
  /*  271 E> */ B(TestEqualStrict), R(3), Flag16(0x0),
                B(JumpIfFalse), U8(2),
  /*  304 S> */ B(LdaConstant), U8(3:"hello world"),
                B(Star4),
  /*  327 S> */ B(LdaConstant), U8(1:"string"),
                B(TestReferenceEqual), R(4),
                B(JumpIfTrue), U8(9),
                B(LdaConstant), U8(2:"number"),
  /*  350 E> */ B(TestEqual), R(4), FBV(4),
                B(JumpIfFalse), U8(2),
  /*  382 S> */ B(LdaConstant), U8(4:"hi"),
                B(Star5),
  /*  409 S> */ B(LdaZero),
                B(Star9),
  /*  414 S> */ B(LdaSmi), I8(2),
  /*  414 E> */ B(TestLessThan), R(9), FBV(5),
                B(JumpIfFalse), U8(19),
  /*  438 S> */ B(LdaConstant), U8(4:"hi"),
  /*  444 E> */ B(TestEqualStrict), R(5), Flag16(0x0),
                B(JumpIfFalse), U8(2),
  /*  421 S> */ B(Ldar), R(9),
                B(Inc), FBV(6),
                B(Star9),
  /*  396 E> */ B(JumpLoop), U8(20), I8(0), FBV(7),
  /*  483 S> */ B(LdaTrue),
                B(Star6),
  /*  497 S> */ B(LdaConstant), U8(5:"s"),
  /*  503 E> */ B(TestEqualStrict), R(6), Flag16(0x0),
                B(JumpIfFalse), U8(2),
  /*  531 S> */ B(LdaTrue),
                B(Star7),
  /*  553 S> */ B(JumpIfToBooleanTrue), U8(4),
                B(LdaConstant), U8(5:"s"),
                B(Star8),
  /*  571 S> */ B(LdaConstant), U8(5:"s"),
  /*  577 E> */ B(TestEqualStrict), R(8), Flag16(0x0),
                B(JumpIfFalse), U8(2),
                B(LdaUndefined),
  /*  593 S> */ B(Return),
]
constant pool: [
  INTERNALIZED_ONE_BYTE_STRING_TYPE ["str"],
  INTERNALIZED_ONE_BYTE_STRING_TYPE ["string"],
  INTERNALIZED_ONE_BYTE_STRING_TYPE ["number"],
  INTERNALIZED_ONE_BYTE_STRING_TYPE ["hello world"],
  INTERNALIZED_ONE_BYTE_STRING_TYPE ["hi"],
  INTERNALIZED_ONE_BYTE_STRING_TYPE ["s"],
]
handlers: [
]

