#
# Autogenerated by generate-bytecode-expectations.
#

---
wrap: no
module: yes
top level: yes
top level await: yes

---
snippet: "
  await 42;
"
frame size: 7
parameter count: 1
bytecode array length: 128
bytecodes: [
  /*    0 E> */ B(StackCheck),
                B(SwitchOnGeneratorState), R(0), U8(0), U8(2),
                B(Mov), R(closure), R(2),
                B(Mov), R(this), R(3),
                B(InvokeIntrinsic), U8(Runtime::k_AsyncFunctionEnter), R(2), U8(2),
                B(Star), R(0),
  /*    0 E> */ B(SuspendGenerator), R(0), R(0), U8(2), U8(0),
                B(ResumeGenerator), R(0), R(0), U8(2),
                B(Star), R(2),
                B(InvokeIntrinsic), U8(Runtime::k_GeneratorGetResumeMode), R(0), U8(1),
                B(SwitchOnSmiNoFeedback), U8(2), U8(2), I8(0),
                B(Ldar), R(2),
  /*    0 E> */ B(Throw),
                B(Ldar), R(2),
  /*   10 S> */ B(Return),
                B(Mov), R(2), R(1),
                B(Ldar), R(1),
                B(Mov), R(context), R(2),
  /*    0 S> */ B(LdaSmi), I8(42),
                B(Star), R(4),
                B(Mov), R(0), R(3),
                B(InvokeIntrinsic), U8(Runtime::k_AsyncFunctionAwaitUncaught), R(3), U8(2),
  /*    0 E> */ B(SuspendGenerator), R(0), R(0), U8(3), U8(1),
                B(ResumeGenerator), R(0), R(0), U8(3),
                B(Star), R(3),
                B(InvokeIntrinsic), U8(Runtime::k_GeneratorGetResumeMode), R(0), U8(1),
                B(Star), R(4),
                B(LdaZero),
                B(TestReferenceEqual), R(4),
                B(JumpIfTrue), U8(5),
                B(Ldar), R(3),
                B(ReThrow),
                B(LdaUndefined),
                B(Star), R(4),
                B(LdaTrue),
                B(Star), R(5),
                B(Mov), R(0), R(3),
                B(InvokeIntrinsic), U8(Runtime::k_AsyncFunctionResolve), R(3), U8(3),
  /*   10 S> */ B(Return),
                B(Star), R(3),
                B(CreateCatchContext), R(3), U8(4),
                B(Star), R(2),
                B(LdaTheHole),
                B(SetPendingMessage),
                B(Ldar), R(2),
                B(PushContext), R(3),
                B(LdaImmutableCurrentContextSlot), U8(2),
                B(Star), R(5),
                B(LdaTrue),
                B(Star), R(6),
                B(Mov), R(0), R(4),
                B(InvokeIntrinsic), U8(Runtime::k_AsyncFunctionReject), R(4), U8(3),
  /*   10 S> */ B(Return),
]
constant pool: [
  Smi [21],
  Smi [65],
  Smi [10],
  Smi [7],
  SCOPE_INFO_TYPE,
]
handlers: [
  [50, 100, 100],
]

---
snippet: "
  await import(\"foo\");
"
frame size: 7
parameter count: 1
bytecode array length: 138
bytecodes: [
  /*    0 E> */ B(StackCheck),
                B(SwitchOnGeneratorState), R(0), U8(0), U8(2),
                B(Mov), R(closure), R(2),
                B(Mov), R(this), R(3),
                B(InvokeIntrinsic), U8(Runtime::k_AsyncFunctionEnter), R(2), U8(2),
                B(Star), R(0),
  /*    0 E> */ B(SuspendGenerator), R(0), R(0), U8(2), U8(0),
                B(ResumeGenerator), R(0), R(0), U8(2),
                B(Star), R(2),
                B(InvokeIntrinsic), U8(Runtime::k_GeneratorGetResumeMode), R(0), U8(1),
                B(SwitchOnSmiNoFeedback), U8(2), U8(2), I8(0),
                B(Ldar), R(2),
  /*    0 E> */ B(Throw),
                B(Ldar), R(2),
  /*   21 S> */ B(Return),
                B(Mov), R(2), R(1),
                B(Ldar), R(1),
                B(Mov), R(context), R(2),
  /*    0 S> */ B(LdaConstant), U8(4),
                B(Star), R(4),
                B(Mov), R(closure), R(3),
                B(CallRuntime), U16(Runtime::kDynamicImportCall), R(3), U8(2),
                B(Star), R(4),
                B(Mov), R(0), R(3),
                B(InvokeIntrinsic), U8(Runtime::k_AsyncFunctionAwaitUncaught), R(3), U8(2),
  /*    0 E> */ B(SuspendGenerator), R(0), R(0), U8(3), U8(1),
                B(ResumeGenerator), R(0), R(0), U8(3),
                B(Star), R(3),
                B(InvokeIntrinsic), U8(Runtime::k_GeneratorGetResumeMode), R(0), U8(1),
                B(Star), R(4),
                B(LdaZero),
                B(TestReferenceEqual), R(4),
                B(JumpIfTrue), U8(5),
                B(Ldar), R(3),
                B(ReThrow),
                B(LdaUndefined),
                B(Star), R(4),
                B(LdaTrue),
                B(Star), R(5),
                B(Mov), R(0), R(3),
                B(InvokeIntrinsic), U8(Runtime::k_AsyncFunctionResolve), R(3), U8(3),
  /*   21 S> */ B(Return),
                B(Star), R(3),
                B(CreateCatchContext), R(3), U8(5),
                B(Star), R(2),
                B(LdaTheHole),
                B(SetPendingMessage),
                B(Ldar), R(2),
                B(PushContext), R(3),
                B(LdaImmutableCurrentContextSlot), U8(2),
                B(Star), R(5),
                B(LdaTrue),
                B(Star), R(6),
                B(Mov), R(0), R(4),
                B(InvokeIntrinsic), U8(Runtime::k_AsyncFunctionReject), R(4), U8(3),
  /*   21 S> */ B(Return),
]
constant pool: [
  Smi [21],
  Smi [75],
  Smi [10],
  Smi [7],
  ONE_BYTE_INTERNALIZED_STRING_TYPE ["foo"],
  SCOPE_INFO_TYPE,
]
handlers: [
  [50, 110, 110],
]

---
snippet: "
  await 42;
  async function foo() {
    await 42;
  }
  foo();
"
frame size: 8
parameter count: 1
bytecode array length: 139
bytecodes: [
  /*    0 E> */ B(StackCheck),
                B(SwitchOnGeneratorState), R(0), U8(0), U8(2),
                B(Mov), R(closure), R(3),
                B(Mov), R(this), R(4),
                B(InvokeIntrinsic), U8(Runtime::k_AsyncFunctionEnter), R(3), U8(2),
                B(Star), R(0),
                B(CreateClosure), U8(2), U8(0), U8(0),
                B(Star), R(1),
                B(Ldar), R(0),
  /*    0 E> */ B(SuspendGenerator), R(0), R(0), U8(3), U8(0),
                B(ResumeGenerator), R(0), R(0), U8(3),
                B(Star), R(3),
                B(InvokeIntrinsic), U8(Runtime::k_GeneratorGetResumeMode), R(0), U8(1),
                B(SwitchOnSmiNoFeedback), U8(3), U8(2), I8(0),
                B(Ldar), R(3),
  /*    0 E> */ B(Throw),
                B(Ldar), R(3),
  /*   54 S> */ B(Return),
                B(Mov), R(3), R(2),
                B(Ldar), R(2),
                B(Mov), R(context), R(3),
  /*    0 S> */ B(LdaSmi), I8(42),
                B(Star), R(5),
                B(Mov), R(0), R(4),
                B(InvokeIntrinsic), U8(Runtime::k_AsyncFunctionAwaitUncaught), R(4), U8(2),
  /*    0 E> */ B(SuspendGenerator), R(0), R(0), U8(4), U8(1),
                B(ResumeGenerator), R(0), R(0), U8(4),
                B(Star), R(4),
                B(InvokeIntrinsic), U8(Runtime::k_GeneratorGetResumeMode), R(0), U8(1),
                B(Star), R(5),
                B(LdaZero),
                B(TestReferenceEqual), R(5),
                B(JumpIfTrue), U8(5),
                B(Ldar), R(4),
                B(ReThrow),
  /*   47 S> */ B(CallUndefinedReceiver0), R(1), U8(0),
                B(LdaUndefined),
                B(Star), R(5),
                B(LdaTrue),
                B(Star), R(6),
                B(Mov), R(0), R(4),
                B(InvokeIntrinsic), U8(Runtime::k_AsyncFunctionResolve), R(4), U8(3),
  /*   54 S> */ B(Return),
                B(Star), R(4),
                B(CreateCatchContext), R(4), U8(5),
                B(Star), R(3),
                B(LdaTheHole),
                B(SetPendingMessage),
                B(Ldar), R(3),
                B(PushContext), R(4),
                B(LdaImmutableCurrentContextSlot), U8(2),
                B(Star), R(6),
                B(LdaTrue),
                B(Star), R(7),
                B(Mov), R(0), R(5),
                B(InvokeIntrinsic), U8(Runtime::k_AsyncFunctionReject), R(5), U8(3),
  /*   54 S> */ B(Return),
]
constant pool: [
  Smi [29],
  Smi [73],
  SHARED_FUNCTION_INFO_TYPE,
  Smi [10],
  Smi [7],
  SCOPE_INFO_TYPE,
]
handlers: [
  [58, 111, 111],
]

---
snippet: "
  import * as foo from \"bar\";
  await import(\"goo\");
"
frame size: 8
parameter count: 1
bytecode array length: 150
bytecodes: [
  /*    0 E> */ B(StackCheck),
                B(SwitchOnGeneratorState), R(0), U8(0), U8(2),
                B(Mov), R(closure), R(3),
                B(Mov), R(this), R(4),
                B(InvokeIntrinsic), U8(Runtime::k_AsyncFunctionEnter), R(3), U8(2),
                B(Star), R(0),
                B(LdaZero),
                B(Star), R(3),
                B(CallRuntime), U16(Runtime::kGetModuleNamespace), R(3), U8(1),
                B(Star), R(1),
                B(Ldar), R(0),
  /*    0 E> */ B(SuspendGenerator), R(0), R(0), U8(3), U8(0),
                B(ResumeGenerator), R(0), R(0), U8(3),
                B(Star), R(3),
                B(InvokeIntrinsic), U8(Runtime::k_GeneratorGetResumeMode), R(0), U8(1),
                B(SwitchOnSmiNoFeedback), U8(2), U8(2), I8(0),
                B(Ldar), R(3),
  /*    0 E> */ B(Throw),
                B(Ldar), R(3),
  /*   49 S> */ B(Return),
                B(Mov), R(3), R(2),
                B(Ldar), R(2),
                B(Mov), R(context), R(3),
  /*   28 S> */ B(LdaConstant), U8(4),
                B(Star), R(5),
                B(Mov), R(closure), R(4),
                B(CallRuntime), U16(Runtime::kDynamicImportCall), R(4), U8(2),
                B(Star), R(5),
                B(Mov), R(0), R(4),
                B(InvokeIntrinsic), U8(Runtime::k_AsyncFunctionAwaitUncaught), R(4), U8(2),
  /*   28 E> */ B(SuspendGenerator), R(0), R(0), U8(4), U8(1),
                B(ResumeGenerator), R(0), R(0), U8(4),
                B(Star), R(4),
                B(InvokeIntrinsic), U8(Runtime::k_GeneratorGetResumeMode), R(0), U8(1),
                B(Star), R(5),
                B(LdaZero),
                B(TestReferenceEqual), R(5),
                B(JumpIfTrue), U8(5),
                B(Ldar), R(4),
                B(ReThrow),
                B(LdaUndefined),
                B(Star), R(5),
                B(LdaTrue),
                B(Star), R(6),
                B(Mov), R(0), R(4),
                B(InvokeIntrinsic), U8(Runtime::k_AsyncFunctionResolve), R(4), U8(3),
  /*   49 S> */ B(Return),
                B(Star), R(4),
                B(CreateCatchContext), R(4), U8(5),
                B(Star), R(3),
                B(LdaTheHole),
                B(SetPendingMessage),
                B(Ldar), R(3),
                B(PushContext), R(4),
                B(LdaImmutableCurrentContextSlot), U8(2),
                B(Star), R(6),
                B(LdaTrue),
                B(Star), R(7),
                B(Mov), R(0), R(5),
                B(InvokeIntrinsic), U8(Runtime::k_AsyncFunctionReject), R(5), U8(3),
  /*   49 S> */ B(Return),
]
constant pool: [
  Smi [33],
  Smi [87],
  Smi [10],
  Smi [7],
  ONE_BYTE_INTERNALIZED_STRING_TYPE ["goo"],
  SCOPE_INFO_TYPE,
]
handlers: [
  [62, 122, 122],
]

