#
# Autogenerated by generate-bytecode-expectations.
#

---
wrap: yes

---
snippet: "
  Math.max(...[1, 2, 3]);
"
frame size: 3
parameter count: 1
bytecode array length: 21
bytecodes: [
  /*   34 S> */ B(LdaGlobal), U8(0), U8(0),
                B(Star1),
  /*   39 E> */ B(GetNamedProperty), R(1), U8(1), U8(2),
                B(Star0),
                B(CreateArrayLiteral), U8(2), U8(4), U8(37),
                B(Star2),
  /*   39 E> */ B(CallWithSpread), R(0), R(1), U8(2), U8(5),
                B(LdaUndefined),
  /*   58 S> */ B(Return),
]
constant pool: [
  ONE_BYTE_INTERNALIZED_STRING_TYPE ["Math"],
  ONE_BYTE_INTERNALIZED_STRING_TYPE ["max"],
  ARRAY_BOILERPLATE_DESCRIPTION_TYPE,
]
handlers: [
]

---
snippet: "
  Math.max(0, ...[1, 2, 3]);
"
frame size: 4
parameter count: 1
bytecode array length: 23
bytecodes: [
  /*   34 S> */ B(LdaGlobal), U8(0), U8(0),
                B(Star1),
  /*   39 E> */ B(GetNamedProperty), R(1), U8(1), U8(2),
                B(Star0),
                B(LdaZero),
                B(Star2),
                B(CreateArrayLiteral), U8(2), U8(4), U8(37),
                B(Star3),
  /*   39 E> */ B(CallWithSpread), R(0), R(1), U8(3), U8(5),
                B(LdaUndefined),
  /*   61 S> */ B(Return),
]
constant pool: [
  ONE_BYTE_INTERNALIZED_STRING_TYPE ["Math"],
  ONE_BYTE_INTERNALIZED_STRING_TYPE ["max"],
  ARRAY_BOILERPLATE_DESCRIPTION_TYPE,
]
handlers: [
]

---
snippet: "
  Math.max(0, ...[1, 2, 3], 4);
"
frame size: 7
parameter count: 1
bytecode array length: 89
bytecodes: [
  /*   34 S> */ B(LdaGlobal), U8(0), U8(0),
                B(Star1),
  /*   39 E> */ B(GetNamedProperty), R(1), U8(1), U8(2),
                B(Star0),
                B(CreateArrayLiteral), U8(2), U8(4), U8(37),
                B(Star3),
                B(LdaSmi), I8(1),
                B(Star2),
  /*   49 S> */ B(CreateArrayLiteral), U8(3), U8(5), U8(37),
                B(Star6),
  /*   49 E> */ B(GetIterator), R(6), U8(6), U8(8),
                B(JumpIfJSReceiver), U8(7),
                B(CallRuntime), U16(Runtime::kThrowSymbolIteratorInvalid), R(0), U8(0),
                B(Star5),
                B(GetNamedProperty), R(5), U8(4), U8(10),
                B(Star4),
                B(CallProperty0), R(4), R(5), U8(19),
                B(Star6),
                B(JumpIfJSReceiver), U8(7),
                B(CallRuntime), U16(Runtime::kThrowIteratorResultNotAnObject), R(6), U8(1),
                B(GetNamedProperty), R(6), U8(5), U8(21),
                B(JumpIfToBooleanTrue), U8(19),
                B(GetNamedProperty), R(6), U8(6), U8(12),
                B(StaInArrayLiteral), R(3), R(2), U8(17),
                B(Ldar), R(2),
                B(Inc), U8(16),
                B(Star2),
                B(JumpLoop), U8(31), I8(0), U8(23),
                B(LdaSmi), I8(4),
                B(StaInArrayLiteral), R(3), R(2), U8(17),
                B(Mov), R(3), R(2),
  /*   39 E> */ B(CallJSRuntime), U8(%reflect_apply), R(0), U8(3),
                B(LdaUndefined),
  /*   64 S> */ B(Return),
]
constant pool: [
  ONE_BYTE_INTERNALIZED_STRING_TYPE ["Math"],
  ONE_BYTE_INTERNALIZED_STRING_TYPE ["max"],
  ARRAY_BOILERPLATE_DESCRIPTION_TYPE,
  ARRAY_BOILERPLATE_DESCRIPTION_TYPE,
  ONE_BYTE_INTERNALIZED_STRING_TYPE ["next"],
  ONE_BYTE_INTERNALIZED_STRING_TYPE ["done"],
  ONE_BYTE_INTERNALIZED_STRING_TYPE ["value"],
]
handlers: [
]

