#
# Autogenerated by generate-bytecode-expectations.
#

---
wrap: yes

---
snippet: "
  return typeof(1) === 'number';
"
frame size: 0
parameter count: 1
bytecode array length: 6
bytecodes: [
  /*   30 E> */ B(StackCheck),
  /*   34 S> */ B(LdaSmi), I8(1),
  /*   51 E> */ B(TestTypeOf), U8(0),
  /*   65 S> */ B(Return),
]
constant pool: [
]
handlers: [
]

---
snippet: "
  return 'string' === typeof('foo');
"
frame size: 0
parameter count: 1
bytecode array length: 6
bytecodes: [
  /*   30 E> */ B(StackCheck),
  /*   34 S> */ B(LdaConstant), U8(0),
  /*   50 E> */ B(TestTypeOf), U8(1),
  /*   69 S> */ B(Return),
]
constant pool: [
  ONE_BYTE_INTERNALIZED_STRING_TYPE ["foo"],
]
handlers: [
]

---
snippet: "
  return typeof(true) == 'boolean';
"
frame size: 0
parameter count: 1
bytecode array length: 5
bytecodes: [
  /*   30 E> */ B(StackCheck),
  /*   34 S> */ B(LdaTrue),
  /*   54 E> */ B(TestTypeOf), U8(3),
  /*   68 S> */ B(Return),
]
constant pool: [
]
handlers: [
]

---
snippet: "
  return 'string' === typeof(undefined);
"
frame size: 0
parameter count: 1
bytecode array length: 5
bytecodes: [
  /*   30 E> */ B(StackCheck),
  /*   34 S> */ B(LdaUndefined),
  /*   50 E> */ B(TestTypeOf), U8(1),
  /*   73 S> */ B(Return),
]
constant pool: [
]
handlers: [
]

---
snippet: "
  return 'unknown' === typeof(undefined);
"
frame size: 0
parameter count: 1
bytecode array length: 3
bytecodes: [
  /*   30 E> */ B(StackCheck),
  /*   34 S> */ B(LdaFalse),
  /*   74 S> */ B(Return),
]
constant pool: [
]
handlers: [
]

