#
# Autogenerated by generate-bytecode-expectations.
#

---
wrap: yes

---
snippet: "
  return (1 === true) ? 1 : 2;
"
frame size: 0
parameter count: 1
bytecode array length: 14
bytecodes: [
  /*   30 E> */ B(StackCheck),
  /*   34 S> */ B(LdaSmi), I8(1),
                B(JumpIfTrue), U8(4),
                B(Jump), U8(6),
                B(LdaSmi), I8(1),
                B(Jump), U8(4),
                B(LdaSmi), I8(2),
  /*   63 S> */ B(Return),
]
constant pool: [
]
handlers: [
]

---
snippet: "
  return (false === 1) ? 1 : 2;
"
frame size: 0
parameter count: 1
bytecode array length: 14
bytecodes: [
  /*   30 E> */ B(StackCheck),
  /*   34 S> */ B(LdaSmi), I8(1),
                B(JumpIfFalse), U8(4),
                B(Jump), U8(6),
                B(LdaSmi), I8(1),
                B(Jump), U8(4),
                B(LdaSmi), I8(2),
  /*   64 S> */ B(Return),
]
constant pool: [
]
handlers: [
]

---
snippet: "
  return (1 === true || 0 === false) ? 1 : 2;
"
frame size: 0
parameter count: 1
bytecode array length: 17
bytecodes: [
  /*   30 E> */ B(StackCheck),
  /*   34 S> */ B(LdaSmi), I8(1),
                B(JumpIfTrue), U8(7),
                B(LdaZero),
                B(JumpIfFalse), U8(4),
                B(Jump), U8(6),
                B(LdaSmi), I8(1),
                B(Jump), U8(4),
                B(LdaSmi), I8(2),
  /*   78 S> */ B(Return),
]
constant pool: [
]
handlers: [
]

---
snippet: "
  if (1 === true || 1 === false) return 1;
"
frame size: 0
parameter count: 1
bytecode array length: 16
bytecodes: [
  /*   30 E> */ B(StackCheck),
  /*   34 S> */ B(LdaSmi), I8(1),
                B(JumpIfTrue), U8(8),
                B(LdaSmi), I8(1),
                B(JumpIfFalse), U8(4),
                B(Jump), U8(5),
  /*   65 S> */ B(LdaSmi), I8(1),
  /*   75 S> */ B(Return),
                B(LdaUndefined),
  /*   75 S> */ B(Return),
]
constant pool: [
]
handlers: [
]

---
snippet: "
  if (!('false' === false)) return 1;
"
frame size: 0
parameter count: 1
bytecode array length: 10
bytecodes: [
  /*   30 E> */ B(StackCheck),
  /*   34 S> */ B(LdaConstant), U8(0),
                B(JumpIfFalse), U8(5),
  /*   60 S> */ B(LdaSmi), I8(1),
  /*   70 S> */ B(Return),
                B(LdaUndefined),
  /*   70 S> */ B(Return),
]
constant pool: [
  ONE_BYTE_INTERNALIZED_STRING_TYPE ["false"],
]
handlers: [
]

