#
# Autogenerated by generate-bytecode-expectations.
#

---
wrap: yes

---
snippet: "
  var a = 1;
  return a === null;
"
frame size: 1
parameter count: 1
bytecode array length: 6
bytecodes: [
  /*   42 S> */ B(LdaSmi), I8(1),
                B(Star), R(0),
  /*   45 S> */ B(TestNull),
  /*   63 S> */ B(Return),
]
constant pool: [
]
handlers: [
]

---
snippet: "
  var a = undefined;
  return undefined === a;
"
frame size: 1
parameter count: 1
bytecode array length: 5
bytecodes: [
  /*   42 S> */ B(LdaUndefined),
                B(Star), R(0),
  /*   53 S> */ B(TestUndefined),
  /*   76 S> */ B(Return),
]
constant pool: [
]
handlers: [
]

---
snippet: "
  var a = undefined;
  return undefined !== a;
"
frame size: 1
parameter count: 1
bytecode array length: 6
bytecodes: [
  /*   42 S> */ B(LdaUndefined),
                B(Star), R(0),
  /*   53 S> */ B(TestUndefined),
  /*   70 E> */ B(LogicalNot),
  /*   76 S> */ B(Return),
]
constant pool: [
]
handlers: [
]

---
snippet: "
  var a = 2;
  return a != null;
"
frame size: 1
parameter count: 1
bytecode array length: 7
bytecodes: [
  /*   42 S> */ B(LdaSmi), I8(2),
                B(Star), R(0),
  /*   45 S> */ B(TestUndetectable),
  /*   54 E> */ B(LogicalNot),
  /*   62 S> */ B(Return),
]
constant pool: [
]
handlers: [
]

---
snippet: "
  var a = undefined;
  return undefined == a;
"
frame size: 1
parameter count: 1
bytecode array length: 5
bytecodes: [
  /*   42 S> */ B(LdaUndefined),
                B(Star), R(0),
  /*   53 S> */ B(TestUndetectable),
  /*   75 S> */ B(Return),
]
constant pool: [
]
handlers: [
]

---
snippet: "
  var a = undefined;
  return undefined === a ? 1 : 2;
"
frame size: 1
parameter count: 1
bytecode array length: 12
bytecodes: [
  /*   42 S> */ B(LdaUndefined),
                B(Star), R(0),
  /*   53 S> */ B(JumpIfNotUndefined), U8(6),
                B(LdaSmi), I8(1),
                B(Jump), U8(4),
                B(LdaSmi), I8(2),
  /*   84 S> */ B(Return),
]
constant pool: [
]
handlers: [
]

---
snippet: "
  var a = 0;
  return null == a ? 1 : 2;
"
frame size: 1
parameter count: 1
bytecode array length: 13
bytecodes: [
  /*   42 S> */ B(LdaZero),
                B(Star), R(0),
  /*   45 S> */ B(TestUndetectable),
                B(JumpIfFalse), U8(6),
                B(LdaSmi), I8(1),
                B(Jump), U8(4),
                B(LdaSmi), I8(2),
  /*   70 S> */ B(Return),
]
constant pool: [
]
handlers: [
]

---
snippet: "
  var a = 0;
  return undefined !== a ? 1 : 2;
"
frame size: 1
parameter count: 1
bytecode array length: 12
bytecodes: [
  /*   42 S> */ B(LdaZero),
                B(Star), R(0),
  /*   45 S> */ B(JumpIfUndefined), U8(6),
                B(LdaSmi), I8(1),
                B(Jump), U8(4),
                B(LdaSmi), I8(2),
  /*   76 S> */ B(Return),
]
constant pool: [
]
handlers: [
]

---
snippet: "
  var a = 0;
  return a === null ? 1 : 2;
"
frame size: 1
parameter count: 1
bytecode array length: 12
bytecodes: [
  /*   42 S> */ B(LdaZero),
                B(Star), R(0),
  /*   45 S> */ B(JumpIfNotNull), U8(6),
                B(LdaSmi), I8(1),
                B(Jump), U8(4),
                B(LdaSmi), I8(2),
  /*   71 S> */ B(Return),
]
constant pool: [
]
handlers: [
]

---
snippet: "
  var a = 0;
  if (a === null) {
    return 1;
  } else {
    return 2;
  }
"
frame size: 1
parameter count: 1
bytecode array length: 11
bytecodes: [
  /*   42 S> */ B(LdaZero),
                B(Star), R(0),
  /*   45 S> */ B(JumpIfNotNull), U8(5),
  /*   65 S> */ B(LdaSmi), I8(1),
  /*   74 S> */ B(Return),
  /*   86 S> */ B(LdaSmi), I8(2),
  /*   95 S> */ B(Return),
]
constant pool: [
]
handlers: [
]

---
snippet: "
  var a = 0;
  if (a != undefined) {
    return 1;
  }
"
frame size: 1
parameter count: 1
bytecode array length: 11
bytecodes: [
  /*   42 S> */ B(LdaZero),
                B(Star), R(0),
  /*   45 S> */ B(TestUndetectable),
                B(JumpIfTrue), U8(5),
  /*   69 S> */ B(LdaSmi), I8(1),
  /*   78 S> */ B(Return),
                B(LdaUndefined),
  /*   81 S> */ B(Return),
]
constant pool: [
]
handlers: [
]

---
snippet: "
  var a = undefined;
  var b = 0;
  while (a !== undefined) {
    b++;
  }
"
frame size: 2
parameter count: 1
bytecode array length: 22
bytecodes: [
  /*   42 S> */ B(LdaUndefined),
                B(Star), R(0),
  /*   61 S> */ B(LdaZero),
                B(Star), R(1),
  /*   73 S> */ B(Ldar), R(0),
                B(JumpIfUndefined), U8(12),
  /*   92 S> */ B(Ldar), R(1),
                B(Inc), U8(0),
                B(Star), R(1),
  /*   64 E> */ B(StackCheck),
                B(JumpLoop), U8(11), I8(0),
                B(LdaUndefined),
  /*   99 S> */ B(Return),
]
constant pool: [
]
handlers: [
]

