#
# Autogenerated by generate-bytecode-expectations.
#

---
wrap: yes

---
snippet: "
  return 1 ? 2 : 3;
"
frame size: 0
parameter count: 1
bytecode array length: 4
bytecodes: [
  /*   30 E> */ B(StackCheck),
  /*   34 S> */ B(LdaSmi), I8(2),
  /*   51 S> */ B(Return),
]
constant pool: [
]
handlers: [
]

---
snippet: "
  return 1 ? 2 ? 3 : 4 : 5;
"
frame size: 0
parameter count: 1
bytecode array length: 4
bytecodes: [
  /*   30 E> */ B(StackCheck),
  /*   34 S> */ B(LdaSmi), I8(3),
  /*   59 S> */ B(Return),
]
constant pool: [
]
handlers: [
]

---
snippet: "
  return 0 < 1 ? 2 : 3;
"
frame size: 1
parameter count: 1
bytecode array length: 18
bytecodes: [
  /*   30 E> */ B(StackCheck),
  /*   34 S> */ B(LdaZero),
                B(Star), R(0),
                B(LdaSmi), I8(1),
  /*   43 E> */ B(TestLessThan), R(0), U8(4),
                B(JumpIfFalse), U8(6),
                B(LdaSmi), I8(2),
                B(Jump), U8(4),
                B(LdaSmi), I8(3),
  /*   55 S> */ B(Return),
]
constant pool: [
]
handlers: [
]

---
snippet: "
  var x = 0;
  return x ? 2 : 3;
"
frame size: 1
parameter count: 1
bytecode array length: 13
bytecodes: [
  /*   30 E> */ B(StackCheck),
  /*   42 S> */ B(LdaZero),
                B(Star), R(0),
  /*   45 S> */ B(JumpIfToBooleanFalse), U8(6),
                B(LdaSmi), I8(2),
                B(Jump), U8(4),
                B(LdaSmi), I8(3),
  /*   62 S> */ B(Return),
]
constant pool: [
]
handlers: [
]

