#
# Autogenerated by generate-bytecode-expectations.
#

---
execute: yes
wrap: yes

---
snippet: "
  return; var a = 1; a();
"
frame size: 1
parameter count: 1
bytecode array length: 3
bytecodes: [
  /*   30 E> */ B(StackCheck),
  /*   34 S> */ B(LdaUndefined),
  /*   58 S> */ B(Return),
]
constant pool: [
]
handlers: [
]

---
snippet: "
  if (false) { return; }; var a = 1;
"
frame size: 1
parameter count: 1
bytecode array length: 7
bytecodes: [
  /*   30 E> */ B(StackCheck),
  /*   66 S> */ B(LdaSmi), U8(1),
                B(Star), R(0),
                B(LdaUndefined),
  /*   69 S> */ B(Return),
]
constant pool: [
]
handlers: [
]

---
snippet: "
  if (true) { return 1; } else { return 2; };
"
frame size: 0
parameter count: 1
bytecode array length: 4
bytecodes: [
  /*   30 E> */ B(StackCheck),
  /*   46 S> */ B(LdaSmi), U8(1),
  /*   78 S> */ B(Return),
]
constant pool: [
]
handlers: [
]

---
snippet: "
  var a = 1; if (a) { return 1; }; return 2;
"
frame size: 1
parameter count: 1
bytecode array length: 13
bytecodes: [
  /*   30 E> */ B(StackCheck),
  /*   42 S> */ B(LdaSmi), U8(1),
                B(Star), R(0),
  /*   45 S> */ B(JumpIfToBooleanFalse), U8(5),
  /*   54 S> */ B(LdaSmi), U8(1),
  /*   77 S> */ B(Return),
  /*   67 S> */ B(LdaSmi), U8(2),
  /*   77 S> */ B(Return),
]
constant pool: [
]
handlers: [
]

