#
# Autogenerated by generate-bytecode-expectations.
#

---
wrap: no
test function name: f

---
snippet: "
  var global = 1;
  function f() { return global &= 1; }
  f();
"
frame size: 0
parameter count: 1
bytecode array length: 11
bytecodes: [
  /*   26 E> */ B(StackCheck),
  /*   31 S> */ B(LdaGlobal), U8(0), U8(4),
                B(BitwiseAndSmi), I8(1), U8(6),
  /*   45 E> */ B(StaGlobalSloppy), U8(0), U8(7),
  /*   50 S> */ B(Return),
]
constant pool: [
  ONE_BYTE_INTERNALIZED_STRING_TYPE ["global"],
]
handlers: [
]

---
snippet: "
  unallocated = 1;
  function f() { return unallocated += 1; }
  f();
"
frame size: 0
parameter count: 1
bytecode array length: 11
bytecodes: [
  /*   27 E> */ B(StackCheck),
  /*   32 S> */ B(LdaGlobal), U8(0), U8(4),
                B(AddSmi), I8(1), U8(6),
  /*   51 E> */ B(StaGlobalSloppy), U8(0), U8(7),
  /*   56 S> */ B(Return),
]
constant pool: [
  ONE_BYTE_INTERNALIZED_STRING_TYPE ["unallocated"],
]
handlers: [
]

