#
# Autogenerated by generate-bytecode-expectations.
#

---
execute: yes
wrap: yes

---
snippet: "
  return 1.2;
"
frame size: 0
parameter count: 1
bytecode array length: 4
bytecodes: [
  /*   30 E> */ B(StackCheck),
  /*   34 S> */ B(LdaConstant), U8(0),
  /*   46 S> */ B(Return),
]
constant pool: [
  HEAP_NUMBER_TYPE [1.2],
]
handlers: [
]

---
snippet: "
  var a = 1.2; return 2.6;
"
frame size: 1
parameter count: 1
bytecode array length: 8
bytecodes: [
  /*   30 E> */ B(StackCheck),
  /*   42 S> */ B(LdaConstant), U8(0),
                B(Star), R(0),
  /*   47 S> */ B(LdaConstant), U8(1),
  /*   59 S> */ B(Return),
]
constant pool: [
  HEAP_NUMBER_TYPE [1.2],
  HEAP_NUMBER_TYPE [2.6],
]
handlers: [
]

---
snippet: "
  var a = 3.14; return 3.14;
"
frame size: 1
parameter count: 1
bytecode array length: 8
bytecodes: [
  /*   30 E> */ B(StackCheck),
  /*   42 S> */ B(LdaConstant), U8(0),
                B(Star), R(0),
  /*   48 S> */ B(LdaConstant), U8(1),
  /*   61 S> */ B(Return),
]
constant pool: [
  HEAP_NUMBER_TYPE [3.14],
  HEAP_NUMBER_TYPE [3.14],
]
handlers: [
]

---
snippet: "
  var a;
  a = 1.414;
  a = 1.414;
  a = 1.414;
  a = 1.414;
  a = 1.414;
  a = 1.414;
  a = 1.414;
  a = 1.414;
  a = 1.414;
  a = 1.414;
  a = 1.414;
  a = 1.414;
  a = 1.414;
  a = 1.414;
  a = 1.414;
  a = 1.414;
  a = 1.414;
  a = 1.414;
  a = 1.414;
  a = 1.414;
  a = 1.414;
  a = 1.414;
  a = 1.414;
  a = 1.414;
  a = 1.414;
  a = 1.414;
  a = 1.414;
  a = 1.414;
  a = 1.414;
  a = 1.414;
  a = 1.414;
  a = 1.414;
  a = 1.414;
  a = 1.414;
  a = 1.414;
  a = 1.414;
  a = 1.414;
  a = 1.414;
  a = 1.414;
  a = 1.414;
  a = 1.414;
  a = 1.414;
  a = 1.414;
  a = 1.414;
  a = 1.414;
  a = 1.414;
  a = 1.414;
  a = 1.414;
  a = 1.414;
  a = 1.414;
  a = 1.414;
  a = 1.414;
  a = 1.414;
  a = 1.414;
  a = 1.414;
  a = 1.414;
  a = 1.414;
  a = 1.414;
  a = 1.414;
  a = 1.414;
  a = 1.414;
  a = 1.414;
  a = 1.414;
  a = 1.414;
  a = 1.414;
  a = 1.414;
  a = 1.414;
  a = 1.414;
  a = 1.414;
  a = 1.414;
  a = 1.414;
  a = 1.414;
  a = 1.414;
  a = 1.414;
  a = 1.414;
  a = 1.414;
  a = 1.414;
  a = 1.414;
  a = 1.414;
  a = 1.414;
  a = 1.414;
  a = 1.414;
  a = 1.414;
  a = 1.414;
  a = 1.414;
  a = 1.414;
  a = 1.414;
  a = 1.414;
  a = 1.414;
  a = 1.414;
  a = 1.414;
  a = 1.414;
  a = 1.414;
  a = 1.414;
  a = 1.414;
  a = 1.414;
  a = 1.414;
  a = 1.414;
  a = 1.414;
  a = 1.414;
  a = 1.414;
  a = 1.414;
  a = 1.414;
  a = 1.414;
  a = 1.414;
  a = 1.414;
  a = 1.414;
  a = 1.414;
  a = 1.414;
  a = 1.414;
  a = 1.414;
  a = 1.414;
  a = 1.414;
  a = 1.414;
  a = 1.414;
  a = 1.414;
  a = 1.414;
  a = 1.414;
  a = 1.414;
  a = 1.414;
  a = 1.414;
  a = 1.414;
  a = 1.414;
  a = 1.414;
  a = 1.414;
  a = 1.414;
  a = 1.414;
  a = 1.414;
  a = 1.414;
  a = 1.414;
  a = 1.414;
  a = 1.414;
  a = 1.414;
  a = 1.414;
  a = 1.414;
  a = 1.414;
  a = 1.414;
  a = 1.414;
  a = 1.414;
  a = 1.414;
  a = 1.414;
  a = 1.414;
  a = 1.414;
  a = 1.414;
  a = 1.414;
  a = 1.414;
  a = 1.414;
  a = 1.414;
  a = 1.414;
  a = 1.414;
  a = 1.414;
  a = 1.414;
  a = 1.414;
  a = 1.414;
  a = 1.414;
  a = 1.414;
  a = 1.414;
  a = 1.414;
  a = 1.414;
  a = 1.414;
  a = 1.414;
  a = 1.414;
  a = 1.414;
  a = 1.414;
  a = 1.414;
  a = 1.414;
  a = 1.414;
  a = 1.414;
  a = 1.414;
  a = 1.414;
  a = 1.414;
  a = 1.414;
  a = 1.414;
  a = 1.414;
  a = 1.414;
  a = 1.414;
  a = 1.414;
  a = 1.414;
  a = 1.414;
  a = 1.414;
  a = 1.414;
  a = 1.414;
  a = 1.414;
  a = 1.414;
  a = 1.414;
  a = 1.414;
  a = 1.414;
  a = 1.414;
  a = 1.414;
  a = 1.414;
  a = 1.414;
  a = 1.414;
  a = 1.414;
  a = 1.414;
  a = 1.414;
  a = 1.414;
  a = 1.414;
  a = 1.414;
  a = 1.414;
  a = 1.414;
  a = 1.414;
  a = 1.414;
  a = 1.414;
  a = 1.414;
  a = 1.414;
  a = 1.414;
  a = 1.414;
  a = 1.414;
  a = 1.414;
  a = 1.414;
  a = 1.414;
  a = 1.414;
  a = 1.414;
  a = 1.414;
  a = 1.414;
  a = 1.414;
  a = 1.414;
  a = 1.414;
  a = 1.414;
  a = 1.414;
  a = 1.414;
  a = 1.414;
  a = 1.414;
  a = 1.414;
  a = 1.414;
  a = 1.414;
  a = 1.414;
  a = 1.414;
  a = 1.414;
  a = 1.414;
  a = 1.414;
  a = 1.414;
  a = 1.414;
  a = 1.414;
  a = 1.414;
  a = 1.414;
  a = 1.414;
  a = 1.414;
  a = 1.414;
  a = 1.414;
  a = 1.414;
  a = 1.414;
  a = 1.414;
  a = 1.414;
  a = 1.414;
  a = 1.414;
  a = 1.414;
  a = 1.414;
  a = 1.414;
  a = 1.414;
  a = 1.414;
  a = 1.414;
  a = 1.414;
  a = 1.414;
  a = 1.414;
  a = 1.414; a = 3.14;
"
frame size: 1
parameter count: 1
bytecode array length: 1033
bytecodes: [
  /*   30 E> */ B(StackCheck),
  /*   41 S> */ B(LdaConstant), U8(0),
                B(Star), R(0),
  /*   52 S> */ B(LdaConstant), U8(1),
                B(Star), R(0),
  /*   63 S> */ B(LdaConstant), U8(2),
                B(Star), R(0),
  /*   74 S> */ B(LdaConstant), U8(3),
                B(Star), R(0),
  /*   85 S> */ B(LdaConstant), U8(4),
                B(Star), R(0),
  /*   96 S> */ B(LdaConstant), U8(5),
                B(Star), R(0),
  /*  107 S> */ B(LdaConstant), U8(6),
                B(Star), R(0),
  /*  118 S> */ B(LdaConstant), U8(7),
                B(Star), R(0),
  /*  129 S> */ B(LdaConstant), U8(8),
                B(Star), R(0),
  /*  140 S> */ B(LdaConstant), U8(9),
                B(Star), R(0),
  /*  151 S> */ B(LdaConstant), U8(10),
                B(Star), R(0),
  /*  162 S> */ B(LdaConstant), U8(11),
                B(Star), R(0),
  /*  173 S> */ B(LdaConstant), U8(12),
                B(Star), R(0),
  /*  184 S> */ B(LdaConstant), U8(13),
                B(Star), R(0),
  /*  195 S> */ B(LdaConstant), U8(14),
                B(Star), R(0),
  /*  206 S> */ B(LdaConstant), U8(15),
                B(Star), R(0),
  /*  217 S> */ B(LdaConstant), U8(16),
                B(Star), R(0),
  /*  228 S> */ B(LdaConstant), U8(17),
                B(Star), R(0),
  /*  239 S> */ B(LdaConstant), U8(18),
                B(Star), R(0),
  /*  250 S> */ B(LdaConstant), U8(19),
                B(Star), R(0),
  /*  261 S> */ B(LdaConstant), U8(20),
                B(Star), R(0),
  /*  272 S> */ B(LdaConstant), U8(21),
                B(Star), R(0),
  /*  283 S> */ B(LdaConstant), U8(22),
                B(Star), R(0),
  /*  294 S> */ B(LdaConstant), U8(23),
                B(Star), R(0),
  /*  305 S> */ B(LdaConstant), U8(24),
                B(Star), R(0),
  /*  316 S> */ B(LdaConstant), U8(25),
                B(Star), R(0),
  /*  327 S> */ B(LdaConstant), U8(26),
                B(Star), R(0),
  /*  338 S> */ B(LdaConstant), U8(27),
                B(Star), R(0),
  /*  349 S> */ B(LdaConstant), U8(28),
                B(Star), R(0),
  /*  360 S> */ B(LdaConstant), U8(29),
                B(Star), R(0),
  /*  371 S> */ B(LdaConstant), U8(30),
                B(Star), R(0),
  /*  382 S> */ B(LdaConstant), U8(31),
                B(Star), R(0),
  /*  393 S> */ B(LdaConstant), U8(32),
                B(Star), R(0),
  /*  404 S> */ B(LdaConstant), U8(33),
                B(Star), R(0),
  /*  415 S> */ B(LdaConstant), U8(34),
                B(Star), R(0),
  /*  426 S> */ B(LdaConstant), U8(35),
                B(Star), R(0),
  /*  437 S> */ B(LdaConstant), U8(36),
                B(Star), R(0),
  /*  448 S> */ B(LdaConstant), U8(37),
                B(Star), R(0),
  /*  459 S> */ B(LdaConstant), U8(38),
                B(Star), R(0),
  /*  470 S> */ B(LdaConstant), U8(39),
                B(Star), R(0),
  /*  481 S> */ B(LdaConstant), U8(40),
                B(Star), R(0),
  /*  492 S> */ B(LdaConstant), U8(41),
                B(Star), R(0),
  /*  503 S> */ B(LdaConstant), U8(42),
                B(Star), R(0),
  /*  514 S> */ B(LdaConstant), U8(43),
                B(Star), R(0),
  /*  525 S> */ B(LdaConstant), U8(44),
                B(Star), R(0),
  /*  536 S> */ B(LdaConstant), U8(45),
                B(Star), R(0),
  /*  547 S> */ B(LdaConstant), U8(46),
                B(Star), R(0),
  /*  558 S> */ B(LdaConstant), U8(47),
                B(Star), R(0),
  /*  569 S> */ B(LdaConstant), U8(48),
                B(Star), R(0),
  /*  580 S> */ B(LdaConstant), U8(49),
                B(Star), R(0),
  /*  591 S> */ B(LdaConstant), U8(50),
                B(Star), R(0),
  /*  602 S> */ B(LdaConstant), U8(51),
                B(Star), R(0),
  /*  613 S> */ B(LdaConstant), U8(52),
                B(Star), R(0),
  /*  624 S> */ B(LdaConstant), U8(53),
                B(Star), R(0),
  /*  635 S> */ B(LdaConstant), U8(54),
                B(Star), R(0),
  /*  646 S> */ B(LdaConstant), U8(55),
                B(Star), R(0),
  /*  657 S> */ B(LdaConstant), U8(56),
                B(Star), R(0),
  /*  668 S> */ B(LdaConstant), U8(57),
                B(Star), R(0),
  /*  679 S> */ B(LdaConstant), U8(58),
                B(Star), R(0),
  /*  690 S> */ B(LdaConstant), U8(59),
                B(Star), R(0),
  /*  701 S> */ B(LdaConstant), U8(60),
                B(Star), R(0),
  /*  712 S> */ B(LdaConstant), U8(61),
                B(Star), R(0),
  /*  723 S> */ B(LdaConstant), U8(62),
                B(Star), R(0),
  /*  734 S> */ B(LdaConstant), U8(63),
                B(Star), R(0),
  /*  745 S> */ B(LdaConstant), U8(64),
                B(Star), R(0),
  /*  756 S> */ B(LdaConstant), U8(65),
                B(Star), R(0),
  /*  767 S> */ B(LdaConstant), U8(66),
                B(Star), R(0),
  /*  778 S> */ B(LdaConstant), U8(67),
                B(Star), R(0),
  /*  789 S> */ B(LdaConstant), U8(68),
                B(Star), R(0),
  /*  800 S> */ B(LdaConstant), U8(69),
                B(Star), R(0),
  /*  811 S> */ B(LdaConstant), U8(70),
                B(Star), R(0),
  /*  822 S> */ B(LdaConstant), U8(71),
                B(Star), R(0),
  /*  833 S> */ B(LdaConstant), U8(72),
                B(Star), R(0),
  /*  844 S> */ B(LdaConstant), U8(73),
                B(Star), R(0),
  /*  855 S> */ B(LdaConstant), U8(74),
                B(Star), R(0),
  /*  866 S> */ B(LdaConstant), U8(75),
                B(Star), R(0),
  /*  877 S> */ B(LdaConstant), U8(76),
                B(Star), R(0),
  /*  888 S> */ B(LdaConstant), U8(77),
                B(Star), R(0),
  /*  899 S> */ B(LdaConstant), U8(78),
                B(Star), R(0),
  /*  910 S> */ B(LdaConstant), U8(79),
                B(Star), R(0),
  /*  921 S> */ B(LdaConstant), U8(80),
                B(Star), R(0),
  /*  932 S> */ B(LdaConstant), U8(81),
                B(Star), R(0),
  /*  943 S> */ B(LdaConstant), U8(82),
                B(Star), R(0),
  /*  954 S> */ B(LdaConstant), U8(83),
                B(Star), R(0),
  /*  965 S> */ B(LdaConstant), U8(84),
                B(Star), R(0),
  /*  976 S> */ B(LdaConstant), U8(85),
                B(Star), R(0),
  /*  987 S> */ B(LdaConstant), U8(86),
                B(Star), R(0),
  /*  998 S> */ B(LdaConstant), U8(87),
                B(Star), R(0),
  /* 1009 S> */ B(LdaConstant), U8(88),
                B(Star), R(0),
  /* 1020 S> */ B(LdaConstant), U8(89),
                B(Star), R(0),
  /* 1031 S> */ B(LdaConstant), U8(90),
                B(Star), R(0),
  /* 1042 S> */ B(LdaConstant), U8(91),
                B(Star), R(0),
  /* 1053 S> */ B(LdaConstant), U8(92),
                B(Star), R(0),
  /* 1064 S> */ B(LdaConstant), U8(93),
                B(Star), R(0),
  /* 1075 S> */ B(LdaConstant), U8(94),
                B(Star), R(0),
  /* 1086 S> */ B(LdaConstant), U8(95),
                B(Star), R(0),
  /* 1097 S> */ B(LdaConstant), U8(96),
                B(Star), R(0),
  /* 1108 S> */ B(LdaConstant), U8(97),
                B(Star), R(0),
  /* 1119 S> */ B(LdaConstant), U8(98),
                B(Star), R(0),
  /* 1130 S> */ B(LdaConstant), U8(99),
                B(Star), R(0),
  /* 1141 S> */ B(LdaConstant), U8(100),
                B(Star), R(0),
  /* 1152 S> */ B(LdaConstant), U8(101),
                B(Star), R(0),
  /* 1163 S> */ B(LdaConstant), U8(102),
                B(Star), R(0),
  /* 1174 S> */ B(LdaConstant), U8(103),
                B(Star), R(0),
  /* 1185 S> */ B(LdaConstant), U8(104),
                B(Star), R(0),
  /* 1196 S> */ B(LdaConstant), U8(105),
                B(Star), R(0),
  /* 1207 S> */ B(LdaConstant), U8(106),
                B(Star), R(0),
  /* 1218 S> */ B(LdaConstant), U8(107),
                B(Star), R(0),
  /* 1229 S> */ B(LdaConstant), U8(108),
                B(Star), R(0),
  /* 1240 S> */ B(LdaConstant), U8(109),
                B(Star), R(0),
  /* 1251 S> */ B(LdaConstant), U8(110),
                B(Star), R(0),
  /* 1262 S> */ B(LdaConstant), U8(111),
                B(Star), R(0),
  /* 1273 S> */ B(LdaConstant), U8(112),
                B(Star), R(0),
  /* 1284 S> */ B(LdaConstant), U8(113),
                B(Star), R(0),
  /* 1295 S> */ B(LdaConstant), U8(114),
                B(Star), R(0),
  /* 1306 S> */ B(LdaConstant), U8(115),
                B(Star), R(0),
  /* 1317 S> */ B(LdaConstant), U8(116),
                B(Star), R(0),
  /* 1328 S> */ B(LdaConstant), U8(117),
                B(Star), R(0),
  /* 1339 S> */ B(LdaConstant), U8(118),
                B(Star), R(0),
  /* 1350 S> */ B(LdaConstant), U8(119),
                B(Star), R(0),
  /* 1361 S> */ B(LdaConstant), U8(120),
                B(Star), R(0),
  /* 1372 S> */ B(LdaConstant), U8(121),
                B(Star), R(0),
  /* 1383 S> */ B(LdaConstant), U8(122),
                B(Star), R(0),
  /* 1394 S> */ B(LdaConstant), U8(123),
                B(Star), R(0),
  /* 1405 S> */ B(LdaConstant), U8(124),
                B(Star), R(0),
  /* 1416 S> */ B(LdaConstant), U8(125),
                B(Star), R(0),
  /* 1427 S> */ B(LdaConstant), U8(126),
                B(Star), R(0),
  /* 1438 S> */ B(LdaConstant), U8(127),
                B(Star), R(0),
  /* 1449 S> */ B(LdaConstant), U8(128),
                B(Star), R(0),
  /* 1460 S> */ B(LdaConstant), U8(129),
                B(Star), R(0),
  /* 1471 S> */ B(LdaConstant), U8(130),
                B(Star), R(0),
  /* 1482 S> */ B(LdaConstant), U8(131),
                B(Star), R(0),
  /* 1493 S> */ B(LdaConstant), U8(132),
                B(Star), R(0),
  /* 1504 S> */ B(LdaConstant), U8(133),
                B(Star), R(0),
  /* 1515 S> */ B(LdaConstant), U8(134),
                B(Star), R(0),
  /* 1526 S> */ B(LdaConstant), U8(135),
                B(Star), R(0),
  /* 1537 S> */ B(LdaConstant), U8(136),
                B(Star), R(0),
  /* 1548 S> */ B(LdaConstant), U8(137),
                B(Star), R(0),
  /* 1559 S> */ B(LdaConstant), U8(138),
                B(Star), R(0),
  /* 1570 S> */ B(LdaConstant), U8(139),
                B(Star), R(0),
  /* 1581 S> */ B(LdaConstant), U8(140),
                B(Star), R(0),
  /* 1592 S> */ B(LdaConstant), U8(141),
                B(Star), R(0),
  /* 1603 S> */ B(LdaConstant), U8(142),
                B(Star), R(0),
  /* 1614 S> */ B(LdaConstant), U8(143),
                B(Star), R(0),
  /* 1625 S> */ B(LdaConstant), U8(144),
                B(Star), R(0),
  /* 1636 S> */ B(LdaConstant), U8(145),
                B(Star), R(0),
  /* 1647 S> */ B(LdaConstant), U8(146),
                B(Star), R(0),
  /* 1658 S> */ B(LdaConstant), U8(147),
                B(Star), R(0),
  /* 1669 S> */ B(LdaConstant), U8(148),
                B(Star), R(0),
  /* 1680 S> */ B(LdaConstant), U8(149),
                B(Star), R(0),
  /* 1691 S> */ B(LdaConstant), U8(150),
                B(Star), R(0),
  /* 1702 S> */ B(LdaConstant), U8(151),
                B(Star), R(0),
  /* 1713 S> */ B(LdaConstant), U8(152),
                B(Star), R(0),
  /* 1724 S> */ B(LdaConstant), U8(153),
                B(Star), R(0),
  /* 1735 S> */ B(LdaConstant), U8(154),
                B(Star), R(0),
  /* 1746 S> */ B(LdaConstant), U8(155),
                B(Star), R(0),
  /* 1757 S> */ B(LdaConstant), U8(156),
                B(Star), R(0),
  /* 1768 S> */ B(LdaConstant), U8(157),
                B(Star), R(0),
  /* 1779 S> */ B(LdaConstant), U8(158),
                B(Star), R(0),
  /* 1790 S> */ B(LdaConstant), U8(159),
                B(Star), R(0),
  /* 1801 S> */ B(LdaConstant), U8(160),
                B(Star), R(0),
  /* 1812 S> */ B(LdaConstant), U8(161),
                B(Star), R(0),
  /* 1823 S> */ B(LdaConstant), U8(162),
                B(Star), R(0),
  /* 1834 S> */ B(LdaConstant), U8(163),
                B(Star), R(0),
  /* 1845 S> */ B(LdaConstant), U8(164),
                B(Star), R(0),
  /* 1856 S> */ B(LdaConstant), U8(165),
                B(Star), R(0),
  /* 1867 S> */ B(LdaConstant), U8(166),
                B(Star), R(0),
  /* 1878 S> */ B(LdaConstant), U8(167),
                B(Star), R(0),
  /* 1889 S> */ B(LdaConstant), U8(168),
                B(Star), R(0),
  /* 1900 S> */ B(LdaConstant), U8(169),
                B(Star), R(0),
  /* 1911 S> */ B(LdaConstant), U8(170),
                B(Star), R(0),
  /* 1922 S> */ B(LdaConstant), U8(171),
                B(Star), R(0),
  /* 1933 S> */ B(LdaConstant), U8(172),
                B(Star), R(0),
  /* 1944 S> */ B(LdaConstant), U8(173),
                B(Star), R(0),
  /* 1955 S> */ B(LdaConstant), U8(174),
                B(Star), R(0),
  /* 1966 S> */ B(LdaConstant), U8(175),
                B(Star), R(0),
  /* 1977 S> */ B(LdaConstant), U8(176),
                B(Star), R(0),
  /* 1988 S> */ B(LdaConstant), U8(177),
                B(Star), R(0),
  /* 1999 S> */ B(LdaConstant), U8(178),
                B(Star), R(0),
  /* 2010 S> */ B(LdaConstant), U8(179),
                B(Star), R(0),
  /* 2021 S> */ B(LdaConstant), U8(180),
                B(Star), R(0),
  /* 2032 S> */ B(LdaConstant), U8(181),
                B(Star), R(0),
  /* 2043 S> */ B(LdaConstant), U8(182),
                B(Star), R(0),
  /* 2054 S> */ B(LdaConstant), U8(183),
                B(Star), R(0),
  /* 2065 S> */ B(LdaConstant), U8(184),
                B(Star), R(0),
  /* 2076 S> */ B(LdaConstant), U8(185),
                B(Star), R(0),
  /* 2087 S> */ B(LdaConstant), U8(186),
                B(Star), R(0),
  /* 2098 S> */ B(LdaConstant), U8(187),
                B(Star), R(0),
  /* 2109 S> */ B(LdaConstant), U8(188),
                B(Star), R(0),
  /* 2120 S> */ B(LdaConstant), U8(189),
                B(Star), R(0),
  /* 2131 S> */ B(LdaConstant), U8(190),
                B(Star), R(0),
  /* 2142 S> */ B(LdaConstant), U8(191),
                B(Star), R(0),
  /* 2153 S> */ B(LdaConstant), U8(192),
                B(Star), R(0),
  /* 2164 S> */ B(LdaConstant), U8(193),
                B(Star), R(0),
  /* 2175 S> */ B(LdaConstant), U8(194),
                B(Star), R(0),
  /* 2186 S> */ B(LdaConstant), U8(195),
                B(Star), R(0),
  /* 2197 S> */ B(LdaConstant), U8(196),
                B(Star), R(0),
  /* 2208 S> */ B(LdaConstant), U8(197),
                B(Star), R(0),
  /* 2219 S> */ B(LdaConstant), U8(198),
                B(Star), R(0),
  /* 2230 S> */ B(LdaConstant), U8(199),
                B(Star), R(0),
  /* 2241 S> */ B(LdaConstant), U8(200),
                B(Star), R(0),
  /* 2252 S> */ B(LdaConstant), U8(201),
                B(Star), R(0),
  /* 2263 S> */ B(LdaConstant), U8(202),
                B(Star), R(0),
  /* 2274 S> */ B(LdaConstant), U8(203),
                B(Star), R(0),
  /* 2285 S> */ B(LdaConstant), U8(204),
                B(Star), R(0),
  /* 2296 S> */ B(LdaConstant), U8(205),
                B(Star), R(0),
  /* 2307 S> */ B(LdaConstant), U8(206),
                B(Star), R(0),
  /* 2318 S> */ B(LdaConstant), U8(207),
                B(Star), R(0),
  /* 2329 S> */ B(LdaConstant), U8(208),
                B(Star), R(0),
  /* 2340 S> */ B(LdaConstant), U8(209),
                B(Star), R(0),
  /* 2351 S> */ B(LdaConstant), U8(210),
                B(Star), R(0),
  /* 2362 S> */ B(LdaConstant), U8(211),
                B(Star), R(0),
  /* 2373 S> */ B(LdaConstant), U8(212),
                B(Star), R(0),
  /* 2384 S> */ B(LdaConstant), U8(213),
                B(Star), R(0),
  /* 2395 S> */ B(LdaConstant), U8(214),
                B(Star), R(0),
  /* 2406 S> */ B(LdaConstant), U8(215),
                B(Star), R(0),
  /* 2417 S> */ B(LdaConstant), U8(216),
                B(Star), R(0),
  /* 2428 S> */ B(LdaConstant), U8(217),
                B(Star), R(0),
  /* 2439 S> */ B(LdaConstant), U8(218),
                B(Star), R(0),
  /* 2450 S> */ B(LdaConstant), U8(219),
                B(Star), R(0),
  /* 2461 S> */ B(LdaConstant), U8(220),
                B(Star), R(0),
  /* 2472 S> */ B(LdaConstant), U8(221),
                B(Star), R(0),
  /* 2483 S> */ B(LdaConstant), U8(222),
                B(Star), R(0),
  /* 2494 S> */ B(LdaConstant), U8(223),
                B(Star), R(0),
  /* 2505 S> */ B(LdaConstant), U8(224),
                B(Star), R(0),
  /* 2516 S> */ B(LdaConstant), U8(225),
                B(Star), R(0),
  /* 2527 S> */ B(LdaConstant), U8(226),
                B(Star), R(0),
  /* 2538 S> */ B(LdaConstant), U8(227),
                B(Star), R(0),
  /* 2549 S> */ B(LdaConstant), U8(228),
                B(Star), R(0),
  /* 2560 S> */ B(LdaConstant), U8(229),
                B(Star), R(0),
  /* 2571 S> */ B(LdaConstant), U8(230),
                B(Star), R(0),
  /* 2582 S> */ B(LdaConstant), U8(231),
                B(Star), R(0),
  /* 2593 S> */ B(LdaConstant), U8(232),
                B(Star), R(0),
  /* 2604 S> */ B(LdaConstant), U8(233),
                B(Star), R(0),
  /* 2615 S> */ B(LdaConstant), U8(234),
                B(Star), R(0),
  /* 2626 S> */ B(LdaConstant), U8(235),
                B(Star), R(0),
  /* 2637 S> */ B(LdaConstant), U8(236),
                B(Star), R(0),
  /* 2648 S> */ B(LdaConstant), U8(237),
                B(Star), R(0),
  /* 2659 S> */ B(LdaConstant), U8(238),
                B(Star), R(0),
  /* 2670 S> */ B(LdaConstant), U8(239),
                B(Star), R(0),
  /* 2681 S> */ B(LdaConstant), U8(240),
                B(Star), R(0),
  /* 2692 S> */ B(LdaConstant), U8(241),
                B(Star), R(0),
  /* 2703 S> */ B(LdaConstant), U8(242),
                B(Star), R(0),
  /* 2714 S> */ B(LdaConstant), U8(243),
                B(Star), R(0),
  /* 2725 S> */ B(LdaConstant), U8(244),
                B(Star), R(0),
  /* 2736 S> */ B(LdaConstant), U8(245),
                B(Star), R(0),
  /* 2747 S> */ B(LdaConstant), U8(246),
                B(Star), R(0),
  /* 2758 S> */ B(LdaConstant), U8(247),
                B(Star), R(0),
  /* 2769 S> */ B(LdaConstant), U8(248),
                B(Star), R(0),
  /* 2780 S> */ B(LdaConstant), U8(249),
                B(Star), R(0),
  /* 2791 S> */ B(LdaConstant), U8(250),
                B(Star), R(0),
  /* 2802 S> */ B(LdaConstant), U8(251),
                B(Star), R(0),
  /* 2813 S> */ B(LdaConstant), U8(252),
                B(Star), R(0),
  /* 2824 S> */ B(LdaConstant), U8(253),
                B(Star), R(0),
  /* 2835 S> */ B(LdaConstant), U8(254),
                B(Star), R(0),
  /* 2846 S> */ B(LdaConstant), U8(255),
                B(Star), R(0),
  /* 2857 S> */ B(Wide), B(LdaConstant), U16(256),
                B(Star), R(0),
                B(LdaUndefined),
  /* 2867 S> */ B(Return),
]
constant pool: [
  HEAP_NUMBER_TYPE [1.414],
  HEAP_NUMBER_TYPE [1.414],
  HEAP_NUMBER_TYPE [1.414],
  HEAP_NUMBER_TYPE [1.414],
  HEAP_NUMBER_TYPE [1.414],
  HEAP_NUMBER_TYPE [1.414],
  HEAP_NUMBER_TYPE [1.414],
  HEAP_NUMBER_TYPE [1.414],
  HEAP_NUMBER_TYPE [1.414],
  HEAP_NUMBER_TYPE [1.414],
  HEAP_NUMBER_TYPE [1.414],
  HEAP_NUMBER_TYPE [1.414],
  HEAP_NUMBER_TYPE [1.414],
  HEAP_NUMBER_TYPE [1.414],
  HEAP_NUMBER_TYPE [1.414],
  HEAP_NUMBER_TYPE [1.414],
  HEAP_NUMBER_TYPE [1.414],
  HEAP_NUMBER_TYPE [1.414],
  HEAP_NUMBER_TYPE [1.414],
  HEAP_NUMBER_TYPE [1.414],
  HEAP_NUMBER_TYPE [1.414],
  HEAP_NUMBER_TYPE [1.414],
  HEAP_NUMBER_TYPE [1.414],
  HEAP_NUMBER_TYPE [1.414],
  HEAP_NUMBER_TYPE [1.414],
  HEAP_NUMBER_TYPE [1.414],
  HEAP_NUMBER_TYPE [1.414],
  HEAP_NUMBER_TYPE [1.414],
  HEAP_NUMBER_TYPE [1.414],
  HEAP_NUMBER_TYPE [1.414],
  HEAP_NUMBER_TYPE [1.414],
  HEAP_NUMBER_TYPE [1.414],
  HEAP_NUMBER_TYPE [1.414],
  HEAP_NUMBER_TYPE [1.414],
  HEAP_NUMBER_TYPE [1.414],
  HEAP_NUMBER_TYPE [1.414],
  HEAP_NUMBER_TYPE [1.414],
  HEAP_NUMBER_TYPE [1.414],
  HEAP_NUMBER_TYPE [1.414],
  HEAP_NUMBER_TYPE [1.414],
  HEAP_NUMBER_TYPE [1.414],
  HEAP_NUMBER_TYPE [1.414],
  HEAP_NUMBER_TYPE [1.414],
  HEAP_NUMBER_TYPE [1.414],
  HEAP_NUMBER_TYPE [1.414],
  HEAP_NUMBER_TYPE [1.414],
  HEAP_NUMBER_TYPE [1.414],
  HEAP_NUMBER_TYPE [1.414],
  HEAP_NUMBER_TYPE [1.414],
  HEAP_NUMBER_TYPE [1.414],
  HEAP_NUMBER_TYPE [1.414],
  HEAP_NUMBER_TYPE [1.414],
  HEAP_NUMBER_TYPE [1.414],
  HEAP_NUMBER_TYPE [1.414],
  HEAP_NUMBER_TYPE [1.414],
  HEAP_NUMBER_TYPE [1.414],
  HEAP_NUMBER_TYPE [1.414],
  HEAP_NUMBER_TYPE [1.414],
  HEAP_NUMBER_TYPE [1.414],
  HEAP_NUMBER_TYPE [1.414],
  HEAP_NUMBER_TYPE [1.414],
  HEAP_NUMBER_TYPE [1.414],
  HEAP_NUMBER_TYPE [1.414],
  HEAP_NUMBER_TYPE [1.414],
  HEAP_NUMBER_TYPE [1.414],
  HEAP_NUMBER_TYPE [1.414],
  HEAP_NUMBER_TYPE [1.414],
  HEAP_NUMBER_TYPE [1.414],
  HEAP_NUMBER_TYPE [1.414],
  HEAP_NUMBER_TYPE [1.414],
  HEAP_NUMBER_TYPE [1.414],
  HEAP_NUMBER_TYPE [1.414],
  HEAP_NUMBER_TYPE [1.414],
  HEAP_NUMBER_TYPE [1.414],
  HEAP_NUMBER_TYPE [1.414],
  HEAP_NUMBER_TYPE [1.414],
  HEAP_NUMBER_TYPE [1.414],
  HEAP_NUMBER_TYPE [1.414],
  HEAP_NUMBER_TYPE [1.414],
  HEAP_NUMBER_TYPE [1.414],
  HEAP_NUMBER_TYPE [1.414],
  HEAP_NUMBER_TYPE [1.414],
  HEAP_NUMBER_TYPE [1.414],
  HEAP_NUMBER_TYPE [1.414],
  HEAP_NUMBER_TYPE [1.414],
  HEAP_NUMBER_TYPE [1.414],
  HEAP_NUMBER_TYPE [1.414],
  HEAP_NUMBER_TYPE [1.414],
  HEAP_NUMBER_TYPE [1.414],
  HEAP_NUMBER_TYPE [1.414],
  HEAP_NUMBER_TYPE [1.414],
  HEAP_NUMBER_TYPE [1.414],
  HEAP_NUMBER_TYPE [1.414],
  HEAP_NUMBER_TYPE [1.414],
  HEAP_NUMBER_TYPE [1.414],
  HEAP_NUMBER_TYPE [1.414],
  HEAP_NUMBER_TYPE [1.414],
  HEAP_NUMBER_TYPE [1.414],
  HEAP_NUMBER_TYPE [1.414],
  HEAP_NUMBER_TYPE [1.414],
  HEAP_NUMBER_TYPE [1.414],
  HEAP_NUMBER_TYPE [1.414],
  HEAP_NUMBER_TYPE [1.414],
  HEAP_NUMBER_TYPE [1.414],
  HEAP_NUMBER_TYPE [1.414],
  HEAP_NUMBER_TYPE [1.414],
  HEAP_NUMBER_TYPE [1.414],
  HEAP_NUMBER_TYPE [1.414],
  HEAP_NUMBER_TYPE [1.414],
  HEAP_NUMBER_TYPE [1.414],
  HEAP_NUMBER_TYPE [1.414],
  HEAP_NUMBER_TYPE [1.414],
  HEAP_NUMBER_TYPE [1.414],
  HEAP_NUMBER_TYPE [1.414],
  HEAP_NUMBER_TYPE [1.414],
  HEAP_NUMBER_TYPE [1.414],
  HEAP_NUMBER_TYPE [1.414],
  HEAP_NUMBER_TYPE [1.414],
  HEAP_NUMBER_TYPE [1.414],
  HEAP_NUMBER_TYPE [1.414],
  HEAP_NUMBER_TYPE [1.414],
  HEAP_NUMBER_TYPE [1.414],
  HEAP_NUMBER_TYPE [1.414],
  HEAP_NUMBER_TYPE [1.414],
  HEAP_NUMBER_TYPE [1.414],
  HEAP_NUMBER_TYPE [1.414],
  HEAP_NUMBER_TYPE [1.414],
  HEAP_NUMBER_TYPE [1.414],
  HEAP_NUMBER_TYPE [1.414],
  HEAP_NUMBER_TYPE [1.414],
  HEAP_NUMBER_TYPE [1.414],
  HEAP_NUMBER_TYPE [1.414],
  HEAP_NUMBER_TYPE [1.414],
  HEAP_NUMBER_TYPE [1.414],
  HEAP_NUMBER_TYPE [1.414],
  HEAP_NUMBER_TYPE [1.414],
  HEAP_NUMBER_TYPE [1.414],
  HEAP_NUMBER_TYPE [1.414],
  HEAP_NUMBER_TYPE [1.414],
  HEAP_NUMBER_TYPE [1.414],
  HEAP_NUMBER_TYPE [1.414],
  HEAP_NUMBER_TYPE [1.414],
  HEAP_NUMBER_TYPE [1.414],
  HEAP_NUMBER_TYPE [1.414],
  HEAP_NUMBER_TYPE [1.414],
  HEAP_NUMBER_TYPE [1.414],
  HEAP_NUMBER_TYPE [1.414],
  HEAP_NUMBER_TYPE [1.414],
  HEAP_NUMBER_TYPE [1.414],
  HEAP_NUMBER_TYPE [1.414],
  HEAP_NUMBER_TYPE [1.414],
  HEAP_NUMBER_TYPE [1.414],
  HEAP_NUMBER_TYPE [1.414],
  HEAP_NUMBER_TYPE [1.414],
  HEAP_NUMBER_TYPE [1.414],
  HEAP_NUMBER_TYPE [1.414],
  HEAP_NUMBER_TYPE [1.414],
  HEAP_NUMBER_TYPE [1.414],
  HEAP_NUMBER_TYPE [1.414],
  HEAP_NUMBER_TYPE [1.414],
  HEAP_NUMBER_TYPE [1.414],
  HEAP_NUMBER_TYPE [1.414],
  HEAP_NUMBER_TYPE [1.414],
  HEAP_NUMBER_TYPE [1.414],
  HEAP_NUMBER_TYPE [1.414],
  HEAP_NUMBER_TYPE [1.414],
  HEAP_NUMBER_TYPE [1.414],
  HEAP_NUMBER_TYPE [1.414],
  HEAP_NUMBER_TYPE [1.414],
  HEAP_NUMBER_TYPE [1.414],
  HEAP_NUMBER_TYPE [1.414],
  HEAP_NUMBER_TYPE [1.414],
  HEAP_NUMBER_TYPE [1.414],
  HEAP_NUMBER_TYPE [1.414],
  HEAP_NUMBER_TYPE [1.414],
  HEAP_NUMBER_TYPE [1.414],
  HEAP_NUMBER_TYPE [1.414],
  HEAP_NUMBER_TYPE [1.414],
  HEAP_NUMBER_TYPE [1.414],
  HEAP_NUMBER_TYPE [1.414],
  HEAP_NUMBER_TYPE [1.414],
  HEAP_NUMBER_TYPE [1.414],
  HEAP_NUMBER_TYPE [1.414],
  HEAP_NUMBER_TYPE [1.414],
  HEAP_NUMBER_TYPE [1.414],
  HEAP_NUMBER_TYPE [1.414],
  HEAP_NUMBER_TYPE [1.414],
  HEAP_NUMBER_TYPE [1.414],
  HEAP_NUMBER_TYPE [1.414],
  HEAP_NUMBER_TYPE [1.414],
  HEAP_NUMBER_TYPE [1.414],
  HEAP_NUMBER_TYPE [1.414],
  HEAP_NUMBER_TYPE [1.414],
  HEAP_NUMBER_TYPE [1.414],
  HEAP_NUMBER_TYPE [1.414],
  HEAP_NUMBER_TYPE [1.414],
  HEAP_NUMBER_TYPE [1.414],
  HEAP_NUMBER_TYPE [1.414],
  HEAP_NUMBER_TYPE [1.414],
  HEAP_NUMBER_TYPE [1.414],
  HEAP_NUMBER_TYPE [1.414],
  HEAP_NUMBER_TYPE [1.414],
  HEAP_NUMBER_TYPE [1.414],
  HEAP_NUMBER_TYPE [1.414],
  HEAP_NUMBER_TYPE [1.414],
  HEAP_NUMBER_TYPE [1.414],
  HEAP_NUMBER_TYPE [1.414],
  HEAP_NUMBER_TYPE [1.414],
  HEAP_NUMBER_TYPE [1.414],
  HEAP_NUMBER_TYPE [1.414],
  HEAP_NUMBER_TYPE [1.414],
  HEAP_NUMBER_TYPE [1.414],
  HEAP_NUMBER_TYPE [1.414],
  HEAP_NUMBER_TYPE [1.414],
  HEAP_NUMBER_TYPE [1.414],
  HEAP_NUMBER_TYPE [1.414],
  HEAP_NUMBER_TYPE [1.414],
  HEAP_NUMBER_TYPE [1.414],
  HEAP_NUMBER_TYPE [1.414],
  HEAP_NUMBER_TYPE [1.414],
  HEAP_NUMBER_TYPE [1.414],
  HEAP_NUMBER_TYPE [1.414],
  HEAP_NUMBER_TYPE [1.414],
  HEAP_NUMBER_TYPE [1.414],
  HEAP_NUMBER_TYPE [1.414],
  HEAP_NUMBER_TYPE [1.414],
  HEAP_NUMBER_TYPE [1.414],
  HEAP_NUMBER_TYPE [1.414],
  HEAP_NUMBER_TYPE [1.414],
  HEAP_NUMBER_TYPE [1.414],
  HEAP_NUMBER_TYPE [1.414],
  HEAP_NUMBER_TYPE [1.414],
  HEAP_NUMBER_TYPE [1.414],
  HEAP_NUMBER_TYPE [1.414],
  HEAP_NUMBER_TYPE [1.414],
  HEAP_NUMBER_TYPE [1.414],
  HEAP_NUMBER_TYPE [1.414],
  HEAP_NUMBER_TYPE [1.414],
  HEAP_NUMBER_TYPE [1.414],
  HEAP_NUMBER_TYPE [1.414],
  HEAP_NUMBER_TYPE [1.414],
  HEAP_NUMBER_TYPE [1.414],
  HEAP_NUMBER_TYPE [1.414],
  HEAP_NUMBER_TYPE [1.414],
  HEAP_NUMBER_TYPE [1.414],
  HEAP_NUMBER_TYPE [1.414],
  HEAP_NUMBER_TYPE [1.414],
  HEAP_NUMBER_TYPE [1.414],
  HEAP_NUMBER_TYPE [1.414],
  HEAP_NUMBER_TYPE [1.414],
  HEAP_NUMBER_TYPE [1.414],
  HEAP_NUMBER_TYPE [1.414],
  HEAP_NUMBER_TYPE [1.414],
  HEAP_NUMBER_TYPE [1.414],
  HEAP_NUMBER_TYPE [1.414],
  HEAP_NUMBER_TYPE [1.414],
  HEAP_NUMBER_TYPE [3.14],
]
handlers: [
]

