#
# Autogenerated by generate-bytecode-expectations.
#

---
wrap: no
top level: yes
print callee: yes
oneshot opt: no

---
snippet: "
  
        (function() {
          l = {};
          l.a = 2;
          l.b = l.a;
          return arguments.callee;
        })();
  
"
frame size: 3
parameter count: 1
bytecode array length: 42
bytecodes: [
                B(CreateMappedArguments),
                B(Star), R(0),
  /*   16 E> */ B(StackCheck),
  /*   29 S> */ B(CreateEmptyObjectLiteral),
  /*   31 E> */ B(StaGlobal), U8(0), U8(0),
  /*   45 S> */ B(LdaGlobal), U8(0), U8(2),
                B(Star), R(1),
                B(LdaSmi), I8(2),
  /*   49 E> */ B(StaNamedProperty), R(1), U8(1), U8(4),
  /*   62 S> */ B(LdaGlobal), U8(0), U8(2),
                B(Star), R(1),
  /*   68 E> */ B(LdaGlobal), U8(0), U8(2),
                B(Star), R(2),
  /*   70 E> */ B(LdaNamedProperty), R(2), U8(1), U8(6),
  /*   66 E> */ B(StaNamedProperty), R(1), U8(2), U8(8),
  /*   98 S> */ B(LdaNamedProperty), R(0), U8(3), U8(10),
  /*  105 S> */ B(Return),
]
constant pool: [
  ONE_BYTE_INTERNALIZED_STRING_TYPE ["l"],
  ONE_BYTE_INTERNALIZED_STRING_TYPE ["a"],
  ONE_BYTE_INTERNALIZED_STRING_TYPE ["b"],
  ONE_BYTE_INTERNALIZED_STRING_TYPE ["callee"],
]
handlers: [
]

---
snippet: "
  
        (function() {
          l = {
            'a': 3.3,
            'b': 4.4
          };
          if (l.a < 3) {
            l.a = 3;
          } else {
            l.a = l.b;
          }
          return arguments.callee;
        })();
  
"
frame size: 3
parameter count: 1
bytecode array length: 68
bytecodes: [
                B(CreateMappedArguments),
                B(Star), R(0),
  /*   16 E> */ B(StackCheck),
  /*   29 S> */ B(CreateObjectLiteral), U8(0), U8(0), U8(41), R(1),
                B(Ldar), R(1),
  /*   31 E> */ B(StaGlobal), U8(1), U8(1),
  /*   93 S> */ B(LdaGlobal), U8(1), U8(3),
                B(Star), R(1),
  /*   99 E> */ B(LdaNamedProperty), R(1), U8(2), U8(5),
                B(Star), R(1),
                B(LdaSmi), I8(3),
  /*  101 E> */ B(TestLessThan), R(1), U8(7),
                B(JumpIfFalse), U8(15),
  /*  118 S> */ B(LdaGlobal), U8(1), U8(3),
                B(Star), R(1),
                B(LdaSmi), I8(3),
  /*  122 E> */ B(StaNamedProperty), R(1), U8(2), U8(8),
                B(Jump), U8(20),
  /*  154 S> */ B(LdaGlobal), U8(1), U8(3),
                B(Star), R(1),
  /*  160 E> */ B(LdaGlobal), U8(1), U8(3),
                B(Star), R(2),
  /*  162 E> */ B(LdaNamedProperty), R(2), U8(3), U8(10),
  /*  158 E> */ B(StaNamedProperty), R(1), U8(2), U8(8),
  /*  200 S> */ B(LdaNamedProperty), R(0), U8(4), U8(12),
  /*  207 S> */ B(Return),
]
constant pool: [
  OBJECT_BOILERPLATE_DESCRIPTION_TYPE,
  ONE_BYTE_INTERNALIZED_STRING_TYPE ["l"],
  ONE_BYTE_INTERNALIZED_STRING_TYPE ["a"],
  ONE_BYTE_INTERNALIZED_STRING_TYPE ["b"],
  ONE_BYTE_INTERNALIZED_STRING_TYPE ["callee"],
]
handlers: [
]

