#
# Autogenerated by generate-bytecode-expectations.
#

---
pool type: string
execute: yes
wrap: yes
legacy const: yes

---
snippet: "
  const x = 10;
"
frame size: 2
parameter count: 1
bytecode array length: 19
bytecodes: [
  B(LdaTheHole),
  B(Star), R(0),
  B(StackCheck),
  B(LdaSmi), U8(10),
  B(Star), R(1),
  B(Ldar), R(0),
  B(JumpIfNotHole), U8(5),
  B(Mov), R(1), R(0),
  B(Ldar), R(1),
  B(LdaUndefined),
  B(Return),
]
constant pool: [
]
handlers: [
]

---
snippet: "
  const x = 10; return x;
"
frame size: 2
parameter count: 1
bytecode array length: 23
bytecodes: [
  B(LdaTheHole),
  B(Star), R(0),
  B(StackCheck),
  B(LdaSmi), U8(10),
  B(Star), R(1),
  B(Ldar), R(0),
  B(JumpIfNotHole), U8(5),
  B(Mov), R(1), R(0),
  B(Ldar), R(1),
  B(Ldar), R(0),
  B(JumpIfNotHole), U8(3),
  B(LdaUndefined),
  B(Return),
]
constant pool: [
]
handlers: [
]

---
snippet: "
  const x = ( x = 20);
"
frame size: 2
parameter count: 1
bytecode array length: 23
bytecodes: [
  B(LdaTheHole),
  B(Star), R(0),
  B(StackCheck),
  B(LdaSmi), U8(20),
  B(Star), R(1),
  B(Ldar), R(0),
  B(Ldar), R(1),
  B(Ldar), R(0),
  B(JumpIfNotHole), U8(5),
  B(Mov), R(1), R(0),
  B(Ldar), R(1),
  B(LdaUndefined),
  B(Return),
]
constant pool: [
]
handlers: [
]

---
snippet: "
  const x = 10; x = 20;
"
frame size: 2
parameter count: 1
bytecode array length: 27
bytecodes: [
  B(LdaTheHole),
  B(Star), R(0),
  B(StackCheck),
  B(LdaSmi), U8(10),
  B(Star), R(1),
  B(Ldar), R(0),
  B(JumpIfNotHole), U8(5),
  B(Mov), R(1), R(0),
  B(Ldar), R(1),
  B(LdaSmi), U8(20),
  B(Star), R(1),
  B(Ldar), R(0),
  B(Ldar), R(1),
  B(LdaUndefined),
  B(Return),
]
constant pool: [
]
handlers: [
]

