#
# Autogenerated by generate-bytecode-expectations.
#

---
wrap: yes

---
snippet: "
  let x = 10;
"
frame size: 1
parameter count: 1
bytecode array length: 7
bytecodes: [
  /*   30 E> */ B(StackCheck),
  /*   42 S> */ B(LdaSmi), I8(10),
                B(Star), R(0),
                B(LdaUndefined),
  /*   46 S> */ B(Return),
]
constant pool: [
]
handlers: [
]

---
snippet: "
  let x = 10; return x;
"
frame size: 1
parameter count: 1
bytecode array length: 7
bytecodes: [
  /*   30 E> */ B(StackCheck),
  /*   42 S> */ B(LdaSmi), I8(10),
                B(Star), R(0),
  /*   46 S> */ B(Nop),
  /*   55 S> */ B(Return),
]
constant pool: [
]
handlers: [
]

---
snippet: "
  let x = (x = 20);
"
frame size: 2
parameter count: 1
bytecode array length: 17
bytecodes: [
                B(LdaTheHole),
                B(Star), R(0),
  /*   30 E> */ B(StackCheck),
  /*   42 S> */ B(LdaSmi), I8(20),
                B(Star), R(1),
                B(Ldar), R(0),
  /*   45 E> */ B(ThrowReferenceErrorIfHole), U8(0),
                B(Mov), R(1), R(0),
                B(LdaUndefined),
  /*   52 S> */ B(Return),
]
constant pool: [
  ONE_BYTE_INTERNALIZED_STRING_TYPE ["x"],
]
handlers: [
]

---
snippet: "
  let x = 10; x = 20;
"
frame size: 1
parameter count: 1
bytecode array length: 11
bytecodes: [
  /*   30 E> */ B(StackCheck),
  /*   42 S> */ B(LdaSmi), I8(10),
                B(Star), R(0),
  /*   46 S> */ B(LdaSmi), I8(20),
                B(Star), R(0),
                B(LdaUndefined),
  /*   54 S> */ B(Return),
]
constant pool: [
]
handlers: [
]

