#
# Autogenerated by generate-bytecode-expectations.
#

---
wrap: no
test function name: f

---
snippet: "
  var a = 1;
  function f() { return a; }
  f()
"
frame size: 0
parameter count: 1
bytecode array length: 5
bytecodes: [
  /*   21 E> */ B(StackCheck),
  /*   26 S> */ B(LdaGlobal), U8(0), U8(4),
  /*   35 S> */ B(Return),
]
constant pool: [
  ONE_BYTE_INTERNALIZED_STRING_TYPE ["a"],
]
handlers: [
]

---
snippet: "
  function t() { }
  function f() { return t; }
  f()
"
frame size: 0
parameter count: 1
bytecode array length: 5
bytecodes: [
  /*   27 E> */ B(StackCheck),
  /*   32 S> */ B(LdaGlobal), U8(0), U8(4),
  /*   41 S> */ B(Return),
]
constant pool: [
  ONE_BYTE_INTERNALIZED_STRING_TYPE ["t"],
]
handlers: [
]

---
snippet: "
  a = 1;
  function f() { return a; }
  f()
"
frame size: 0
parameter count: 1
bytecode array length: 5
bytecodes: [
  /*   17 E> */ B(StackCheck),
  /*   22 S> */ B(LdaGlobal), U8(0), U8(4),
  /*   31 S> */ B(Return),
]
constant pool: [
  ONE_BYTE_INTERNALIZED_STRING_TYPE ["a"],
]
handlers: [
]

---
snippet: "
  a = 1;
  function f(b) {
    b.name;
    b.name;
    b.name;
    b.name;
    b.name;
    b.name;
    b.name;
    b.name;
    b.name;
    b.name;
    b.name;
    b.name;
    b.name;
    b.name;
    b.name;
    b.name;
    b.name;
    b.name;
    b.name;
    b.name;
    b.name;
    b.name;
    b.name;
    b.name;
    b.name;
    b.name;
    b.name;
    b.name;
    b.name;
    b.name;
    b.name;
    b.name;
    b.name;
    b.name;
    b.name;
    b.name;
    b.name;
    b.name;
    b.name;
    b.name;
    b.name;
    b.name;
    b.name;
    b.name;
    b.name;
    b.name;
    b.name;
    b.name;
    b.name;
    b.name;
    b.name;
    b.name;
    b.name;
    b.name;
    b.name;
    b.name;
    b.name;
    b.name;
    b.name;
    b.name;
    b.name;
    b.name;
    b.name;
    b.name;
    b.name;
    b.name;
    b.name;
    b.name;
    b.name;
    b.name;
    b.name;
    b.name;
    b.name;
    b.name;
    b.name;
    b.name;
    b.name;
    b.name;
    b.name;
    b.name;
    b.name;
    b.name;
    b.name;
    b.name;
    b.name;
    b.name;
    b.name;
    b.name;
    b.name;
    b.name;
    b.name;
    b.name;
    b.name;
    b.name;
    b.name;
    b.name;
    b.name;
    b.name;
    b.name;
    b.name;
    b.name;
    b.name;
    b.name;
    b.name;
    b.name;
    b.name;
    b.name;
    b.name;
    b.name;
    b.name;
    b.name;
    b.name;
    b.name;
    b.name;
    b.name;
    b.name;
    b.name;
    b.name;
    b.name;
    b.name;
    b.name;
    b.name;
    b.name;
    b.name;
    b.name;
    b.name;
    b.name;
    b.name;
    return a;
  }
  f({name: 1});
"
frame size: 0
parameter count: 2
bytecode array length: 528
bytecodes: [
  /*   17 E> */ B(StackCheck),
  /*   27 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(4),
  /*   37 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(6),
  /*   47 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(8),
  /*   57 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(10),
  /*   67 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(12),
  /*   77 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(14),
  /*   87 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(16),
  /*   97 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(18),
  /*  107 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(20),
  /*  117 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(22),
  /*  127 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(24),
  /*  137 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(26),
  /*  147 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(28),
  /*  157 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(30),
  /*  167 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(32),
  /*  177 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(34),
  /*  187 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(36),
  /*  197 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(38),
  /*  207 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(40),
  /*  217 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(42),
  /*  227 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(44),
  /*  237 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(46),
  /*  247 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(48),
  /*  257 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(50),
  /*  267 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(52),
  /*  277 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(54),
  /*  287 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(56),
  /*  297 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(58),
  /*  307 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(60),
  /*  317 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(62),
  /*  327 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(64),
  /*  337 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(66),
  /*  347 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(68),
  /*  357 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(70),
  /*  367 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(72),
  /*  377 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(74),
  /*  387 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(76),
  /*  397 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(78),
  /*  407 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(80),
  /*  417 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(82),
  /*  427 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(84),
  /*  437 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(86),
  /*  447 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(88),
  /*  457 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(90),
  /*  467 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(92),
  /*  477 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(94),
  /*  487 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(96),
  /*  497 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(98),
  /*  507 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(100),
  /*  517 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(102),
  /*  527 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(104),
  /*  537 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(106),
  /*  547 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(108),
  /*  557 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(110),
  /*  567 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(112),
  /*  577 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(114),
  /*  587 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(116),
  /*  597 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(118),
  /*  607 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(120),
  /*  617 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(122),
  /*  627 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(124),
  /*  637 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(126),
  /*  647 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(128),
  /*  657 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(130),
  /*  667 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(132),
  /*  677 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(134),
  /*  687 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(136),
  /*  697 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(138),
  /*  707 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(140),
  /*  717 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(142),
  /*  727 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(144),
  /*  737 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(146),
  /*  747 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(148),
  /*  757 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(150),
  /*  767 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(152),
  /*  777 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(154),
  /*  787 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(156),
  /*  797 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(158),
  /*  807 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(160),
  /*  817 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(162),
  /*  827 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(164),
  /*  837 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(166),
  /*  847 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(168),
  /*  857 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(170),
  /*  867 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(172),
  /*  877 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(174),
  /*  887 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(176),
  /*  897 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(178),
  /*  907 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(180),
  /*  917 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(182),
  /*  927 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(184),
  /*  937 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(186),
  /*  947 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(188),
  /*  957 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(190),
  /*  967 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(192),
  /*  977 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(194),
  /*  987 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(196),
  /*  997 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(198),
  /* 1007 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(200),
  /* 1017 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(202),
  /* 1027 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(204),
  /* 1037 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(206),
  /* 1047 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(208),
  /* 1057 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(210),
  /* 1067 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(212),
  /* 1077 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(214),
  /* 1087 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(216),
  /* 1097 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(218),
  /* 1107 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(220),
  /* 1117 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(222),
  /* 1127 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(224),
  /* 1137 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(226),
  /* 1147 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(228),
  /* 1157 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(230),
  /* 1167 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(232),
  /* 1177 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(234),
  /* 1187 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(236),
  /* 1197 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(238),
  /* 1207 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(240),
  /* 1217 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(242),
  /* 1227 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(244),
  /* 1237 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(246),
  /* 1247 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(248),
  /* 1257 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(250),
  /* 1267 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(252),
  /* 1277 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(254),
  /* 1287 S> */ B(Wide), B(LdaNamedProperty), R16(arg0), U16(0), U16(256),
  /* 1297 S> */ B(Wide), B(LdaNamedProperty), R16(arg0), U16(0), U16(258),
  /* 1305 S> */ B(Wide), B(LdaGlobal), U16(1), U16(260),
  /* 1314 S> */ B(Return),
]
constant pool: [
  ONE_BYTE_INTERNALIZED_STRING_TYPE ["name"],
  ONE_BYTE_INTERNALIZED_STRING_TYPE ["a"],
]
handlers: [
]

