#
# Autogenerated by generate-bytecode-expectations.
#

---
wrap: no
test function name: f

---
snippet: "
  var f;
  var x = 1;
  function f1() {
    eval(\"function t() {\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"return x;\" +
    \"};\" +
    \"f = t; f();\"
  );
  }
  f1();
"
frame size: 1
parameter count: 1
bytecode array length: 1034
bytecodes: [
  /*   10 E> */ B(StackCheck),
  /*   22 S> */ B(LdaConstant), U8(0),
                B(Star), R(0),
  /*   34 S> */ B(LdaConstant), U8(1),
                B(Star), R(0),
  /*   46 S> */ B(LdaConstant), U8(2),
                B(Star), R(0),
  /*   58 S> */ B(LdaConstant), U8(3),
                B(Star), R(0),
  /*   70 S> */ B(LdaConstant), U8(4),
                B(Star), R(0),
  /*   82 S> */ B(LdaConstant), U8(5),
                B(Star), R(0),
  /*   94 S> */ B(LdaConstant), U8(6),
                B(Star), R(0),
  /*  106 S> */ B(LdaConstant), U8(7),
                B(Star), R(0),
  /*  118 S> */ B(LdaConstant), U8(8),
                B(Star), R(0),
  /*  130 S> */ B(LdaConstant), U8(9),
                B(Star), R(0),
  /*  142 S> */ B(LdaConstant), U8(10),
                B(Star), R(0),
  /*  154 S> */ B(LdaConstant), U8(11),
                B(Star), R(0),
  /*  166 S> */ B(LdaConstant), U8(12),
                B(Star), R(0),
  /*  178 S> */ B(LdaConstant), U8(13),
                B(Star), R(0),
  /*  190 S> */ B(LdaConstant), U8(14),
                B(Star), R(0),
  /*  202 S> */ B(LdaConstant), U8(15),
                B(Star), R(0),
  /*  214 S> */ B(LdaConstant), U8(16),
                B(Star), R(0),
  /*  226 S> */ B(LdaConstant), U8(17),
                B(Star), R(0),
  /*  238 S> */ B(LdaConstant), U8(18),
                B(Star), R(0),
  /*  250 S> */ B(LdaConstant), U8(19),
                B(Star), R(0),
  /*  262 S> */ B(LdaConstant), U8(20),
                B(Star), R(0),
  /*  274 S> */ B(LdaConstant), U8(21),
                B(Star), R(0),
  /*  286 S> */ B(LdaConstant), U8(22),
                B(Star), R(0),
  /*  298 S> */ B(LdaConstant), U8(23),
                B(Star), R(0),
  /*  310 S> */ B(LdaConstant), U8(24),
                B(Star), R(0),
  /*  322 S> */ B(LdaConstant), U8(25),
                B(Star), R(0),
  /*  334 S> */ B(LdaConstant), U8(26),
                B(Star), R(0),
  /*  346 S> */ B(LdaConstant), U8(27),
                B(Star), R(0),
  /*  358 S> */ B(LdaConstant), U8(28),
                B(Star), R(0),
  /*  370 S> */ B(LdaConstant), U8(29),
                B(Star), R(0),
  /*  382 S> */ B(LdaConstant), U8(30),
                B(Star), R(0),
  /*  394 S> */ B(LdaConstant), U8(31),
                B(Star), R(0),
  /*  406 S> */ B(LdaConstant), U8(32),
                B(Star), R(0),
  /*  418 S> */ B(LdaConstant), U8(33),
                B(Star), R(0),
  /*  430 S> */ B(LdaConstant), U8(34),
                B(Star), R(0),
  /*  442 S> */ B(LdaConstant), U8(35),
                B(Star), R(0),
  /*  454 S> */ B(LdaConstant), U8(36),
                B(Star), R(0),
  /*  466 S> */ B(LdaConstant), U8(37),
                B(Star), R(0),
  /*  478 S> */ B(LdaConstant), U8(38),
                B(Star), R(0),
  /*  490 S> */ B(LdaConstant), U8(39),
                B(Star), R(0),
  /*  502 S> */ B(LdaConstant), U8(40),
                B(Star), R(0),
  /*  514 S> */ B(LdaConstant), U8(41),
                B(Star), R(0),
  /*  526 S> */ B(LdaConstant), U8(42),
                B(Star), R(0),
  /*  538 S> */ B(LdaConstant), U8(43),
                B(Star), R(0),
  /*  550 S> */ B(LdaConstant), U8(44),
                B(Star), R(0),
  /*  562 S> */ B(LdaConstant), U8(45),
                B(Star), R(0),
  /*  574 S> */ B(LdaConstant), U8(46),
                B(Star), R(0),
  /*  586 S> */ B(LdaConstant), U8(47),
                B(Star), R(0),
  /*  598 S> */ B(LdaConstant), U8(48),
                B(Star), R(0),
  /*  610 S> */ B(LdaConstant), U8(49),
                B(Star), R(0),
  /*  622 S> */ B(LdaConstant), U8(50),
                B(Star), R(0),
  /*  634 S> */ B(LdaConstant), U8(51),
                B(Star), R(0),
  /*  646 S> */ B(LdaConstant), U8(52),
                B(Star), R(0),
  /*  658 S> */ B(LdaConstant), U8(53),
                B(Star), R(0),
  /*  670 S> */ B(LdaConstant), U8(54),
                B(Star), R(0),
  /*  682 S> */ B(LdaConstant), U8(55),
                B(Star), R(0),
  /*  694 S> */ B(LdaConstant), U8(56),
                B(Star), R(0),
  /*  706 S> */ B(LdaConstant), U8(57),
                B(Star), R(0),
  /*  718 S> */ B(LdaConstant), U8(58),
                B(Star), R(0),
  /*  730 S> */ B(LdaConstant), U8(59),
                B(Star), R(0),
  /*  742 S> */ B(LdaConstant), U8(60),
                B(Star), R(0),
  /*  754 S> */ B(LdaConstant), U8(61),
                B(Star), R(0),
  /*  766 S> */ B(LdaConstant), U8(62),
                B(Star), R(0),
  /*  778 S> */ B(LdaConstant), U8(63),
                B(Star), R(0),
  /*  790 S> */ B(LdaConstant), U8(64),
                B(Star), R(0),
  /*  802 S> */ B(LdaConstant), U8(65),
                B(Star), R(0),
  /*  814 S> */ B(LdaConstant), U8(66),
                B(Star), R(0),
  /*  826 S> */ B(LdaConstant), U8(67),
                B(Star), R(0),
  /*  838 S> */ B(LdaConstant), U8(68),
                B(Star), R(0),
  /*  850 S> */ B(LdaConstant), U8(69),
                B(Star), R(0),
  /*  862 S> */ B(LdaConstant), U8(70),
                B(Star), R(0),
  /*  874 S> */ B(LdaConstant), U8(71),
                B(Star), R(0),
  /*  886 S> */ B(LdaConstant), U8(72),
                B(Star), R(0),
  /*  898 S> */ B(LdaConstant), U8(73),
                B(Star), R(0),
  /*  910 S> */ B(LdaConstant), U8(74),
                B(Star), R(0),
  /*  922 S> */ B(LdaConstant), U8(75),
                B(Star), R(0),
  /*  934 S> */ B(LdaConstant), U8(76),
                B(Star), R(0),
  /*  946 S> */ B(LdaConstant), U8(77),
                B(Star), R(0),
  /*  958 S> */ B(LdaConstant), U8(78),
                B(Star), R(0),
  /*  970 S> */ B(LdaConstant), U8(79),
                B(Star), R(0),
  /*  982 S> */ B(LdaConstant), U8(80),
                B(Star), R(0),
  /*  994 S> */ B(LdaConstant), U8(81),
                B(Star), R(0),
  /* 1006 S> */ B(LdaConstant), U8(82),
                B(Star), R(0),
  /* 1018 S> */ B(LdaConstant), U8(83),
                B(Star), R(0),
  /* 1030 S> */ B(LdaConstant), U8(84),
                B(Star), R(0),
  /* 1042 S> */ B(LdaConstant), U8(85),
                B(Star), R(0),
  /* 1054 S> */ B(LdaConstant), U8(86),
                B(Star), R(0),
  /* 1066 S> */ B(LdaConstant), U8(87),
                B(Star), R(0),
  /* 1078 S> */ B(LdaConstant), U8(88),
                B(Star), R(0),
  /* 1090 S> */ B(LdaConstant), U8(89),
                B(Star), R(0),
  /* 1102 S> */ B(LdaConstant), U8(90),
                B(Star), R(0),
  /* 1114 S> */ B(LdaConstant), U8(91),
                B(Star), R(0),
  /* 1126 S> */ B(LdaConstant), U8(92),
                B(Star), R(0),
  /* 1138 S> */ B(LdaConstant), U8(93),
                B(Star), R(0),
  /* 1150 S> */ B(LdaConstant), U8(94),
                B(Star), R(0),
  /* 1162 S> */ B(LdaConstant), U8(95),
                B(Star), R(0),
  /* 1174 S> */ B(LdaConstant), U8(96),
                B(Star), R(0),
  /* 1186 S> */ B(LdaConstant), U8(97),
                B(Star), R(0),
  /* 1198 S> */ B(LdaConstant), U8(98),
                B(Star), R(0),
  /* 1210 S> */ B(LdaConstant), U8(99),
                B(Star), R(0),
  /* 1222 S> */ B(LdaConstant), U8(100),
                B(Star), R(0),
  /* 1234 S> */ B(LdaConstant), U8(101),
                B(Star), R(0),
  /* 1246 S> */ B(LdaConstant), U8(102),
                B(Star), R(0),
  /* 1258 S> */ B(LdaConstant), U8(103),
                B(Star), R(0),
  /* 1270 S> */ B(LdaConstant), U8(104),
                B(Star), R(0),
  /* 1282 S> */ B(LdaConstant), U8(105),
                B(Star), R(0),
  /* 1294 S> */ B(LdaConstant), U8(106),
                B(Star), R(0),
  /* 1306 S> */ B(LdaConstant), U8(107),
                B(Star), R(0),
  /* 1318 S> */ B(LdaConstant), U8(108),
                B(Star), R(0),
  /* 1330 S> */ B(LdaConstant), U8(109),
                B(Star), R(0),
  /* 1342 S> */ B(LdaConstant), U8(110),
                B(Star), R(0),
  /* 1354 S> */ B(LdaConstant), U8(111),
                B(Star), R(0),
  /* 1366 S> */ B(LdaConstant), U8(112),
                B(Star), R(0),
  /* 1378 S> */ B(LdaConstant), U8(113),
                B(Star), R(0),
  /* 1390 S> */ B(LdaConstant), U8(114),
                B(Star), R(0),
  /* 1402 S> */ B(LdaConstant), U8(115),
                B(Star), R(0),
  /* 1414 S> */ B(LdaConstant), U8(116),
                B(Star), R(0),
  /* 1426 S> */ B(LdaConstant), U8(117),
                B(Star), R(0),
  /* 1438 S> */ B(LdaConstant), U8(118),
                B(Star), R(0),
  /* 1450 S> */ B(LdaConstant), U8(119),
                B(Star), R(0),
  /* 1462 S> */ B(LdaConstant), U8(120),
                B(Star), R(0),
  /* 1474 S> */ B(LdaConstant), U8(121),
                B(Star), R(0),
  /* 1486 S> */ B(LdaConstant), U8(122),
                B(Star), R(0),
  /* 1498 S> */ B(LdaConstant), U8(123),
                B(Star), R(0),
  /* 1510 S> */ B(LdaConstant), U8(124),
                B(Star), R(0),
  /* 1522 S> */ B(LdaConstant), U8(125),
                B(Star), R(0),
  /* 1534 S> */ B(LdaConstant), U8(126),
                B(Star), R(0),
  /* 1546 S> */ B(LdaConstant), U8(127),
                B(Star), R(0),
  /* 1558 S> */ B(LdaConstant), U8(128),
                B(Star), R(0),
  /* 1570 S> */ B(LdaConstant), U8(129),
                B(Star), R(0),
  /* 1582 S> */ B(LdaConstant), U8(130),
                B(Star), R(0),
  /* 1594 S> */ B(LdaConstant), U8(131),
                B(Star), R(0),
  /* 1606 S> */ B(LdaConstant), U8(132),
                B(Star), R(0),
  /* 1618 S> */ B(LdaConstant), U8(133),
                B(Star), R(0),
  /* 1630 S> */ B(LdaConstant), U8(134),
                B(Star), R(0),
  /* 1642 S> */ B(LdaConstant), U8(135),
                B(Star), R(0),
  /* 1654 S> */ B(LdaConstant), U8(136),
                B(Star), R(0),
  /* 1666 S> */ B(LdaConstant), U8(137),
                B(Star), R(0),
  /* 1678 S> */ B(LdaConstant), U8(138),
                B(Star), R(0),
  /* 1690 S> */ B(LdaConstant), U8(139),
                B(Star), R(0),
  /* 1702 S> */ B(LdaConstant), U8(140),
                B(Star), R(0),
  /* 1714 S> */ B(LdaConstant), U8(141),
                B(Star), R(0),
  /* 1726 S> */ B(LdaConstant), U8(142),
                B(Star), R(0),
  /* 1738 S> */ B(LdaConstant), U8(143),
                B(Star), R(0),
  /* 1750 S> */ B(LdaConstant), U8(144),
                B(Star), R(0),
  /* 1762 S> */ B(LdaConstant), U8(145),
                B(Star), R(0),
  /* 1774 S> */ B(LdaConstant), U8(146),
                B(Star), R(0),
  /* 1786 S> */ B(LdaConstant), U8(147),
                B(Star), R(0),
  /* 1798 S> */ B(LdaConstant), U8(148),
                B(Star), R(0),
  /* 1810 S> */ B(LdaConstant), U8(149),
                B(Star), R(0),
  /* 1822 S> */ B(LdaConstant), U8(150),
                B(Star), R(0),
  /* 1834 S> */ B(LdaConstant), U8(151),
                B(Star), R(0),
  /* 1846 S> */ B(LdaConstant), U8(152),
                B(Star), R(0),
  /* 1858 S> */ B(LdaConstant), U8(153),
                B(Star), R(0),
  /* 1870 S> */ B(LdaConstant), U8(154),
                B(Star), R(0),
  /* 1882 S> */ B(LdaConstant), U8(155),
                B(Star), R(0),
  /* 1894 S> */ B(LdaConstant), U8(156),
                B(Star), R(0),
  /* 1906 S> */ B(LdaConstant), U8(157),
                B(Star), R(0),
  /* 1918 S> */ B(LdaConstant), U8(158),
                B(Star), R(0),
  /* 1930 S> */ B(LdaConstant), U8(159),
                B(Star), R(0),
  /* 1942 S> */ B(LdaConstant), U8(160),
                B(Star), R(0),
  /* 1954 S> */ B(LdaConstant), U8(161),
                B(Star), R(0),
  /* 1966 S> */ B(LdaConstant), U8(162),
                B(Star), R(0),
  /* 1978 S> */ B(LdaConstant), U8(163),
                B(Star), R(0),
  /* 1990 S> */ B(LdaConstant), U8(164),
                B(Star), R(0),
  /* 2002 S> */ B(LdaConstant), U8(165),
                B(Star), R(0),
  /* 2014 S> */ B(LdaConstant), U8(166),
                B(Star), R(0),
  /* 2026 S> */ B(LdaConstant), U8(167),
                B(Star), R(0),
  /* 2038 S> */ B(LdaConstant), U8(168),
                B(Star), R(0),
  /* 2050 S> */ B(LdaConstant), U8(169),
                B(Star), R(0),
  /* 2062 S> */ B(LdaConstant), U8(170),
                B(Star), R(0),
  /* 2074 S> */ B(LdaConstant), U8(171),
                B(Star), R(0),
  /* 2086 S> */ B(LdaConstant), U8(172),
                B(Star), R(0),
  /* 2098 S> */ B(LdaConstant), U8(173),
                B(Star), R(0),
  /* 2110 S> */ B(LdaConstant), U8(174),
                B(Star), R(0),
  /* 2122 S> */ B(LdaConstant), U8(175),
                B(Star), R(0),
  /* 2134 S> */ B(LdaConstant), U8(176),
                B(Star), R(0),
  /* 2146 S> */ B(LdaConstant), U8(177),
                B(Star), R(0),
  /* 2158 S> */ B(LdaConstant), U8(178),
                B(Star), R(0),
  /* 2170 S> */ B(LdaConstant), U8(179),
                B(Star), R(0),
  /* 2182 S> */ B(LdaConstant), U8(180),
                B(Star), R(0),
  /* 2194 S> */ B(LdaConstant), U8(181),
                B(Star), R(0),
  /* 2206 S> */ B(LdaConstant), U8(182),
                B(Star), R(0),
  /* 2218 S> */ B(LdaConstant), U8(183),
                B(Star), R(0),
  /* 2230 S> */ B(LdaConstant), U8(184),
                B(Star), R(0),
  /* 2242 S> */ B(LdaConstant), U8(185),
                B(Star), R(0),
  /* 2254 S> */ B(LdaConstant), U8(186),
                B(Star), R(0),
  /* 2266 S> */ B(LdaConstant), U8(187),
                B(Star), R(0),
  /* 2278 S> */ B(LdaConstant), U8(188),
                B(Star), R(0),
  /* 2290 S> */ B(LdaConstant), U8(189),
                B(Star), R(0),
  /* 2302 S> */ B(LdaConstant), U8(190),
                B(Star), R(0),
  /* 2314 S> */ B(LdaConstant), U8(191),
                B(Star), R(0),
  /* 2326 S> */ B(LdaConstant), U8(192),
                B(Star), R(0),
  /* 2338 S> */ B(LdaConstant), U8(193),
                B(Star), R(0),
  /* 2350 S> */ B(LdaConstant), U8(194),
                B(Star), R(0),
  /* 2362 S> */ B(LdaConstant), U8(195),
                B(Star), R(0),
  /* 2374 S> */ B(LdaConstant), U8(196),
                B(Star), R(0),
  /* 2386 S> */ B(LdaConstant), U8(197),
                B(Star), R(0),
  /* 2398 S> */ B(LdaConstant), U8(198),
                B(Star), R(0),
  /* 2410 S> */ B(LdaConstant), U8(199),
                B(Star), R(0),
  /* 2422 S> */ B(LdaConstant), U8(200),
                B(Star), R(0),
  /* 2434 S> */ B(LdaConstant), U8(201),
                B(Star), R(0),
  /* 2446 S> */ B(LdaConstant), U8(202),
                B(Star), R(0),
  /* 2458 S> */ B(LdaConstant), U8(203),
                B(Star), R(0),
  /* 2470 S> */ B(LdaConstant), U8(204),
                B(Star), R(0),
  /* 2482 S> */ B(LdaConstant), U8(205),
                B(Star), R(0),
  /* 2494 S> */ B(LdaConstant), U8(206),
                B(Star), R(0),
  /* 2506 S> */ B(LdaConstant), U8(207),
                B(Star), R(0),
  /* 2518 S> */ B(LdaConstant), U8(208),
                B(Star), R(0),
  /* 2530 S> */ B(LdaConstant), U8(209),
                B(Star), R(0),
  /* 2542 S> */ B(LdaConstant), U8(210),
                B(Star), R(0),
  /* 2554 S> */ B(LdaConstant), U8(211),
                B(Star), R(0),
  /* 2566 S> */ B(LdaConstant), U8(212),
                B(Star), R(0),
  /* 2578 S> */ B(LdaConstant), U8(213),
                B(Star), R(0),
  /* 2590 S> */ B(LdaConstant), U8(214),
                B(Star), R(0),
  /* 2602 S> */ B(LdaConstant), U8(215),
                B(Star), R(0),
  /* 2614 S> */ B(LdaConstant), U8(216),
                B(Star), R(0),
  /* 2626 S> */ B(LdaConstant), U8(217),
                B(Star), R(0),
  /* 2638 S> */ B(LdaConstant), U8(218),
                B(Star), R(0),
  /* 2650 S> */ B(LdaConstant), U8(219),
                B(Star), R(0),
  /* 2662 S> */ B(LdaConstant), U8(220),
                B(Star), R(0),
  /* 2674 S> */ B(LdaConstant), U8(221),
                B(Star), R(0),
  /* 2686 S> */ B(LdaConstant), U8(222),
                B(Star), R(0),
  /* 2698 S> */ B(LdaConstant), U8(223),
                B(Star), R(0),
  /* 2710 S> */ B(LdaConstant), U8(224),
                B(Star), R(0),
  /* 2722 S> */ B(LdaConstant), U8(225),
                B(Star), R(0),
  /* 2734 S> */ B(LdaConstant), U8(226),
                B(Star), R(0),
  /* 2746 S> */ B(LdaConstant), U8(227),
                B(Star), R(0),
  /* 2758 S> */ B(LdaConstant), U8(228),
                B(Star), R(0),
  /* 2770 S> */ B(LdaConstant), U8(229),
                B(Star), R(0),
  /* 2782 S> */ B(LdaConstant), U8(230),
                B(Star), R(0),
  /* 2794 S> */ B(LdaConstant), U8(231),
                B(Star), R(0),
  /* 2806 S> */ B(LdaConstant), U8(232),
                B(Star), R(0),
  /* 2818 S> */ B(LdaConstant), U8(233),
                B(Star), R(0),
  /* 2830 S> */ B(LdaConstant), U8(234),
                B(Star), R(0),
  /* 2842 S> */ B(LdaConstant), U8(235),
                B(Star), R(0),
  /* 2854 S> */ B(LdaConstant), U8(236),
                B(Star), R(0),
  /* 2866 S> */ B(LdaConstant), U8(237),
                B(Star), R(0),
  /* 2878 S> */ B(LdaConstant), U8(238),
                B(Star), R(0),
  /* 2890 S> */ B(LdaConstant), U8(239),
                B(Star), R(0),
  /* 2902 S> */ B(LdaConstant), U8(240),
                B(Star), R(0),
  /* 2914 S> */ B(LdaConstant), U8(241),
                B(Star), R(0),
  /* 2926 S> */ B(LdaConstant), U8(242),
                B(Star), R(0),
  /* 2938 S> */ B(LdaConstant), U8(243),
                B(Star), R(0),
  /* 2950 S> */ B(LdaConstant), U8(244),
                B(Star), R(0),
  /* 2962 S> */ B(LdaConstant), U8(245),
                B(Star), R(0),
  /* 2974 S> */ B(LdaConstant), U8(246),
                B(Star), R(0),
  /* 2986 S> */ B(LdaConstant), U8(247),
                B(Star), R(0),
  /* 2998 S> */ B(LdaConstant), U8(248),
                B(Star), R(0),
  /* 3010 S> */ B(LdaConstant), U8(249),
                B(Star), R(0),
  /* 3022 S> */ B(LdaConstant), U8(250),
                B(Star), R(0),
  /* 3034 S> */ B(LdaConstant), U8(251),
                B(Star), R(0),
  /* 3046 S> */ B(LdaConstant), U8(252),
                B(Star), R(0),
  /* 3058 S> */ B(LdaConstant), U8(253),
                B(Star), R(0),
  /* 3070 S> */ B(LdaConstant), U8(254),
                B(Star), R(0),
  /* 3082 S> */ B(LdaConstant), U8(255),
                B(Star), R(0),
  /* 3086 S> */ B(Wide), B(LdaLookupGlobalSlot), U16(256), U16(4), U16(1),
  /* 3095 S> */ B(Return),
]
constant pool: [
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  ONE_BYTE_INTERNALIZED_STRING_TYPE ["x"],
]
handlers: [
]

---
snippet: "
  var f;
  var x = 1;
  function f1() {
    eval(\"function t() {\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"return typeof x;\" +
    \"};\" +
    \"f = t; f();\"
  );
  }
  f1();
"
frame size: 1
parameter count: 1
bytecode array length: 1035
bytecodes: [
  /*   10 E> */ B(StackCheck),
  /*   22 S> */ B(LdaConstant), U8(0),
                B(Star), R(0),
  /*   34 S> */ B(LdaConstant), U8(1),
                B(Star), R(0),
  /*   46 S> */ B(LdaConstant), U8(2),
                B(Star), R(0),
  /*   58 S> */ B(LdaConstant), U8(3),
                B(Star), R(0),
  /*   70 S> */ B(LdaConstant), U8(4),
                B(Star), R(0),
  /*   82 S> */ B(LdaConstant), U8(5),
                B(Star), R(0),
  /*   94 S> */ B(LdaConstant), U8(6),
                B(Star), R(0),
  /*  106 S> */ B(LdaConstant), U8(7),
                B(Star), R(0),
  /*  118 S> */ B(LdaConstant), U8(8),
                B(Star), R(0),
  /*  130 S> */ B(LdaConstant), U8(9),
                B(Star), R(0),
  /*  142 S> */ B(LdaConstant), U8(10),
                B(Star), R(0),
  /*  154 S> */ B(LdaConstant), U8(11),
                B(Star), R(0),
  /*  166 S> */ B(LdaConstant), U8(12),
                B(Star), R(0),
  /*  178 S> */ B(LdaConstant), U8(13),
                B(Star), R(0),
  /*  190 S> */ B(LdaConstant), U8(14),
                B(Star), R(0),
  /*  202 S> */ B(LdaConstant), U8(15),
                B(Star), R(0),
  /*  214 S> */ B(LdaConstant), U8(16),
                B(Star), R(0),
  /*  226 S> */ B(LdaConstant), U8(17),
                B(Star), R(0),
  /*  238 S> */ B(LdaConstant), U8(18),
                B(Star), R(0),
  /*  250 S> */ B(LdaConstant), U8(19),
                B(Star), R(0),
  /*  262 S> */ B(LdaConstant), U8(20),
                B(Star), R(0),
  /*  274 S> */ B(LdaConstant), U8(21),
                B(Star), R(0),
  /*  286 S> */ B(LdaConstant), U8(22),
                B(Star), R(0),
  /*  298 S> */ B(LdaConstant), U8(23),
                B(Star), R(0),
  /*  310 S> */ B(LdaConstant), U8(24),
                B(Star), R(0),
  /*  322 S> */ B(LdaConstant), U8(25),
                B(Star), R(0),
  /*  334 S> */ B(LdaConstant), U8(26),
                B(Star), R(0),
  /*  346 S> */ B(LdaConstant), U8(27),
                B(Star), R(0),
  /*  358 S> */ B(LdaConstant), U8(28),
                B(Star), R(0),
  /*  370 S> */ B(LdaConstant), U8(29),
                B(Star), R(0),
  /*  382 S> */ B(LdaConstant), U8(30),
                B(Star), R(0),
  /*  394 S> */ B(LdaConstant), U8(31),
                B(Star), R(0),
  /*  406 S> */ B(LdaConstant), U8(32),
                B(Star), R(0),
  /*  418 S> */ B(LdaConstant), U8(33),
                B(Star), R(0),
  /*  430 S> */ B(LdaConstant), U8(34),
                B(Star), R(0),
  /*  442 S> */ B(LdaConstant), U8(35),
                B(Star), R(0),
  /*  454 S> */ B(LdaConstant), U8(36),
                B(Star), R(0),
  /*  466 S> */ B(LdaConstant), U8(37),
                B(Star), R(0),
  /*  478 S> */ B(LdaConstant), U8(38),
                B(Star), R(0),
  /*  490 S> */ B(LdaConstant), U8(39),
                B(Star), R(0),
  /*  502 S> */ B(LdaConstant), U8(40),
                B(Star), R(0),
  /*  514 S> */ B(LdaConstant), U8(41),
                B(Star), R(0),
  /*  526 S> */ B(LdaConstant), U8(42),
                B(Star), R(0),
  /*  538 S> */ B(LdaConstant), U8(43),
                B(Star), R(0),
  /*  550 S> */ B(LdaConstant), U8(44),
                B(Star), R(0),
  /*  562 S> */ B(LdaConstant), U8(45),
                B(Star), R(0),
  /*  574 S> */ B(LdaConstant), U8(46),
                B(Star), R(0),
  /*  586 S> */ B(LdaConstant), U8(47),
                B(Star), R(0),
  /*  598 S> */ B(LdaConstant), U8(48),
                B(Star), R(0),
  /*  610 S> */ B(LdaConstant), U8(49),
                B(Star), R(0),
  /*  622 S> */ B(LdaConstant), U8(50),
                B(Star), R(0),
  /*  634 S> */ B(LdaConstant), U8(51),
                B(Star), R(0),
  /*  646 S> */ B(LdaConstant), U8(52),
                B(Star), R(0),
  /*  658 S> */ B(LdaConstant), U8(53),
                B(Star), R(0),
  /*  670 S> */ B(LdaConstant), U8(54),
                B(Star), R(0),
  /*  682 S> */ B(LdaConstant), U8(55),
                B(Star), R(0),
  /*  694 S> */ B(LdaConstant), U8(56),
                B(Star), R(0),
  /*  706 S> */ B(LdaConstant), U8(57),
                B(Star), R(0),
  /*  718 S> */ B(LdaConstant), U8(58),
                B(Star), R(0),
  /*  730 S> */ B(LdaConstant), U8(59),
                B(Star), R(0),
  /*  742 S> */ B(LdaConstant), U8(60),
                B(Star), R(0),
  /*  754 S> */ B(LdaConstant), U8(61),
                B(Star), R(0),
  /*  766 S> */ B(LdaConstant), U8(62),
                B(Star), R(0),
  /*  778 S> */ B(LdaConstant), U8(63),
                B(Star), R(0),
  /*  790 S> */ B(LdaConstant), U8(64),
                B(Star), R(0),
  /*  802 S> */ B(LdaConstant), U8(65),
                B(Star), R(0),
  /*  814 S> */ B(LdaConstant), U8(66),
                B(Star), R(0),
  /*  826 S> */ B(LdaConstant), U8(67),
                B(Star), R(0),
  /*  838 S> */ B(LdaConstant), U8(68),
                B(Star), R(0),
  /*  850 S> */ B(LdaConstant), U8(69),
                B(Star), R(0),
  /*  862 S> */ B(LdaConstant), U8(70),
                B(Star), R(0),
  /*  874 S> */ B(LdaConstant), U8(71),
                B(Star), R(0),
  /*  886 S> */ B(LdaConstant), U8(72),
                B(Star), R(0),
  /*  898 S> */ B(LdaConstant), U8(73),
                B(Star), R(0),
  /*  910 S> */ B(LdaConstant), U8(74),
                B(Star), R(0),
  /*  922 S> */ B(LdaConstant), U8(75),
                B(Star), R(0),
  /*  934 S> */ B(LdaConstant), U8(76),
                B(Star), R(0),
  /*  946 S> */ B(LdaConstant), U8(77),
                B(Star), R(0),
  /*  958 S> */ B(LdaConstant), U8(78),
                B(Star), R(0),
  /*  970 S> */ B(LdaConstant), U8(79),
                B(Star), R(0),
  /*  982 S> */ B(LdaConstant), U8(80),
                B(Star), R(0),
  /*  994 S> */ B(LdaConstant), U8(81),
                B(Star), R(0),
  /* 1006 S> */ B(LdaConstant), U8(82),
                B(Star), R(0),
  /* 1018 S> */ B(LdaConstant), U8(83),
                B(Star), R(0),
  /* 1030 S> */ B(LdaConstant), U8(84),
                B(Star), R(0),
  /* 1042 S> */ B(LdaConstant), U8(85),
                B(Star), R(0),
  /* 1054 S> */ B(LdaConstant), U8(86),
                B(Star), R(0),
  /* 1066 S> */ B(LdaConstant), U8(87),
                B(Star), R(0),
  /* 1078 S> */ B(LdaConstant), U8(88),
                B(Star), R(0),
  /* 1090 S> */ B(LdaConstant), U8(89),
                B(Star), R(0),
  /* 1102 S> */ B(LdaConstant), U8(90),
                B(Star), R(0),
  /* 1114 S> */ B(LdaConstant), U8(91),
                B(Star), R(0),
  /* 1126 S> */ B(LdaConstant), U8(92),
                B(Star), R(0),
  /* 1138 S> */ B(LdaConstant), U8(93),
                B(Star), R(0),
  /* 1150 S> */ B(LdaConstant), U8(94),
                B(Star), R(0),
  /* 1162 S> */ B(LdaConstant), U8(95),
                B(Star), R(0),
  /* 1174 S> */ B(LdaConstant), U8(96),
                B(Star), R(0),
  /* 1186 S> */ B(LdaConstant), U8(97),
                B(Star), R(0),
  /* 1198 S> */ B(LdaConstant), U8(98),
                B(Star), R(0),
  /* 1210 S> */ B(LdaConstant), U8(99),
                B(Star), R(0),
  /* 1222 S> */ B(LdaConstant), U8(100),
                B(Star), R(0),
  /* 1234 S> */ B(LdaConstant), U8(101),
                B(Star), R(0),
  /* 1246 S> */ B(LdaConstant), U8(102),
                B(Star), R(0),
  /* 1258 S> */ B(LdaConstant), U8(103),
                B(Star), R(0),
  /* 1270 S> */ B(LdaConstant), U8(104),
                B(Star), R(0),
  /* 1282 S> */ B(LdaConstant), U8(105),
                B(Star), R(0),
  /* 1294 S> */ B(LdaConstant), U8(106),
                B(Star), R(0),
  /* 1306 S> */ B(LdaConstant), U8(107),
                B(Star), R(0),
  /* 1318 S> */ B(LdaConstant), U8(108),
                B(Star), R(0),
  /* 1330 S> */ B(LdaConstant), U8(109),
                B(Star), R(0),
  /* 1342 S> */ B(LdaConstant), U8(110),
                B(Star), R(0),
  /* 1354 S> */ B(LdaConstant), U8(111),
                B(Star), R(0),
  /* 1366 S> */ B(LdaConstant), U8(112),
                B(Star), R(0),
  /* 1378 S> */ B(LdaConstant), U8(113),
                B(Star), R(0),
  /* 1390 S> */ B(LdaConstant), U8(114),
                B(Star), R(0),
  /* 1402 S> */ B(LdaConstant), U8(115),
                B(Star), R(0),
  /* 1414 S> */ B(LdaConstant), U8(116),
                B(Star), R(0),
  /* 1426 S> */ B(LdaConstant), U8(117),
                B(Star), R(0),
  /* 1438 S> */ B(LdaConstant), U8(118),
                B(Star), R(0),
  /* 1450 S> */ B(LdaConstant), U8(119),
                B(Star), R(0),
  /* 1462 S> */ B(LdaConstant), U8(120),
                B(Star), R(0),
  /* 1474 S> */ B(LdaConstant), U8(121),
                B(Star), R(0),
  /* 1486 S> */ B(LdaConstant), U8(122),
                B(Star), R(0),
  /* 1498 S> */ B(LdaConstant), U8(123),
                B(Star), R(0),
  /* 1510 S> */ B(LdaConstant), U8(124),
                B(Star), R(0),
  /* 1522 S> */ B(LdaConstant), U8(125),
                B(Star), R(0),
  /* 1534 S> */ B(LdaConstant), U8(126),
                B(Star), R(0),
  /* 1546 S> */ B(LdaConstant), U8(127),
                B(Star), R(0),
  /* 1558 S> */ B(LdaConstant), U8(128),
                B(Star), R(0),
  /* 1570 S> */ B(LdaConstant), U8(129),
                B(Star), R(0),
  /* 1582 S> */ B(LdaConstant), U8(130),
                B(Star), R(0),
  /* 1594 S> */ B(LdaConstant), U8(131),
                B(Star), R(0),
  /* 1606 S> */ B(LdaConstant), U8(132),
                B(Star), R(0),
  /* 1618 S> */ B(LdaConstant), U8(133),
                B(Star), R(0),
  /* 1630 S> */ B(LdaConstant), U8(134),
                B(Star), R(0),
  /* 1642 S> */ B(LdaConstant), U8(135),
                B(Star), R(0),
  /* 1654 S> */ B(LdaConstant), U8(136),
                B(Star), R(0),
  /* 1666 S> */ B(LdaConstant), U8(137),
                B(Star), R(0),
  /* 1678 S> */ B(LdaConstant), U8(138),
                B(Star), R(0),
  /* 1690 S> */ B(LdaConstant), U8(139),
                B(Star), R(0),
  /* 1702 S> */ B(LdaConstant), U8(140),
                B(Star), R(0),
  /* 1714 S> */ B(LdaConstant), U8(141),
                B(Star), R(0),
  /* 1726 S> */ B(LdaConstant), U8(142),
                B(Star), R(0),
  /* 1738 S> */ B(LdaConstant), U8(143),
                B(Star), R(0),
  /* 1750 S> */ B(LdaConstant), U8(144),
                B(Star), R(0),
  /* 1762 S> */ B(LdaConstant), U8(145),
                B(Star), R(0),
  /* 1774 S> */ B(LdaConstant), U8(146),
                B(Star), R(0),
  /* 1786 S> */ B(LdaConstant), U8(147),
                B(Star), R(0),
  /* 1798 S> */ B(LdaConstant), U8(148),
                B(Star), R(0),
  /* 1810 S> */ B(LdaConstant), U8(149),
                B(Star), R(0),
  /* 1822 S> */ B(LdaConstant), U8(150),
                B(Star), R(0),
  /* 1834 S> */ B(LdaConstant), U8(151),
                B(Star), R(0),
  /* 1846 S> */ B(LdaConstant), U8(152),
                B(Star), R(0),
  /* 1858 S> */ B(LdaConstant), U8(153),
                B(Star), R(0),
  /* 1870 S> */ B(LdaConstant), U8(154),
                B(Star), R(0),
  /* 1882 S> */ B(LdaConstant), U8(155),
                B(Star), R(0),
  /* 1894 S> */ B(LdaConstant), U8(156),
                B(Star), R(0),
  /* 1906 S> */ B(LdaConstant), U8(157),
                B(Star), R(0),
  /* 1918 S> */ B(LdaConstant), U8(158),
                B(Star), R(0),
  /* 1930 S> */ B(LdaConstant), U8(159),
                B(Star), R(0),
  /* 1942 S> */ B(LdaConstant), U8(160),
                B(Star), R(0),
  /* 1954 S> */ B(LdaConstant), U8(161),
                B(Star), R(0),
  /* 1966 S> */ B(LdaConstant), U8(162),
                B(Star), R(0),
  /* 1978 S> */ B(LdaConstant), U8(163),
                B(Star), R(0),
  /* 1990 S> */ B(LdaConstant), U8(164),
                B(Star), R(0),
  /* 2002 S> */ B(LdaConstant), U8(165),
                B(Star), R(0),
  /* 2014 S> */ B(LdaConstant), U8(166),
                B(Star), R(0),
  /* 2026 S> */ B(LdaConstant), U8(167),
                B(Star), R(0),
  /* 2038 S> */ B(LdaConstant), U8(168),
                B(Star), R(0),
  /* 2050 S> */ B(LdaConstant), U8(169),
                B(Star), R(0),
  /* 2062 S> */ B(LdaConstant), U8(170),
                B(Star), R(0),
  /* 2074 S> */ B(LdaConstant), U8(171),
                B(Star), R(0),
  /* 2086 S> */ B(LdaConstant), U8(172),
                B(Star), R(0),
  /* 2098 S> */ B(LdaConstant), U8(173),
                B(Star), R(0),
  /* 2110 S> */ B(LdaConstant), U8(174),
                B(Star), R(0),
  /* 2122 S> */ B(LdaConstant), U8(175),
                B(Star), R(0),
  /* 2134 S> */ B(LdaConstant), U8(176),
                B(Star), R(0),
  /* 2146 S> */ B(LdaConstant), U8(177),
                B(Star), R(0),
  /* 2158 S> */ B(LdaConstant), U8(178),
                B(Star), R(0),
  /* 2170 S> */ B(LdaConstant), U8(179),
                B(Star), R(0),
  /* 2182 S> */ B(LdaConstant), U8(180),
                B(Star), R(0),
  /* 2194 S> */ B(LdaConstant), U8(181),
                B(Star), R(0),
  /* 2206 S> */ B(LdaConstant), U8(182),
                B(Star), R(0),
  /* 2218 S> */ B(LdaConstant), U8(183),
                B(Star), R(0),
  /* 2230 S> */ B(LdaConstant), U8(184),
                B(Star), R(0),
  /* 2242 S> */ B(LdaConstant), U8(185),
                B(Star), R(0),
  /* 2254 S> */ B(LdaConstant), U8(186),
                B(Star), R(0),
  /* 2266 S> */ B(LdaConstant), U8(187),
                B(Star), R(0),
  /* 2278 S> */ B(LdaConstant), U8(188),
                B(Star), R(0),
  /* 2290 S> */ B(LdaConstant), U8(189),
                B(Star), R(0),
  /* 2302 S> */ B(LdaConstant), U8(190),
                B(Star), R(0),
  /* 2314 S> */ B(LdaConstant), U8(191),
                B(Star), R(0),
  /* 2326 S> */ B(LdaConstant), U8(192),
                B(Star), R(0),
  /* 2338 S> */ B(LdaConstant), U8(193),
                B(Star), R(0),
  /* 2350 S> */ B(LdaConstant), U8(194),
                B(Star), R(0),
  /* 2362 S> */ B(LdaConstant), U8(195),
                B(Star), R(0),
  /* 2374 S> */ B(LdaConstant), U8(196),
                B(Star), R(0),
  /* 2386 S> */ B(LdaConstant), U8(197),
                B(Star), R(0),
  /* 2398 S> */ B(LdaConstant), U8(198),
                B(Star), R(0),
  /* 2410 S> */ B(LdaConstant), U8(199),
                B(Star), R(0),
  /* 2422 S> */ B(LdaConstant), U8(200),
                B(Star), R(0),
  /* 2434 S> */ B(LdaConstant), U8(201),
                B(Star), R(0),
  /* 2446 S> */ B(LdaConstant), U8(202),
                B(Star), R(0),
  /* 2458 S> */ B(LdaConstant), U8(203),
                B(Star), R(0),
  /* 2470 S> */ B(LdaConstant), U8(204),
                B(Star), R(0),
  /* 2482 S> */ B(LdaConstant), U8(205),
                B(Star), R(0),
  /* 2494 S> */ B(LdaConstant), U8(206),
                B(Star), R(0),
  /* 2506 S> */ B(LdaConstant), U8(207),
                B(Star), R(0),
  /* 2518 S> */ B(LdaConstant), U8(208),
                B(Star), R(0),
  /* 2530 S> */ B(LdaConstant), U8(209),
                B(Star), R(0),
  /* 2542 S> */ B(LdaConstant), U8(210),
                B(Star), R(0),
  /* 2554 S> */ B(LdaConstant), U8(211),
                B(Star), R(0),
  /* 2566 S> */ B(LdaConstant), U8(212),
                B(Star), R(0),
  /* 2578 S> */ B(LdaConstant), U8(213),
                B(Star), R(0),
  /* 2590 S> */ B(LdaConstant), U8(214),
                B(Star), R(0),
  /* 2602 S> */ B(LdaConstant), U8(215),
                B(Star), R(0),
  /* 2614 S> */ B(LdaConstant), U8(216),
                B(Star), R(0),
  /* 2626 S> */ B(LdaConstant), U8(217),
                B(Star), R(0),
  /* 2638 S> */ B(LdaConstant), U8(218),
                B(Star), R(0),
  /* 2650 S> */ B(LdaConstant), U8(219),
                B(Star), R(0),
  /* 2662 S> */ B(LdaConstant), U8(220),
                B(Star), R(0),
  /* 2674 S> */ B(LdaConstant), U8(221),
                B(Star), R(0),
  /* 2686 S> */ B(LdaConstant), U8(222),
                B(Star), R(0),
  /* 2698 S> */ B(LdaConstant), U8(223),
                B(Star), R(0),
  /* 2710 S> */ B(LdaConstant), U8(224),
                B(Star), R(0),
  /* 2722 S> */ B(LdaConstant), U8(225),
                B(Star), R(0),
  /* 2734 S> */ B(LdaConstant), U8(226),
                B(Star), R(0),
  /* 2746 S> */ B(LdaConstant), U8(227),
                B(Star), R(0),
  /* 2758 S> */ B(LdaConstant), U8(228),
                B(Star), R(0),
  /* 2770 S> */ B(LdaConstant), U8(229),
                B(Star), R(0),
  /* 2782 S> */ B(LdaConstant), U8(230),
                B(Star), R(0),
  /* 2794 S> */ B(LdaConstant), U8(231),
                B(Star), R(0),
  /* 2806 S> */ B(LdaConstant), U8(232),
                B(Star), R(0),
  /* 2818 S> */ B(LdaConstant), U8(233),
                B(Star), R(0),
  /* 2830 S> */ B(LdaConstant), U8(234),
                B(Star), R(0),
  /* 2842 S> */ B(LdaConstant), U8(235),
                B(Star), R(0),
  /* 2854 S> */ B(LdaConstant), U8(236),
                B(Star), R(0),
  /* 2866 S> */ B(LdaConstant), U8(237),
                B(Star), R(0),
  /* 2878 S> */ B(LdaConstant), U8(238),
                B(Star), R(0),
  /* 2890 S> */ B(LdaConstant), U8(239),
                B(Star), R(0),
  /* 2902 S> */ B(LdaConstant), U8(240),
                B(Star), R(0),
  /* 2914 S> */ B(LdaConstant), U8(241),
                B(Star), R(0),
  /* 2926 S> */ B(LdaConstant), U8(242),
                B(Star), R(0),
  /* 2938 S> */ B(LdaConstant), U8(243),
                B(Star), R(0),
  /* 2950 S> */ B(LdaConstant), U8(244),
                B(Star), R(0),
  /* 2962 S> */ B(LdaConstant), U8(245),
                B(Star), R(0),
  /* 2974 S> */ B(LdaConstant), U8(246),
                B(Star), R(0),
  /* 2986 S> */ B(LdaConstant), U8(247),
                B(Star), R(0),
  /* 2998 S> */ B(LdaConstant), U8(248),
                B(Star), R(0),
  /* 3010 S> */ B(LdaConstant), U8(249),
                B(Star), R(0),
  /* 3022 S> */ B(LdaConstant), U8(250),
                B(Star), R(0),
  /* 3034 S> */ B(LdaConstant), U8(251),
                B(Star), R(0),
  /* 3046 S> */ B(LdaConstant), U8(252),
                B(Star), R(0),
  /* 3058 S> */ B(LdaConstant), U8(253),
                B(Star), R(0),
  /* 3070 S> */ B(LdaConstant), U8(254),
                B(Star), R(0),
  /* 3082 S> */ B(LdaConstant), U8(255),
                B(Star), R(0),
  /* 3086 S> */ B(Wide), B(LdaLookupGlobalSlotInsideTypeof), U16(256), U16(4), U16(1),
                B(TypeOf),
  /* 3102 S> */ B(Return),
]
constant pool: [
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  ONE_BYTE_INTERNALIZED_STRING_TYPE ["x"],
]
handlers: [
]

---
snippet: "
  var f;
  var x = 1;
  function f1() {
    eval(\"function t() {\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"x = 10;\" +
    \"};\" +
    \"f = t; f();\"
  );
  }
  f1();
"
frame size: 1
parameter count: 1
bytecode array length: 1034
bytecodes: [
  /*   10 E> */ B(StackCheck),
  /*   22 S> */ B(LdaConstant), U8(0),
                B(Star), R(0),
  /*   34 S> */ B(LdaConstant), U8(1),
                B(Star), R(0),
  /*   46 S> */ B(LdaConstant), U8(2),
                B(Star), R(0),
  /*   58 S> */ B(LdaConstant), U8(3),
                B(Star), R(0),
  /*   70 S> */ B(LdaConstant), U8(4),
                B(Star), R(0),
  /*   82 S> */ B(LdaConstant), U8(5),
                B(Star), R(0),
  /*   94 S> */ B(LdaConstant), U8(6),
                B(Star), R(0),
  /*  106 S> */ B(LdaConstant), U8(7),
                B(Star), R(0),
  /*  118 S> */ B(LdaConstant), U8(8),
                B(Star), R(0),
  /*  130 S> */ B(LdaConstant), U8(9),
                B(Star), R(0),
  /*  142 S> */ B(LdaConstant), U8(10),
                B(Star), R(0),
  /*  154 S> */ B(LdaConstant), U8(11),
                B(Star), R(0),
  /*  166 S> */ B(LdaConstant), U8(12),
                B(Star), R(0),
  /*  178 S> */ B(LdaConstant), U8(13),
                B(Star), R(0),
  /*  190 S> */ B(LdaConstant), U8(14),
                B(Star), R(0),
  /*  202 S> */ B(LdaConstant), U8(15),
                B(Star), R(0),
  /*  214 S> */ B(LdaConstant), U8(16),
                B(Star), R(0),
  /*  226 S> */ B(LdaConstant), U8(17),
                B(Star), R(0),
  /*  238 S> */ B(LdaConstant), U8(18),
                B(Star), R(0),
  /*  250 S> */ B(LdaConstant), U8(19),
                B(Star), R(0),
  /*  262 S> */ B(LdaConstant), U8(20),
                B(Star), R(0),
  /*  274 S> */ B(LdaConstant), U8(21),
                B(Star), R(0),
  /*  286 S> */ B(LdaConstant), U8(22),
                B(Star), R(0),
  /*  298 S> */ B(LdaConstant), U8(23),
                B(Star), R(0),
  /*  310 S> */ B(LdaConstant), U8(24),
                B(Star), R(0),
  /*  322 S> */ B(LdaConstant), U8(25),
                B(Star), R(0),
  /*  334 S> */ B(LdaConstant), U8(26),
                B(Star), R(0),
  /*  346 S> */ B(LdaConstant), U8(27),
                B(Star), R(0),
  /*  358 S> */ B(LdaConstant), U8(28),
                B(Star), R(0),
  /*  370 S> */ B(LdaConstant), U8(29),
                B(Star), R(0),
  /*  382 S> */ B(LdaConstant), U8(30),
                B(Star), R(0),
  /*  394 S> */ B(LdaConstant), U8(31),
                B(Star), R(0),
  /*  406 S> */ B(LdaConstant), U8(32),
                B(Star), R(0),
  /*  418 S> */ B(LdaConstant), U8(33),
                B(Star), R(0),
  /*  430 S> */ B(LdaConstant), U8(34),
                B(Star), R(0),
  /*  442 S> */ B(LdaConstant), U8(35),
                B(Star), R(0),
  /*  454 S> */ B(LdaConstant), U8(36),
                B(Star), R(0),
  /*  466 S> */ B(LdaConstant), U8(37),
                B(Star), R(0),
  /*  478 S> */ B(LdaConstant), U8(38),
                B(Star), R(0),
  /*  490 S> */ B(LdaConstant), U8(39),
                B(Star), R(0),
  /*  502 S> */ B(LdaConstant), U8(40),
                B(Star), R(0),
  /*  514 S> */ B(LdaConstant), U8(41),
                B(Star), R(0),
  /*  526 S> */ B(LdaConstant), U8(42),
                B(Star), R(0),
  /*  538 S> */ B(LdaConstant), U8(43),
                B(Star), R(0),
  /*  550 S> */ B(LdaConstant), U8(44),
                B(Star), R(0),
  /*  562 S> */ B(LdaConstant), U8(45),
                B(Star), R(0),
  /*  574 S> */ B(LdaConstant), U8(46),
                B(Star), R(0),
  /*  586 S> */ B(LdaConstant), U8(47),
                B(Star), R(0),
  /*  598 S> */ B(LdaConstant), U8(48),
                B(Star), R(0),
  /*  610 S> */ B(LdaConstant), U8(49),
                B(Star), R(0),
  /*  622 S> */ B(LdaConstant), U8(50),
                B(Star), R(0),
  /*  634 S> */ B(LdaConstant), U8(51),
                B(Star), R(0),
  /*  646 S> */ B(LdaConstant), U8(52),
                B(Star), R(0),
  /*  658 S> */ B(LdaConstant), U8(53),
                B(Star), R(0),
  /*  670 S> */ B(LdaConstant), U8(54),
                B(Star), R(0),
  /*  682 S> */ B(LdaConstant), U8(55),
                B(Star), R(0),
  /*  694 S> */ B(LdaConstant), U8(56),
                B(Star), R(0),
  /*  706 S> */ B(LdaConstant), U8(57),
                B(Star), R(0),
  /*  718 S> */ B(LdaConstant), U8(58),
                B(Star), R(0),
  /*  730 S> */ B(LdaConstant), U8(59),
                B(Star), R(0),
  /*  742 S> */ B(LdaConstant), U8(60),
                B(Star), R(0),
  /*  754 S> */ B(LdaConstant), U8(61),
                B(Star), R(0),
  /*  766 S> */ B(LdaConstant), U8(62),
                B(Star), R(0),
  /*  778 S> */ B(LdaConstant), U8(63),
                B(Star), R(0),
  /*  790 S> */ B(LdaConstant), U8(64),
                B(Star), R(0),
  /*  802 S> */ B(LdaConstant), U8(65),
                B(Star), R(0),
  /*  814 S> */ B(LdaConstant), U8(66),
                B(Star), R(0),
  /*  826 S> */ B(LdaConstant), U8(67),
                B(Star), R(0),
  /*  838 S> */ B(LdaConstant), U8(68),
                B(Star), R(0),
  /*  850 S> */ B(LdaConstant), U8(69),
                B(Star), R(0),
  /*  862 S> */ B(LdaConstant), U8(70),
                B(Star), R(0),
  /*  874 S> */ B(LdaConstant), U8(71),
                B(Star), R(0),
  /*  886 S> */ B(LdaConstant), U8(72),
                B(Star), R(0),
  /*  898 S> */ B(LdaConstant), U8(73),
                B(Star), R(0),
  /*  910 S> */ B(LdaConstant), U8(74),
                B(Star), R(0),
  /*  922 S> */ B(LdaConstant), U8(75),
                B(Star), R(0),
  /*  934 S> */ B(LdaConstant), U8(76),
                B(Star), R(0),
  /*  946 S> */ B(LdaConstant), U8(77),
                B(Star), R(0),
  /*  958 S> */ B(LdaConstant), U8(78),
                B(Star), R(0),
  /*  970 S> */ B(LdaConstant), U8(79),
                B(Star), R(0),
  /*  982 S> */ B(LdaConstant), U8(80),
                B(Star), R(0),
  /*  994 S> */ B(LdaConstant), U8(81),
                B(Star), R(0),
  /* 1006 S> */ B(LdaConstant), U8(82),
                B(Star), R(0),
  /* 1018 S> */ B(LdaConstant), U8(83),
                B(Star), R(0),
  /* 1030 S> */ B(LdaConstant), U8(84),
                B(Star), R(0),
  /* 1042 S> */ B(LdaConstant), U8(85),
                B(Star), R(0),
  /* 1054 S> */ B(LdaConstant), U8(86),
                B(Star), R(0),
  /* 1066 S> */ B(LdaConstant), U8(87),
                B(Star), R(0),
  /* 1078 S> */ B(LdaConstant), U8(88),
                B(Star), R(0),
  /* 1090 S> */ B(LdaConstant), U8(89),
                B(Star), R(0),
  /* 1102 S> */ B(LdaConstant), U8(90),
                B(Star), R(0),
  /* 1114 S> */ B(LdaConstant), U8(91),
                B(Star), R(0),
  /* 1126 S> */ B(LdaConstant), U8(92),
                B(Star), R(0),
  /* 1138 S> */ B(LdaConstant), U8(93),
                B(Star), R(0),
  /* 1150 S> */ B(LdaConstant), U8(94),
                B(Star), R(0),
  /* 1162 S> */ B(LdaConstant), U8(95),
                B(Star), R(0),
  /* 1174 S> */ B(LdaConstant), U8(96),
                B(Star), R(0),
  /* 1186 S> */ B(LdaConstant), U8(97),
                B(Star), R(0),
  /* 1198 S> */ B(LdaConstant), U8(98),
                B(Star), R(0),
  /* 1210 S> */ B(LdaConstant), U8(99),
                B(Star), R(0),
  /* 1222 S> */ B(LdaConstant), U8(100),
                B(Star), R(0),
  /* 1234 S> */ B(LdaConstant), U8(101),
                B(Star), R(0),
  /* 1246 S> */ B(LdaConstant), U8(102),
                B(Star), R(0),
  /* 1258 S> */ B(LdaConstant), U8(103),
                B(Star), R(0),
  /* 1270 S> */ B(LdaConstant), U8(104),
                B(Star), R(0),
  /* 1282 S> */ B(LdaConstant), U8(105),
                B(Star), R(0),
  /* 1294 S> */ B(LdaConstant), U8(106),
                B(Star), R(0),
  /* 1306 S> */ B(LdaConstant), U8(107),
                B(Star), R(0),
  /* 1318 S> */ B(LdaConstant), U8(108),
                B(Star), R(0),
  /* 1330 S> */ B(LdaConstant), U8(109),
                B(Star), R(0),
  /* 1342 S> */ B(LdaConstant), U8(110),
                B(Star), R(0),
  /* 1354 S> */ B(LdaConstant), U8(111),
                B(Star), R(0),
  /* 1366 S> */ B(LdaConstant), U8(112),
                B(Star), R(0),
  /* 1378 S> */ B(LdaConstant), U8(113),
                B(Star), R(0),
  /* 1390 S> */ B(LdaConstant), U8(114),
                B(Star), R(0),
  /* 1402 S> */ B(LdaConstant), U8(115),
                B(Star), R(0),
  /* 1414 S> */ B(LdaConstant), U8(116),
                B(Star), R(0),
  /* 1426 S> */ B(LdaConstant), U8(117),
                B(Star), R(0),
  /* 1438 S> */ B(LdaConstant), U8(118),
                B(Star), R(0),
  /* 1450 S> */ B(LdaConstant), U8(119),
                B(Star), R(0),
  /* 1462 S> */ B(LdaConstant), U8(120),
                B(Star), R(0),
  /* 1474 S> */ B(LdaConstant), U8(121),
                B(Star), R(0),
  /* 1486 S> */ B(LdaConstant), U8(122),
                B(Star), R(0),
  /* 1498 S> */ B(LdaConstant), U8(123),
                B(Star), R(0),
  /* 1510 S> */ B(LdaConstant), U8(124),
                B(Star), R(0),
  /* 1522 S> */ B(LdaConstant), U8(125),
                B(Star), R(0),
  /* 1534 S> */ B(LdaConstant), U8(126),
                B(Star), R(0),
  /* 1546 S> */ B(LdaConstant), U8(127),
                B(Star), R(0),
  /* 1558 S> */ B(LdaConstant), U8(128),
                B(Star), R(0),
  /* 1570 S> */ B(LdaConstant), U8(129),
                B(Star), R(0),
  /* 1582 S> */ B(LdaConstant), U8(130),
                B(Star), R(0),
  /* 1594 S> */ B(LdaConstant), U8(131),
                B(Star), R(0),
  /* 1606 S> */ B(LdaConstant), U8(132),
                B(Star), R(0),
  /* 1618 S> */ B(LdaConstant), U8(133),
                B(Star), R(0),
  /* 1630 S> */ B(LdaConstant), U8(134),
                B(Star), R(0),
  /* 1642 S> */ B(LdaConstant), U8(135),
                B(Star), R(0),
  /* 1654 S> */ B(LdaConstant), U8(136),
                B(Star), R(0),
  /* 1666 S> */ B(LdaConstant), U8(137),
                B(Star), R(0),
  /* 1678 S> */ B(LdaConstant), U8(138),
                B(Star), R(0),
  /* 1690 S> */ B(LdaConstant), U8(139),
                B(Star), R(0),
  /* 1702 S> */ B(LdaConstant), U8(140),
                B(Star), R(0),
  /* 1714 S> */ B(LdaConstant), U8(141),
                B(Star), R(0),
  /* 1726 S> */ B(LdaConstant), U8(142),
                B(Star), R(0),
  /* 1738 S> */ B(LdaConstant), U8(143),
                B(Star), R(0),
  /* 1750 S> */ B(LdaConstant), U8(144),
                B(Star), R(0),
  /* 1762 S> */ B(LdaConstant), U8(145),
                B(Star), R(0),
  /* 1774 S> */ B(LdaConstant), U8(146),
                B(Star), R(0),
  /* 1786 S> */ B(LdaConstant), U8(147),
                B(Star), R(0),
  /* 1798 S> */ B(LdaConstant), U8(148),
                B(Star), R(0),
  /* 1810 S> */ B(LdaConstant), U8(149),
                B(Star), R(0),
  /* 1822 S> */ B(LdaConstant), U8(150),
                B(Star), R(0),
  /* 1834 S> */ B(LdaConstant), U8(151),
                B(Star), R(0),
  /* 1846 S> */ B(LdaConstant), U8(152),
                B(Star), R(0),
  /* 1858 S> */ B(LdaConstant), U8(153),
                B(Star), R(0),
  /* 1870 S> */ B(LdaConstant), U8(154),
                B(Star), R(0),
  /* 1882 S> */ B(LdaConstant), U8(155),
                B(Star), R(0),
  /* 1894 S> */ B(LdaConstant), U8(156),
                B(Star), R(0),
  /* 1906 S> */ B(LdaConstant), U8(157),
                B(Star), R(0),
  /* 1918 S> */ B(LdaConstant), U8(158),
                B(Star), R(0),
  /* 1930 S> */ B(LdaConstant), U8(159),
                B(Star), R(0),
  /* 1942 S> */ B(LdaConstant), U8(160),
                B(Star), R(0),
  /* 1954 S> */ B(LdaConstant), U8(161),
                B(Star), R(0),
  /* 1966 S> */ B(LdaConstant), U8(162),
                B(Star), R(0),
  /* 1978 S> */ B(LdaConstant), U8(163),
                B(Star), R(0),
  /* 1990 S> */ B(LdaConstant), U8(164),
                B(Star), R(0),
  /* 2002 S> */ B(LdaConstant), U8(165),
                B(Star), R(0),
  /* 2014 S> */ B(LdaConstant), U8(166),
                B(Star), R(0),
  /* 2026 S> */ B(LdaConstant), U8(167),
                B(Star), R(0),
  /* 2038 S> */ B(LdaConstant), U8(168),
                B(Star), R(0),
  /* 2050 S> */ B(LdaConstant), U8(169),
                B(Star), R(0),
  /* 2062 S> */ B(LdaConstant), U8(170),
                B(Star), R(0),
  /* 2074 S> */ B(LdaConstant), U8(171),
                B(Star), R(0),
  /* 2086 S> */ B(LdaConstant), U8(172),
                B(Star), R(0),
  /* 2098 S> */ B(LdaConstant), U8(173),
                B(Star), R(0),
  /* 2110 S> */ B(LdaConstant), U8(174),
                B(Star), R(0),
  /* 2122 S> */ B(LdaConstant), U8(175),
                B(Star), R(0),
  /* 2134 S> */ B(LdaConstant), U8(176),
                B(Star), R(0),
  /* 2146 S> */ B(LdaConstant), U8(177),
                B(Star), R(0),
  /* 2158 S> */ B(LdaConstant), U8(178),
                B(Star), R(0),
  /* 2170 S> */ B(LdaConstant), U8(179),
                B(Star), R(0),
  /* 2182 S> */ B(LdaConstant), U8(180),
                B(Star), R(0),
  /* 2194 S> */ B(LdaConstant), U8(181),
                B(Star), R(0),
  /* 2206 S> */ B(LdaConstant), U8(182),
                B(Star), R(0),
  /* 2218 S> */ B(LdaConstant), U8(183),
                B(Star), R(0),
  /* 2230 S> */ B(LdaConstant), U8(184),
                B(Star), R(0),
  /* 2242 S> */ B(LdaConstant), U8(185),
                B(Star), R(0),
  /* 2254 S> */ B(LdaConstant), U8(186),
                B(Star), R(0),
  /* 2266 S> */ B(LdaConstant), U8(187),
                B(Star), R(0),
  /* 2278 S> */ B(LdaConstant), U8(188),
                B(Star), R(0),
  /* 2290 S> */ B(LdaConstant), U8(189),
                B(Star), R(0),
  /* 2302 S> */ B(LdaConstant), U8(190),
                B(Star), R(0),
  /* 2314 S> */ B(LdaConstant), U8(191),
                B(Star), R(0),
  /* 2326 S> */ B(LdaConstant), U8(192),
                B(Star), R(0),
  /* 2338 S> */ B(LdaConstant), U8(193),
                B(Star), R(0),
  /* 2350 S> */ B(LdaConstant), U8(194),
                B(Star), R(0),
  /* 2362 S> */ B(LdaConstant), U8(195),
                B(Star), R(0),
  /* 2374 S> */ B(LdaConstant), U8(196),
                B(Star), R(0),
  /* 2386 S> */ B(LdaConstant), U8(197),
                B(Star), R(0),
  /* 2398 S> */ B(LdaConstant), U8(198),
                B(Star), R(0),
  /* 2410 S> */ B(LdaConstant), U8(199),
                B(Star), R(0),
  /* 2422 S> */ B(LdaConstant), U8(200),
                B(Star), R(0),
  /* 2434 S> */ B(LdaConstant), U8(201),
                B(Star), R(0),
  /* 2446 S> */ B(LdaConstant), U8(202),
                B(Star), R(0),
  /* 2458 S> */ B(LdaConstant), U8(203),
                B(Star), R(0),
  /* 2470 S> */ B(LdaConstant), U8(204),
                B(Star), R(0),
  /* 2482 S> */ B(LdaConstant), U8(205),
                B(Star), R(0),
  /* 2494 S> */ B(LdaConstant), U8(206),
                B(Star), R(0),
  /* 2506 S> */ B(LdaConstant), U8(207),
                B(Star), R(0),
  /* 2518 S> */ B(LdaConstant), U8(208),
                B(Star), R(0),
  /* 2530 S> */ B(LdaConstant), U8(209),
                B(Star), R(0),
  /* 2542 S> */ B(LdaConstant), U8(210),
                B(Star), R(0),
  /* 2554 S> */ B(LdaConstant), U8(211),
                B(Star), R(0),
  /* 2566 S> */ B(LdaConstant), U8(212),
                B(Star), R(0),
  /* 2578 S> */ B(LdaConstant), U8(213),
                B(Star), R(0),
  /* 2590 S> */ B(LdaConstant), U8(214),
                B(Star), R(0),
  /* 2602 S> */ B(LdaConstant), U8(215),
                B(Star), R(0),
  /* 2614 S> */ B(LdaConstant), U8(216),
                B(Star), R(0),
  /* 2626 S> */ B(LdaConstant), U8(217),
                B(Star), R(0),
  /* 2638 S> */ B(LdaConstant), U8(218),
                B(Star), R(0),
  /* 2650 S> */ B(LdaConstant), U8(219),
                B(Star), R(0),
  /* 2662 S> */ B(LdaConstant), U8(220),
                B(Star), R(0),
  /* 2674 S> */ B(LdaConstant), U8(221),
                B(Star), R(0),
  /* 2686 S> */ B(LdaConstant), U8(222),
                B(Star), R(0),
  /* 2698 S> */ B(LdaConstant), U8(223),
                B(Star), R(0),
  /* 2710 S> */ B(LdaConstant), U8(224),
                B(Star), R(0),
  /* 2722 S> */ B(LdaConstant), U8(225),
                B(Star), R(0),
  /* 2734 S> */ B(LdaConstant), U8(226),
                B(Star), R(0),
  /* 2746 S> */ B(LdaConstant), U8(227),
                B(Star), R(0),
  /* 2758 S> */ B(LdaConstant), U8(228),
                B(Star), R(0),
  /* 2770 S> */ B(LdaConstant), U8(229),
                B(Star), R(0),
  /* 2782 S> */ B(LdaConstant), U8(230),
                B(Star), R(0),
  /* 2794 S> */ B(LdaConstant), U8(231),
                B(Star), R(0),
  /* 2806 S> */ B(LdaConstant), U8(232),
                B(Star), R(0),
  /* 2818 S> */ B(LdaConstant), U8(233),
                B(Star), R(0),
  /* 2830 S> */ B(LdaConstant), U8(234),
                B(Star), R(0),
  /* 2842 S> */ B(LdaConstant), U8(235),
                B(Star), R(0),
  /* 2854 S> */ B(LdaConstant), U8(236),
                B(Star), R(0),
  /* 2866 S> */ B(LdaConstant), U8(237),
                B(Star), R(0),
  /* 2878 S> */ B(LdaConstant), U8(238),
                B(Star), R(0),
  /* 2890 S> */ B(LdaConstant), U8(239),
                B(Star), R(0),
  /* 2902 S> */ B(LdaConstant), U8(240),
                B(Star), R(0),
  /* 2914 S> */ B(LdaConstant), U8(241),
                B(Star), R(0),
  /* 2926 S> */ B(LdaConstant), U8(242),
                B(Star), R(0),
  /* 2938 S> */ B(LdaConstant), U8(243),
                B(Star), R(0),
  /* 2950 S> */ B(LdaConstant), U8(244),
                B(Star), R(0),
  /* 2962 S> */ B(LdaConstant), U8(245),
                B(Star), R(0),
  /* 2974 S> */ B(LdaConstant), U8(246),
                B(Star), R(0),
  /* 2986 S> */ B(LdaConstant), U8(247),
                B(Star), R(0),
  /* 2998 S> */ B(LdaConstant), U8(248),
                B(Star), R(0),
  /* 3010 S> */ B(LdaConstant), U8(249),
                B(Star), R(0),
  /* 3022 S> */ B(LdaConstant), U8(250),
                B(Star), R(0),
  /* 3034 S> */ B(LdaConstant), U8(251),
                B(Star), R(0),
  /* 3046 S> */ B(LdaConstant), U8(252),
                B(Star), R(0),
  /* 3058 S> */ B(LdaConstant), U8(253),
                B(Star), R(0),
  /* 3070 S> */ B(LdaConstant), U8(254),
                B(Star), R(0),
  /* 3082 S> */ B(LdaConstant), U8(255),
                B(Star), R(0),
  /* 3086 S> */ B(LdaSmi), I8(10),
  /* 3088 E> */ B(Wide), B(StaLookupSlot), U16(256), U8(0),
                B(LdaUndefined),
  /* 3093 S> */ B(Return),
]
constant pool: [
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  ONE_BYTE_INTERNALIZED_STRING_TYPE ["x"],
]
handlers: [
]

---
snippet: "
  var f;
  var x = 1;
  function f1() {
    eval(\"function t() {\" +
      \"'use strict';\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"var y = 2.3;\" +
      \"x = 10;\" +
    \"};\" +
    \"f = t; f();\"
  );
  }
  f1();
"
frame size: 1
parameter count: 1
bytecode array length: 1034
bytecodes: [
  /*   10 E> */ B(StackCheck),
  /*   35 S> */ B(LdaConstant), U8(0),
                B(Star), R(0),
  /*   47 S> */ B(LdaConstant), U8(1),
                B(Star), R(0),
  /*   59 S> */ B(LdaConstant), U8(2),
                B(Star), R(0),
  /*   71 S> */ B(LdaConstant), U8(3),
                B(Star), R(0),
  /*   83 S> */ B(LdaConstant), U8(4),
                B(Star), R(0),
  /*   95 S> */ B(LdaConstant), U8(5),
                B(Star), R(0),
  /*  107 S> */ B(LdaConstant), U8(6),
                B(Star), R(0),
  /*  119 S> */ B(LdaConstant), U8(7),
                B(Star), R(0),
  /*  131 S> */ B(LdaConstant), U8(8),
                B(Star), R(0),
  /*  143 S> */ B(LdaConstant), U8(9),
                B(Star), R(0),
  /*  155 S> */ B(LdaConstant), U8(10),
                B(Star), R(0),
  /*  167 S> */ B(LdaConstant), U8(11),
                B(Star), R(0),
  /*  179 S> */ B(LdaConstant), U8(12),
                B(Star), R(0),
  /*  191 S> */ B(LdaConstant), U8(13),
                B(Star), R(0),
  /*  203 S> */ B(LdaConstant), U8(14),
                B(Star), R(0),
  /*  215 S> */ B(LdaConstant), U8(15),
                B(Star), R(0),
  /*  227 S> */ B(LdaConstant), U8(16),
                B(Star), R(0),
  /*  239 S> */ B(LdaConstant), U8(17),
                B(Star), R(0),
  /*  251 S> */ B(LdaConstant), U8(18),
                B(Star), R(0),
  /*  263 S> */ B(LdaConstant), U8(19),
                B(Star), R(0),
  /*  275 S> */ B(LdaConstant), U8(20),
                B(Star), R(0),
  /*  287 S> */ B(LdaConstant), U8(21),
                B(Star), R(0),
  /*  299 S> */ B(LdaConstant), U8(22),
                B(Star), R(0),
  /*  311 S> */ B(LdaConstant), U8(23),
                B(Star), R(0),
  /*  323 S> */ B(LdaConstant), U8(24),
                B(Star), R(0),
  /*  335 S> */ B(LdaConstant), U8(25),
                B(Star), R(0),
  /*  347 S> */ B(LdaConstant), U8(26),
                B(Star), R(0),
  /*  359 S> */ B(LdaConstant), U8(27),
                B(Star), R(0),
  /*  371 S> */ B(LdaConstant), U8(28),
                B(Star), R(0),
  /*  383 S> */ B(LdaConstant), U8(29),
                B(Star), R(0),
  /*  395 S> */ B(LdaConstant), U8(30),
                B(Star), R(0),
  /*  407 S> */ B(LdaConstant), U8(31),
                B(Star), R(0),
  /*  419 S> */ B(LdaConstant), U8(32),
                B(Star), R(0),
  /*  431 S> */ B(LdaConstant), U8(33),
                B(Star), R(0),
  /*  443 S> */ B(LdaConstant), U8(34),
                B(Star), R(0),
  /*  455 S> */ B(LdaConstant), U8(35),
                B(Star), R(0),
  /*  467 S> */ B(LdaConstant), U8(36),
                B(Star), R(0),
  /*  479 S> */ B(LdaConstant), U8(37),
                B(Star), R(0),
  /*  491 S> */ B(LdaConstant), U8(38),
                B(Star), R(0),
  /*  503 S> */ B(LdaConstant), U8(39),
                B(Star), R(0),
  /*  515 S> */ B(LdaConstant), U8(40),
                B(Star), R(0),
  /*  527 S> */ B(LdaConstant), U8(41),
                B(Star), R(0),
  /*  539 S> */ B(LdaConstant), U8(42),
                B(Star), R(0),
  /*  551 S> */ B(LdaConstant), U8(43),
                B(Star), R(0),
  /*  563 S> */ B(LdaConstant), U8(44),
                B(Star), R(0),
  /*  575 S> */ B(LdaConstant), U8(45),
                B(Star), R(0),
  /*  587 S> */ B(LdaConstant), U8(46),
                B(Star), R(0),
  /*  599 S> */ B(LdaConstant), U8(47),
                B(Star), R(0),
  /*  611 S> */ B(LdaConstant), U8(48),
                B(Star), R(0),
  /*  623 S> */ B(LdaConstant), U8(49),
                B(Star), R(0),
  /*  635 S> */ B(LdaConstant), U8(50),
                B(Star), R(0),
  /*  647 S> */ B(LdaConstant), U8(51),
                B(Star), R(0),
  /*  659 S> */ B(LdaConstant), U8(52),
                B(Star), R(0),
  /*  671 S> */ B(LdaConstant), U8(53),
                B(Star), R(0),
  /*  683 S> */ B(LdaConstant), U8(54),
                B(Star), R(0),
  /*  695 S> */ B(LdaConstant), U8(55),
                B(Star), R(0),
  /*  707 S> */ B(LdaConstant), U8(56),
                B(Star), R(0),
  /*  719 S> */ B(LdaConstant), U8(57),
                B(Star), R(0),
  /*  731 S> */ B(LdaConstant), U8(58),
                B(Star), R(0),
  /*  743 S> */ B(LdaConstant), U8(59),
                B(Star), R(0),
  /*  755 S> */ B(LdaConstant), U8(60),
                B(Star), R(0),
  /*  767 S> */ B(LdaConstant), U8(61),
                B(Star), R(0),
  /*  779 S> */ B(LdaConstant), U8(62),
                B(Star), R(0),
  /*  791 S> */ B(LdaConstant), U8(63),
                B(Star), R(0),
  /*  803 S> */ B(LdaConstant), U8(64),
                B(Star), R(0),
  /*  815 S> */ B(LdaConstant), U8(65),
                B(Star), R(0),
  /*  827 S> */ B(LdaConstant), U8(66),
                B(Star), R(0),
  /*  839 S> */ B(LdaConstant), U8(67),
                B(Star), R(0),
  /*  851 S> */ B(LdaConstant), U8(68),
                B(Star), R(0),
  /*  863 S> */ B(LdaConstant), U8(69),
                B(Star), R(0),
  /*  875 S> */ B(LdaConstant), U8(70),
                B(Star), R(0),
  /*  887 S> */ B(LdaConstant), U8(71),
                B(Star), R(0),
  /*  899 S> */ B(LdaConstant), U8(72),
                B(Star), R(0),
  /*  911 S> */ B(LdaConstant), U8(73),
                B(Star), R(0),
  /*  923 S> */ B(LdaConstant), U8(74),
                B(Star), R(0),
  /*  935 S> */ B(LdaConstant), U8(75),
                B(Star), R(0),
  /*  947 S> */ B(LdaConstant), U8(76),
                B(Star), R(0),
  /*  959 S> */ B(LdaConstant), U8(77),
                B(Star), R(0),
  /*  971 S> */ B(LdaConstant), U8(78),
                B(Star), R(0),
  /*  983 S> */ B(LdaConstant), U8(79),
                B(Star), R(0),
  /*  995 S> */ B(LdaConstant), U8(80),
                B(Star), R(0),
  /* 1007 S> */ B(LdaConstant), U8(81),
                B(Star), R(0),
  /* 1019 S> */ B(LdaConstant), U8(82),
                B(Star), R(0),
  /* 1031 S> */ B(LdaConstant), U8(83),
                B(Star), R(0),
  /* 1043 S> */ B(LdaConstant), U8(84),
                B(Star), R(0),
  /* 1055 S> */ B(LdaConstant), U8(85),
                B(Star), R(0),
  /* 1067 S> */ B(LdaConstant), U8(86),
                B(Star), R(0),
  /* 1079 S> */ B(LdaConstant), U8(87),
                B(Star), R(0),
  /* 1091 S> */ B(LdaConstant), U8(88),
                B(Star), R(0),
  /* 1103 S> */ B(LdaConstant), U8(89),
                B(Star), R(0),
  /* 1115 S> */ B(LdaConstant), U8(90),
                B(Star), R(0),
  /* 1127 S> */ B(LdaConstant), U8(91),
                B(Star), R(0),
  /* 1139 S> */ B(LdaConstant), U8(92),
                B(Star), R(0),
  /* 1151 S> */ B(LdaConstant), U8(93),
                B(Star), R(0),
  /* 1163 S> */ B(LdaConstant), U8(94),
                B(Star), R(0),
  /* 1175 S> */ B(LdaConstant), U8(95),
                B(Star), R(0),
  /* 1187 S> */ B(LdaConstant), U8(96),
                B(Star), R(0),
  /* 1199 S> */ B(LdaConstant), U8(97),
                B(Star), R(0),
  /* 1211 S> */ B(LdaConstant), U8(98),
                B(Star), R(0),
  /* 1223 S> */ B(LdaConstant), U8(99),
                B(Star), R(0),
  /* 1235 S> */ B(LdaConstant), U8(100),
                B(Star), R(0),
  /* 1247 S> */ B(LdaConstant), U8(101),
                B(Star), R(0),
  /* 1259 S> */ B(LdaConstant), U8(102),
                B(Star), R(0),
  /* 1271 S> */ B(LdaConstant), U8(103),
                B(Star), R(0),
  /* 1283 S> */ B(LdaConstant), U8(104),
                B(Star), R(0),
  /* 1295 S> */ B(LdaConstant), U8(105),
                B(Star), R(0),
  /* 1307 S> */ B(LdaConstant), U8(106),
                B(Star), R(0),
  /* 1319 S> */ B(LdaConstant), U8(107),
                B(Star), R(0),
  /* 1331 S> */ B(LdaConstant), U8(108),
                B(Star), R(0),
  /* 1343 S> */ B(LdaConstant), U8(109),
                B(Star), R(0),
  /* 1355 S> */ B(LdaConstant), U8(110),
                B(Star), R(0),
  /* 1367 S> */ B(LdaConstant), U8(111),
                B(Star), R(0),
  /* 1379 S> */ B(LdaConstant), U8(112),
                B(Star), R(0),
  /* 1391 S> */ B(LdaConstant), U8(113),
                B(Star), R(0),
  /* 1403 S> */ B(LdaConstant), U8(114),
                B(Star), R(0),
  /* 1415 S> */ B(LdaConstant), U8(115),
                B(Star), R(0),
  /* 1427 S> */ B(LdaConstant), U8(116),
                B(Star), R(0),
  /* 1439 S> */ B(LdaConstant), U8(117),
                B(Star), R(0),
  /* 1451 S> */ B(LdaConstant), U8(118),
                B(Star), R(0),
  /* 1463 S> */ B(LdaConstant), U8(119),
                B(Star), R(0),
  /* 1475 S> */ B(LdaConstant), U8(120),
                B(Star), R(0),
  /* 1487 S> */ B(LdaConstant), U8(121),
                B(Star), R(0),
  /* 1499 S> */ B(LdaConstant), U8(122),
                B(Star), R(0),
  /* 1511 S> */ B(LdaConstant), U8(123),
                B(Star), R(0),
  /* 1523 S> */ B(LdaConstant), U8(124),
                B(Star), R(0),
  /* 1535 S> */ B(LdaConstant), U8(125),
                B(Star), R(0),
  /* 1547 S> */ B(LdaConstant), U8(126),
                B(Star), R(0),
  /* 1559 S> */ B(LdaConstant), U8(127),
                B(Star), R(0),
  /* 1571 S> */ B(LdaConstant), U8(128),
                B(Star), R(0),
  /* 1583 S> */ B(LdaConstant), U8(129),
                B(Star), R(0),
  /* 1595 S> */ B(LdaConstant), U8(130),
                B(Star), R(0),
  /* 1607 S> */ B(LdaConstant), U8(131),
                B(Star), R(0),
  /* 1619 S> */ B(LdaConstant), U8(132),
                B(Star), R(0),
  /* 1631 S> */ B(LdaConstant), U8(133),
                B(Star), R(0),
  /* 1643 S> */ B(LdaConstant), U8(134),
                B(Star), R(0),
  /* 1655 S> */ B(LdaConstant), U8(135),
                B(Star), R(0),
  /* 1667 S> */ B(LdaConstant), U8(136),
                B(Star), R(0),
  /* 1679 S> */ B(LdaConstant), U8(137),
                B(Star), R(0),
  /* 1691 S> */ B(LdaConstant), U8(138),
                B(Star), R(0),
  /* 1703 S> */ B(LdaConstant), U8(139),
                B(Star), R(0),
  /* 1715 S> */ B(LdaConstant), U8(140),
                B(Star), R(0),
  /* 1727 S> */ B(LdaConstant), U8(141),
                B(Star), R(0),
  /* 1739 S> */ B(LdaConstant), U8(142),
                B(Star), R(0),
  /* 1751 S> */ B(LdaConstant), U8(143),
                B(Star), R(0),
  /* 1763 S> */ B(LdaConstant), U8(144),
                B(Star), R(0),
  /* 1775 S> */ B(LdaConstant), U8(145),
                B(Star), R(0),
  /* 1787 S> */ B(LdaConstant), U8(146),
                B(Star), R(0),
  /* 1799 S> */ B(LdaConstant), U8(147),
                B(Star), R(0),
  /* 1811 S> */ B(LdaConstant), U8(148),
                B(Star), R(0),
  /* 1823 S> */ B(LdaConstant), U8(149),
                B(Star), R(0),
  /* 1835 S> */ B(LdaConstant), U8(150),
                B(Star), R(0),
  /* 1847 S> */ B(LdaConstant), U8(151),
                B(Star), R(0),
  /* 1859 S> */ B(LdaConstant), U8(152),
                B(Star), R(0),
  /* 1871 S> */ B(LdaConstant), U8(153),
                B(Star), R(0),
  /* 1883 S> */ B(LdaConstant), U8(154),
                B(Star), R(0),
  /* 1895 S> */ B(LdaConstant), U8(155),
                B(Star), R(0),
  /* 1907 S> */ B(LdaConstant), U8(156),
                B(Star), R(0),
  /* 1919 S> */ B(LdaConstant), U8(157),
                B(Star), R(0),
  /* 1931 S> */ B(LdaConstant), U8(158),
                B(Star), R(0),
  /* 1943 S> */ B(LdaConstant), U8(159),
                B(Star), R(0),
  /* 1955 S> */ B(LdaConstant), U8(160),
                B(Star), R(0),
  /* 1967 S> */ B(LdaConstant), U8(161),
                B(Star), R(0),
  /* 1979 S> */ B(LdaConstant), U8(162),
                B(Star), R(0),
  /* 1991 S> */ B(LdaConstant), U8(163),
                B(Star), R(0),
  /* 2003 S> */ B(LdaConstant), U8(164),
                B(Star), R(0),
  /* 2015 S> */ B(LdaConstant), U8(165),
                B(Star), R(0),
  /* 2027 S> */ B(LdaConstant), U8(166),
                B(Star), R(0),
  /* 2039 S> */ B(LdaConstant), U8(167),
                B(Star), R(0),
  /* 2051 S> */ B(LdaConstant), U8(168),
                B(Star), R(0),
  /* 2063 S> */ B(LdaConstant), U8(169),
                B(Star), R(0),
  /* 2075 S> */ B(LdaConstant), U8(170),
                B(Star), R(0),
  /* 2087 S> */ B(LdaConstant), U8(171),
                B(Star), R(0),
  /* 2099 S> */ B(LdaConstant), U8(172),
                B(Star), R(0),
  /* 2111 S> */ B(LdaConstant), U8(173),
                B(Star), R(0),
  /* 2123 S> */ B(LdaConstant), U8(174),
                B(Star), R(0),
  /* 2135 S> */ B(LdaConstant), U8(175),
                B(Star), R(0),
  /* 2147 S> */ B(LdaConstant), U8(176),
                B(Star), R(0),
  /* 2159 S> */ B(LdaConstant), U8(177),
                B(Star), R(0),
  /* 2171 S> */ B(LdaConstant), U8(178),
                B(Star), R(0),
  /* 2183 S> */ B(LdaConstant), U8(179),
                B(Star), R(0),
  /* 2195 S> */ B(LdaConstant), U8(180),
                B(Star), R(0),
  /* 2207 S> */ B(LdaConstant), U8(181),
                B(Star), R(0),
  /* 2219 S> */ B(LdaConstant), U8(182),
                B(Star), R(0),
  /* 2231 S> */ B(LdaConstant), U8(183),
                B(Star), R(0),
  /* 2243 S> */ B(LdaConstant), U8(184),
                B(Star), R(0),
  /* 2255 S> */ B(LdaConstant), U8(185),
                B(Star), R(0),
  /* 2267 S> */ B(LdaConstant), U8(186),
                B(Star), R(0),
  /* 2279 S> */ B(LdaConstant), U8(187),
                B(Star), R(0),
  /* 2291 S> */ B(LdaConstant), U8(188),
                B(Star), R(0),
  /* 2303 S> */ B(LdaConstant), U8(189),
                B(Star), R(0),
  /* 2315 S> */ B(LdaConstant), U8(190),
                B(Star), R(0),
  /* 2327 S> */ B(LdaConstant), U8(191),
                B(Star), R(0),
  /* 2339 S> */ B(LdaConstant), U8(192),
                B(Star), R(0),
  /* 2351 S> */ B(LdaConstant), U8(193),
                B(Star), R(0),
  /* 2363 S> */ B(LdaConstant), U8(194),
                B(Star), R(0),
  /* 2375 S> */ B(LdaConstant), U8(195),
                B(Star), R(0),
  /* 2387 S> */ B(LdaConstant), U8(196),
                B(Star), R(0),
  /* 2399 S> */ B(LdaConstant), U8(197),
                B(Star), R(0),
  /* 2411 S> */ B(LdaConstant), U8(198),
                B(Star), R(0),
  /* 2423 S> */ B(LdaConstant), U8(199),
                B(Star), R(0),
  /* 2435 S> */ B(LdaConstant), U8(200),
                B(Star), R(0),
  /* 2447 S> */ B(LdaConstant), U8(201),
                B(Star), R(0),
  /* 2459 S> */ B(LdaConstant), U8(202),
                B(Star), R(0),
  /* 2471 S> */ B(LdaConstant), U8(203),
                B(Star), R(0),
  /* 2483 S> */ B(LdaConstant), U8(204),
                B(Star), R(0),
  /* 2495 S> */ B(LdaConstant), U8(205),
                B(Star), R(0),
  /* 2507 S> */ B(LdaConstant), U8(206),
                B(Star), R(0),
  /* 2519 S> */ B(LdaConstant), U8(207),
                B(Star), R(0),
  /* 2531 S> */ B(LdaConstant), U8(208),
                B(Star), R(0),
  /* 2543 S> */ B(LdaConstant), U8(209),
                B(Star), R(0),
  /* 2555 S> */ B(LdaConstant), U8(210),
                B(Star), R(0),
  /* 2567 S> */ B(LdaConstant), U8(211),
                B(Star), R(0),
  /* 2579 S> */ B(LdaConstant), U8(212),
                B(Star), R(0),
  /* 2591 S> */ B(LdaConstant), U8(213),
                B(Star), R(0),
  /* 2603 S> */ B(LdaConstant), U8(214),
                B(Star), R(0),
  /* 2615 S> */ B(LdaConstant), U8(215),
                B(Star), R(0),
  /* 2627 S> */ B(LdaConstant), U8(216),
                B(Star), R(0),
  /* 2639 S> */ B(LdaConstant), U8(217),
                B(Star), R(0),
  /* 2651 S> */ B(LdaConstant), U8(218),
                B(Star), R(0),
  /* 2663 S> */ B(LdaConstant), U8(219),
                B(Star), R(0),
  /* 2675 S> */ B(LdaConstant), U8(220),
                B(Star), R(0),
  /* 2687 S> */ B(LdaConstant), U8(221),
                B(Star), R(0),
  /* 2699 S> */ B(LdaConstant), U8(222),
                B(Star), R(0),
  /* 2711 S> */ B(LdaConstant), U8(223),
                B(Star), R(0),
  /* 2723 S> */ B(LdaConstant), U8(224),
                B(Star), R(0),
  /* 2735 S> */ B(LdaConstant), U8(225),
                B(Star), R(0),
  /* 2747 S> */ B(LdaConstant), U8(226),
                B(Star), R(0),
  /* 2759 S> */ B(LdaConstant), U8(227),
                B(Star), R(0),
  /* 2771 S> */ B(LdaConstant), U8(228),
                B(Star), R(0),
  /* 2783 S> */ B(LdaConstant), U8(229),
                B(Star), R(0),
  /* 2795 S> */ B(LdaConstant), U8(230),
                B(Star), R(0),
  /* 2807 S> */ B(LdaConstant), U8(231),
                B(Star), R(0),
  /* 2819 S> */ B(LdaConstant), U8(232),
                B(Star), R(0),
  /* 2831 S> */ B(LdaConstant), U8(233),
                B(Star), R(0),
  /* 2843 S> */ B(LdaConstant), U8(234),
                B(Star), R(0),
  /* 2855 S> */ B(LdaConstant), U8(235),
                B(Star), R(0),
  /* 2867 S> */ B(LdaConstant), U8(236),
                B(Star), R(0),
  /* 2879 S> */ B(LdaConstant), U8(237),
                B(Star), R(0),
  /* 2891 S> */ B(LdaConstant), U8(238),
                B(Star), R(0),
  /* 2903 S> */ B(LdaConstant), U8(239),
                B(Star), R(0),
  /* 2915 S> */ B(LdaConstant), U8(240),
                B(Star), R(0),
  /* 2927 S> */ B(LdaConstant), U8(241),
                B(Star), R(0),
  /* 2939 S> */ B(LdaConstant), U8(242),
                B(Star), R(0),
  /* 2951 S> */ B(LdaConstant), U8(243),
                B(Star), R(0),
  /* 2963 S> */ B(LdaConstant), U8(244),
                B(Star), R(0),
  /* 2975 S> */ B(LdaConstant), U8(245),
                B(Star), R(0),
  /* 2987 S> */ B(LdaConstant), U8(246),
                B(Star), R(0),
  /* 2999 S> */ B(LdaConstant), U8(247),
                B(Star), R(0),
  /* 3011 S> */ B(LdaConstant), U8(248),
                B(Star), R(0),
  /* 3023 S> */ B(LdaConstant), U8(249),
                B(Star), R(0),
  /* 3035 S> */ B(LdaConstant), U8(250),
                B(Star), R(0),
  /* 3047 S> */ B(LdaConstant), U8(251),
                B(Star), R(0),
  /* 3059 S> */ B(LdaConstant), U8(252),
                B(Star), R(0),
  /* 3071 S> */ B(LdaConstant), U8(253),
                B(Star), R(0),
  /* 3083 S> */ B(LdaConstant), U8(254),
                B(Star), R(0),
  /* 3095 S> */ B(LdaConstant), U8(255),
                B(Star), R(0),
  /* 3099 S> */ B(LdaSmi), I8(10),
  /* 3101 E> */ B(Wide), B(StaLookupSlot), U16(256), U8(1),
                B(LdaUndefined),
  /* 3106 S> */ B(Return),
]
constant pool: [
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  HEAP_NUMBER_TYPE [2.3],
  ONE_BYTE_INTERNALIZED_STRING_TYPE ["x"],
]
handlers: [
]

