#
# Autogenerated by generate-bytecode-expectations.
#

---
wrap: yes

---
snippet: "
  return new.target;
"
frame size: 1
parameter count: 1
bytecode array length: 9
bytecodes: [
                B(Mov), R(new_target), R(0),
                B(Ldar), R(0),
  /*   30 E> */ B(StackCheck),
  /*   34 S> */ B(Ldar), R(0),
  /*   53 S> */ B(Return),
]
constant pool: [
]
handlers: [
]

---
snippet: "
  new.target;
"
frame size: 1
parameter count: 1
bytecode array length: 8
bytecodes: [
                B(Mov), R(new_target), R(0),
                B(Ldar), R(0),
  /*   30 E> */ B(StackCheck),
  /*   34 S> */ B(LdaUndefined),
  /*   46 S> */ B(Return),
]
constant pool: [
]
handlers: [
]

