#
# Autogenerated by generate-bytecode-expectations.
#

---
execute: yes
wrap: yes

---
snippet: "
"
frame size: 0
parameter count: 1
bytecode array length: 3
bytecodes: [
  /*   30 E> */ B(StackCheck),
                B(LdaUndefined),
  /*   34 S> */ B(Return),
]
constant pool: [
]
handlers: [
]

---
snippet: "
  return;
"
frame size: 0
parameter count: 1
bytecode array length: 3
bytecodes: [
  /*   30 E> */ B(StackCheck),
  /*   34 S> */ B(LdaUndefined),
  /*   42 S> */ B(Return),
]
constant pool: [
]
handlers: [
]

---
snippet: "
  return null;
"
frame size: 0
parameter count: 1
bytecode array length: 3
bytecodes: [
  /*   30 E> */ B(StackCheck),
  /*   34 S> */ B(LdaNull),
  /*   47 S> */ B(Return),
]
constant pool: [
]
handlers: [
]

---
snippet: "
  return true;
"
frame size: 0
parameter count: 1
bytecode array length: 3
bytecodes: [
  /*   30 E> */ B(StackCheck),
  /*   34 S> */ B(LdaTrue),
  /*   47 S> */ B(Return),
]
constant pool: [
]
handlers: [
]

---
snippet: "
  return false;
"
frame size: 0
parameter count: 1
bytecode array length: 3
bytecodes: [
  /*   30 E> */ B(StackCheck),
  /*   34 S> */ B(LdaFalse),
  /*   48 S> */ B(Return),
]
constant pool: [
]
handlers: [
]

---
snippet: "
  return 0;
"
frame size: 0
parameter count: 1
bytecode array length: 3
bytecodes: [
  /*   30 E> */ B(StackCheck),
  /*   34 S> */ B(LdaZero),
  /*   44 S> */ B(Return),
]
constant pool: [
]
handlers: [
]

---
snippet: "
  return +1;
"
frame size: 0
parameter count: 1
bytecode array length: 4
bytecodes: [
  /*   30 E> */ B(StackCheck),
  /*   34 S> */ B(LdaSmi), U8(1),
  /*   45 S> */ B(Return),
]
constant pool: [
]
handlers: [
]

---
snippet: "
  return -1;
"
frame size: 0
parameter count: 1
bytecode array length: 4
bytecodes: [
  /*   30 E> */ B(StackCheck),
  /*   34 S> */ B(LdaSmi), U8(-1),
  /*   45 S> */ B(Return),
]
constant pool: [
]
handlers: [
]

---
snippet: "
  return +127;
"
frame size: 0
parameter count: 1
bytecode array length: 4
bytecodes: [
  /*   30 E> */ B(StackCheck),
  /*   34 S> */ B(LdaSmi), U8(127),
  /*   47 S> */ B(Return),
]
constant pool: [
]
handlers: [
]

---
snippet: "
  return -128;
"
frame size: 0
parameter count: 1
bytecode array length: 4
bytecodes: [
  /*   30 E> */ B(StackCheck),
  /*   34 S> */ B(LdaSmi), U8(-128),
  /*   47 S> */ B(Return),
]
constant pool: [
]
handlers: [
]

---
snippet: "
  return 2.0;
"
frame size: 0
parameter count: 1
bytecode array length: 4
bytecodes: [
  /*   30 E> */ B(StackCheck),
  /*   34 S> */ B(LdaSmi), U8(2),
  /*   46 S> */ B(Return),
]
constant pool: [
]
handlers: [
]

