#
# Autogenerated by generate-bytecode-expectations.
#

---
wrap: yes
private methods: yes

---
snippet: "
  {
    class A {
      get #a() { return 1; }
      set #a(val) { }
    }
  }
"
frame size: 7
parameter count: 1
bytecode array length: 49
bytecodes: [
  /*   30 E> */ B(StackCheck),
                B(CreateBlockContext), U8(0),
                B(PushContext), R(2),
                B(LdaTheHole),
                B(Star), R(6),
                B(CreateClosure), U8(2), U8(0), U8(2),
                B(Star), R(3),
                B(LdaConstant), U8(1),
                B(Star), R(4),
                B(Mov), R(3), R(5),
                B(CallRuntime), U16(Runtime::kDefineClass), R(4), U8(3),
                B(Star), R(4),
                B(Mov), R(5), R(1),
                B(LdaConstant), U8(3),
                B(Star), R(5),
                B(CallRuntime), U16(Runtime::kCreatePrivateNameSymbol), R(5), U8(1),
                B(StaCurrentContextSlot), U8(5),
                B(PopContext), R(2),
                B(Mov), R(1), R(0),
                B(LdaUndefined),
  /*  101 S> */ B(Return),
]
constant pool: [
  SCOPE_INFO_TYPE,
  FIXED_ARRAY_TYPE,
  SHARED_FUNCTION_INFO_TYPE,
  ONE_BYTE_INTERNALIZED_STRING_TYPE ["A"],
]
handlers: [
]

---
snippet: "
  {
    class B {
      get #b() { return 1; }
    }
  }
"
frame size: 7
parameter count: 1
bytecode array length: 49
bytecodes: [
  /*   30 E> */ B(StackCheck),
                B(CreateBlockContext), U8(0),
                B(PushContext), R(2),
                B(LdaTheHole),
                B(Star), R(6),
                B(CreateClosure), U8(2), U8(0), U8(2),
                B(Star), R(3),
                B(LdaConstant), U8(1),
                B(Star), R(4),
                B(Mov), R(3), R(5),
                B(CallRuntime), U16(Runtime::kDefineClass), R(4), U8(3),
                B(Star), R(4),
                B(Mov), R(5), R(1),
                B(LdaConstant), U8(3),
                B(Star), R(5),
                B(CallRuntime), U16(Runtime::kCreatePrivateNameSymbol), R(5), U8(1),
                B(StaCurrentContextSlot), U8(5),
                B(PopContext), R(2),
                B(Mov), R(1), R(0),
                B(LdaUndefined),
  /*   81 S> */ B(Return),
]
constant pool: [
  SCOPE_INFO_TYPE,
  FIXED_ARRAY_TYPE,
  SHARED_FUNCTION_INFO_TYPE,
  ONE_BYTE_INTERNALIZED_STRING_TYPE ["B"],
]
handlers: [
]

---
snippet: "
  {
    class C {
      set #c(val) { }
    }
  }
"
frame size: 7
parameter count: 1
bytecode array length: 49
bytecodes: [
  /*   30 E> */ B(StackCheck),
                B(CreateBlockContext), U8(0),
                B(PushContext), R(2),
                B(LdaTheHole),
                B(Star), R(6),
                B(CreateClosure), U8(2), U8(0), U8(2),
                B(Star), R(3),
                B(LdaConstant), U8(1),
                B(Star), R(4),
                B(Mov), R(3), R(5),
                B(CallRuntime), U16(Runtime::kDefineClass), R(4), U8(3),
                B(Star), R(4),
                B(Mov), R(5), R(1),
                B(LdaConstant), U8(3),
                B(Star), R(5),
                B(CallRuntime), U16(Runtime::kCreatePrivateNameSymbol), R(5), U8(1),
                B(StaCurrentContextSlot), U8(5),
                B(PopContext), R(2),
                B(Mov), R(1), R(0),
                B(LdaUndefined),
  /*   74 S> */ B(Return),
]
constant pool: [
  SCOPE_INFO_TYPE,
  FIXED_ARRAY_TYPE,
  SHARED_FUNCTION_INFO_TYPE,
  ONE_BYTE_INTERNALIZED_STRING_TYPE ["C"],
]
handlers: [
]

---
snippet: "
  {
    class D {
      get #d() { return 1; }
      set #d(val) { }
    }
  
    class E extends D {
      get #e() { return 2; }
      set #e(val) { }
    }
  }
"
frame size: 9
parameter count: 1
bytecode array length: 95
bytecodes: [
  /*   30 E> */ B(StackCheck),
                B(CreateBlockContext), U8(0),
                B(PushContext), R(4),
                B(LdaTheHole),
                B(Star), R(8),
                B(CreateClosure), U8(2), U8(0), U8(2),
                B(Star), R(5),
                B(LdaConstant), U8(1),
                B(Star), R(6),
                B(Mov), R(5), R(7),
                B(CallRuntime), U16(Runtime::kDefineClass), R(6), U8(3),
                B(Star), R(6),
                B(Mov), R(7), R(3),
                B(LdaConstant), U8(3),
                B(Star), R(7),
                B(CallRuntime), U16(Runtime::kCreatePrivateNameSymbol), R(7), U8(1),
                B(StaCurrentContextSlot), U8(5),
                B(PopContext), R(4),
                B(Mov), R(3), R(0),
  /*   38 E> */ B(CreateBlockContext), U8(4),
                B(PushContext), R(4),
  /*  118 E> */ B(CreateClosure), U8(6), U8(1), U8(2),
                B(Star), R(5),
                B(LdaConstant), U8(5),
                B(Star), R(6),
                B(Mov), R(5), R(7),
                B(Mov), R(3), R(8),
                B(CallRuntime), U16(Runtime::kDefineClass), R(6), U8(3),
                B(Star), R(6),
                B(Mov), R(7), R(2),
                B(LdaConstant), U8(7),
                B(Star), R(7),
                B(CallRuntime), U16(Runtime::kCreatePrivateNameSymbol), R(7), U8(1),
                B(StaCurrentContextSlot), U8(5),
                B(PopContext), R(4),
                B(Mov), R(2), R(1),
                B(LdaUndefined),
  /*  175 S> */ B(Return),
]
constant pool: [
  SCOPE_INFO_TYPE,
  FIXED_ARRAY_TYPE,
  SHARED_FUNCTION_INFO_TYPE,
  ONE_BYTE_INTERNALIZED_STRING_TYPE ["D"],
  SCOPE_INFO_TYPE,
  FIXED_ARRAY_TYPE,
  SHARED_FUNCTION_INFO_TYPE,
  ONE_BYTE_INTERNALIZED_STRING_TYPE ["E"],
]
handlers: [
]

