#
# Autogenerated by generate-bytecode-expectations.
#

---
wrap: no
test function name: f

---
snippet: "
  function f(a) { return a.func(); }
  f(new (function Obj() { this.func = function() { return; }})())
"
frame size: 1
parameter count: 2
bytecode array length: 12
bytecodes: [
  /*   10 E> */ B(StackCheck),
  /*   25 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(6),
                B(Star), R(0),
  /*   25 E> */ B(CallProperty0), R(0), R(arg0), U8(4),
  /*   32 S> */ B(Return),
]
constant pool: [
  ONE_BYTE_INTERNALIZED_STRING_TYPE ["func"],
]
handlers: [
]

---
snippet: "
  function f(a, b, c) { return a.func(b, c); }
  f(new (function Obj() { this.func = function() { return; }})(), 1, 2)
"
frame size: 1
parameter count: 4
bytecode array length: 14
bytecodes: [
  /*   10 E> */ B(StackCheck),
  /*   31 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(6),
                B(Star), R(0),
  /*   31 E> */ B(CallProperty2), R(0), R(arg0), R(arg1), R(arg2), U8(4),
  /*   42 S> */ B(Return),
]
constant pool: [
  ONE_BYTE_INTERNALIZED_STRING_TYPE ["func"],
]
handlers: [
]

---
snippet: "
  function f(a, b) { return a.func(b + b, b); }
  f(new (function Obj() { this.func = function() { return; }})(), 1)
"
frame size: 3
parameter count: 3
bytecode array length: 21
bytecodes: [
  /*   10 E> */ B(StackCheck),
  /*   28 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(6),
                B(Star), R(0),
                B(Ldar), R(arg1),
  /*   35 E> */ B(Add), R(arg1), U8(8),
                B(Star), R(2),
  /*   28 E> */ B(CallProperty2), R(0), R(arg0), R(2), R(arg1), U8(4),
  /*   43 S> */ B(Return),
]
constant pool: [
  ONE_BYTE_INTERNALIZED_STRING_TYPE ["func"],
]
handlers: [
]

---
snippet: "
  function f(a) {
   a.func;
   a.func;
   a.func;
   a.func;
   a.func;
   a.func;
   a.func;
   a.func;
   a.func;
   a.func;
   a.func;
   a.func;
   a.func;
   a.func;
   a.func;
   a.func;
   a.func;
   a.func;
   a.func;
   a.func;
   a.func;
   a.func;
   a.func;
   a.func;
   a.func;
   a.func;
   a.func;
   a.func;
   a.func;
   a.func;
   a.func;
   a.func;
   a.func;
   a.func;
   a.func;
   a.func;
   a.func;
   a.func;
   a.func;
   a.func;
   a.func;
   a.func;
   a.func;
   a.func;
   a.func;
   a.func;
   a.func;
   a.func;
   a.func;
   a.func;
   a.func;
   a.func;
   a.func;
   a.func;
   a.func;
   a.func;
   a.func;
   a.func;
   a.func;
   a.func;
   a.func;
   a.func;
   a.func;
   a.func;
   a.func;
   a.func;
   a.func;
   a.func;
   a.func;
   a.func;
   a.func;
   a.func;
   a.func;
   a.func;
   a.func;
   a.func;
   a.func;
   a.func;
   a.func;
   a.func;
   a.func;
   a.func;
   a.func;
   a.func;
   a.func;
   a.func;
   a.func;
   a.func;
   a.func;
   a.func;
   a.func;
   a.func;
   a.func;
   a.func;
   a.func;
   a.func;
   a.func;
   a.func;
   a.func;
   a.func;
   a.func;
   a.func;
   a.func;
   a.func;
   a.func;
   a.func;
   a.func;
   a.func;
   a.func;
   a.func;
   a.func;
   a.func;
   a.func;
   a.func;
   a.func;
   a.func;
   a.func;
   a.func;
   a.func;
   a.func;
   a.func;
   a.func;
   a.func;
   a.func;
   a.func;
   a.func;
   a.func;
   a.func;
   return a.func(); }
  f(new (function Obj() { this.func = function() { return; }})())
"
frame size: 1
parameter count: 2
bytecode array length: 540
bytecodes: [
  /*   10 E> */ B(StackCheck),
  /*   19 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(4),
  /*   28 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(6),
  /*   37 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(8),
  /*   46 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(10),
  /*   55 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(12),
  /*   64 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(14),
  /*   73 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(16),
  /*   82 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(18),
  /*   91 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(20),
  /*  100 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(22),
  /*  109 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(24),
  /*  118 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(26),
  /*  127 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(28),
  /*  136 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(30),
  /*  145 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(32),
  /*  154 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(34),
  /*  163 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(36),
  /*  172 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(38),
  /*  181 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(40),
  /*  190 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(42),
  /*  199 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(44),
  /*  208 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(46),
  /*  217 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(48),
  /*  226 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(50),
  /*  235 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(52),
  /*  244 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(54),
  /*  253 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(56),
  /*  262 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(58),
  /*  271 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(60),
  /*  280 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(62),
  /*  289 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(64),
  /*  298 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(66),
  /*  307 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(68),
  /*  316 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(70),
  /*  325 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(72),
  /*  334 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(74),
  /*  343 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(76),
  /*  352 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(78),
  /*  361 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(80),
  /*  370 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(82),
  /*  379 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(84),
  /*  388 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(86),
  /*  397 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(88),
  /*  406 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(90),
  /*  415 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(92),
  /*  424 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(94),
  /*  433 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(96),
  /*  442 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(98),
  /*  451 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(100),
  /*  460 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(102),
  /*  469 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(104),
  /*  478 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(106),
  /*  487 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(108),
  /*  496 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(110),
  /*  505 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(112),
  /*  514 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(114),
  /*  523 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(116),
  /*  532 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(118),
  /*  541 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(120),
  /*  550 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(122),
  /*  559 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(124),
  /*  568 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(126),
  /*  577 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(128),
  /*  586 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(130),
  /*  595 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(132),
  /*  604 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(134),
  /*  613 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(136),
  /*  622 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(138),
  /*  631 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(140),
  /*  640 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(142),
  /*  649 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(144),
  /*  658 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(146),
  /*  667 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(148),
  /*  676 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(150),
  /*  685 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(152),
  /*  694 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(154),
  /*  703 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(156),
  /*  712 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(158),
  /*  721 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(160),
  /*  730 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(162),
  /*  739 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(164),
  /*  748 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(166),
  /*  757 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(168),
  /*  766 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(170),
  /*  775 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(172),
  /*  784 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(174),
  /*  793 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(176),
  /*  802 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(178),
  /*  811 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(180),
  /*  820 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(182),
  /*  829 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(184),
  /*  838 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(186),
  /*  847 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(188),
  /*  856 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(190),
  /*  865 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(192),
  /*  874 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(194),
  /*  883 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(196),
  /*  892 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(198),
  /*  901 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(200),
  /*  910 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(202),
  /*  919 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(204),
  /*  928 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(206),
  /*  937 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(208),
  /*  946 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(210),
  /*  955 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(212),
  /*  964 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(214),
  /*  973 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(216),
  /*  982 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(218),
  /*  991 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(220),
  /* 1000 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(222),
  /* 1009 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(224),
  /* 1018 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(226),
  /* 1027 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(228),
  /* 1036 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(230),
  /* 1045 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(232),
  /* 1054 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(234),
  /* 1063 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(236),
  /* 1072 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(238),
  /* 1081 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(240),
  /* 1090 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(242),
  /* 1099 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(244),
  /* 1108 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(246),
  /* 1117 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(248),
  /* 1126 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(250),
  /* 1135 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(252),
  /* 1144 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(254),
  /* 1153 S> */ B(Wide), B(LdaNamedProperty), R16(arg0), U16(0), U16(256),
  /* 1162 S> */ B(Wide), B(LdaNamedProperty), R16(arg0), U16(0), U16(258),
  /* 1178 S> */ B(Wide), B(LdaNamedProperty), R16(arg0), U16(0), U16(262),
                B(Star), R(0),
  /* 1178 E> */ B(Wide), B(CallProperty0), R16(0), R16(arg0), U16(260),
  /* 1185 S> */ B(Return),
]
constant pool: [
  ONE_BYTE_INTERNALIZED_STRING_TYPE ["func"],
]
handlers: [
]

---
snippet: "
  function f(a) { return a.func(1).func(2).func(3); }
  f(new (function Obj() { this.func = function(a) { return this; }})())
"
frame size: 5
parameter count: 2
bytecode array length: 51
bytecodes: [
  /*   10 E> */ B(StackCheck),
  /*   25 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(10),
                B(Star), R(2),
                B(LdaSmi), I8(1),
                B(Star), R(4),
  /*   25 E> */ B(CallProperty1), R(2), R(arg0), R(4), U8(8),
                B(Star), R(2),
  /*   32 E> */ B(LdaNamedProperty), R(2), U8(0), U8(12),
                B(Star), R(1),
                B(LdaSmi), I8(2),
                B(Star), R(3),
  /*   33 E> */ B(CallProperty1), R(1), R(2), R(3), U8(6),
                B(Star), R(1),
  /*   40 E> */ B(LdaNamedProperty), R(1), U8(0), U8(14),
                B(Star), R(0),
                B(LdaSmi), I8(3),
                B(Star), R(2),
  /*   41 E> */ B(CallProperty1), R(0), R(1), R(2), U8(4),
  /*   49 S> */ B(Return),
]
constant pool: [
  ONE_BYTE_INTERNALIZED_STRING_TYPE ["func"],
]
handlers: [
]

