#
# Autogenerated by generate-bytecode-expectations.
#

---
wrap: no
test function name: f

---
snippet: "
  function f(a) { a.name = \"val\"; }
  f({name : \"test\"})
"
frame size: 0
parameter count: 2
bytecode array length: 9
bytecodes: [
  /*   10 E> */ B(StackCheck),
  /*   16 S> */ B(LdaConstant), U8(0),
  /*   23 E> */ B(StaNamedPropertySloppy), R(arg0), U8(1), U8(4),
                B(LdaUndefined),
  /*   32 S> */ B(Return),
]
constant pool: [
  ONE_BYTE_INTERNALIZED_STRING_TYPE ["val"],
  ONE_BYTE_INTERNALIZED_STRING_TYPE ["name"],
]
handlers: [
]

---
snippet: "
  function f(a) { a[\"key\"] = \"val\"; }
  f({key : \"test\"})
"
frame size: 0
parameter count: 2
bytecode array length: 9
bytecodes: [
  /*   10 E> */ B(StackCheck),
  /*   16 S> */ B(LdaConstant), U8(0),
  /*   25 E> */ B(StaNamedPropertySloppy), R(arg0), U8(1), U8(4),
                B(LdaUndefined),
  /*   34 S> */ B(Return),
]
constant pool: [
  ONE_BYTE_INTERNALIZED_STRING_TYPE ["val"],
  ONE_BYTE_INTERNALIZED_STRING_TYPE ["key"],
]
handlers: [
]

---
snippet: "
  function f(a) { a[100] = \"val\"; }
  f({100 : \"test\"})
"
frame size: 2
parameter count: 2
bytecode array length: 13
bytecodes: [
  /*   10 E> */ B(StackCheck),
  /*   16 S> */ B(LdaSmi), I8(100),
                B(Star), R(1),
                B(LdaConstant), U8(0),
  /*   23 E> */ B(StaKeyedPropertySloppy), R(arg0), R(1), U8(4),
                B(LdaUndefined),
  /*   32 S> */ B(Return),
]
constant pool: [
  ONE_BYTE_INTERNALIZED_STRING_TYPE ["val"],
]
handlers: [
]

---
snippet: "
  function f(a, b) { a[b] = \"val\"; }
  f({arg : \"test\"}, \"arg\")
"
frame size: 0
parameter count: 3
bytecode array length: 9
bytecodes: [
  /*   10 E> */ B(StackCheck),
  /*   19 S> */ B(LdaConstant), U8(0),
  /*   24 E> */ B(StaKeyedPropertySloppy), R(arg0), R(arg1), U8(4),
                B(LdaUndefined),
  /*   33 S> */ B(Return),
]
constant pool: [
  ONE_BYTE_INTERNALIZED_STRING_TYPE ["val"],
]
handlers: [
]

---
snippet: "
  function f(a) { a.name = a[-124]; }
  f({\"-124\" : \"test\", name : 123 })
"
frame size: 0
parameter count: 2
bytecode array length: 12
bytecodes: [
  /*   10 E> */ B(StackCheck),
  /*   16 S> */ B(LdaSmi), I8(-124),
  /*   26 E> */ B(LdaKeyedProperty), R(arg0), U8(4),
  /*   23 E> */ B(StaNamedPropertySloppy), R(arg0), U8(0), U8(6),
                B(LdaUndefined),
  /*   34 S> */ B(Return),
]
constant pool: [
  ONE_BYTE_INTERNALIZED_STRING_TYPE ["name"],
]
handlers: [
]

---
snippet: "
  function f(a) { \"use strict\"; a.name = \"val\"; }
  f({name : \"test\"})
"
frame size: 0
parameter count: 2
bytecode array length: 9
bytecodes: [
  /*   10 E> */ B(StackCheck),
  /*   30 S> */ B(LdaConstant), U8(0),
  /*   37 E> */ B(StaNamedPropertyStrict), R(arg0), U8(1), U8(4),
                B(LdaUndefined),
  /*   46 S> */ B(Return),
]
constant pool: [
  ONE_BYTE_INTERNALIZED_STRING_TYPE ["val"],
  ONE_BYTE_INTERNALIZED_STRING_TYPE ["name"],
]
handlers: [
]

---
snippet: "
  function f(a, b) { \"use strict\"; a[b] = \"val\"; }
  f({arg : \"test\"}, \"arg\")
"
frame size: 0
parameter count: 3
bytecode array length: 9
bytecodes: [
  /*   10 E> */ B(StackCheck),
  /*   33 S> */ B(LdaConstant), U8(0),
  /*   38 E> */ B(StaKeyedPropertyStrict), R(arg0), R(arg1), U8(4),
                B(LdaUndefined),
  /*   47 S> */ B(Return),
]
constant pool: [
  ONE_BYTE_INTERNALIZED_STRING_TYPE ["val"],
]
handlers: [
]

---
snippet: "
  function f(a) {
    a.name = 1;
    a.name = 1;
    a.name = 1;
    a.name = 1;
    a.name = 1;
    a.name = 1;
    a.name = 1;
    a.name = 1;
    a.name = 1;
    a.name = 1;
    a.name = 1;
    a.name = 1;
    a.name = 1;
    a.name = 1;
    a.name = 1;
    a.name = 1;
    a.name = 1;
    a.name = 1;
    a.name = 1;
    a.name = 1;
    a.name = 1;
    a.name = 1;
    a.name = 1;
    a.name = 1;
    a.name = 1;
    a.name = 1;
    a.name = 1;
    a.name = 1;
    a.name = 1;
    a.name = 1;
    a.name = 1;
    a.name = 1;
    a.name = 1;
    a.name = 1;
    a.name = 1;
    a.name = 1;
    a.name = 1;
    a.name = 1;
    a.name = 1;
    a.name = 1;
    a.name = 1;
    a.name = 1;
    a.name = 1;
    a.name = 1;
    a.name = 1;
    a.name = 1;
    a.name = 1;
    a.name = 1;
    a.name = 1;
    a.name = 1;
    a.name = 1;
    a.name = 1;
    a.name = 1;
    a.name = 1;
    a.name = 1;
    a.name = 1;
    a.name = 1;
    a.name = 1;
    a.name = 1;
    a.name = 1;
    a.name = 1;
    a.name = 1;
    a.name = 1;
    a.name = 1;
    a.name = 1;
    a.name = 1;
    a.name = 1;
    a.name = 1;
    a.name = 1;
    a.name = 1;
    a.name = 1;
    a.name = 1;
    a.name = 1;
    a.name = 1;
    a.name = 1;
    a.name = 1;
    a.name = 1;
    a.name = 1;
    a.name = 1;
    a.name = 1;
    a.name = 1;
    a.name = 1;
    a.name = 1;
    a.name = 1;
    a.name = 1;
    a.name = 1;
    a.name = 1;
    a.name = 1;
    a.name = 1;
    a.name = 1;
    a.name = 1;
    a.name = 1;
    a.name = 1;
    a.name = 1;
    a.name = 1;
    a.name = 1;
    a.name = 1;
    a.name = 1;
    a.name = 1;
    a.name = 1;
    a.name = 1;
    a.name = 1;
    a.name = 1;
    a.name = 1;
    a.name = 1;
    a.name = 1;
    a.name = 1;
    a.name = 1;
    a.name = 1;
    a.name = 1;
    a.name = 1;
    a.name = 1;
    a.name = 1;
    a.name = 1;
    a.name = 1;
    a.name = 1;
    a.name = 1;
    a.name = 1;
    a.name = 1;
    a.name = 1;
    a.name = 1;
    a.name = 1;
    a.name = 1;
    a.name = 1;
    a.name = 1;
    a.name = 1;
    a.name = 1;
    a.name = 1;
    a.name = 2;
  }
  f({name : \"test\"})
"
frame size: 0
parameter count: 2
bytecode array length: 789
bytecodes: [
  /*   10 E> */ B(StackCheck),
  /*   18 S> */ B(LdaSmi), I8(1),
  /*   25 E> */ B(StaNamedPropertySloppy), R(arg0), U8(0), U8(4),
  /*   32 S> */ B(LdaSmi), I8(1),
  /*   39 E> */ B(StaNamedPropertySloppy), R(arg0), U8(0), U8(6),
  /*   46 S> */ B(LdaSmi), I8(1),
  /*   53 E> */ B(StaNamedPropertySloppy), R(arg0), U8(0), U8(8),
  /*   60 S> */ B(LdaSmi), I8(1),
  /*   67 E> */ B(StaNamedPropertySloppy), R(arg0), U8(0), U8(10),
  /*   74 S> */ B(LdaSmi), I8(1),
  /*   81 E> */ B(StaNamedPropertySloppy), R(arg0), U8(0), U8(12),
  /*   88 S> */ B(LdaSmi), I8(1),
  /*   95 E> */ B(StaNamedPropertySloppy), R(arg0), U8(0), U8(14),
  /*  102 S> */ B(LdaSmi), I8(1),
  /*  109 E> */ B(StaNamedPropertySloppy), R(arg0), U8(0), U8(16),
  /*  116 S> */ B(LdaSmi), I8(1),
  /*  123 E> */ B(StaNamedPropertySloppy), R(arg0), U8(0), U8(18),
  /*  130 S> */ B(LdaSmi), I8(1),
  /*  137 E> */ B(StaNamedPropertySloppy), R(arg0), U8(0), U8(20),
  /*  144 S> */ B(LdaSmi), I8(1),
  /*  151 E> */ B(StaNamedPropertySloppy), R(arg0), U8(0), U8(22),
  /*  158 S> */ B(LdaSmi), I8(1),
  /*  165 E> */ B(StaNamedPropertySloppy), R(arg0), U8(0), U8(24),
  /*  172 S> */ B(LdaSmi), I8(1),
  /*  179 E> */ B(StaNamedPropertySloppy), R(arg0), U8(0), U8(26),
  /*  186 S> */ B(LdaSmi), I8(1),
  /*  193 E> */ B(StaNamedPropertySloppy), R(arg0), U8(0), U8(28),
  /*  200 S> */ B(LdaSmi), I8(1),
  /*  207 E> */ B(StaNamedPropertySloppy), R(arg0), U8(0), U8(30),
  /*  214 S> */ B(LdaSmi), I8(1),
  /*  221 E> */ B(StaNamedPropertySloppy), R(arg0), U8(0), U8(32),
  /*  228 S> */ B(LdaSmi), I8(1),
  /*  235 E> */ B(StaNamedPropertySloppy), R(arg0), U8(0), U8(34),
  /*  242 S> */ B(LdaSmi), I8(1),
  /*  249 E> */ B(StaNamedPropertySloppy), R(arg0), U8(0), U8(36),
  /*  256 S> */ B(LdaSmi), I8(1),
  /*  263 E> */ B(StaNamedPropertySloppy), R(arg0), U8(0), U8(38),
  /*  270 S> */ B(LdaSmi), I8(1),
  /*  277 E> */ B(StaNamedPropertySloppy), R(arg0), U8(0), U8(40),
  /*  284 S> */ B(LdaSmi), I8(1),
  /*  291 E> */ B(StaNamedPropertySloppy), R(arg0), U8(0), U8(42),
  /*  298 S> */ B(LdaSmi), I8(1),
  /*  305 E> */ B(StaNamedPropertySloppy), R(arg0), U8(0), U8(44),
  /*  312 S> */ B(LdaSmi), I8(1),
  /*  319 E> */ B(StaNamedPropertySloppy), R(arg0), U8(0), U8(46),
  /*  326 S> */ B(LdaSmi), I8(1),
  /*  333 E> */ B(StaNamedPropertySloppy), R(arg0), U8(0), U8(48),
  /*  340 S> */ B(LdaSmi), I8(1),
  /*  347 E> */ B(StaNamedPropertySloppy), R(arg0), U8(0), U8(50),
  /*  354 S> */ B(LdaSmi), I8(1),
  /*  361 E> */ B(StaNamedPropertySloppy), R(arg0), U8(0), U8(52),
  /*  368 S> */ B(LdaSmi), I8(1),
  /*  375 E> */ B(StaNamedPropertySloppy), R(arg0), U8(0), U8(54),
  /*  382 S> */ B(LdaSmi), I8(1),
  /*  389 E> */ B(StaNamedPropertySloppy), R(arg0), U8(0), U8(56),
  /*  396 S> */ B(LdaSmi), I8(1),
  /*  403 E> */ B(StaNamedPropertySloppy), R(arg0), U8(0), U8(58),
  /*  410 S> */ B(LdaSmi), I8(1),
  /*  417 E> */ B(StaNamedPropertySloppy), R(arg0), U8(0), U8(60),
  /*  424 S> */ B(LdaSmi), I8(1),
  /*  431 E> */ B(StaNamedPropertySloppy), R(arg0), U8(0), U8(62),
  /*  438 S> */ B(LdaSmi), I8(1),
  /*  445 E> */ B(StaNamedPropertySloppy), R(arg0), U8(0), U8(64),
  /*  452 S> */ B(LdaSmi), I8(1),
  /*  459 E> */ B(StaNamedPropertySloppy), R(arg0), U8(0), U8(66),
  /*  466 S> */ B(LdaSmi), I8(1),
  /*  473 E> */ B(StaNamedPropertySloppy), R(arg0), U8(0), U8(68),
  /*  480 S> */ B(LdaSmi), I8(1),
  /*  487 E> */ B(StaNamedPropertySloppy), R(arg0), U8(0), U8(70),
  /*  494 S> */ B(LdaSmi), I8(1),
  /*  501 E> */ B(StaNamedPropertySloppy), R(arg0), U8(0), U8(72),
  /*  508 S> */ B(LdaSmi), I8(1),
  /*  515 E> */ B(StaNamedPropertySloppy), R(arg0), U8(0), U8(74),
  /*  522 S> */ B(LdaSmi), I8(1),
  /*  529 E> */ B(StaNamedPropertySloppy), R(arg0), U8(0), U8(76),
  /*  536 S> */ B(LdaSmi), I8(1),
  /*  543 E> */ B(StaNamedPropertySloppy), R(arg0), U8(0), U8(78),
  /*  550 S> */ B(LdaSmi), I8(1),
  /*  557 E> */ B(StaNamedPropertySloppy), R(arg0), U8(0), U8(80),
  /*  564 S> */ B(LdaSmi), I8(1),
  /*  571 E> */ B(StaNamedPropertySloppy), R(arg0), U8(0), U8(82),
  /*  578 S> */ B(LdaSmi), I8(1),
  /*  585 E> */ B(StaNamedPropertySloppy), R(arg0), U8(0), U8(84),
  /*  592 S> */ B(LdaSmi), I8(1),
  /*  599 E> */ B(StaNamedPropertySloppy), R(arg0), U8(0), U8(86),
  /*  606 S> */ B(LdaSmi), I8(1),
  /*  613 E> */ B(StaNamedPropertySloppy), R(arg0), U8(0), U8(88),
  /*  620 S> */ B(LdaSmi), I8(1),
  /*  627 E> */ B(StaNamedPropertySloppy), R(arg0), U8(0), U8(90),
  /*  634 S> */ B(LdaSmi), I8(1),
  /*  641 E> */ B(StaNamedPropertySloppy), R(arg0), U8(0), U8(92),
  /*  648 S> */ B(LdaSmi), I8(1),
  /*  655 E> */ B(StaNamedPropertySloppy), R(arg0), U8(0), U8(94),
  /*  662 S> */ B(LdaSmi), I8(1),
  /*  669 E> */ B(StaNamedPropertySloppy), R(arg0), U8(0), U8(96),
  /*  676 S> */ B(LdaSmi), I8(1),
  /*  683 E> */ B(StaNamedPropertySloppy), R(arg0), U8(0), U8(98),
  /*  690 S> */ B(LdaSmi), I8(1),
  /*  697 E> */ B(StaNamedPropertySloppy), R(arg0), U8(0), U8(100),
  /*  704 S> */ B(LdaSmi), I8(1),
  /*  711 E> */ B(StaNamedPropertySloppy), R(arg0), U8(0), U8(102),
  /*  718 S> */ B(LdaSmi), I8(1),
  /*  725 E> */ B(StaNamedPropertySloppy), R(arg0), U8(0), U8(104),
  /*  732 S> */ B(LdaSmi), I8(1),
  /*  739 E> */ B(StaNamedPropertySloppy), R(arg0), U8(0), U8(106),
  /*  746 S> */ B(LdaSmi), I8(1),
  /*  753 E> */ B(StaNamedPropertySloppy), R(arg0), U8(0), U8(108),
  /*  760 S> */ B(LdaSmi), I8(1),
  /*  767 E> */ B(StaNamedPropertySloppy), R(arg0), U8(0), U8(110),
  /*  774 S> */ B(LdaSmi), I8(1),
  /*  781 E> */ B(StaNamedPropertySloppy), R(arg0), U8(0), U8(112),
  /*  788 S> */ B(LdaSmi), I8(1),
  /*  795 E> */ B(StaNamedPropertySloppy), R(arg0), U8(0), U8(114),
  /*  802 S> */ B(LdaSmi), I8(1),
  /*  809 E> */ B(StaNamedPropertySloppy), R(arg0), U8(0), U8(116),
  /*  816 S> */ B(LdaSmi), I8(1),
  /*  823 E> */ B(StaNamedPropertySloppy), R(arg0), U8(0), U8(118),
  /*  830 S> */ B(LdaSmi), I8(1),
  /*  837 E> */ B(StaNamedPropertySloppy), R(arg0), U8(0), U8(120),
  /*  844 S> */ B(LdaSmi), I8(1),
  /*  851 E> */ B(StaNamedPropertySloppy), R(arg0), U8(0), U8(122),
  /*  858 S> */ B(LdaSmi), I8(1),
  /*  865 E> */ B(StaNamedPropertySloppy), R(arg0), U8(0), U8(124),
  /*  872 S> */ B(LdaSmi), I8(1),
  /*  879 E> */ B(StaNamedPropertySloppy), R(arg0), U8(0), U8(126),
  /*  886 S> */ B(LdaSmi), I8(1),
  /*  893 E> */ B(StaNamedPropertySloppy), R(arg0), U8(0), U8(128),
  /*  900 S> */ B(LdaSmi), I8(1),
  /*  907 E> */ B(StaNamedPropertySloppy), R(arg0), U8(0), U8(130),
  /*  914 S> */ B(LdaSmi), I8(1),
  /*  921 E> */ B(StaNamedPropertySloppy), R(arg0), U8(0), U8(132),
  /*  928 S> */ B(LdaSmi), I8(1),
  /*  935 E> */ B(StaNamedPropertySloppy), R(arg0), U8(0), U8(134),
  /*  942 S> */ B(LdaSmi), I8(1),
  /*  949 E> */ B(StaNamedPropertySloppy), R(arg0), U8(0), U8(136),
  /*  956 S> */ B(LdaSmi), I8(1),
  /*  963 E> */ B(StaNamedPropertySloppy), R(arg0), U8(0), U8(138),
  /*  970 S> */ B(LdaSmi), I8(1),
  /*  977 E> */ B(StaNamedPropertySloppy), R(arg0), U8(0), U8(140),
  /*  984 S> */ B(LdaSmi), I8(1),
  /*  991 E> */ B(StaNamedPropertySloppy), R(arg0), U8(0), U8(142),
  /*  998 S> */ B(LdaSmi), I8(1),
  /* 1005 E> */ B(StaNamedPropertySloppy), R(arg0), U8(0), U8(144),
  /* 1012 S> */ B(LdaSmi), I8(1),
  /* 1019 E> */ B(StaNamedPropertySloppy), R(arg0), U8(0), U8(146),
  /* 1026 S> */ B(LdaSmi), I8(1),
  /* 1033 E> */ B(StaNamedPropertySloppy), R(arg0), U8(0), U8(148),
  /* 1040 S> */ B(LdaSmi), I8(1),
  /* 1047 E> */ B(StaNamedPropertySloppy), R(arg0), U8(0), U8(150),
  /* 1054 S> */ B(LdaSmi), I8(1),
  /* 1061 E> */ B(StaNamedPropertySloppy), R(arg0), U8(0), U8(152),
  /* 1068 S> */ B(LdaSmi), I8(1),
  /* 1075 E> */ B(StaNamedPropertySloppy), R(arg0), U8(0), U8(154),
  /* 1082 S> */ B(LdaSmi), I8(1),
  /* 1089 E> */ B(StaNamedPropertySloppy), R(arg0), U8(0), U8(156),
  /* 1096 S> */ B(LdaSmi), I8(1),
  /* 1103 E> */ B(StaNamedPropertySloppy), R(arg0), U8(0), U8(158),
  /* 1110 S> */ B(LdaSmi), I8(1),
  /* 1117 E> */ B(StaNamedPropertySloppy), R(arg0), U8(0), U8(160),
  /* 1124 S> */ B(LdaSmi), I8(1),
  /* 1131 E> */ B(StaNamedPropertySloppy), R(arg0), U8(0), U8(162),
  /* 1138 S> */ B(LdaSmi), I8(1),
  /* 1145 E> */ B(StaNamedPropertySloppy), R(arg0), U8(0), U8(164),
  /* 1152 S> */ B(LdaSmi), I8(1),
  /* 1159 E> */ B(StaNamedPropertySloppy), R(arg0), U8(0), U8(166),
  /* 1166 S> */ B(LdaSmi), I8(1),
  /* 1173 E> */ B(StaNamedPropertySloppy), R(arg0), U8(0), U8(168),
  /* 1180 S> */ B(LdaSmi), I8(1),
  /* 1187 E> */ B(StaNamedPropertySloppy), R(arg0), U8(0), U8(170),
  /* 1194 S> */ B(LdaSmi), I8(1),
  /* 1201 E> */ B(StaNamedPropertySloppy), R(arg0), U8(0), U8(172),
  /* 1208 S> */ B(LdaSmi), I8(1),
  /* 1215 E> */ B(StaNamedPropertySloppy), R(arg0), U8(0), U8(174),
  /* 1222 S> */ B(LdaSmi), I8(1),
  /* 1229 E> */ B(StaNamedPropertySloppy), R(arg0), U8(0), U8(176),
  /* 1236 S> */ B(LdaSmi), I8(1),
  /* 1243 E> */ B(StaNamedPropertySloppy), R(arg0), U8(0), U8(178),
  /* 1250 S> */ B(LdaSmi), I8(1),
  /* 1257 E> */ B(StaNamedPropertySloppy), R(arg0), U8(0), U8(180),
  /* 1264 S> */ B(LdaSmi), I8(1),
  /* 1271 E> */ B(StaNamedPropertySloppy), R(arg0), U8(0), U8(182),
  /* 1278 S> */ B(LdaSmi), I8(1),
  /* 1285 E> */ B(StaNamedPropertySloppy), R(arg0), U8(0), U8(184),
  /* 1292 S> */ B(LdaSmi), I8(1),
  /* 1299 E> */ B(StaNamedPropertySloppy), R(arg0), U8(0), U8(186),
  /* 1306 S> */ B(LdaSmi), I8(1),
  /* 1313 E> */ B(StaNamedPropertySloppy), R(arg0), U8(0), U8(188),
  /* 1320 S> */ B(LdaSmi), I8(1),
  /* 1327 E> */ B(StaNamedPropertySloppy), R(arg0), U8(0), U8(190),
  /* 1334 S> */ B(LdaSmi), I8(1),
  /* 1341 E> */ B(StaNamedPropertySloppy), R(arg0), U8(0), U8(192),
  /* 1348 S> */ B(LdaSmi), I8(1),
  /* 1355 E> */ B(StaNamedPropertySloppy), R(arg0), U8(0), U8(194),
  /* 1362 S> */ B(LdaSmi), I8(1),
  /* 1369 E> */ B(StaNamedPropertySloppy), R(arg0), U8(0), U8(196),
  /* 1376 S> */ B(LdaSmi), I8(1),
  /* 1383 E> */ B(StaNamedPropertySloppy), R(arg0), U8(0), U8(198),
  /* 1390 S> */ B(LdaSmi), I8(1),
  /* 1397 E> */ B(StaNamedPropertySloppy), R(arg0), U8(0), U8(200),
  /* 1404 S> */ B(LdaSmi), I8(1),
  /* 1411 E> */ B(StaNamedPropertySloppy), R(arg0), U8(0), U8(202),
  /* 1418 S> */ B(LdaSmi), I8(1),
  /* 1425 E> */ B(StaNamedPropertySloppy), R(arg0), U8(0), U8(204),
  /* 1432 S> */ B(LdaSmi), I8(1),
  /* 1439 E> */ B(StaNamedPropertySloppy), R(arg0), U8(0), U8(206),
  /* 1446 S> */ B(LdaSmi), I8(1),
  /* 1453 E> */ B(StaNamedPropertySloppy), R(arg0), U8(0), U8(208),
  /* 1460 S> */ B(LdaSmi), I8(1),
  /* 1467 E> */ B(StaNamedPropertySloppy), R(arg0), U8(0), U8(210),
  /* 1474 S> */ B(LdaSmi), I8(1),
  /* 1481 E> */ B(StaNamedPropertySloppy), R(arg0), U8(0), U8(212),
  /* 1488 S> */ B(LdaSmi), I8(1),
  /* 1495 E> */ B(StaNamedPropertySloppy), R(arg0), U8(0), U8(214),
  /* 1502 S> */ B(LdaSmi), I8(1),
  /* 1509 E> */ B(StaNamedPropertySloppy), R(arg0), U8(0), U8(216),
  /* 1516 S> */ B(LdaSmi), I8(1),
  /* 1523 E> */ B(StaNamedPropertySloppy), R(arg0), U8(0), U8(218),
  /* 1530 S> */ B(LdaSmi), I8(1),
  /* 1537 E> */ B(StaNamedPropertySloppy), R(arg0), U8(0), U8(220),
  /* 1544 S> */ B(LdaSmi), I8(1),
  /* 1551 E> */ B(StaNamedPropertySloppy), R(arg0), U8(0), U8(222),
  /* 1558 S> */ B(LdaSmi), I8(1),
  /* 1565 E> */ B(StaNamedPropertySloppy), R(arg0), U8(0), U8(224),
  /* 1572 S> */ B(LdaSmi), I8(1),
  /* 1579 E> */ B(StaNamedPropertySloppy), R(arg0), U8(0), U8(226),
  /* 1586 S> */ B(LdaSmi), I8(1),
  /* 1593 E> */ B(StaNamedPropertySloppy), R(arg0), U8(0), U8(228),
  /* 1600 S> */ B(LdaSmi), I8(1),
  /* 1607 E> */ B(StaNamedPropertySloppy), R(arg0), U8(0), U8(230),
  /* 1614 S> */ B(LdaSmi), I8(1),
  /* 1621 E> */ B(StaNamedPropertySloppy), R(arg0), U8(0), U8(232),
  /* 1628 S> */ B(LdaSmi), I8(1),
  /* 1635 E> */ B(StaNamedPropertySloppy), R(arg0), U8(0), U8(234),
  /* 1642 S> */ B(LdaSmi), I8(1),
  /* 1649 E> */ B(StaNamedPropertySloppy), R(arg0), U8(0), U8(236),
  /* 1656 S> */ B(LdaSmi), I8(1),
  /* 1663 E> */ B(StaNamedPropertySloppy), R(arg0), U8(0), U8(238),
  /* 1670 S> */ B(LdaSmi), I8(1),
  /* 1677 E> */ B(StaNamedPropertySloppy), R(arg0), U8(0), U8(240),
  /* 1684 S> */ B(LdaSmi), I8(1),
  /* 1691 E> */ B(StaNamedPropertySloppy), R(arg0), U8(0), U8(242),
  /* 1698 S> */ B(LdaSmi), I8(1),
  /* 1705 E> */ B(StaNamedPropertySloppy), R(arg0), U8(0), U8(244),
  /* 1712 S> */ B(LdaSmi), I8(1),
  /* 1719 E> */ B(StaNamedPropertySloppy), R(arg0), U8(0), U8(246),
  /* 1726 S> */ B(LdaSmi), I8(1),
  /* 1733 E> */ B(StaNamedPropertySloppy), R(arg0), U8(0), U8(248),
  /* 1740 S> */ B(LdaSmi), I8(1),
  /* 1747 E> */ B(StaNamedPropertySloppy), R(arg0), U8(0), U8(250),
  /* 1754 S> */ B(LdaSmi), I8(1),
  /* 1761 E> */ B(StaNamedPropertySloppy), R(arg0), U8(0), U8(252),
  /* 1768 S> */ B(LdaSmi), I8(1),
  /* 1775 E> */ B(StaNamedPropertySloppy), R(arg0), U8(0), U8(254),
  /* 1782 S> */ B(LdaSmi), I8(1),
  /* 1789 E> */ B(Wide), B(StaNamedPropertySloppy), R16(arg0), U16(0), U16(256),
  /* 1796 S> */ B(LdaSmi), I8(1),
  /* 1803 E> */ B(Wide), B(StaNamedPropertySloppy), R16(arg0), U16(0), U16(258),
  /* 1810 S> */ B(LdaSmi), I8(2),
  /* 1817 E> */ B(Wide), B(StaNamedPropertySloppy), R16(arg0), U16(0), U16(260),
                B(LdaUndefined),
  /* 1822 S> */ B(Return),
]
constant pool: [
  ONE_BYTE_INTERNALIZED_STRING_TYPE ["name"],
]
handlers: [
]

---
snippet: "
  function f(a) {
   'use strict';
    a.name = 1;
    a.name = 1;
    a.name = 1;
    a.name = 1;
    a.name = 1;
    a.name = 1;
    a.name = 1;
    a.name = 1;
    a.name = 1;
    a.name = 1;
    a.name = 1;
    a.name = 1;
    a.name = 1;
    a.name = 1;
    a.name = 1;
    a.name = 1;
    a.name = 1;
    a.name = 1;
    a.name = 1;
    a.name = 1;
    a.name = 1;
    a.name = 1;
    a.name = 1;
    a.name = 1;
    a.name = 1;
    a.name = 1;
    a.name = 1;
    a.name = 1;
    a.name = 1;
    a.name = 1;
    a.name = 1;
    a.name = 1;
    a.name = 1;
    a.name = 1;
    a.name = 1;
    a.name = 1;
    a.name = 1;
    a.name = 1;
    a.name = 1;
    a.name = 1;
    a.name = 1;
    a.name = 1;
    a.name = 1;
    a.name = 1;
    a.name = 1;
    a.name = 1;
    a.name = 1;
    a.name = 1;
    a.name = 1;
    a.name = 1;
    a.name = 1;
    a.name = 1;
    a.name = 1;
    a.name = 1;
    a.name = 1;
    a.name = 1;
    a.name = 1;
    a.name = 1;
    a.name = 1;
    a.name = 1;
    a.name = 1;
    a.name = 1;
    a.name = 1;
    a.name = 1;
    a.name = 1;
    a.name = 1;
    a.name = 1;
    a.name = 1;
    a.name = 1;
    a.name = 1;
    a.name = 1;
    a.name = 1;
    a.name = 1;
    a.name = 1;
    a.name = 1;
    a.name = 1;
    a.name = 1;
    a.name = 1;
    a.name = 1;
    a.name = 1;
    a.name = 1;
    a.name = 1;
    a.name = 1;
    a.name = 1;
    a.name = 1;
    a.name = 1;
    a.name = 1;
    a.name = 1;
    a.name = 1;
    a.name = 1;
    a.name = 1;
    a.name = 1;
    a.name = 1;
    a.name = 1;
    a.name = 1;
    a.name = 1;
    a.name = 1;
    a.name = 1;
    a.name = 1;
    a.name = 1;
    a.name = 1;
    a.name = 1;
    a.name = 1;
    a.name = 1;
    a.name = 1;
    a.name = 1;
    a.name = 1;
    a.name = 1;
    a.name = 1;
    a.name = 1;
    a.name = 1;
    a.name = 1;
    a.name = 1;
    a.name = 1;
    a.name = 1;
    a.name = 1;
    a.name = 1;
    a.name = 1;
    a.name = 1;
    a.name = 1;
    a.name = 1;
    a.name = 1;
    a.name = 1;
    a.name = 1;
    a.name = 1;
    a.name = 1;
    a.name = 1;
    a.name = 1;
    a.name = 2;
  }
  f({name : \"test\"})
"
frame size: 0
parameter count: 2
bytecode array length: 789
bytecodes: [
  /*   10 E> */ B(StackCheck),
  /*   33 S> */ B(LdaSmi), I8(1),
  /*   40 E> */ B(StaNamedPropertyStrict), R(arg0), U8(0), U8(4),
  /*   47 S> */ B(LdaSmi), I8(1),
  /*   54 E> */ B(StaNamedPropertyStrict), R(arg0), U8(0), U8(6),
  /*   61 S> */ B(LdaSmi), I8(1),
  /*   68 E> */ B(StaNamedPropertyStrict), R(arg0), U8(0), U8(8),
  /*   75 S> */ B(LdaSmi), I8(1),
  /*   82 E> */ B(StaNamedPropertyStrict), R(arg0), U8(0), U8(10),
  /*   89 S> */ B(LdaSmi), I8(1),
  /*   96 E> */ B(StaNamedPropertyStrict), R(arg0), U8(0), U8(12),
  /*  103 S> */ B(LdaSmi), I8(1),
  /*  110 E> */ B(StaNamedPropertyStrict), R(arg0), U8(0), U8(14),
  /*  117 S> */ B(LdaSmi), I8(1),
  /*  124 E> */ B(StaNamedPropertyStrict), R(arg0), U8(0), U8(16),
  /*  131 S> */ B(LdaSmi), I8(1),
  /*  138 E> */ B(StaNamedPropertyStrict), R(arg0), U8(0), U8(18),
  /*  145 S> */ B(LdaSmi), I8(1),
  /*  152 E> */ B(StaNamedPropertyStrict), R(arg0), U8(0), U8(20),
  /*  159 S> */ B(LdaSmi), I8(1),
  /*  166 E> */ B(StaNamedPropertyStrict), R(arg0), U8(0), U8(22),
  /*  173 S> */ B(LdaSmi), I8(1),
  /*  180 E> */ B(StaNamedPropertyStrict), R(arg0), U8(0), U8(24),
  /*  187 S> */ B(LdaSmi), I8(1),
  /*  194 E> */ B(StaNamedPropertyStrict), R(arg0), U8(0), U8(26),
  /*  201 S> */ B(LdaSmi), I8(1),
  /*  208 E> */ B(StaNamedPropertyStrict), R(arg0), U8(0), U8(28),
  /*  215 S> */ B(LdaSmi), I8(1),
  /*  222 E> */ B(StaNamedPropertyStrict), R(arg0), U8(0), U8(30),
  /*  229 S> */ B(LdaSmi), I8(1),
  /*  236 E> */ B(StaNamedPropertyStrict), R(arg0), U8(0), U8(32),
  /*  243 S> */ B(LdaSmi), I8(1),
  /*  250 E> */ B(StaNamedPropertyStrict), R(arg0), U8(0), U8(34),
  /*  257 S> */ B(LdaSmi), I8(1),
  /*  264 E> */ B(StaNamedPropertyStrict), R(arg0), U8(0), U8(36),
  /*  271 S> */ B(LdaSmi), I8(1),
  /*  278 E> */ B(StaNamedPropertyStrict), R(arg0), U8(0), U8(38),
  /*  285 S> */ B(LdaSmi), I8(1),
  /*  292 E> */ B(StaNamedPropertyStrict), R(arg0), U8(0), U8(40),
  /*  299 S> */ B(LdaSmi), I8(1),
  /*  306 E> */ B(StaNamedPropertyStrict), R(arg0), U8(0), U8(42),
  /*  313 S> */ B(LdaSmi), I8(1),
  /*  320 E> */ B(StaNamedPropertyStrict), R(arg0), U8(0), U8(44),
  /*  327 S> */ B(LdaSmi), I8(1),
  /*  334 E> */ B(StaNamedPropertyStrict), R(arg0), U8(0), U8(46),
  /*  341 S> */ B(LdaSmi), I8(1),
  /*  348 E> */ B(StaNamedPropertyStrict), R(arg0), U8(0), U8(48),
  /*  355 S> */ B(LdaSmi), I8(1),
  /*  362 E> */ B(StaNamedPropertyStrict), R(arg0), U8(0), U8(50),
  /*  369 S> */ B(LdaSmi), I8(1),
  /*  376 E> */ B(StaNamedPropertyStrict), R(arg0), U8(0), U8(52),
  /*  383 S> */ B(LdaSmi), I8(1),
  /*  390 E> */ B(StaNamedPropertyStrict), R(arg0), U8(0), U8(54),
  /*  397 S> */ B(LdaSmi), I8(1),
  /*  404 E> */ B(StaNamedPropertyStrict), R(arg0), U8(0), U8(56),
  /*  411 S> */ B(LdaSmi), I8(1),
  /*  418 E> */ B(StaNamedPropertyStrict), R(arg0), U8(0), U8(58),
  /*  425 S> */ B(LdaSmi), I8(1),
  /*  432 E> */ B(StaNamedPropertyStrict), R(arg0), U8(0), U8(60),
  /*  439 S> */ B(LdaSmi), I8(1),
  /*  446 E> */ B(StaNamedPropertyStrict), R(arg0), U8(0), U8(62),
  /*  453 S> */ B(LdaSmi), I8(1),
  /*  460 E> */ B(StaNamedPropertyStrict), R(arg0), U8(0), U8(64),
  /*  467 S> */ B(LdaSmi), I8(1),
  /*  474 E> */ B(StaNamedPropertyStrict), R(arg0), U8(0), U8(66),
  /*  481 S> */ B(LdaSmi), I8(1),
  /*  488 E> */ B(StaNamedPropertyStrict), R(arg0), U8(0), U8(68),
  /*  495 S> */ B(LdaSmi), I8(1),
  /*  502 E> */ B(StaNamedPropertyStrict), R(arg0), U8(0), U8(70),
  /*  509 S> */ B(LdaSmi), I8(1),
  /*  516 E> */ B(StaNamedPropertyStrict), R(arg0), U8(0), U8(72),
  /*  523 S> */ B(LdaSmi), I8(1),
  /*  530 E> */ B(StaNamedPropertyStrict), R(arg0), U8(0), U8(74),
  /*  537 S> */ B(LdaSmi), I8(1),
  /*  544 E> */ B(StaNamedPropertyStrict), R(arg0), U8(0), U8(76),
  /*  551 S> */ B(LdaSmi), I8(1),
  /*  558 E> */ B(StaNamedPropertyStrict), R(arg0), U8(0), U8(78),
  /*  565 S> */ B(LdaSmi), I8(1),
  /*  572 E> */ B(StaNamedPropertyStrict), R(arg0), U8(0), U8(80),
  /*  579 S> */ B(LdaSmi), I8(1),
  /*  586 E> */ B(StaNamedPropertyStrict), R(arg0), U8(0), U8(82),
  /*  593 S> */ B(LdaSmi), I8(1),
  /*  600 E> */ B(StaNamedPropertyStrict), R(arg0), U8(0), U8(84),
  /*  607 S> */ B(LdaSmi), I8(1),
  /*  614 E> */ B(StaNamedPropertyStrict), R(arg0), U8(0), U8(86),
  /*  621 S> */ B(LdaSmi), I8(1),
  /*  628 E> */ B(StaNamedPropertyStrict), R(arg0), U8(0), U8(88),
  /*  635 S> */ B(LdaSmi), I8(1),
  /*  642 E> */ B(StaNamedPropertyStrict), R(arg0), U8(0), U8(90),
  /*  649 S> */ B(LdaSmi), I8(1),
  /*  656 E> */ B(StaNamedPropertyStrict), R(arg0), U8(0), U8(92),
  /*  663 S> */ B(LdaSmi), I8(1),
  /*  670 E> */ B(StaNamedPropertyStrict), R(arg0), U8(0), U8(94),
  /*  677 S> */ B(LdaSmi), I8(1),
  /*  684 E> */ B(StaNamedPropertyStrict), R(arg0), U8(0), U8(96),
  /*  691 S> */ B(LdaSmi), I8(1),
  /*  698 E> */ B(StaNamedPropertyStrict), R(arg0), U8(0), U8(98),
  /*  705 S> */ B(LdaSmi), I8(1),
  /*  712 E> */ B(StaNamedPropertyStrict), R(arg0), U8(0), U8(100),
  /*  719 S> */ B(LdaSmi), I8(1),
  /*  726 E> */ B(StaNamedPropertyStrict), R(arg0), U8(0), U8(102),
  /*  733 S> */ B(LdaSmi), I8(1),
  /*  740 E> */ B(StaNamedPropertyStrict), R(arg0), U8(0), U8(104),
  /*  747 S> */ B(LdaSmi), I8(1),
  /*  754 E> */ B(StaNamedPropertyStrict), R(arg0), U8(0), U8(106),
  /*  761 S> */ B(LdaSmi), I8(1),
  /*  768 E> */ B(StaNamedPropertyStrict), R(arg0), U8(0), U8(108),
  /*  775 S> */ B(LdaSmi), I8(1),
  /*  782 E> */ B(StaNamedPropertyStrict), R(arg0), U8(0), U8(110),
  /*  789 S> */ B(LdaSmi), I8(1),
  /*  796 E> */ B(StaNamedPropertyStrict), R(arg0), U8(0), U8(112),
  /*  803 S> */ B(LdaSmi), I8(1),
  /*  810 E> */ B(StaNamedPropertyStrict), R(arg0), U8(0), U8(114),
  /*  817 S> */ B(LdaSmi), I8(1),
  /*  824 E> */ B(StaNamedPropertyStrict), R(arg0), U8(0), U8(116),
  /*  831 S> */ B(LdaSmi), I8(1),
  /*  838 E> */ B(StaNamedPropertyStrict), R(arg0), U8(0), U8(118),
  /*  845 S> */ B(LdaSmi), I8(1),
  /*  852 E> */ B(StaNamedPropertyStrict), R(arg0), U8(0), U8(120),
  /*  859 S> */ B(LdaSmi), I8(1),
  /*  866 E> */ B(StaNamedPropertyStrict), R(arg0), U8(0), U8(122),
  /*  873 S> */ B(LdaSmi), I8(1),
  /*  880 E> */ B(StaNamedPropertyStrict), R(arg0), U8(0), U8(124),
  /*  887 S> */ B(LdaSmi), I8(1),
  /*  894 E> */ B(StaNamedPropertyStrict), R(arg0), U8(0), U8(126),
  /*  901 S> */ B(LdaSmi), I8(1),
  /*  908 E> */ B(StaNamedPropertyStrict), R(arg0), U8(0), U8(128),
  /*  915 S> */ B(LdaSmi), I8(1),
  /*  922 E> */ B(StaNamedPropertyStrict), R(arg0), U8(0), U8(130),
  /*  929 S> */ B(LdaSmi), I8(1),
  /*  936 E> */ B(StaNamedPropertyStrict), R(arg0), U8(0), U8(132),
  /*  943 S> */ B(LdaSmi), I8(1),
  /*  950 E> */ B(StaNamedPropertyStrict), R(arg0), U8(0), U8(134),
  /*  957 S> */ B(LdaSmi), I8(1),
  /*  964 E> */ B(StaNamedPropertyStrict), R(arg0), U8(0), U8(136),
  /*  971 S> */ B(LdaSmi), I8(1),
  /*  978 E> */ B(StaNamedPropertyStrict), R(arg0), U8(0), U8(138),
  /*  985 S> */ B(LdaSmi), I8(1),
  /*  992 E> */ B(StaNamedPropertyStrict), R(arg0), U8(0), U8(140),
  /*  999 S> */ B(LdaSmi), I8(1),
  /* 1006 E> */ B(StaNamedPropertyStrict), R(arg0), U8(0), U8(142),
  /* 1013 S> */ B(LdaSmi), I8(1),
  /* 1020 E> */ B(StaNamedPropertyStrict), R(arg0), U8(0), U8(144),
  /* 1027 S> */ B(LdaSmi), I8(1),
  /* 1034 E> */ B(StaNamedPropertyStrict), R(arg0), U8(0), U8(146),
  /* 1041 S> */ B(LdaSmi), I8(1),
  /* 1048 E> */ B(StaNamedPropertyStrict), R(arg0), U8(0), U8(148),
  /* 1055 S> */ B(LdaSmi), I8(1),
  /* 1062 E> */ B(StaNamedPropertyStrict), R(arg0), U8(0), U8(150),
  /* 1069 S> */ B(LdaSmi), I8(1),
  /* 1076 E> */ B(StaNamedPropertyStrict), R(arg0), U8(0), U8(152),
  /* 1083 S> */ B(LdaSmi), I8(1),
  /* 1090 E> */ B(StaNamedPropertyStrict), R(arg0), U8(0), U8(154),
  /* 1097 S> */ B(LdaSmi), I8(1),
  /* 1104 E> */ B(StaNamedPropertyStrict), R(arg0), U8(0), U8(156),
  /* 1111 S> */ B(LdaSmi), I8(1),
  /* 1118 E> */ B(StaNamedPropertyStrict), R(arg0), U8(0), U8(158),
  /* 1125 S> */ B(LdaSmi), I8(1),
  /* 1132 E> */ B(StaNamedPropertyStrict), R(arg0), U8(0), U8(160),
  /* 1139 S> */ B(LdaSmi), I8(1),
  /* 1146 E> */ B(StaNamedPropertyStrict), R(arg0), U8(0), U8(162),
  /* 1153 S> */ B(LdaSmi), I8(1),
  /* 1160 E> */ B(StaNamedPropertyStrict), R(arg0), U8(0), U8(164),
  /* 1167 S> */ B(LdaSmi), I8(1),
  /* 1174 E> */ B(StaNamedPropertyStrict), R(arg0), U8(0), U8(166),
  /* 1181 S> */ B(LdaSmi), I8(1),
  /* 1188 E> */ B(StaNamedPropertyStrict), R(arg0), U8(0), U8(168),
  /* 1195 S> */ B(LdaSmi), I8(1),
  /* 1202 E> */ B(StaNamedPropertyStrict), R(arg0), U8(0), U8(170),
  /* 1209 S> */ B(LdaSmi), I8(1),
  /* 1216 E> */ B(StaNamedPropertyStrict), R(arg0), U8(0), U8(172),
  /* 1223 S> */ B(LdaSmi), I8(1),
  /* 1230 E> */ B(StaNamedPropertyStrict), R(arg0), U8(0), U8(174),
  /* 1237 S> */ B(LdaSmi), I8(1),
  /* 1244 E> */ B(StaNamedPropertyStrict), R(arg0), U8(0), U8(176),
  /* 1251 S> */ B(LdaSmi), I8(1),
  /* 1258 E> */ B(StaNamedPropertyStrict), R(arg0), U8(0), U8(178),
  /* 1265 S> */ B(LdaSmi), I8(1),
  /* 1272 E> */ B(StaNamedPropertyStrict), R(arg0), U8(0), U8(180),
  /* 1279 S> */ B(LdaSmi), I8(1),
  /* 1286 E> */ B(StaNamedPropertyStrict), R(arg0), U8(0), U8(182),
  /* 1293 S> */ B(LdaSmi), I8(1),
  /* 1300 E> */ B(StaNamedPropertyStrict), R(arg0), U8(0), U8(184),
  /* 1307 S> */ B(LdaSmi), I8(1),
  /* 1314 E> */ B(StaNamedPropertyStrict), R(arg0), U8(0), U8(186),
  /* 1321 S> */ B(LdaSmi), I8(1),
  /* 1328 E> */ B(StaNamedPropertyStrict), R(arg0), U8(0), U8(188),
  /* 1335 S> */ B(LdaSmi), I8(1),
  /* 1342 E> */ B(StaNamedPropertyStrict), R(arg0), U8(0), U8(190),
  /* 1349 S> */ B(LdaSmi), I8(1),
  /* 1356 E> */ B(StaNamedPropertyStrict), R(arg0), U8(0), U8(192),
  /* 1363 S> */ B(LdaSmi), I8(1),
  /* 1370 E> */ B(StaNamedPropertyStrict), R(arg0), U8(0), U8(194),
  /* 1377 S> */ B(LdaSmi), I8(1),
  /* 1384 E> */ B(StaNamedPropertyStrict), R(arg0), U8(0), U8(196),
  /* 1391 S> */ B(LdaSmi), I8(1),
  /* 1398 E> */ B(StaNamedPropertyStrict), R(arg0), U8(0), U8(198),
  /* 1405 S> */ B(LdaSmi), I8(1),
  /* 1412 E> */ B(StaNamedPropertyStrict), R(arg0), U8(0), U8(200),
  /* 1419 S> */ B(LdaSmi), I8(1),
  /* 1426 E> */ B(StaNamedPropertyStrict), R(arg0), U8(0), U8(202),
  /* 1433 S> */ B(LdaSmi), I8(1),
  /* 1440 E> */ B(StaNamedPropertyStrict), R(arg0), U8(0), U8(204),
  /* 1447 S> */ B(LdaSmi), I8(1),
  /* 1454 E> */ B(StaNamedPropertyStrict), R(arg0), U8(0), U8(206),
  /* 1461 S> */ B(LdaSmi), I8(1),
  /* 1468 E> */ B(StaNamedPropertyStrict), R(arg0), U8(0), U8(208),
  /* 1475 S> */ B(LdaSmi), I8(1),
  /* 1482 E> */ B(StaNamedPropertyStrict), R(arg0), U8(0), U8(210),
  /* 1489 S> */ B(LdaSmi), I8(1),
  /* 1496 E> */ B(StaNamedPropertyStrict), R(arg0), U8(0), U8(212),
  /* 1503 S> */ B(LdaSmi), I8(1),
  /* 1510 E> */ B(StaNamedPropertyStrict), R(arg0), U8(0), U8(214),
  /* 1517 S> */ B(LdaSmi), I8(1),
  /* 1524 E> */ B(StaNamedPropertyStrict), R(arg0), U8(0), U8(216),
  /* 1531 S> */ B(LdaSmi), I8(1),
  /* 1538 E> */ B(StaNamedPropertyStrict), R(arg0), U8(0), U8(218),
  /* 1545 S> */ B(LdaSmi), I8(1),
  /* 1552 E> */ B(StaNamedPropertyStrict), R(arg0), U8(0), U8(220),
  /* 1559 S> */ B(LdaSmi), I8(1),
  /* 1566 E> */ B(StaNamedPropertyStrict), R(arg0), U8(0), U8(222),
  /* 1573 S> */ B(LdaSmi), I8(1),
  /* 1580 E> */ B(StaNamedPropertyStrict), R(arg0), U8(0), U8(224),
  /* 1587 S> */ B(LdaSmi), I8(1),
  /* 1594 E> */ B(StaNamedPropertyStrict), R(arg0), U8(0), U8(226),
  /* 1601 S> */ B(LdaSmi), I8(1),
  /* 1608 E> */ B(StaNamedPropertyStrict), R(arg0), U8(0), U8(228),
  /* 1615 S> */ B(LdaSmi), I8(1),
  /* 1622 E> */ B(StaNamedPropertyStrict), R(arg0), U8(0), U8(230),
  /* 1629 S> */ B(LdaSmi), I8(1),
  /* 1636 E> */ B(StaNamedPropertyStrict), R(arg0), U8(0), U8(232),
  /* 1643 S> */ B(LdaSmi), I8(1),
  /* 1650 E> */ B(StaNamedPropertyStrict), R(arg0), U8(0), U8(234),
  /* 1657 S> */ B(LdaSmi), I8(1),
  /* 1664 E> */ B(StaNamedPropertyStrict), R(arg0), U8(0), U8(236),
  /* 1671 S> */ B(LdaSmi), I8(1),
  /* 1678 E> */ B(StaNamedPropertyStrict), R(arg0), U8(0), U8(238),
  /* 1685 S> */ B(LdaSmi), I8(1),
  /* 1692 E> */ B(StaNamedPropertyStrict), R(arg0), U8(0), U8(240),
  /* 1699 S> */ B(LdaSmi), I8(1),
  /* 1706 E> */ B(StaNamedPropertyStrict), R(arg0), U8(0), U8(242),
  /* 1713 S> */ B(LdaSmi), I8(1),
  /* 1720 E> */ B(StaNamedPropertyStrict), R(arg0), U8(0), U8(244),
  /* 1727 S> */ B(LdaSmi), I8(1),
  /* 1734 E> */ B(StaNamedPropertyStrict), R(arg0), U8(0), U8(246),
  /* 1741 S> */ B(LdaSmi), I8(1),
  /* 1748 E> */ B(StaNamedPropertyStrict), R(arg0), U8(0), U8(248),
  /* 1755 S> */ B(LdaSmi), I8(1),
  /* 1762 E> */ B(StaNamedPropertyStrict), R(arg0), U8(0), U8(250),
  /* 1769 S> */ B(LdaSmi), I8(1),
  /* 1776 E> */ B(StaNamedPropertyStrict), R(arg0), U8(0), U8(252),
  /* 1783 S> */ B(LdaSmi), I8(1),
  /* 1790 E> */ B(StaNamedPropertyStrict), R(arg0), U8(0), U8(254),
  /* 1797 S> */ B(LdaSmi), I8(1),
  /* 1804 E> */ B(Wide), B(StaNamedPropertyStrict), R16(arg0), U16(0), U16(256),
  /* 1811 S> */ B(LdaSmi), I8(1),
  /* 1818 E> */ B(Wide), B(StaNamedPropertyStrict), R16(arg0), U16(0), U16(258),
  /* 1825 S> */ B(LdaSmi), I8(2),
  /* 1832 E> */ B(Wide), B(StaNamedPropertyStrict), R16(arg0), U16(0), U16(260),
                B(LdaUndefined),
  /* 1837 S> */ B(Return),
]
constant pool: [
  ONE_BYTE_INTERNALIZED_STRING_TYPE ["name"],
]
handlers: [
]

---
snippet: "
  function f(a, b) {
    a[b] = 1;
    a[b] = 1;
    a[b] = 1;
    a[b] = 1;
    a[b] = 1;
    a[b] = 1;
    a[b] = 1;
    a[b] = 1;
    a[b] = 1;
    a[b] = 1;
    a[b] = 1;
    a[b] = 1;
    a[b] = 1;
    a[b] = 1;
    a[b] = 1;
    a[b] = 1;
    a[b] = 1;
    a[b] = 1;
    a[b] = 1;
    a[b] = 1;
    a[b] = 1;
    a[b] = 1;
    a[b] = 1;
    a[b] = 1;
    a[b] = 1;
    a[b] = 1;
    a[b] = 1;
    a[b] = 1;
    a[b] = 1;
    a[b] = 1;
    a[b] = 1;
    a[b] = 1;
    a[b] = 1;
    a[b] = 1;
    a[b] = 1;
    a[b] = 1;
    a[b] = 1;
    a[b] = 1;
    a[b] = 1;
    a[b] = 1;
    a[b] = 1;
    a[b] = 1;
    a[b] = 1;
    a[b] = 1;
    a[b] = 1;
    a[b] = 1;
    a[b] = 1;
    a[b] = 1;
    a[b] = 1;
    a[b] = 1;
    a[b] = 1;
    a[b] = 1;
    a[b] = 1;
    a[b] = 1;
    a[b] = 1;
    a[b] = 1;
    a[b] = 1;
    a[b] = 1;
    a[b] = 1;
    a[b] = 1;
    a[b] = 1;
    a[b] = 1;
    a[b] = 1;
    a[b] = 1;
    a[b] = 1;
    a[b] = 1;
    a[b] = 1;
    a[b] = 1;
    a[b] = 1;
    a[b] = 1;
    a[b] = 1;
    a[b] = 1;
    a[b] = 1;
    a[b] = 1;
    a[b] = 1;
    a[b] = 1;
    a[b] = 1;
    a[b] = 1;
    a[b] = 1;
    a[b] = 1;
    a[b] = 1;
    a[b] = 1;
    a[b] = 1;
    a[b] = 1;
    a[b] = 1;
    a[b] = 1;
    a[b] = 1;
    a[b] = 1;
    a[b] = 1;
    a[b] = 1;
    a[b] = 1;
    a[b] = 1;
    a[b] = 1;
    a[b] = 1;
    a[b] = 1;
    a[b] = 1;
    a[b] = 1;
    a[b] = 1;
    a[b] = 1;
    a[b] = 1;
    a[b] = 1;
    a[b] = 1;
    a[b] = 1;
    a[b] = 1;
    a[b] = 1;
    a[b] = 1;
    a[b] = 1;
    a[b] = 1;
    a[b] = 1;
    a[b] = 1;
    a[b] = 1;
    a[b] = 1;
    a[b] = 1;
    a[b] = 1;
    a[b] = 1;
    a[b] = 1;
    a[b] = 1;
    a[b] = 1;
    a[b] = 1;
    a[b] = 1;
    a[b] = 1;
    a[b] = 1;
    a[b] = 1;
    a[b] = 1;
    a[b] = 1;
    a[b] = 1;
    a[b] = 1;
    a[b] = 1;
    a[b] = 2;
  }
  f({name : \"test\"})
"
frame size: 0
parameter count: 3
bytecode array length: 789
bytecodes: [
  /*   10 E> */ B(StackCheck),
  /*   21 S> */ B(LdaSmi), I8(1),
  /*   26 E> */ B(StaKeyedPropertySloppy), R(arg0), R(arg1), U8(4),
  /*   33 S> */ B(LdaSmi), I8(1),
  /*   38 E> */ B(StaKeyedPropertySloppy), R(arg0), R(arg1), U8(6),
  /*   45 S> */ B(LdaSmi), I8(1),
  /*   50 E> */ B(StaKeyedPropertySloppy), R(arg0), R(arg1), U8(8),
  /*   57 S> */ B(LdaSmi), I8(1),
  /*   62 E> */ B(StaKeyedPropertySloppy), R(arg0), R(arg1), U8(10),
  /*   69 S> */ B(LdaSmi), I8(1),
  /*   74 E> */ B(StaKeyedPropertySloppy), R(arg0), R(arg1), U8(12),
  /*   81 S> */ B(LdaSmi), I8(1),
  /*   86 E> */ B(StaKeyedPropertySloppy), R(arg0), R(arg1), U8(14),
  /*   93 S> */ B(LdaSmi), I8(1),
  /*   98 E> */ B(StaKeyedPropertySloppy), R(arg0), R(arg1), U8(16),
  /*  105 S> */ B(LdaSmi), I8(1),
  /*  110 E> */ B(StaKeyedPropertySloppy), R(arg0), R(arg1), U8(18),
  /*  117 S> */ B(LdaSmi), I8(1),
  /*  122 E> */ B(StaKeyedPropertySloppy), R(arg0), R(arg1), U8(20),
  /*  129 S> */ B(LdaSmi), I8(1),
  /*  134 E> */ B(StaKeyedPropertySloppy), R(arg0), R(arg1), U8(22),
  /*  141 S> */ B(LdaSmi), I8(1),
  /*  146 E> */ B(StaKeyedPropertySloppy), R(arg0), R(arg1), U8(24),
  /*  153 S> */ B(LdaSmi), I8(1),
  /*  158 E> */ B(StaKeyedPropertySloppy), R(arg0), R(arg1), U8(26),
  /*  165 S> */ B(LdaSmi), I8(1),
  /*  170 E> */ B(StaKeyedPropertySloppy), R(arg0), R(arg1), U8(28),
  /*  177 S> */ B(LdaSmi), I8(1),
  /*  182 E> */ B(StaKeyedPropertySloppy), R(arg0), R(arg1), U8(30),
  /*  189 S> */ B(LdaSmi), I8(1),
  /*  194 E> */ B(StaKeyedPropertySloppy), R(arg0), R(arg1), U8(32),
  /*  201 S> */ B(LdaSmi), I8(1),
  /*  206 E> */ B(StaKeyedPropertySloppy), R(arg0), R(arg1), U8(34),
  /*  213 S> */ B(LdaSmi), I8(1),
  /*  218 E> */ B(StaKeyedPropertySloppy), R(arg0), R(arg1), U8(36),
  /*  225 S> */ B(LdaSmi), I8(1),
  /*  230 E> */ B(StaKeyedPropertySloppy), R(arg0), R(arg1), U8(38),
  /*  237 S> */ B(LdaSmi), I8(1),
  /*  242 E> */ B(StaKeyedPropertySloppy), R(arg0), R(arg1), U8(40),
  /*  249 S> */ B(LdaSmi), I8(1),
  /*  254 E> */ B(StaKeyedPropertySloppy), R(arg0), R(arg1), U8(42),
  /*  261 S> */ B(LdaSmi), I8(1),
  /*  266 E> */ B(StaKeyedPropertySloppy), R(arg0), R(arg1), U8(44),
  /*  273 S> */ B(LdaSmi), I8(1),
  /*  278 E> */ B(StaKeyedPropertySloppy), R(arg0), R(arg1), U8(46),
  /*  285 S> */ B(LdaSmi), I8(1),
  /*  290 E> */ B(StaKeyedPropertySloppy), R(arg0), R(arg1), U8(48),
  /*  297 S> */ B(LdaSmi), I8(1),
  /*  302 E> */ B(StaKeyedPropertySloppy), R(arg0), R(arg1), U8(50),
  /*  309 S> */ B(LdaSmi), I8(1),
  /*  314 E> */ B(StaKeyedPropertySloppy), R(arg0), R(arg1), U8(52),
  /*  321 S> */ B(LdaSmi), I8(1),
  /*  326 E> */ B(StaKeyedPropertySloppy), R(arg0), R(arg1), U8(54),
  /*  333 S> */ B(LdaSmi), I8(1),
  /*  338 E> */ B(StaKeyedPropertySloppy), R(arg0), R(arg1), U8(56),
  /*  345 S> */ B(LdaSmi), I8(1),
  /*  350 E> */ B(StaKeyedPropertySloppy), R(arg0), R(arg1), U8(58),
  /*  357 S> */ B(LdaSmi), I8(1),
  /*  362 E> */ B(StaKeyedPropertySloppy), R(arg0), R(arg1), U8(60),
  /*  369 S> */ B(LdaSmi), I8(1),
  /*  374 E> */ B(StaKeyedPropertySloppy), R(arg0), R(arg1), U8(62),
  /*  381 S> */ B(LdaSmi), I8(1),
  /*  386 E> */ B(StaKeyedPropertySloppy), R(arg0), R(arg1), U8(64),
  /*  393 S> */ B(LdaSmi), I8(1),
  /*  398 E> */ B(StaKeyedPropertySloppy), R(arg0), R(arg1), U8(66),
  /*  405 S> */ B(LdaSmi), I8(1),
  /*  410 E> */ B(StaKeyedPropertySloppy), R(arg0), R(arg1), U8(68),
  /*  417 S> */ B(LdaSmi), I8(1),
  /*  422 E> */ B(StaKeyedPropertySloppy), R(arg0), R(arg1), U8(70),
  /*  429 S> */ B(LdaSmi), I8(1),
  /*  434 E> */ B(StaKeyedPropertySloppy), R(arg0), R(arg1), U8(72),
  /*  441 S> */ B(LdaSmi), I8(1),
  /*  446 E> */ B(StaKeyedPropertySloppy), R(arg0), R(arg1), U8(74),
  /*  453 S> */ B(LdaSmi), I8(1),
  /*  458 E> */ B(StaKeyedPropertySloppy), R(arg0), R(arg1), U8(76),
  /*  465 S> */ B(LdaSmi), I8(1),
  /*  470 E> */ B(StaKeyedPropertySloppy), R(arg0), R(arg1), U8(78),
  /*  477 S> */ B(LdaSmi), I8(1),
  /*  482 E> */ B(StaKeyedPropertySloppy), R(arg0), R(arg1), U8(80),
  /*  489 S> */ B(LdaSmi), I8(1),
  /*  494 E> */ B(StaKeyedPropertySloppy), R(arg0), R(arg1), U8(82),
  /*  501 S> */ B(LdaSmi), I8(1),
  /*  506 E> */ B(StaKeyedPropertySloppy), R(arg0), R(arg1), U8(84),
  /*  513 S> */ B(LdaSmi), I8(1),
  /*  518 E> */ B(StaKeyedPropertySloppy), R(arg0), R(arg1), U8(86),
  /*  525 S> */ B(LdaSmi), I8(1),
  /*  530 E> */ B(StaKeyedPropertySloppy), R(arg0), R(arg1), U8(88),
  /*  537 S> */ B(LdaSmi), I8(1),
  /*  542 E> */ B(StaKeyedPropertySloppy), R(arg0), R(arg1), U8(90),
  /*  549 S> */ B(LdaSmi), I8(1),
  /*  554 E> */ B(StaKeyedPropertySloppy), R(arg0), R(arg1), U8(92),
  /*  561 S> */ B(LdaSmi), I8(1),
  /*  566 E> */ B(StaKeyedPropertySloppy), R(arg0), R(arg1), U8(94),
  /*  573 S> */ B(LdaSmi), I8(1),
  /*  578 E> */ B(StaKeyedPropertySloppy), R(arg0), R(arg1), U8(96),
  /*  585 S> */ B(LdaSmi), I8(1),
  /*  590 E> */ B(StaKeyedPropertySloppy), R(arg0), R(arg1), U8(98),
  /*  597 S> */ B(LdaSmi), I8(1),
  /*  602 E> */ B(StaKeyedPropertySloppy), R(arg0), R(arg1), U8(100),
  /*  609 S> */ B(LdaSmi), I8(1),
  /*  614 E> */ B(StaKeyedPropertySloppy), R(arg0), R(arg1), U8(102),
  /*  621 S> */ B(LdaSmi), I8(1),
  /*  626 E> */ B(StaKeyedPropertySloppy), R(arg0), R(arg1), U8(104),
  /*  633 S> */ B(LdaSmi), I8(1),
  /*  638 E> */ B(StaKeyedPropertySloppy), R(arg0), R(arg1), U8(106),
  /*  645 S> */ B(LdaSmi), I8(1),
  /*  650 E> */ B(StaKeyedPropertySloppy), R(arg0), R(arg1), U8(108),
  /*  657 S> */ B(LdaSmi), I8(1),
  /*  662 E> */ B(StaKeyedPropertySloppy), R(arg0), R(arg1), U8(110),
  /*  669 S> */ B(LdaSmi), I8(1),
  /*  674 E> */ B(StaKeyedPropertySloppy), R(arg0), R(arg1), U8(112),
  /*  681 S> */ B(LdaSmi), I8(1),
  /*  686 E> */ B(StaKeyedPropertySloppy), R(arg0), R(arg1), U8(114),
  /*  693 S> */ B(LdaSmi), I8(1),
  /*  698 E> */ B(StaKeyedPropertySloppy), R(arg0), R(arg1), U8(116),
  /*  705 S> */ B(LdaSmi), I8(1),
  /*  710 E> */ B(StaKeyedPropertySloppy), R(arg0), R(arg1), U8(118),
  /*  717 S> */ B(LdaSmi), I8(1),
  /*  722 E> */ B(StaKeyedPropertySloppy), R(arg0), R(arg1), U8(120),
  /*  729 S> */ B(LdaSmi), I8(1),
  /*  734 E> */ B(StaKeyedPropertySloppy), R(arg0), R(arg1), U8(122),
  /*  741 S> */ B(LdaSmi), I8(1),
  /*  746 E> */ B(StaKeyedPropertySloppy), R(arg0), R(arg1), U8(124),
  /*  753 S> */ B(LdaSmi), I8(1),
  /*  758 E> */ B(StaKeyedPropertySloppy), R(arg0), R(arg1), U8(126),
  /*  765 S> */ B(LdaSmi), I8(1),
  /*  770 E> */ B(StaKeyedPropertySloppy), R(arg0), R(arg1), U8(128),
  /*  777 S> */ B(LdaSmi), I8(1),
  /*  782 E> */ B(StaKeyedPropertySloppy), R(arg0), R(arg1), U8(130),
  /*  789 S> */ B(LdaSmi), I8(1),
  /*  794 E> */ B(StaKeyedPropertySloppy), R(arg0), R(arg1), U8(132),
  /*  801 S> */ B(LdaSmi), I8(1),
  /*  806 E> */ B(StaKeyedPropertySloppy), R(arg0), R(arg1), U8(134),
  /*  813 S> */ B(LdaSmi), I8(1),
  /*  818 E> */ B(StaKeyedPropertySloppy), R(arg0), R(arg1), U8(136),
  /*  825 S> */ B(LdaSmi), I8(1),
  /*  830 E> */ B(StaKeyedPropertySloppy), R(arg0), R(arg1), U8(138),
  /*  837 S> */ B(LdaSmi), I8(1),
  /*  842 E> */ B(StaKeyedPropertySloppy), R(arg0), R(arg1), U8(140),
  /*  849 S> */ B(LdaSmi), I8(1),
  /*  854 E> */ B(StaKeyedPropertySloppy), R(arg0), R(arg1), U8(142),
  /*  861 S> */ B(LdaSmi), I8(1),
  /*  866 E> */ B(StaKeyedPropertySloppy), R(arg0), R(arg1), U8(144),
  /*  873 S> */ B(LdaSmi), I8(1),
  /*  878 E> */ B(StaKeyedPropertySloppy), R(arg0), R(arg1), U8(146),
  /*  885 S> */ B(LdaSmi), I8(1),
  /*  890 E> */ B(StaKeyedPropertySloppy), R(arg0), R(arg1), U8(148),
  /*  897 S> */ B(LdaSmi), I8(1),
  /*  902 E> */ B(StaKeyedPropertySloppy), R(arg0), R(arg1), U8(150),
  /*  909 S> */ B(LdaSmi), I8(1),
  /*  914 E> */ B(StaKeyedPropertySloppy), R(arg0), R(arg1), U8(152),
  /*  921 S> */ B(LdaSmi), I8(1),
  /*  926 E> */ B(StaKeyedPropertySloppy), R(arg0), R(arg1), U8(154),
  /*  933 S> */ B(LdaSmi), I8(1),
  /*  938 E> */ B(StaKeyedPropertySloppy), R(arg0), R(arg1), U8(156),
  /*  945 S> */ B(LdaSmi), I8(1),
  /*  950 E> */ B(StaKeyedPropertySloppy), R(arg0), R(arg1), U8(158),
  /*  957 S> */ B(LdaSmi), I8(1),
  /*  962 E> */ B(StaKeyedPropertySloppy), R(arg0), R(arg1), U8(160),
  /*  969 S> */ B(LdaSmi), I8(1),
  /*  974 E> */ B(StaKeyedPropertySloppy), R(arg0), R(arg1), U8(162),
  /*  981 S> */ B(LdaSmi), I8(1),
  /*  986 E> */ B(StaKeyedPropertySloppy), R(arg0), R(arg1), U8(164),
  /*  993 S> */ B(LdaSmi), I8(1),
  /*  998 E> */ B(StaKeyedPropertySloppy), R(arg0), R(arg1), U8(166),
  /* 1005 S> */ B(LdaSmi), I8(1),
  /* 1010 E> */ B(StaKeyedPropertySloppy), R(arg0), R(arg1), U8(168),
  /* 1017 S> */ B(LdaSmi), I8(1),
  /* 1022 E> */ B(StaKeyedPropertySloppy), R(arg0), R(arg1), U8(170),
  /* 1029 S> */ B(LdaSmi), I8(1),
  /* 1034 E> */ B(StaKeyedPropertySloppy), R(arg0), R(arg1), U8(172),
  /* 1041 S> */ B(LdaSmi), I8(1),
  /* 1046 E> */ B(StaKeyedPropertySloppy), R(arg0), R(arg1), U8(174),
  /* 1053 S> */ B(LdaSmi), I8(1),
  /* 1058 E> */ B(StaKeyedPropertySloppy), R(arg0), R(arg1), U8(176),
  /* 1065 S> */ B(LdaSmi), I8(1),
  /* 1070 E> */ B(StaKeyedPropertySloppy), R(arg0), R(arg1), U8(178),
  /* 1077 S> */ B(LdaSmi), I8(1),
  /* 1082 E> */ B(StaKeyedPropertySloppy), R(arg0), R(arg1), U8(180),
  /* 1089 S> */ B(LdaSmi), I8(1),
  /* 1094 E> */ B(StaKeyedPropertySloppy), R(arg0), R(arg1), U8(182),
  /* 1101 S> */ B(LdaSmi), I8(1),
  /* 1106 E> */ B(StaKeyedPropertySloppy), R(arg0), R(arg1), U8(184),
  /* 1113 S> */ B(LdaSmi), I8(1),
  /* 1118 E> */ B(StaKeyedPropertySloppy), R(arg0), R(arg1), U8(186),
  /* 1125 S> */ B(LdaSmi), I8(1),
  /* 1130 E> */ B(StaKeyedPropertySloppy), R(arg0), R(arg1), U8(188),
  /* 1137 S> */ B(LdaSmi), I8(1),
  /* 1142 E> */ B(StaKeyedPropertySloppy), R(arg0), R(arg1), U8(190),
  /* 1149 S> */ B(LdaSmi), I8(1),
  /* 1154 E> */ B(StaKeyedPropertySloppy), R(arg0), R(arg1), U8(192),
  /* 1161 S> */ B(LdaSmi), I8(1),
  /* 1166 E> */ B(StaKeyedPropertySloppy), R(arg0), R(arg1), U8(194),
  /* 1173 S> */ B(LdaSmi), I8(1),
  /* 1178 E> */ B(StaKeyedPropertySloppy), R(arg0), R(arg1), U8(196),
  /* 1185 S> */ B(LdaSmi), I8(1),
  /* 1190 E> */ B(StaKeyedPropertySloppy), R(arg0), R(arg1), U8(198),
  /* 1197 S> */ B(LdaSmi), I8(1),
  /* 1202 E> */ B(StaKeyedPropertySloppy), R(arg0), R(arg1), U8(200),
  /* 1209 S> */ B(LdaSmi), I8(1),
  /* 1214 E> */ B(StaKeyedPropertySloppy), R(arg0), R(arg1), U8(202),
  /* 1221 S> */ B(LdaSmi), I8(1),
  /* 1226 E> */ B(StaKeyedPropertySloppy), R(arg0), R(arg1), U8(204),
  /* 1233 S> */ B(LdaSmi), I8(1),
  /* 1238 E> */ B(StaKeyedPropertySloppy), R(arg0), R(arg1), U8(206),
  /* 1245 S> */ B(LdaSmi), I8(1),
  /* 1250 E> */ B(StaKeyedPropertySloppy), R(arg0), R(arg1), U8(208),
  /* 1257 S> */ B(LdaSmi), I8(1),
  /* 1262 E> */ B(StaKeyedPropertySloppy), R(arg0), R(arg1), U8(210),
  /* 1269 S> */ B(LdaSmi), I8(1),
  /* 1274 E> */ B(StaKeyedPropertySloppy), R(arg0), R(arg1), U8(212),
  /* 1281 S> */ B(LdaSmi), I8(1),
  /* 1286 E> */ B(StaKeyedPropertySloppy), R(arg0), R(arg1), U8(214),
  /* 1293 S> */ B(LdaSmi), I8(1),
  /* 1298 E> */ B(StaKeyedPropertySloppy), R(arg0), R(arg1), U8(216),
  /* 1305 S> */ B(LdaSmi), I8(1),
  /* 1310 E> */ B(StaKeyedPropertySloppy), R(arg0), R(arg1), U8(218),
  /* 1317 S> */ B(LdaSmi), I8(1),
  /* 1322 E> */ B(StaKeyedPropertySloppy), R(arg0), R(arg1), U8(220),
  /* 1329 S> */ B(LdaSmi), I8(1),
  /* 1334 E> */ B(StaKeyedPropertySloppy), R(arg0), R(arg1), U8(222),
  /* 1341 S> */ B(LdaSmi), I8(1),
  /* 1346 E> */ B(StaKeyedPropertySloppy), R(arg0), R(arg1), U8(224),
  /* 1353 S> */ B(LdaSmi), I8(1),
  /* 1358 E> */ B(StaKeyedPropertySloppy), R(arg0), R(arg1), U8(226),
  /* 1365 S> */ B(LdaSmi), I8(1),
  /* 1370 E> */ B(StaKeyedPropertySloppy), R(arg0), R(arg1), U8(228),
  /* 1377 S> */ B(LdaSmi), I8(1),
  /* 1382 E> */ B(StaKeyedPropertySloppy), R(arg0), R(arg1), U8(230),
  /* 1389 S> */ B(LdaSmi), I8(1),
  /* 1394 E> */ B(StaKeyedPropertySloppy), R(arg0), R(arg1), U8(232),
  /* 1401 S> */ B(LdaSmi), I8(1),
  /* 1406 E> */ B(StaKeyedPropertySloppy), R(arg0), R(arg1), U8(234),
  /* 1413 S> */ B(LdaSmi), I8(1),
  /* 1418 E> */ B(StaKeyedPropertySloppy), R(arg0), R(arg1), U8(236),
  /* 1425 S> */ B(LdaSmi), I8(1),
  /* 1430 E> */ B(StaKeyedPropertySloppy), R(arg0), R(arg1), U8(238),
  /* 1437 S> */ B(LdaSmi), I8(1),
  /* 1442 E> */ B(StaKeyedPropertySloppy), R(arg0), R(arg1), U8(240),
  /* 1449 S> */ B(LdaSmi), I8(1),
  /* 1454 E> */ B(StaKeyedPropertySloppy), R(arg0), R(arg1), U8(242),
  /* 1461 S> */ B(LdaSmi), I8(1),
  /* 1466 E> */ B(StaKeyedPropertySloppy), R(arg0), R(arg1), U8(244),
  /* 1473 S> */ B(LdaSmi), I8(1),
  /* 1478 E> */ B(StaKeyedPropertySloppy), R(arg0), R(arg1), U8(246),
  /* 1485 S> */ B(LdaSmi), I8(1),
  /* 1490 E> */ B(StaKeyedPropertySloppy), R(arg0), R(arg1), U8(248),
  /* 1497 S> */ B(LdaSmi), I8(1),
  /* 1502 E> */ B(StaKeyedPropertySloppy), R(arg0), R(arg1), U8(250),
  /* 1509 S> */ B(LdaSmi), I8(1),
  /* 1514 E> */ B(StaKeyedPropertySloppy), R(arg0), R(arg1), U8(252),
  /* 1521 S> */ B(LdaSmi), I8(1),
  /* 1526 E> */ B(StaKeyedPropertySloppy), R(arg0), R(arg1), U8(254),
  /* 1533 S> */ B(LdaSmi), I8(1),
  /* 1538 E> */ B(Wide), B(StaKeyedPropertySloppy), R16(arg0), R16(arg1), U16(256),
  /* 1545 S> */ B(LdaSmi), I8(1),
  /* 1550 E> */ B(Wide), B(StaKeyedPropertySloppy), R16(arg0), R16(arg1), U16(258),
  /* 1557 S> */ B(LdaSmi), I8(2),
  /* 1562 E> */ B(Wide), B(StaKeyedPropertySloppy), R16(arg0), R16(arg1), U16(260),
                B(LdaUndefined),
  /* 1567 S> */ B(Return),
]
constant pool: [
]
handlers: [
]

---
snippet: "
  function f(a, b) {
    'use strict';
    a[b] = 1;
    a[b] = 1;
    a[b] = 1;
    a[b] = 1;
    a[b] = 1;
    a[b] = 1;
    a[b] = 1;
    a[b] = 1;
    a[b] = 1;
    a[b] = 1;
    a[b] = 1;
    a[b] = 1;
    a[b] = 1;
    a[b] = 1;
    a[b] = 1;
    a[b] = 1;
    a[b] = 1;
    a[b] = 1;
    a[b] = 1;
    a[b] = 1;
    a[b] = 1;
    a[b] = 1;
    a[b] = 1;
    a[b] = 1;
    a[b] = 1;
    a[b] = 1;
    a[b] = 1;
    a[b] = 1;
    a[b] = 1;
    a[b] = 1;
    a[b] = 1;
    a[b] = 1;
    a[b] = 1;
    a[b] = 1;
    a[b] = 1;
    a[b] = 1;
    a[b] = 1;
    a[b] = 1;
    a[b] = 1;
    a[b] = 1;
    a[b] = 1;
    a[b] = 1;
    a[b] = 1;
    a[b] = 1;
    a[b] = 1;
    a[b] = 1;
    a[b] = 1;
    a[b] = 1;
    a[b] = 1;
    a[b] = 1;
    a[b] = 1;
    a[b] = 1;
    a[b] = 1;
    a[b] = 1;
    a[b] = 1;
    a[b] = 1;
    a[b] = 1;
    a[b] = 1;
    a[b] = 1;
    a[b] = 1;
    a[b] = 1;
    a[b] = 1;
    a[b] = 1;
    a[b] = 1;
    a[b] = 1;
    a[b] = 1;
    a[b] = 1;
    a[b] = 1;
    a[b] = 1;
    a[b] = 1;
    a[b] = 1;
    a[b] = 1;
    a[b] = 1;
    a[b] = 1;
    a[b] = 1;
    a[b] = 1;
    a[b] = 1;
    a[b] = 1;
    a[b] = 1;
    a[b] = 1;
    a[b] = 1;
    a[b] = 1;
    a[b] = 1;
    a[b] = 1;
    a[b] = 1;
    a[b] = 1;
    a[b] = 1;
    a[b] = 1;
    a[b] = 1;
    a[b] = 1;
    a[b] = 1;
    a[b] = 1;
    a[b] = 1;
    a[b] = 1;
    a[b] = 1;
    a[b] = 1;
    a[b] = 1;
    a[b] = 1;
    a[b] = 1;
    a[b] = 1;
    a[b] = 1;
    a[b] = 1;
    a[b] = 1;
    a[b] = 1;
    a[b] = 1;
    a[b] = 1;
    a[b] = 1;
    a[b] = 1;
    a[b] = 1;
    a[b] = 1;
    a[b] = 1;
    a[b] = 1;
    a[b] = 1;
    a[b] = 1;
    a[b] = 1;
    a[b] = 1;
    a[b] = 1;
    a[b] = 1;
    a[b] = 1;
    a[b] = 1;
    a[b] = 1;
    a[b] = 1;
    a[b] = 1;
    a[b] = 1;
    a[b] = 1;
    a[b] = 1;
    a[b] = 1;
    a[b] = 1;
    a[b] = 2;
  }
  f({name : \"test\"})
"
frame size: 0
parameter count: 3
bytecode array length: 789
bytecodes: [
  /*   10 E> */ B(StackCheck),
  /*   37 S> */ B(LdaSmi), I8(1),
  /*   42 E> */ B(StaKeyedPropertyStrict), R(arg0), R(arg1), U8(4),
  /*   49 S> */ B(LdaSmi), I8(1),
  /*   54 E> */ B(StaKeyedPropertyStrict), R(arg0), R(arg1), U8(6),
  /*   61 S> */ B(LdaSmi), I8(1),
  /*   66 E> */ B(StaKeyedPropertyStrict), R(arg0), R(arg1), U8(8),
  /*   73 S> */ B(LdaSmi), I8(1),
  /*   78 E> */ B(StaKeyedPropertyStrict), R(arg0), R(arg1), U8(10),
  /*   85 S> */ B(LdaSmi), I8(1),
  /*   90 E> */ B(StaKeyedPropertyStrict), R(arg0), R(arg1), U8(12),
  /*   97 S> */ B(LdaSmi), I8(1),
  /*  102 E> */ B(StaKeyedPropertyStrict), R(arg0), R(arg1), U8(14),
  /*  109 S> */ B(LdaSmi), I8(1),
  /*  114 E> */ B(StaKeyedPropertyStrict), R(arg0), R(arg1), U8(16),
  /*  121 S> */ B(LdaSmi), I8(1),
  /*  126 E> */ B(StaKeyedPropertyStrict), R(arg0), R(arg1), U8(18),
  /*  133 S> */ B(LdaSmi), I8(1),
  /*  138 E> */ B(StaKeyedPropertyStrict), R(arg0), R(arg1), U8(20),
  /*  145 S> */ B(LdaSmi), I8(1),
  /*  150 E> */ B(StaKeyedPropertyStrict), R(arg0), R(arg1), U8(22),
  /*  157 S> */ B(LdaSmi), I8(1),
  /*  162 E> */ B(StaKeyedPropertyStrict), R(arg0), R(arg1), U8(24),
  /*  169 S> */ B(LdaSmi), I8(1),
  /*  174 E> */ B(StaKeyedPropertyStrict), R(arg0), R(arg1), U8(26),
  /*  181 S> */ B(LdaSmi), I8(1),
  /*  186 E> */ B(StaKeyedPropertyStrict), R(arg0), R(arg1), U8(28),
  /*  193 S> */ B(LdaSmi), I8(1),
  /*  198 E> */ B(StaKeyedPropertyStrict), R(arg0), R(arg1), U8(30),
  /*  205 S> */ B(LdaSmi), I8(1),
  /*  210 E> */ B(StaKeyedPropertyStrict), R(arg0), R(arg1), U8(32),
  /*  217 S> */ B(LdaSmi), I8(1),
  /*  222 E> */ B(StaKeyedPropertyStrict), R(arg0), R(arg1), U8(34),
  /*  229 S> */ B(LdaSmi), I8(1),
  /*  234 E> */ B(StaKeyedPropertyStrict), R(arg0), R(arg1), U8(36),
  /*  241 S> */ B(LdaSmi), I8(1),
  /*  246 E> */ B(StaKeyedPropertyStrict), R(arg0), R(arg1), U8(38),
  /*  253 S> */ B(LdaSmi), I8(1),
  /*  258 E> */ B(StaKeyedPropertyStrict), R(arg0), R(arg1), U8(40),
  /*  265 S> */ B(LdaSmi), I8(1),
  /*  270 E> */ B(StaKeyedPropertyStrict), R(arg0), R(arg1), U8(42),
  /*  277 S> */ B(LdaSmi), I8(1),
  /*  282 E> */ B(StaKeyedPropertyStrict), R(arg0), R(arg1), U8(44),
  /*  289 S> */ B(LdaSmi), I8(1),
  /*  294 E> */ B(StaKeyedPropertyStrict), R(arg0), R(arg1), U8(46),
  /*  301 S> */ B(LdaSmi), I8(1),
  /*  306 E> */ B(StaKeyedPropertyStrict), R(arg0), R(arg1), U8(48),
  /*  313 S> */ B(LdaSmi), I8(1),
  /*  318 E> */ B(StaKeyedPropertyStrict), R(arg0), R(arg1), U8(50),
  /*  325 S> */ B(LdaSmi), I8(1),
  /*  330 E> */ B(StaKeyedPropertyStrict), R(arg0), R(arg1), U8(52),
  /*  337 S> */ B(LdaSmi), I8(1),
  /*  342 E> */ B(StaKeyedPropertyStrict), R(arg0), R(arg1), U8(54),
  /*  349 S> */ B(LdaSmi), I8(1),
  /*  354 E> */ B(StaKeyedPropertyStrict), R(arg0), R(arg1), U8(56),
  /*  361 S> */ B(LdaSmi), I8(1),
  /*  366 E> */ B(StaKeyedPropertyStrict), R(arg0), R(arg1), U8(58),
  /*  373 S> */ B(LdaSmi), I8(1),
  /*  378 E> */ B(StaKeyedPropertyStrict), R(arg0), R(arg1), U8(60),
  /*  385 S> */ B(LdaSmi), I8(1),
  /*  390 E> */ B(StaKeyedPropertyStrict), R(arg0), R(arg1), U8(62),
  /*  397 S> */ B(LdaSmi), I8(1),
  /*  402 E> */ B(StaKeyedPropertyStrict), R(arg0), R(arg1), U8(64),
  /*  409 S> */ B(LdaSmi), I8(1),
  /*  414 E> */ B(StaKeyedPropertyStrict), R(arg0), R(arg1), U8(66),
  /*  421 S> */ B(LdaSmi), I8(1),
  /*  426 E> */ B(StaKeyedPropertyStrict), R(arg0), R(arg1), U8(68),
  /*  433 S> */ B(LdaSmi), I8(1),
  /*  438 E> */ B(StaKeyedPropertyStrict), R(arg0), R(arg1), U8(70),
  /*  445 S> */ B(LdaSmi), I8(1),
  /*  450 E> */ B(StaKeyedPropertyStrict), R(arg0), R(arg1), U8(72),
  /*  457 S> */ B(LdaSmi), I8(1),
  /*  462 E> */ B(StaKeyedPropertyStrict), R(arg0), R(arg1), U8(74),
  /*  469 S> */ B(LdaSmi), I8(1),
  /*  474 E> */ B(StaKeyedPropertyStrict), R(arg0), R(arg1), U8(76),
  /*  481 S> */ B(LdaSmi), I8(1),
  /*  486 E> */ B(StaKeyedPropertyStrict), R(arg0), R(arg1), U8(78),
  /*  493 S> */ B(LdaSmi), I8(1),
  /*  498 E> */ B(StaKeyedPropertyStrict), R(arg0), R(arg1), U8(80),
  /*  505 S> */ B(LdaSmi), I8(1),
  /*  510 E> */ B(StaKeyedPropertyStrict), R(arg0), R(arg1), U8(82),
  /*  517 S> */ B(LdaSmi), I8(1),
  /*  522 E> */ B(StaKeyedPropertyStrict), R(arg0), R(arg1), U8(84),
  /*  529 S> */ B(LdaSmi), I8(1),
  /*  534 E> */ B(StaKeyedPropertyStrict), R(arg0), R(arg1), U8(86),
  /*  541 S> */ B(LdaSmi), I8(1),
  /*  546 E> */ B(StaKeyedPropertyStrict), R(arg0), R(arg1), U8(88),
  /*  553 S> */ B(LdaSmi), I8(1),
  /*  558 E> */ B(StaKeyedPropertyStrict), R(arg0), R(arg1), U8(90),
  /*  565 S> */ B(LdaSmi), I8(1),
  /*  570 E> */ B(StaKeyedPropertyStrict), R(arg0), R(arg1), U8(92),
  /*  577 S> */ B(LdaSmi), I8(1),
  /*  582 E> */ B(StaKeyedPropertyStrict), R(arg0), R(arg1), U8(94),
  /*  589 S> */ B(LdaSmi), I8(1),
  /*  594 E> */ B(StaKeyedPropertyStrict), R(arg0), R(arg1), U8(96),
  /*  601 S> */ B(LdaSmi), I8(1),
  /*  606 E> */ B(StaKeyedPropertyStrict), R(arg0), R(arg1), U8(98),
  /*  613 S> */ B(LdaSmi), I8(1),
  /*  618 E> */ B(StaKeyedPropertyStrict), R(arg0), R(arg1), U8(100),
  /*  625 S> */ B(LdaSmi), I8(1),
  /*  630 E> */ B(StaKeyedPropertyStrict), R(arg0), R(arg1), U8(102),
  /*  637 S> */ B(LdaSmi), I8(1),
  /*  642 E> */ B(StaKeyedPropertyStrict), R(arg0), R(arg1), U8(104),
  /*  649 S> */ B(LdaSmi), I8(1),
  /*  654 E> */ B(StaKeyedPropertyStrict), R(arg0), R(arg1), U8(106),
  /*  661 S> */ B(LdaSmi), I8(1),
  /*  666 E> */ B(StaKeyedPropertyStrict), R(arg0), R(arg1), U8(108),
  /*  673 S> */ B(LdaSmi), I8(1),
  /*  678 E> */ B(StaKeyedPropertyStrict), R(arg0), R(arg1), U8(110),
  /*  685 S> */ B(LdaSmi), I8(1),
  /*  690 E> */ B(StaKeyedPropertyStrict), R(arg0), R(arg1), U8(112),
  /*  697 S> */ B(LdaSmi), I8(1),
  /*  702 E> */ B(StaKeyedPropertyStrict), R(arg0), R(arg1), U8(114),
  /*  709 S> */ B(LdaSmi), I8(1),
  /*  714 E> */ B(StaKeyedPropertyStrict), R(arg0), R(arg1), U8(116),
  /*  721 S> */ B(LdaSmi), I8(1),
  /*  726 E> */ B(StaKeyedPropertyStrict), R(arg0), R(arg1), U8(118),
  /*  733 S> */ B(LdaSmi), I8(1),
  /*  738 E> */ B(StaKeyedPropertyStrict), R(arg0), R(arg1), U8(120),
  /*  745 S> */ B(LdaSmi), I8(1),
  /*  750 E> */ B(StaKeyedPropertyStrict), R(arg0), R(arg1), U8(122),
  /*  757 S> */ B(LdaSmi), I8(1),
  /*  762 E> */ B(StaKeyedPropertyStrict), R(arg0), R(arg1), U8(124),
  /*  769 S> */ B(LdaSmi), I8(1),
  /*  774 E> */ B(StaKeyedPropertyStrict), R(arg0), R(arg1), U8(126),
  /*  781 S> */ B(LdaSmi), I8(1),
  /*  786 E> */ B(StaKeyedPropertyStrict), R(arg0), R(arg1), U8(128),
  /*  793 S> */ B(LdaSmi), I8(1),
  /*  798 E> */ B(StaKeyedPropertyStrict), R(arg0), R(arg1), U8(130),
  /*  805 S> */ B(LdaSmi), I8(1),
  /*  810 E> */ B(StaKeyedPropertyStrict), R(arg0), R(arg1), U8(132),
  /*  817 S> */ B(LdaSmi), I8(1),
  /*  822 E> */ B(StaKeyedPropertyStrict), R(arg0), R(arg1), U8(134),
  /*  829 S> */ B(LdaSmi), I8(1),
  /*  834 E> */ B(StaKeyedPropertyStrict), R(arg0), R(arg1), U8(136),
  /*  841 S> */ B(LdaSmi), I8(1),
  /*  846 E> */ B(StaKeyedPropertyStrict), R(arg0), R(arg1), U8(138),
  /*  853 S> */ B(LdaSmi), I8(1),
  /*  858 E> */ B(StaKeyedPropertyStrict), R(arg0), R(arg1), U8(140),
  /*  865 S> */ B(LdaSmi), I8(1),
  /*  870 E> */ B(StaKeyedPropertyStrict), R(arg0), R(arg1), U8(142),
  /*  877 S> */ B(LdaSmi), I8(1),
  /*  882 E> */ B(StaKeyedPropertyStrict), R(arg0), R(arg1), U8(144),
  /*  889 S> */ B(LdaSmi), I8(1),
  /*  894 E> */ B(StaKeyedPropertyStrict), R(arg0), R(arg1), U8(146),
  /*  901 S> */ B(LdaSmi), I8(1),
  /*  906 E> */ B(StaKeyedPropertyStrict), R(arg0), R(arg1), U8(148),
  /*  913 S> */ B(LdaSmi), I8(1),
  /*  918 E> */ B(StaKeyedPropertyStrict), R(arg0), R(arg1), U8(150),
  /*  925 S> */ B(LdaSmi), I8(1),
  /*  930 E> */ B(StaKeyedPropertyStrict), R(arg0), R(arg1), U8(152),
  /*  937 S> */ B(LdaSmi), I8(1),
  /*  942 E> */ B(StaKeyedPropertyStrict), R(arg0), R(arg1), U8(154),
  /*  949 S> */ B(LdaSmi), I8(1),
  /*  954 E> */ B(StaKeyedPropertyStrict), R(arg0), R(arg1), U8(156),
  /*  961 S> */ B(LdaSmi), I8(1),
  /*  966 E> */ B(StaKeyedPropertyStrict), R(arg0), R(arg1), U8(158),
  /*  973 S> */ B(LdaSmi), I8(1),
  /*  978 E> */ B(StaKeyedPropertyStrict), R(arg0), R(arg1), U8(160),
  /*  985 S> */ B(LdaSmi), I8(1),
  /*  990 E> */ B(StaKeyedPropertyStrict), R(arg0), R(arg1), U8(162),
  /*  997 S> */ B(LdaSmi), I8(1),
  /* 1002 E> */ B(StaKeyedPropertyStrict), R(arg0), R(arg1), U8(164),
  /* 1009 S> */ B(LdaSmi), I8(1),
  /* 1014 E> */ B(StaKeyedPropertyStrict), R(arg0), R(arg1), U8(166),
  /* 1021 S> */ B(LdaSmi), I8(1),
  /* 1026 E> */ B(StaKeyedPropertyStrict), R(arg0), R(arg1), U8(168),
  /* 1033 S> */ B(LdaSmi), I8(1),
  /* 1038 E> */ B(StaKeyedPropertyStrict), R(arg0), R(arg1), U8(170),
  /* 1045 S> */ B(LdaSmi), I8(1),
  /* 1050 E> */ B(StaKeyedPropertyStrict), R(arg0), R(arg1), U8(172),
  /* 1057 S> */ B(LdaSmi), I8(1),
  /* 1062 E> */ B(StaKeyedPropertyStrict), R(arg0), R(arg1), U8(174),
  /* 1069 S> */ B(LdaSmi), I8(1),
  /* 1074 E> */ B(StaKeyedPropertyStrict), R(arg0), R(arg1), U8(176),
  /* 1081 S> */ B(LdaSmi), I8(1),
  /* 1086 E> */ B(StaKeyedPropertyStrict), R(arg0), R(arg1), U8(178),
  /* 1093 S> */ B(LdaSmi), I8(1),
  /* 1098 E> */ B(StaKeyedPropertyStrict), R(arg0), R(arg1), U8(180),
  /* 1105 S> */ B(LdaSmi), I8(1),
  /* 1110 E> */ B(StaKeyedPropertyStrict), R(arg0), R(arg1), U8(182),
  /* 1117 S> */ B(LdaSmi), I8(1),
  /* 1122 E> */ B(StaKeyedPropertyStrict), R(arg0), R(arg1), U8(184),
  /* 1129 S> */ B(LdaSmi), I8(1),
  /* 1134 E> */ B(StaKeyedPropertyStrict), R(arg0), R(arg1), U8(186),
  /* 1141 S> */ B(LdaSmi), I8(1),
  /* 1146 E> */ B(StaKeyedPropertyStrict), R(arg0), R(arg1), U8(188),
  /* 1153 S> */ B(LdaSmi), I8(1),
  /* 1158 E> */ B(StaKeyedPropertyStrict), R(arg0), R(arg1), U8(190),
  /* 1165 S> */ B(LdaSmi), I8(1),
  /* 1170 E> */ B(StaKeyedPropertyStrict), R(arg0), R(arg1), U8(192),
  /* 1177 S> */ B(LdaSmi), I8(1),
  /* 1182 E> */ B(StaKeyedPropertyStrict), R(arg0), R(arg1), U8(194),
  /* 1189 S> */ B(LdaSmi), I8(1),
  /* 1194 E> */ B(StaKeyedPropertyStrict), R(arg0), R(arg1), U8(196),
  /* 1201 S> */ B(LdaSmi), I8(1),
  /* 1206 E> */ B(StaKeyedPropertyStrict), R(arg0), R(arg1), U8(198),
  /* 1213 S> */ B(LdaSmi), I8(1),
  /* 1218 E> */ B(StaKeyedPropertyStrict), R(arg0), R(arg1), U8(200),
  /* 1225 S> */ B(LdaSmi), I8(1),
  /* 1230 E> */ B(StaKeyedPropertyStrict), R(arg0), R(arg1), U8(202),
  /* 1237 S> */ B(LdaSmi), I8(1),
  /* 1242 E> */ B(StaKeyedPropertyStrict), R(arg0), R(arg1), U8(204),
  /* 1249 S> */ B(LdaSmi), I8(1),
  /* 1254 E> */ B(StaKeyedPropertyStrict), R(arg0), R(arg1), U8(206),
  /* 1261 S> */ B(LdaSmi), I8(1),
  /* 1266 E> */ B(StaKeyedPropertyStrict), R(arg0), R(arg1), U8(208),
  /* 1273 S> */ B(LdaSmi), I8(1),
  /* 1278 E> */ B(StaKeyedPropertyStrict), R(arg0), R(arg1), U8(210),
  /* 1285 S> */ B(LdaSmi), I8(1),
  /* 1290 E> */ B(StaKeyedPropertyStrict), R(arg0), R(arg1), U8(212),
  /* 1297 S> */ B(LdaSmi), I8(1),
  /* 1302 E> */ B(StaKeyedPropertyStrict), R(arg0), R(arg1), U8(214),
  /* 1309 S> */ B(LdaSmi), I8(1),
  /* 1314 E> */ B(StaKeyedPropertyStrict), R(arg0), R(arg1), U8(216),
  /* 1321 S> */ B(LdaSmi), I8(1),
  /* 1326 E> */ B(StaKeyedPropertyStrict), R(arg0), R(arg1), U8(218),
  /* 1333 S> */ B(LdaSmi), I8(1),
  /* 1338 E> */ B(StaKeyedPropertyStrict), R(arg0), R(arg1), U8(220),
  /* 1345 S> */ B(LdaSmi), I8(1),
  /* 1350 E> */ B(StaKeyedPropertyStrict), R(arg0), R(arg1), U8(222),
  /* 1357 S> */ B(LdaSmi), I8(1),
  /* 1362 E> */ B(StaKeyedPropertyStrict), R(arg0), R(arg1), U8(224),
  /* 1369 S> */ B(LdaSmi), I8(1),
  /* 1374 E> */ B(StaKeyedPropertyStrict), R(arg0), R(arg1), U8(226),
  /* 1381 S> */ B(LdaSmi), I8(1),
  /* 1386 E> */ B(StaKeyedPropertyStrict), R(arg0), R(arg1), U8(228),
  /* 1393 S> */ B(LdaSmi), I8(1),
  /* 1398 E> */ B(StaKeyedPropertyStrict), R(arg0), R(arg1), U8(230),
  /* 1405 S> */ B(LdaSmi), I8(1),
  /* 1410 E> */ B(StaKeyedPropertyStrict), R(arg0), R(arg1), U8(232),
  /* 1417 S> */ B(LdaSmi), I8(1),
  /* 1422 E> */ B(StaKeyedPropertyStrict), R(arg0), R(arg1), U8(234),
  /* 1429 S> */ B(LdaSmi), I8(1),
  /* 1434 E> */ B(StaKeyedPropertyStrict), R(arg0), R(arg1), U8(236),
  /* 1441 S> */ B(LdaSmi), I8(1),
  /* 1446 E> */ B(StaKeyedPropertyStrict), R(arg0), R(arg1), U8(238),
  /* 1453 S> */ B(LdaSmi), I8(1),
  /* 1458 E> */ B(StaKeyedPropertyStrict), R(arg0), R(arg1), U8(240),
  /* 1465 S> */ B(LdaSmi), I8(1),
  /* 1470 E> */ B(StaKeyedPropertyStrict), R(arg0), R(arg1), U8(242),
  /* 1477 S> */ B(LdaSmi), I8(1),
  /* 1482 E> */ B(StaKeyedPropertyStrict), R(arg0), R(arg1), U8(244),
  /* 1489 S> */ B(LdaSmi), I8(1),
  /* 1494 E> */ B(StaKeyedPropertyStrict), R(arg0), R(arg1), U8(246),
  /* 1501 S> */ B(LdaSmi), I8(1),
  /* 1506 E> */ B(StaKeyedPropertyStrict), R(arg0), R(arg1), U8(248),
  /* 1513 S> */ B(LdaSmi), I8(1),
  /* 1518 E> */ B(StaKeyedPropertyStrict), R(arg0), R(arg1), U8(250),
  /* 1525 S> */ B(LdaSmi), I8(1),
  /* 1530 E> */ B(StaKeyedPropertyStrict), R(arg0), R(arg1), U8(252),
  /* 1537 S> */ B(LdaSmi), I8(1),
  /* 1542 E> */ B(StaKeyedPropertyStrict), R(arg0), R(arg1), U8(254),
  /* 1549 S> */ B(LdaSmi), I8(1),
  /* 1554 E> */ B(Wide), B(StaKeyedPropertyStrict), R16(arg0), R16(arg1), U16(256),
  /* 1561 S> */ B(LdaSmi), I8(1),
  /* 1566 E> */ B(Wide), B(StaKeyedPropertyStrict), R16(arg0), R16(arg1), U16(258),
  /* 1573 S> */ B(LdaSmi), I8(2),
  /* 1578 E> */ B(Wide), B(StaKeyedPropertyStrict), R16(arg0), R16(arg1), U16(260),
                B(LdaUndefined),
  /* 1583 S> */ B(Return),
]
constant pool: [
]
handlers: [
]

