#
# Autogenerated by generate-bytecode-expectations.
#

---
wrap: no
test function name: f

---
snippet: "
  function f(a) { return a.name; }
  f({name : \"test\"});
"
frame size: 0
parameter count: 2
bytecode array length: 6
bytecodes: [
  /*   10 E> */ B(StackCheck),
  /*   25 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(4),
  /*   30 S> */ B(Return),
]
constant pool: [
  ONE_BYTE_INTERNALIZED_STRING_TYPE ["name"],
]
handlers: [
]

---
snippet: "
  function f(a) { return a[\"key\"]; }
  f({key : \"test\"});
"
frame size: 0
parameter count: 2
bytecode array length: 6
bytecodes: [
  /*   10 E> */ B(StackCheck),
  /*   24 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(4),
  /*   32 S> */ B(Return),
]
constant pool: [
  ONE_BYTE_INTERNALIZED_STRING_TYPE ["key"],
]
handlers: [
]

---
snippet: "
  function f(a) { return a[100]; }
  f({100 : \"test\"});
"
frame size: 0
parameter count: 2
bytecode array length: 7
bytecodes: [
  /*   10 E> */ B(StackCheck),
  /*   16 S> */ B(LdaSmi), I8(100),
  /*   24 E> */ B(LdaKeyedProperty), R(arg0), U8(4),
  /*   30 S> */ B(Return),
]
constant pool: [
]
handlers: [
]

---
snippet: "
  function f(a, b) { return a[b]; }
  f({arg : \"test\"}, \"arg\");
"
frame size: 0
parameter count: 3
bytecode array length: 7
bytecodes: [
  /*   10 E> */ B(StackCheck),
  /*   19 S> */ B(Ldar), R(arg1),
  /*   27 E> */ B(LdaKeyedProperty), R(arg0), U8(4),
  /*   31 S> */ B(Return),
]
constant pool: [
]
handlers: [
]

---
snippet: "
  function f(a) { var b = a.name; return a[-124]; }
  f({\"-124\" : \"test\", name : 123 })
"
frame size: 1
parameter count: 2
bytecode array length: 13
bytecodes: [
  /*   10 E> */ B(StackCheck),
  /*   26 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(4),
                B(Star), R(0),
  /*   32 S> */ B(LdaSmi), I8(-124),
  /*   40 E> */ B(LdaKeyedProperty), R(arg0), U8(6),
  /*   47 S> */ B(Return),
]
constant pool: [
  ONE_BYTE_INTERNALIZED_STRING_TYPE ["name"],
]
handlers: [
]

---
snippet: "
  function f(a) {
    var b;
    b = a.name;
    b = a.name;
    b = a.name;
    b = a.name;
    b = a.name;
    b = a.name;
    b = a.name;
    b = a.name;
    b = a.name;
    b = a.name;
    b = a.name;
    b = a.name;
    b = a.name;
    b = a.name;
    b = a.name;
    b = a.name;
    b = a.name;
    b = a.name;
    b = a.name;
    b = a.name;
    b = a.name;
    b = a.name;
    b = a.name;
    b = a.name;
    b = a.name;
    b = a.name;
    b = a.name;
    b = a.name;
    b = a.name;
    b = a.name;
    b = a.name;
    b = a.name;
    b = a.name;
    b = a.name;
    b = a.name;
    b = a.name;
    b = a.name;
    b = a.name;
    b = a.name;
    b = a.name;
    b = a.name;
    b = a.name;
    b = a.name;
    b = a.name;
    b = a.name;
    b = a.name;
    b = a.name;
    b = a.name;
    b = a.name;
    b = a.name;
    b = a.name;
    b = a.name;
    b = a.name;
    b = a.name;
    b = a.name;
    b = a.name;
    b = a.name;
    b = a.name;
    b = a.name;
    b = a.name;
    b = a.name;
    b = a.name;
    b = a.name;
    b = a.name;
    b = a.name;
    b = a.name;
    b = a.name;
    b = a.name;
    b = a.name;
    b = a.name;
    b = a.name;
    b = a.name;
    b = a.name;
    b = a.name;
    b = a.name;
    b = a.name;
    b = a.name;
    b = a.name;
    b = a.name;
    b = a.name;
    b = a.name;
    b = a.name;
    b = a.name;
    b = a.name;
    b = a.name;
    b = a.name;
    b = a.name;
    b = a.name;
    b = a.name;
    b = a.name;
    b = a.name;
    b = a.name;
    b = a.name;
    b = a.name;
    b = a.name;
    b = a.name;
    b = a.name;
    b = a.name;
    b = a.name;
    b = a.name;
    b = a.name;
    b = a.name;
    b = a.name;
    b = a.name;
    b = a.name;
    b = a.name;
    b = a.name;
    b = a.name;
    b = a.name;
    b = a.name;
    b = a.name;
    b = a.name;
    b = a.name;
    b = a.name;
    b = a.name;
    b = a.name;
    b = a.name;
    b = a.name;
    b = a.name;
    b = a.name;
    b = a.name;
    b = a.name;
    b = a.name;
    b = a.name;
    b = a.name;
    b = a.name;
    b = a.name;
    b = a.name;
    return a.name;
  }
  f({name : \"test\"})
"
frame size: 1
parameter count: 2
bytecode array length: 786
bytecodes: [
  /*   10 E> */ B(StackCheck),
  /*   33 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(4),
                B(Star), R(0),
  /*   47 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(6),
                B(Star), R(0),
  /*   61 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(8),
                B(Star), R(0),
  /*   75 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(10),
                B(Star), R(0),
  /*   89 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(12),
                B(Star), R(0),
  /*  103 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(14),
                B(Star), R(0),
  /*  117 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(16),
                B(Star), R(0),
  /*  131 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(18),
                B(Star), R(0),
  /*  145 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(20),
                B(Star), R(0),
  /*  159 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(22),
                B(Star), R(0),
  /*  173 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(24),
                B(Star), R(0),
  /*  187 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(26),
                B(Star), R(0),
  /*  201 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(28),
                B(Star), R(0),
  /*  215 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(30),
                B(Star), R(0),
  /*  229 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(32),
                B(Star), R(0),
  /*  243 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(34),
                B(Star), R(0),
  /*  257 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(36),
                B(Star), R(0),
  /*  271 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(38),
                B(Star), R(0),
  /*  285 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(40),
                B(Star), R(0),
  /*  299 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(42),
                B(Star), R(0),
  /*  313 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(44),
                B(Star), R(0),
  /*  327 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(46),
                B(Star), R(0),
  /*  341 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(48),
                B(Star), R(0),
  /*  355 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(50),
                B(Star), R(0),
  /*  369 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(52),
                B(Star), R(0),
  /*  383 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(54),
                B(Star), R(0),
  /*  397 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(56),
                B(Star), R(0),
  /*  411 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(58),
                B(Star), R(0),
  /*  425 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(60),
                B(Star), R(0),
  /*  439 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(62),
                B(Star), R(0),
  /*  453 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(64),
                B(Star), R(0),
  /*  467 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(66),
                B(Star), R(0),
  /*  481 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(68),
                B(Star), R(0),
  /*  495 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(70),
                B(Star), R(0),
  /*  509 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(72),
                B(Star), R(0),
  /*  523 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(74),
                B(Star), R(0),
  /*  537 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(76),
                B(Star), R(0),
  /*  551 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(78),
                B(Star), R(0),
  /*  565 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(80),
                B(Star), R(0),
  /*  579 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(82),
                B(Star), R(0),
  /*  593 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(84),
                B(Star), R(0),
  /*  607 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(86),
                B(Star), R(0),
  /*  621 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(88),
                B(Star), R(0),
  /*  635 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(90),
                B(Star), R(0),
  /*  649 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(92),
                B(Star), R(0),
  /*  663 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(94),
                B(Star), R(0),
  /*  677 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(96),
                B(Star), R(0),
  /*  691 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(98),
                B(Star), R(0),
  /*  705 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(100),
                B(Star), R(0),
  /*  719 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(102),
                B(Star), R(0),
  /*  733 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(104),
                B(Star), R(0),
  /*  747 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(106),
                B(Star), R(0),
  /*  761 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(108),
                B(Star), R(0),
  /*  775 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(110),
                B(Star), R(0),
  /*  789 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(112),
                B(Star), R(0),
  /*  803 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(114),
                B(Star), R(0),
  /*  817 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(116),
                B(Star), R(0),
  /*  831 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(118),
                B(Star), R(0),
  /*  845 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(120),
                B(Star), R(0),
  /*  859 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(122),
                B(Star), R(0),
  /*  873 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(124),
                B(Star), R(0),
  /*  887 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(126),
                B(Star), R(0),
  /*  901 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(128),
                B(Star), R(0),
  /*  915 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(130),
                B(Star), R(0),
  /*  929 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(132),
                B(Star), R(0),
  /*  943 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(134),
                B(Star), R(0),
  /*  957 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(136),
                B(Star), R(0),
  /*  971 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(138),
                B(Star), R(0),
  /*  985 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(140),
                B(Star), R(0),
  /*  999 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(142),
                B(Star), R(0),
  /* 1013 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(144),
                B(Star), R(0),
  /* 1027 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(146),
                B(Star), R(0),
  /* 1041 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(148),
                B(Star), R(0),
  /* 1055 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(150),
                B(Star), R(0),
  /* 1069 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(152),
                B(Star), R(0),
  /* 1083 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(154),
                B(Star), R(0),
  /* 1097 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(156),
                B(Star), R(0),
  /* 1111 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(158),
                B(Star), R(0),
  /* 1125 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(160),
                B(Star), R(0),
  /* 1139 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(162),
                B(Star), R(0),
  /* 1153 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(164),
                B(Star), R(0),
  /* 1167 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(166),
                B(Star), R(0),
  /* 1181 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(168),
                B(Star), R(0),
  /* 1195 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(170),
                B(Star), R(0),
  /* 1209 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(172),
                B(Star), R(0),
  /* 1223 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(174),
                B(Star), R(0),
  /* 1237 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(176),
                B(Star), R(0),
  /* 1251 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(178),
                B(Star), R(0),
  /* 1265 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(180),
                B(Star), R(0),
  /* 1279 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(182),
                B(Star), R(0),
  /* 1293 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(184),
                B(Star), R(0),
  /* 1307 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(186),
                B(Star), R(0),
  /* 1321 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(188),
                B(Star), R(0),
  /* 1335 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(190),
                B(Star), R(0),
  /* 1349 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(192),
                B(Star), R(0),
  /* 1363 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(194),
                B(Star), R(0),
  /* 1377 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(196),
                B(Star), R(0),
  /* 1391 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(198),
                B(Star), R(0),
  /* 1405 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(200),
                B(Star), R(0),
  /* 1419 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(202),
                B(Star), R(0),
  /* 1433 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(204),
                B(Star), R(0),
  /* 1447 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(206),
                B(Star), R(0),
  /* 1461 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(208),
                B(Star), R(0),
  /* 1475 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(210),
                B(Star), R(0),
  /* 1489 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(212),
                B(Star), R(0),
  /* 1503 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(214),
                B(Star), R(0),
  /* 1517 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(216),
                B(Star), R(0),
  /* 1531 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(218),
                B(Star), R(0),
  /* 1545 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(220),
                B(Star), R(0),
  /* 1559 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(222),
                B(Star), R(0),
  /* 1573 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(224),
                B(Star), R(0),
  /* 1587 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(226),
                B(Star), R(0),
  /* 1601 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(228),
                B(Star), R(0),
  /* 1615 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(230),
                B(Star), R(0),
  /* 1629 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(232),
                B(Star), R(0),
  /* 1643 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(234),
                B(Star), R(0),
  /* 1657 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(236),
                B(Star), R(0),
  /* 1671 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(238),
                B(Star), R(0),
  /* 1685 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(240),
                B(Star), R(0),
  /* 1699 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(242),
                B(Star), R(0),
  /* 1713 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(244),
                B(Star), R(0),
  /* 1727 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(246),
                B(Star), R(0),
  /* 1741 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(248),
                B(Star), R(0),
  /* 1755 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(250),
                B(Star), R(0),
  /* 1769 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(252),
                B(Star), R(0),
  /* 1783 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(254),
                B(Star), R(0),
  /* 1797 S> */ B(Wide), B(LdaNamedProperty), R16(arg0), U16(0), U16(256),
                B(Star), R(0),
  /* 1811 S> */ B(Wide), B(LdaNamedProperty), R16(arg0), U16(0), U16(258),
                B(Star), R(0),
  /* 1828 S> */ B(Wide), B(LdaNamedProperty), R16(arg0), U16(0), U16(260),
  /* 1833 S> */ B(Return),
]
constant pool: [
  ONE_BYTE_INTERNALIZED_STRING_TYPE ["name"],
]
handlers: [
]

---
snippet: "
  function f(a, b) {
    var c;
    c = a[b];
    c = a[b];
    c = a[b];
    c = a[b];
    c = a[b];
    c = a[b];
    c = a[b];
    c = a[b];
    c = a[b];
    c = a[b];
    c = a[b];
    c = a[b];
    c = a[b];
    c = a[b];
    c = a[b];
    c = a[b];
    c = a[b];
    c = a[b];
    c = a[b];
    c = a[b];
    c = a[b];
    c = a[b];
    c = a[b];
    c = a[b];
    c = a[b];
    c = a[b];
    c = a[b];
    c = a[b];
    c = a[b];
    c = a[b];
    c = a[b];
    c = a[b];
    c = a[b];
    c = a[b];
    c = a[b];
    c = a[b];
    c = a[b];
    c = a[b];
    c = a[b];
    c = a[b];
    c = a[b];
    c = a[b];
    c = a[b];
    c = a[b];
    c = a[b];
    c = a[b];
    c = a[b];
    c = a[b];
    c = a[b];
    c = a[b];
    c = a[b];
    c = a[b];
    c = a[b];
    c = a[b];
    c = a[b];
    c = a[b];
    c = a[b];
    c = a[b];
    c = a[b];
    c = a[b];
    c = a[b];
    c = a[b];
    c = a[b];
    c = a[b];
    c = a[b];
    c = a[b];
    c = a[b];
    c = a[b];
    c = a[b];
    c = a[b];
    c = a[b];
    c = a[b];
    c = a[b];
    c = a[b];
    c = a[b];
    c = a[b];
    c = a[b];
    c = a[b];
    c = a[b];
    c = a[b];
    c = a[b];
    c = a[b];
    c = a[b];
    c = a[b];
    c = a[b];
    c = a[b];
    c = a[b];
    c = a[b];
    c = a[b];
    c = a[b];
    c = a[b];
    c = a[b];
    c = a[b];
    c = a[b];
    c = a[b];
    c = a[b];
    c = a[b];
    c = a[b];
    c = a[b];
    c = a[b];
    c = a[b];
    c = a[b];
    c = a[b];
    c = a[b];
    c = a[b];
    c = a[b];
    c = a[b];
    c = a[b];
    c = a[b];
    c = a[b];
    c = a[b];
    c = a[b];
    c = a[b];
    c = a[b];
    c = a[b];
    c = a[b];
    c = a[b];
    c = a[b];
    c = a[b];
    c = a[b];
    c = a[b];
    c = a[b];
    c = a[b];
    c = a[b];
    c = a[b];
    c = a[b];
    c = a[b];
    c = a[b];
    return a[b];
  }
  f({name : \"test\"}, \"name\")
"
frame size: 1
parameter count: 3
bytecode array length: 912
bytecodes: [
  /*   10 E> */ B(StackCheck),
  /*   30 S> */ B(Ldar), R(arg1),
  /*   35 E> */ B(LdaKeyedProperty), R(arg0), U8(4),
                B(Star), R(0),
  /*   42 S> */ B(Ldar), R(arg1),
  /*   47 E> */ B(LdaKeyedProperty), R(arg0), U8(6),
                B(Star), R(0),
  /*   54 S> */ B(Ldar), R(arg1),
  /*   59 E> */ B(LdaKeyedProperty), R(arg0), U8(8),
                B(Star), R(0),
  /*   66 S> */ B(Ldar), R(arg1),
  /*   71 E> */ B(LdaKeyedProperty), R(arg0), U8(10),
                B(Star), R(0),
  /*   78 S> */ B(Ldar), R(arg1),
  /*   83 E> */ B(LdaKeyedProperty), R(arg0), U8(12),
                B(Star), R(0),
  /*   90 S> */ B(Ldar), R(arg1),
  /*   95 E> */ B(LdaKeyedProperty), R(arg0), U8(14),
                B(Star), R(0),
  /*  102 S> */ B(Ldar), R(arg1),
  /*  107 E> */ B(LdaKeyedProperty), R(arg0), U8(16),
                B(Star), R(0),
  /*  114 S> */ B(Ldar), R(arg1),
  /*  119 E> */ B(LdaKeyedProperty), R(arg0), U8(18),
                B(Star), R(0),
  /*  126 S> */ B(Ldar), R(arg1),
  /*  131 E> */ B(LdaKeyedProperty), R(arg0), U8(20),
                B(Star), R(0),
  /*  138 S> */ B(Ldar), R(arg1),
  /*  143 E> */ B(LdaKeyedProperty), R(arg0), U8(22),
                B(Star), R(0),
  /*  150 S> */ B(Ldar), R(arg1),
  /*  155 E> */ B(LdaKeyedProperty), R(arg0), U8(24),
                B(Star), R(0),
  /*  162 S> */ B(Ldar), R(arg1),
  /*  167 E> */ B(LdaKeyedProperty), R(arg0), U8(26),
                B(Star), R(0),
  /*  174 S> */ B(Ldar), R(arg1),
  /*  179 E> */ B(LdaKeyedProperty), R(arg0), U8(28),
                B(Star), R(0),
  /*  186 S> */ B(Ldar), R(arg1),
  /*  191 E> */ B(LdaKeyedProperty), R(arg0), U8(30),
                B(Star), R(0),
  /*  198 S> */ B(Ldar), R(arg1),
  /*  203 E> */ B(LdaKeyedProperty), R(arg0), U8(32),
                B(Star), R(0),
  /*  210 S> */ B(Ldar), R(arg1),
  /*  215 E> */ B(LdaKeyedProperty), R(arg0), U8(34),
                B(Star), R(0),
  /*  222 S> */ B(Ldar), R(arg1),
  /*  227 E> */ B(LdaKeyedProperty), R(arg0), U8(36),
                B(Star), R(0),
  /*  234 S> */ B(Ldar), R(arg1),
  /*  239 E> */ B(LdaKeyedProperty), R(arg0), U8(38),
                B(Star), R(0),
  /*  246 S> */ B(Ldar), R(arg1),
  /*  251 E> */ B(LdaKeyedProperty), R(arg0), U8(40),
                B(Star), R(0),
  /*  258 S> */ B(Ldar), R(arg1),
  /*  263 E> */ B(LdaKeyedProperty), R(arg0), U8(42),
                B(Star), R(0),
  /*  270 S> */ B(Ldar), R(arg1),
  /*  275 E> */ B(LdaKeyedProperty), R(arg0), U8(44),
                B(Star), R(0),
  /*  282 S> */ B(Ldar), R(arg1),
  /*  287 E> */ B(LdaKeyedProperty), R(arg0), U8(46),
                B(Star), R(0),
  /*  294 S> */ B(Ldar), R(arg1),
  /*  299 E> */ B(LdaKeyedProperty), R(arg0), U8(48),
                B(Star), R(0),
  /*  306 S> */ B(Ldar), R(arg1),
  /*  311 E> */ B(LdaKeyedProperty), R(arg0), U8(50),
                B(Star), R(0),
  /*  318 S> */ B(Ldar), R(arg1),
  /*  323 E> */ B(LdaKeyedProperty), R(arg0), U8(52),
                B(Star), R(0),
  /*  330 S> */ B(Ldar), R(arg1),
  /*  335 E> */ B(LdaKeyedProperty), R(arg0), U8(54),
                B(Star), R(0),
  /*  342 S> */ B(Ldar), R(arg1),
  /*  347 E> */ B(LdaKeyedProperty), R(arg0), U8(56),
                B(Star), R(0),
  /*  354 S> */ B(Ldar), R(arg1),
  /*  359 E> */ B(LdaKeyedProperty), R(arg0), U8(58),
                B(Star), R(0),
  /*  366 S> */ B(Ldar), R(arg1),
  /*  371 E> */ B(LdaKeyedProperty), R(arg0), U8(60),
                B(Star), R(0),
  /*  378 S> */ B(Ldar), R(arg1),
  /*  383 E> */ B(LdaKeyedProperty), R(arg0), U8(62),
                B(Star), R(0),
  /*  390 S> */ B(Ldar), R(arg1),
  /*  395 E> */ B(LdaKeyedProperty), R(arg0), U8(64),
                B(Star), R(0),
  /*  402 S> */ B(Ldar), R(arg1),
  /*  407 E> */ B(LdaKeyedProperty), R(arg0), U8(66),
                B(Star), R(0),
  /*  414 S> */ B(Ldar), R(arg1),
  /*  419 E> */ B(LdaKeyedProperty), R(arg0), U8(68),
                B(Star), R(0),
  /*  426 S> */ B(Ldar), R(arg1),
  /*  431 E> */ B(LdaKeyedProperty), R(arg0), U8(70),
                B(Star), R(0),
  /*  438 S> */ B(Ldar), R(arg1),
  /*  443 E> */ B(LdaKeyedProperty), R(arg0), U8(72),
                B(Star), R(0),
  /*  450 S> */ B(Ldar), R(arg1),
  /*  455 E> */ B(LdaKeyedProperty), R(arg0), U8(74),
                B(Star), R(0),
  /*  462 S> */ B(Ldar), R(arg1),
  /*  467 E> */ B(LdaKeyedProperty), R(arg0), U8(76),
                B(Star), R(0),
  /*  474 S> */ B(Ldar), R(arg1),
  /*  479 E> */ B(LdaKeyedProperty), R(arg0), U8(78),
                B(Star), R(0),
  /*  486 S> */ B(Ldar), R(arg1),
  /*  491 E> */ B(LdaKeyedProperty), R(arg0), U8(80),
                B(Star), R(0),
  /*  498 S> */ B(Ldar), R(arg1),
  /*  503 E> */ B(LdaKeyedProperty), R(arg0), U8(82),
                B(Star), R(0),
  /*  510 S> */ B(Ldar), R(arg1),
  /*  515 E> */ B(LdaKeyedProperty), R(arg0), U8(84),
                B(Star), R(0),
  /*  522 S> */ B(Ldar), R(arg1),
  /*  527 E> */ B(LdaKeyedProperty), R(arg0), U8(86),
                B(Star), R(0),
  /*  534 S> */ B(Ldar), R(arg1),
  /*  539 E> */ B(LdaKeyedProperty), R(arg0), U8(88),
                B(Star), R(0),
  /*  546 S> */ B(Ldar), R(arg1),
  /*  551 E> */ B(LdaKeyedProperty), R(arg0), U8(90),
                B(Star), R(0),
  /*  558 S> */ B(Ldar), R(arg1),
  /*  563 E> */ B(LdaKeyedProperty), R(arg0), U8(92),
                B(Star), R(0),
  /*  570 S> */ B(Ldar), R(arg1),
  /*  575 E> */ B(LdaKeyedProperty), R(arg0), U8(94),
                B(Star), R(0),
  /*  582 S> */ B(Ldar), R(arg1),
  /*  587 E> */ B(LdaKeyedProperty), R(arg0), U8(96),
                B(Star), R(0),
  /*  594 S> */ B(Ldar), R(arg1),
  /*  599 E> */ B(LdaKeyedProperty), R(arg0), U8(98),
                B(Star), R(0),
  /*  606 S> */ B(Ldar), R(arg1),
  /*  611 E> */ B(LdaKeyedProperty), R(arg0), U8(100),
                B(Star), R(0),
  /*  618 S> */ B(Ldar), R(arg1),
  /*  623 E> */ B(LdaKeyedProperty), R(arg0), U8(102),
                B(Star), R(0),
  /*  630 S> */ B(Ldar), R(arg1),
  /*  635 E> */ B(LdaKeyedProperty), R(arg0), U8(104),
                B(Star), R(0),
  /*  642 S> */ B(Ldar), R(arg1),
  /*  647 E> */ B(LdaKeyedProperty), R(arg0), U8(106),
                B(Star), R(0),
  /*  654 S> */ B(Ldar), R(arg1),
  /*  659 E> */ B(LdaKeyedProperty), R(arg0), U8(108),
                B(Star), R(0),
  /*  666 S> */ B(Ldar), R(arg1),
  /*  671 E> */ B(LdaKeyedProperty), R(arg0), U8(110),
                B(Star), R(0),
  /*  678 S> */ B(Ldar), R(arg1),
  /*  683 E> */ B(LdaKeyedProperty), R(arg0), U8(112),
                B(Star), R(0),
  /*  690 S> */ B(Ldar), R(arg1),
  /*  695 E> */ B(LdaKeyedProperty), R(arg0), U8(114),
                B(Star), R(0),
  /*  702 S> */ B(Ldar), R(arg1),
  /*  707 E> */ B(LdaKeyedProperty), R(arg0), U8(116),
                B(Star), R(0),
  /*  714 S> */ B(Ldar), R(arg1),
  /*  719 E> */ B(LdaKeyedProperty), R(arg0), U8(118),
                B(Star), R(0),
  /*  726 S> */ B(Ldar), R(arg1),
  /*  731 E> */ B(LdaKeyedProperty), R(arg0), U8(120),
                B(Star), R(0),
  /*  738 S> */ B(Ldar), R(arg1),
  /*  743 E> */ B(LdaKeyedProperty), R(arg0), U8(122),
                B(Star), R(0),
  /*  750 S> */ B(Ldar), R(arg1),
  /*  755 E> */ B(LdaKeyedProperty), R(arg0), U8(124),
                B(Star), R(0),
  /*  762 S> */ B(Ldar), R(arg1),
  /*  767 E> */ B(LdaKeyedProperty), R(arg0), U8(126),
                B(Star), R(0),
  /*  774 S> */ B(Ldar), R(arg1),
  /*  779 E> */ B(LdaKeyedProperty), R(arg0), U8(128),
                B(Star), R(0),
  /*  786 S> */ B(Ldar), R(arg1),
  /*  791 E> */ B(LdaKeyedProperty), R(arg0), U8(130),
                B(Star), R(0),
  /*  798 S> */ B(Ldar), R(arg1),
  /*  803 E> */ B(LdaKeyedProperty), R(arg0), U8(132),
                B(Star), R(0),
  /*  810 S> */ B(Ldar), R(arg1),
  /*  815 E> */ B(LdaKeyedProperty), R(arg0), U8(134),
                B(Star), R(0),
  /*  822 S> */ B(Ldar), R(arg1),
  /*  827 E> */ B(LdaKeyedProperty), R(arg0), U8(136),
                B(Star), R(0),
  /*  834 S> */ B(Ldar), R(arg1),
  /*  839 E> */ B(LdaKeyedProperty), R(arg0), U8(138),
                B(Star), R(0),
  /*  846 S> */ B(Ldar), R(arg1),
  /*  851 E> */ B(LdaKeyedProperty), R(arg0), U8(140),
                B(Star), R(0),
  /*  858 S> */ B(Ldar), R(arg1),
  /*  863 E> */ B(LdaKeyedProperty), R(arg0), U8(142),
                B(Star), R(0),
  /*  870 S> */ B(Ldar), R(arg1),
  /*  875 E> */ B(LdaKeyedProperty), R(arg0), U8(144),
                B(Star), R(0),
  /*  882 S> */ B(Ldar), R(arg1),
  /*  887 E> */ B(LdaKeyedProperty), R(arg0), U8(146),
                B(Star), R(0),
  /*  894 S> */ B(Ldar), R(arg1),
  /*  899 E> */ B(LdaKeyedProperty), R(arg0), U8(148),
                B(Star), R(0),
  /*  906 S> */ B(Ldar), R(arg1),
  /*  911 E> */ B(LdaKeyedProperty), R(arg0), U8(150),
                B(Star), R(0),
  /*  918 S> */ B(Ldar), R(arg1),
  /*  923 E> */ B(LdaKeyedProperty), R(arg0), U8(152),
                B(Star), R(0),
  /*  930 S> */ B(Ldar), R(arg1),
  /*  935 E> */ B(LdaKeyedProperty), R(arg0), U8(154),
                B(Star), R(0),
  /*  942 S> */ B(Ldar), R(arg1),
  /*  947 E> */ B(LdaKeyedProperty), R(arg0), U8(156),
                B(Star), R(0),
  /*  954 S> */ B(Ldar), R(arg1),
  /*  959 E> */ B(LdaKeyedProperty), R(arg0), U8(158),
                B(Star), R(0),
  /*  966 S> */ B(Ldar), R(arg1),
  /*  971 E> */ B(LdaKeyedProperty), R(arg0), U8(160),
                B(Star), R(0),
  /*  978 S> */ B(Ldar), R(arg1),
  /*  983 E> */ B(LdaKeyedProperty), R(arg0), U8(162),
                B(Star), R(0),
  /*  990 S> */ B(Ldar), R(arg1),
  /*  995 E> */ B(LdaKeyedProperty), R(arg0), U8(164),
                B(Star), R(0),
  /* 1002 S> */ B(Ldar), R(arg1),
  /* 1007 E> */ B(LdaKeyedProperty), R(arg0), U8(166),
                B(Star), R(0),
  /* 1014 S> */ B(Ldar), R(arg1),
  /* 1019 E> */ B(LdaKeyedProperty), R(arg0), U8(168),
                B(Star), R(0),
  /* 1026 S> */ B(Ldar), R(arg1),
  /* 1031 E> */ B(LdaKeyedProperty), R(arg0), U8(170),
                B(Star), R(0),
  /* 1038 S> */ B(Ldar), R(arg1),
  /* 1043 E> */ B(LdaKeyedProperty), R(arg0), U8(172),
                B(Star), R(0),
  /* 1050 S> */ B(Ldar), R(arg1),
  /* 1055 E> */ B(LdaKeyedProperty), R(arg0), U8(174),
                B(Star), R(0),
  /* 1062 S> */ B(Ldar), R(arg1),
  /* 1067 E> */ B(LdaKeyedProperty), R(arg0), U8(176),
                B(Star), R(0),
  /* 1074 S> */ B(Ldar), R(arg1),
  /* 1079 E> */ B(LdaKeyedProperty), R(arg0), U8(178),
                B(Star), R(0),
  /* 1086 S> */ B(Ldar), R(arg1),
  /* 1091 E> */ B(LdaKeyedProperty), R(arg0), U8(180),
                B(Star), R(0),
  /* 1098 S> */ B(Ldar), R(arg1),
  /* 1103 E> */ B(LdaKeyedProperty), R(arg0), U8(182),
                B(Star), R(0),
  /* 1110 S> */ B(Ldar), R(arg1),
  /* 1115 E> */ B(LdaKeyedProperty), R(arg0), U8(184),
                B(Star), R(0),
  /* 1122 S> */ B(Ldar), R(arg1),
  /* 1127 E> */ B(LdaKeyedProperty), R(arg0), U8(186),
                B(Star), R(0),
  /* 1134 S> */ B(Ldar), R(arg1),
  /* 1139 E> */ B(LdaKeyedProperty), R(arg0), U8(188),
                B(Star), R(0),
  /* 1146 S> */ B(Ldar), R(arg1),
  /* 1151 E> */ B(LdaKeyedProperty), R(arg0), U8(190),
                B(Star), R(0),
  /* 1158 S> */ B(Ldar), R(arg1),
  /* 1163 E> */ B(LdaKeyedProperty), R(arg0), U8(192),
                B(Star), R(0),
  /* 1170 S> */ B(Ldar), R(arg1),
  /* 1175 E> */ B(LdaKeyedProperty), R(arg0), U8(194),
                B(Star), R(0),
  /* 1182 S> */ B(Ldar), R(arg1),
  /* 1187 E> */ B(LdaKeyedProperty), R(arg0), U8(196),
                B(Star), R(0),
  /* 1194 S> */ B(Ldar), R(arg1),
  /* 1199 E> */ B(LdaKeyedProperty), R(arg0), U8(198),
                B(Star), R(0),
  /* 1206 S> */ B(Ldar), R(arg1),
  /* 1211 E> */ B(LdaKeyedProperty), R(arg0), U8(200),
                B(Star), R(0),
  /* 1218 S> */ B(Ldar), R(arg1),
  /* 1223 E> */ B(LdaKeyedProperty), R(arg0), U8(202),
                B(Star), R(0),
  /* 1230 S> */ B(Ldar), R(arg1),
  /* 1235 E> */ B(LdaKeyedProperty), R(arg0), U8(204),
                B(Star), R(0),
  /* 1242 S> */ B(Ldar), R(arg1),
  /* 1247 E> */ B(LdaKeyedProperty), R(arg0), U8(206),
                B(Star), R(0),
  /* 1254 S> */ B(Ldar), R(arg1),
  /* 1259 E> */ B(LdaKeyedProperty), R(arg0), U8(208),
                B(Star), R(0),
  /* 1266 S> */ B(Ldar), R(arg1),
  /* 1271 E> */ B(LdaKeyedProperty), R(arg0), U8(210),
                B(Star), R(0),
  /* 1278 S> */ B(Ldar), R(arg1),
  /* 1283 E> */ B(LdaKeyedProperty), R(arg0), U8(212),
                B(Star), R(0),
  /* 1290 S> */ B(Ldar), R(arg1),
  /* 1295 E> */ B(LdaKeyedProperty), R(arg0), U8(214),
                B(Star), R(0),
  /* 1302 S> */ B(Ldar), R(arg1),
  /* 1307 E> */ B(LdaKeyedProperty), R(arg0), U8(216),
                B(Star), R(0),
  /* 1314 S> */ B(Ldar), R(arg1),
  /* 1319 E> */ B(LdaKeyedProperty), R(arg0), U8(218),
                B(Star), R(0),
  /* 1326 S> */ B(Ldar), R(arg1),
  /* 1331 E> */ B(LdaKeyedProperty), R(arg0), U8(220),
                B(Star), R(0),
  /* 1338 S> */ B(Ldar), R(arg1),
  /* 1343 E> */ B(LdaKeyedProperty), R(arg0), U8(222),
                B(Star), R(0),
  /* 1350 S> */ B(Ldar), R(arg1),
  /* 1355 E> */ B(LdaKeyedProperty), R(arg0), U8(224),
                B(Star), R(0),
  /* 1362 S> */ B(Ldar), R(arg1),
  /* 1367 E> */ B(LdaKeyedProperty), R(arg0), U8(226),
                B(Star), R(0),
  /* 1374 S> */ B(Ldar), R(arg1),
  /* 1379 E> */ B(LdaKeyedProperty), R(arg0), U8(228),
                B(Star), R(0),
  /* 1386 S> */ B(Ldar), R(arg1),
  /* 1391 E> */ B(LdaKeyedProperty), R(arg0), U8(230),
                B(Star), R(0),
  /* 1398 S> */ B(Ldar), R(arg1),
  /* 1403 E> */ B(LdaKeyedProperty), R(arg0), U8(232),
                B(Star), R(0),
  /* 1410 S> */ B(Ldar), R(arg1),
  /* 1415 E> */ B(LdaKeyedProperty), R(arg0), U8(234),
                B(Star), R(0),
  /* 1422 S> */ B(Ldar), R(arg1),
  /* 1427 E> */ B(LdaKeyedProperty), R(arg0), U8(236),
                B(Star), R(0),
  /* 1434 S> */ B(Ldar), R(arg1),
  /* 1439 E> */ B(LdaKeyedProperty), R(arg0), U8(238),
                B(Star), R(0),
  /* 1446 S> */ B(Ldar), R(arg1),
  /* 1451 E> */ B(LdaKeyedProperty), R(arg0), U8(240),
                B(Star), R(0),
  /* 1458 S> */ B(Ldar), R(arg1),
  /* 1463 E> */ B(LdaKeyedProperty), R(arg0), U8(242),
                B(Star), R(0),
  /* 1470 S> */ B(Ldar), R(arg1),
  /* 1475 E> */ B(LdaKeyedProperty), R(arg0), U8(244),
                B(Star), R(0),
  /* 1482 S> */ B(Ldar), R(arg1),
  /* 1487 E> */ B(LdaKeyedProperty), R(arg0), U8(246),
                B(Star), R(0),
  /* 1494 S> */ B(Ldar), R(arg1),
  /* 1499 E> */ B(LdaKeyedProperty), R(arg0), U8(248),
                B(Star), R(0),
  /* 1506 S> */ B(Ldar), R(arg1),
  /* 1511 E> */ B(LdaKeyedProperty), R(arg0), U8(250),
                B(Star), R(0),
  /* 1518 S> */ B(Ldar), R(arg1),
  /* 1523 E> */ B(LdaKeyedProperty), R(arg0), U8(252),
                B(Star), R(0),
  /* 1530 S> */ B(Ldar), R(arg1),
  /* 1535 E> */ B(LdaKeyedProperty), R(arg0), U8(254),
                B(Star), R(0),
  /* 1542 S> */ B(Ldar), R(arg1),
  /* 1547 E> */ B(Wide), B(LdaKeyedProperty), R16(arg0), U16(256),
                B(Star), R(0),
  /* 1554 S> */ B(Ldar), R(arg1),
  /* 1559 E> */ B(Wide), B(LdaKeyedProperty), R16(arg0), U16(258),
                B(Star), R(0),
  /* 1566 S> */ B(Ldar), R(arg1),
  /* 1574 E> */ B(Wide), B(LdaKeyedProperty), R16(arg0), U16(260),
  /* 1578 S> */ B(Return),
]
constant pool: [
]
handlers: [
]

