#
# Autogenerated by generate-bytecode-expectations.
#

---
wrap: yes

---
snippet: "
  return /ab+d/;
"
frame size: 0
parameter count: 1
bytecode array length: 6
bytecodes: [
  /*   30 E> */ B(StackCheck),
  /*   34 S> */ B(CreateRegExpLiteral), U8(0), U8(4), U8(0),
  /*   48 S> */ B(Return),
]
constant pool: [
  ONE_BYTE_INTERNALIZED_STRING_TYPE ["ab+d"],
]
handlers: [
]

---
snippet: "
  return /(\\w+)\\s(\\w+)/i;
"
frame size: 0
parameter count: 1
bytecode array length: 6
bytecodes: [
  /*   30 E> */ B(StackCheck),
  /*   34 S> */ B(CreateRegExpLiteral), U8(0), U8(4), U8(2),
  /*   57 S> */ B(Return),
]
constant pool: [
  ONE_BYTE_INTERNALIZED_STRING_TYPE ["(\u005cw+)\u005cs(\u005cw+)"],
]
handlers: [
]

---
snippet: "
  return /ab+d/.exec('abdd');
"
frame size: 3
parameter count: 1
bytecode array length: 23
bytecodes: [
  /*   30 E> */ B(StackCheck),
  /*   34 S> */ B(CreateRegExpLiteral), U8(0), U8(6), U8(0),
                B(Star), R(1),
  /*   48 E> */ B(LdaNamedProperty), R(1), U8(1), U8(7),
                B(Star), R(0),
                B(LdaConstant), U8(2),
                B(Star), R(2),
  /*   48 E> */ B(CallProperty1), R(0), R(1), R(2), U8(4),
  /*   61 S> */ B(Return),
]
constant pool: [
  ONE_BYTE_INTERNALIZED_STRING_TYPE ["ab+d"],
  ONE_BYTE_INTERNALIZED_STRING_TYPE ["exec"],
  ONE_BYTE_INTERNALIZED_STRING_TYPE ["abdd"],
]
handlers: [
]

