#
# Autogenerated by generate-bytecode-expectations.
#

---
wrap: yes

---
snippet: "
  var a;
  a = 1.23;
  a = 1.23;
  a = 1.23;
  a = 1.23;
  a = 1.23;
  a = 1.23;
  a = 1.23;
  a = 1.23;
  a = 1.23;
  a = 1.23;
  a = 1.23;
  a = 1.23;
  a = 1.23;
  a = 1.23;
  a = 1.23;
  a = 1.23;
  a = 1.23;
  a = 1.23;
  a = 1.23;
  a = 1.23;
  a = 1.23;
  a = 1.23;
  a = 1.23;
  a = 1.23;
  a = 1.23;
  a = 1.23;
  a = 1.23;
  a = 1.23;
  a = 1.23;
  a = 1.23;
  a = 1.23;
  a = 1.23;
  a = 1.23;
  a = 1.23;
  a = 1.23;
  a = 1.23;
  a = 1.23;
  a = 1.23;
  a = 1.23;
  a = 1.23;
  a = 1.23;
  a = 1.23;
  a = 1.23;
  a = 1.23;
  a = 1.23;
  a = 1.23;
  a = 1.23;
  a = 1.23;
  a = 1.23;
  a = 1.23;
  a = 1.23;
  a = 1.23;
  a = 1.23;
  a = 1.23;
  a = 1.23;
  a = 1.23;
  a = 1.23;
  a = 1.23;
  a = 1.23;
  a = 1.23;
  a = 1.23;
  a = 1.23;
  a = 1.23;
  a = 1.23;
  a = 1.23;
  a = 1.23;
  a = 1.23;
  a = 1.23;
  a = 1.23;
  a = 1.23;
  a = 1.23;
  a = 1.23;
  a = 1.23;
  a = 1.23;
  a = 1.23;
  a = 1.23;
  a = 1.23;
  a = 1.23;
  a = 1.23;
  a = 1.23;
  a = 1.23;
  a = 1.23;
  a = 1.23;
  a = 1.23;
  a = 1.23;
  a = 1.23;
  a = 1.23;
  a = 1.23;
  a = 1.23;
  a = 1.23;
  a = 1.23;
  a = 1.23;
  a = 1.23;
  a = 1.23;
  a = 1.23;
  a = 1.23;
  a = 1.23;
  a = 1.23;
  a = 1.23;
  a = 1.23;
  a = 1.23;
  a = 1.23;
  a = 1.23;
  a = 1.23;
  a = 1.23;
  a = 1.23;
  a = 1.23;
  a = 1.23;
  a = 1.23;
  a = 1.23;
  a = 1.23;
  a = 1.23;
  a = 1.23;
  a = 1.23;
  a = 1.23;
  a = 1.23;
  a = 1.23;
  a = 1.23;
  a = 1.23;
  a = 1.23;
  a = 1.23;
  a = 1.23;
  a = 1.23;
  a = 1.23;
  a = 1.23;
  a = 1.23;
  a = 1.23;
  a = 1.23;
  a = 1.23;
  a = 1.23;
  a = 1.23;
  a = 1.23;
  a = 1.23;
  a = 1.23;
  a = 1.23;
  a = 1.23;
  a = 1.23;
  a = 1.23;
  a = 1.23;
  a = 1.23;
  a = 1.23;
  a = 1.23;
  a = 1.23;
  a = 1.23;
  a = 1.23;
  a = 1.23;
  a = 1.23;
  a = 1.23;
  a = 1.23;
  a = 1.23;
  a = 1.23;
  a = 1.23;
  a = 1.23;
  a = 1.23;
  a = 1.23;
  a = 1.23;
  a = 1.23;
  a = 1.23;
  a = 1.23;
  a = 1.23;
  a = 1.23;
  a = 1.23;
  a = 1.23;
  a = 1.23;
  a = 1.23;
  a = 1.23;
  a = 1.23;
  a = 1.23;
  a = 1.23;
  a = 1.23;
  a = 1.23;
  a = 1.23;
  a = 1.23;
  a = 1.23;
  a = 1.23;
  a = 1.23;
  a = 1.23;
  a = 1.23;
  a = 1.23;
  a = 1.23;
  a = 1.23;
  a = 1.23;
  a = 1.23;
  a = 1.23;
  a = 1.23;
  a = 1.23;
  a = 1.23;
  a = 1.23;
  a = 1.23;
  a = 1.23;
  a = 1.23;
  a = 1.23;
  a = 1.23;
  a = 1.23;
  a = 1.23;
  a = 1.23;
  a = 1.23;
  a = 1.23;
  a = 1.23;
  a = 1.23;
  a = 1.23;
  a = 1.23;
  a = 1.23;
  a = 1.23;
  a = 1.23;
  a = 1.23;
  a = 1.23;
  a = 1.23;
  a = 1.23;
  a = 1.23;
  a = 1.23;
  a = 1.23;
  a = 1.23;
  a = 1.23;
  a = 1.23;
  a = 1.23;
  a = 1.23;
  a = 1.23;
  a = 1.23;
  a = 1.23;
  a = 1.23;
  a = 1.23;
  a = 1.23;
  a = 1.23;
  a = 1.23;
  a = 1.23;
  a = 1.23;
  a = 1.23;
  a = 1.23;
  a = 1.23;
  a = 1.23;
  a = 1.23;
  a = 1.23;
  a = 1.23;
  a = 1.23;
  a = 1.23;
  a = 1.23;
  a = 1.23;
  a = 1.23;
  a = 1.23;
  a = 1.23;
  a = 1.23;
  a = 1.23;
  a = 1.23;
  a = 1.23;
  a = 1.23;
  a = 1.23;
  a = 1.23;
  a = 1.23;
  a = 1.23;
  a = 1.23;
  a = 1.23;
  a = 1.23;
  a = 1.23;
  a = 1.23;
  a = 1.23;
  return /ab+d/;
"
frame size: 1
parameter count: 1
bytecode array length: 1033
bytecodes: [
  /*   30 E> */ B(StackCheck),
  /*   41 S> */ B(LdaConstant), U8(0),
                B(Star), R(0),
  /*   51 S> */ B(LdaConstant), U8(1),
                B(Star), R(0),
  /*   61 S> */ B(LdaConstant), U8(2),
                B(Star), R(0),
  /*   71 S> */ B(LdaConstant), U8(3),
                B(Star), R(0),
  /*   81 S> */ B(LdaConstant), U8(4),
                B(Star), R(0),
  /*   91 S> */ B(LdaConstant), U8(5),
                B(Star), R(0),
  /*  101 S> */ B(LdaConstant), U8(6),
                B(Star), R(0),
  /*  111 S> */ B(LdaConstant), U8(7),
                B(Star), R(0),
  /*  121 S> */ B(LdaConstant), U8(8),
                B(Star), R(0),
  /*  131 S> */ B(LdaConstant), U8(9),
                B(Star), R(0),
  /*  141 S> */ B(LdaConstant), U8(10),
                B(Star), R(0),
  /*  151 S> */ B(LdaConstant), U8(11),
                B(Star), R(0),
  /*  161 S> */ B(LdaConstant), U8(12),
                B(Star), R(0),
  /*  171 S> */ B(LdaConstant), U8(13),
                B(Star), R(0),
  /*  181 S> */ B(LdaConstant), U8(14),
                B(Star), R(0),
  /*  191 S> */ B(LdaConstant), U8(15),
                B(Star), R(0),
  /*  201 S> */ B(LdaConstant), U8(16),
                B(Star), R(0),
  /*  211 S> */ B(LdaConstant), U8(17),
                B(Star), R(0),
  /*  221 S> */ B(LdaConstant), U8(18),
                B(Star), R(0),
  /*  231 S> */ B(LdaConstant), U8(19),
                B(Star), R(0),
  /*  241 S> */ B(LdaConstant), U8(20),
                B(Star), R(0),
  /*  251 S> */ B(LdaConstant), U8(21),
                B(Star), R(0),
  /*  261 S> */ B(LdaConstant), U8(22),
                B(Star), R(0),
  /*  271 S> */ B(LdaConstant), U8(23),
                B(Star), R(0),
  /*  281 S> */ B(LdaConstant), U8(24),
                B(Star), R(0),
  /*  291 S> */ B(LdaConstant), U8(25),
                B(Star), R(0),
  /*  301 S> */ B(LdaConstant), U8(26),
                B(Star), R(0),
  /*  311 S> */ B(LdaConstant), U8(27),
                B(Star), R(0),
  /*  321 S> */ B(LdaConstant), U8(28),
                B(Star), R(0),
  /*  331 S> */ B(LdaConstant), U8(29),
                B(Star), R(0),
  /*  341 S> */ B(LdaConstant), U8(30),
                B(Star), R(0),
  /*  351 S> */ B(LdaConstant), U8(31),
                B(Star), R(0),
  /*  361 S> */ B(LdaConstant), U8(32),
                B(Star), R(0),
  /*  371 S> */ B(LdaConstant), U8(33),
                B(Star), R(0),
  /*  381 S> */ B(LdaConstant), U8(34),
                B(Star), R(0),
  /*  391 S> */ B(LdaConstant), U8(35),
                B(Star), R(0),
  /*  401 S> */ B(LdaConstant), U8(36),
                B(Star), R(0),
  /*  411 S> */ B(LdaConstant), U8(37),
                B(Star), R(0),
  /*  421 S> */ B(LdaConstant), U8(38),
                B(Star), R(0),
  /*  431 S> */ B(LdaConstant), U8(39),
                B(Star), R(0),
  /*  441 S> */ B(LdaConstant), U8(40),
                B(Star), R(0),
  /*  451 S> */ B(LdaConstant), U8(41),
                B(Star), R(0),
  /*  461 S> */ B(LdaConstant), U8(42),
                B(Star), R(0),
  /*  471 S> */ B(LdaConstant), U8(43),
                B(Star), R(0),
  /*  481 S> */ B(LdaConstant), U8(44),
                B(Star), R(0),
  /*  491 S> */ B(LdaConstant), U8(45),
                B(Star), R(0),
  /*  501 S> */ B(LdaConstant), U8(46),
                B(Star), R(0),
  /*  511 S> */ B(LdaConstant), U8(47),
                B(Star), R(0),
  /*  521 S> */ B(LdaConstant), U8(48),
                B(Star), R(0),
  /*  531 S> */ B(LdaConstant), U8(49),
                B(Star), R(0),
  /*  541 S> */ B(LdaConstant), U8(50),
                B(Star), R(0),
  /*  551 S> */ B(LdaConstant), U8(51),
                B(Star), R(0),
  /*  561 S> */ B(LdaConstant), U8(52),
                B(Star), R(0),
  /*  571 S> */ B(LdaConstant), U8(53),
                B(Star), R(0),
  /*  581 S> */ B(LdaConstant), U8(54),
                B(Star), R(0),
  /*  591 S> */ B(LdaConstant), U8(55),
                B(Star), R(0),
  /*  601 S> */ B(LdaConstant), U8(56),
                B(Star), R(0),
  /*  611 S> */ B(LdaConstant), U8(57),
                B(Star), R(0),
  /*  621 S> */ B(LdaConstant), U8(58),
                B(Star), R(0),
  /*  631 S> */ B(LdaConstant), U8(59),
                B(Star), R(0),
  /*  641 S> */ B(LdaConstant), U8(60),
                B(Star), R(0),
  /*  651 S> */ B(LdaConstant), U8(61),
                B(Star), R(0),
  /*  661 S> */ B(LdaConstant), U8(62),
                B(Star), R(0),
  /*  671 S> */ B(LdaConstant), U8(63),
                B(Star), R(0),
  /*  681 S> */ B(LdaConstant), U8(64),
                B(Star), R(0),
  /*  691 S> */ B(LdaConstant), U8(65),
                B(Star), R(0),
  /*  701 S> */ B(LdaConstant), U8(66),
                B(Star), R(0),
  /*  711 S> */ B(LdaConstant), U8(67),
                B(Star), R(0),
  /*  721 S> */ B(LdaConstant), U8(68),
                B(Star), R(0),
  /*  731 S> */ B(LdaConstant), U8(69),
                B(Star), R(0),
  /*  741 S> */ B(LdaConstant), U8(70),
                B(Star), R(0),
  /*  751 S> */ B(LdaConstant), U8(71),
                B(Star), R(0),
  /*  761 S> */ B(LdaConstant), U8(72),
                B(Star), R(0),
  /*  771 S> */ B(LdaConstant), U8(73),
                B(Star), R(0),
  /*  781 S> */ B(LdaConstant), U8(74),
                B(Star), R(0),
  /*  791 S> */ B(LdaConstant), U8(75),
                B(Star), R(0),
  /*  801 S> */ B(LdaConstant), U8(76),
                B(Star), R(0),
  /*  811 S> */ B(LdaConstant), U8(77),
                B(Star), R(0),
  /*  821 S> */ B(LdaConstant), U8(78),
                B(Star), R(0),
  /*  831 S> */ B(LdaConstant), U8(79),
                B(Star), R(0),
  /*  841 S> */ B(LdaConstant), U8(80),
                B(Star), R(0),
  /*  851 S> */ B(LdaConstant), U8(81),
                B(Star), R(0),
  /*  861 S> */ B(LdaConstant), U8(82),
                B(Star), R(0),
  /*  871 S> */ B(LdaConstant), U8(83),
                B(Star), R(0),
  /*  881 S> */ B(LdaConstant), U8(84),
                B(Star), R(0),
  /*  891 S> */ B(LdaConstant), U8(85),
                B(Star), R(0),
  /*  901 S> */ B(LdaConstant), U8(86),
                B(Star), R(0),
  /*  911 S> */ B(LdaConstant), U8(87),
                B(Star), R(0),
  /*  921 S> */ B(LdaConstant), U8(88),
                B(Star), R(0),
  /*  931 S> */ B(LdaConstant), U8(89),
                B(Star), R(0),
  /*  941 S> */ B(LdaConstant), U8(90),
                B(Star), R(0),
  /*  951 S> */ B(LdaConstant), U8(91),
                B(Star), R(0),
  /*  961 S> */ B(LdaConstant), U8(92),
                B(Star), R(0),
  /*  971 S> */ B(LdaConstant), U8(93),
                B(Star), R(0),
  /*  981 S> */ B(LdaConstant), U8(94),
                B(Star), R(0),
  /*  991 S> */ B(LdaConstant), U8(95),
                B(Star), R(0),
  /* 1001 S> */ B(LdaConstant), U8(96),
                B(Star), R(0),
  /* 1011 S> */ B(LdaConstant), U8(97),
                B(Star), R(0),
  /* 1021 S> */ B(LdaConstant), U8(98),
                B(Star), R(0),
  /* 1031 S> */ B(LdaConstant), U8(99),
                B(Star), R(0),
  /* 1041 S> */ B(LdaConstant), U8(100),
                B(Star), R(0),
  /* 1051 S> */ B(LdaConstant), U8(101),
                B(Star), R(0),
  /* 1061 S> */ B(LdaConstant), U8(102),
                B(Star), R(0),
  /* 1071 S> */ B(LdaConstant), U8(103),
                B(Star), R(0),
  /* 1081 S> */ B(LdaConstant), U8(104),
                B(Star), R(0),
  /* 1091 S> */ B(LdaConstant), U8(105),
                B(Star), R(0),
  /* 1101 S> */ B(LdaConstant), U8(106),
                B(Star), R(0),
  /* 1111 S> */ B(LdaConstant), U8(107),
                B(Star), R(0),
  /* 1121 S> */ B(LdaConstant), U8(108),
                B(Star), R(0),
  /* 1131 S> */ B(LdaConstant), U8(109),
                B(Star), R(0),
  /* 1141 S> */ B(LdaConstant), U8(110),
                B(Star), R(0),
  /* 1151 S> */ B(LdaConstant), U8(111),
                B(Star), R(0),
  /* 1161 S> */ B(LdaConstant), U8(112),
                B(Star), R(0),
  /* 1171 S> */ B(LdaConstant), U8(113),
                B(Star), R(0),
  /* 1181 S> */ B(LdaConstant), U8(114),
                B(Star), R(0),
  /* 1191 S> */ B(LdaConstant), U8(115),
                B(Star), R(0),
  /* 1201 S> */ B(LdaConstant), U8(116),
                B(Star), R(0),
  /* 1211 S> */ B(LdaConstant), U8(117),
                B(Star), R(0),
  /* 1221 S> */ B(LdaConstant), U8(118),
                B(Star), R(0),
  /* 1231 S> */ B(LdaConstant), U8(119),
                B(Star), R(0),
  /* 1241 S> */ B(LdaConstant), U8(120),
                B(Star), R(0),
  /* 1251 S> */ B(LdaConstant), U8(121),
                B(Star), R(0),
  /* 1261 S> */ B(LdaConstant), U8(122),
                B(Star), R(0),
  /* 1271 S> */ B(LdaConstant), U8(123),
                B(Star), R(0),
  /* 1281 S> */ B(LdaConstant), U8(124),
                B(Star), R(0),
  /* 1291 S> */ B(LdaConstant), U8(125),
                B(Star), R(0),
  /* 1301 S> */ B(LdaConstant), U8(126),
                B(Star), R(0),
  /* 1311 S> */ B(LdaConstant), U8(127),
                B(Star), R(0),
  /* 1321 S> */ B(LdaConstant), U8(128),
                B(Star), R(0),
  /* 1331 S> */ B(LdaConstant), U8(129),
                B(Star), R(0),
  /* 1341 S> */ B(LdaConstant), U8(130),
                B(Star), R(0),
  /* 1351 S> */ B(LdaConstant), U8(131),
                B(Star), R(0),
  /* 1361 S> */ B(LdaConstant), U8(132),
                B(Star), R(0),
  /* 1371 S> */ B(LdaConstant), U8(133),
                B(Star), R(0),
  /* 1381 S> */ B(LdaConstant), U8(134),
                B(Star), R(0),
  /* 1391 S> */ B(LdaConstant), U8(135),
                B(Star), R(0),
  /* 1401 S> */ B(LdaConstant), U8(136),
                B(Star), R(0),
  /* 1411 S> */ B(LdaConstant), U8(137),
                B(Star), R(0),
  /* 1421 S> */ B(LdaConstant), U8(138),
                B(Star), R(0),
  /* 1431 S> */ B(LdaConstant), U8(139),
                B(Star), R(0),
  /* 1441 S> */ B(LdaConstant), U8(140),
                B(Star), R(0),
  /* 1451 S> */ B(LdaConstant), U8(141),
                B(Star), R(0),
  /* 1461 S> */ B(LdaConstant), U8(142),
                B(Star), R(0),
  /* 1471 S> */ B(LdaConstant), U8(143),
                B(Star), R(0),
  /* 1481 S> */ B(LdaConstant), U8(144),
                B(Star), R(0),
  /* 1491 S> */ B(LdaConstant), U8(145),
                B(Star), R(0),
  /* 1501 S> */ B(LdaConstant), U8(146),
                B(Star), R(0),
  /* 1511 S> */ B(LdaConstant), U8(147),
                B(Star), R(0),
  /* 1521 S> */ B(LdaConstant), U8(148),
                B(Star), R(0),
  /* 1531 S> */ B(LdaConstant), U8(149),
                B(Star), R(0),
  /* 1541 S> */ B(LdaConstant), U8(150),
                B(Star), R(0),
  /* 1551 S> */ B(LdaConstant), U8(151),
                B(Star), R(0),
  /* 1561 S> */ B(LdaConstant), U8(152),
                B(Star), R(0),
  /* 1571 S> */ B(LdaConstant), U8(153),
                B(Star), R(0),
  /* 1581 S> */ B(LdaConstant), U8(154),
                B(Star), R(0),
  /* 1591 S> */ B(LdaConstant), U8(155),
                B(Star), R(0),
  /* 1601 S> */ B(LdaConstant), U8(156),
                B(Star), R(0),
  /* 1611 S> */ B(LdaConstant), U8(157),
                B(Star), R(0),
  /* 1621 S> */ B(LdaConstant), U8(158),
                B(Star), R(0),
  /* 1631 S> */ B(LdaConstant), U8(159),
                B(Star), R(0),
  /* 1641 S> */ B(LdaConstant), U8(160),
                B(Star), R(0),
  /* 1651 S> */ B(LdaConstant), U8(161),
                B(Star), R(0),
  /* 1661 S> */ B(LdaConstant), U8(162),
                B(Star), R(0),
  /* 1671 S> */ B(LdaConstant), U8(163),
                B(Star), R(0),
  /* 1681 S> */ B(LdaConstant), U8(164),
                B(Star), R(0),
  /* 1691 S> */ B(LdaConstant), U8(165),
                B(Star), R(0),
  /* 1701 S> */ B(LdaConstant), U8(166),
                B(Star), R(0),
  /* 1711 S> */ B(LdaConstant), U8(167),
                B(Star), R(0),
  /* 1721 S> */ B(LdaConstant), U8(168),
                B(Star), R(0),
  /* 1731 S> */ B(LdaConstant), U8(169),
                B(Star), R(0),
  /* 1741 S> */ B(LdaConstant), U8(170),
                B(Star), R(0),
  /* 1751 S> */ B(LdaConstant), U8(171),
                B(Star), R(0),
  /* 1761 S> */ B(LdaConstant), U8(172),
                B(Star), R(0),
  /* 1771 S> */ B(LdaConstant), U8(173),
                B(Star), R(0),
  /* 1781 S> */ B(LdaConstant), U8(174),
                B(Star), R(0),
  /* 1791 S> */ B(LdaConstant), U8(175),
                B(Star), R(0),
  /* 1801 S> */ B(LdaConstant), U8(176),
                B(Star), R(0),
  /* 1811 S> */ B(LdaConstant), U8(177),
                B(Star), R(0),
  /* 1821 S> */ B(LdaConstant), U8(178),
                B(Star), R(0),
  /* 1831 S> */ B(LdaConstant), U8(179),
                B(Star), R(0),
  /* 1841 S> */ B(LdaConstant), U8(180),
                B(Star), R(0),
  /* 1851 S> */ B(LdaConstant), U8(181),
                B(Star), R(0),
  /* 1861 S> */ B(LdaConstant), U8(182),
                B(Star), R(0),
  /* 1871 S> */ B(LdaConstant), U8(183),
                B(Star), R(0),
  /* 1881 S> */ B(LdaConstant), U8(184),
                B(Star), R(0),
  /* 1891 S> */ B(LdaConstant), U8(185),
                B(Star), R(0),
  /* 1901 S> */ B(LdaConstant), U8(186),
                B(Star), R(0),
  /* 1911 S> */ B(LdaConstant), U8(187),
                B(Star), R(0),
  /* 1921 S> */ B(LdaConstant), U8(188),
                B(Star), R(0),
  /* 1931 S> */ B(LdaConstant), U8(189),
                B(Star), R(0),
  /* 1941 S> */ B(LdaConstant), U8(190),
                B(Star), R(0),
  /* 1951 S> */ B(LdaConstant), U8(191),
                B(Star), R(0),
  /* 1961 S> */ B(LdaConstant), U8(192),
                B(Star), R(0),
  /* 1971 S> */ B(LdaConstant), U8(193),
                B(Star), R(0),
  /* 1981 S> */ B(LdaConstant), U8(194),
                B(Star), R(0),
  /* 1991 S> */ B(LdaConstant), U8(195),
                B(Star), R(0),
  /* 2001 S> */ B(LdaConstant), U8(196),
                B(Star), R(0),
  /* 2011 S> */ B(LdaConstant), U8(197),
                B(Star), R(0),
  /* 2021 S> */ B(LdaConstant), U8(198),
                B(Star), R(0),
  /* 2031 S> */ B(LdaConstant), U8(199),
                B(Star), R(0),
  /* 2041 S> */ B(LdaConstant), U8(200),
                B(Star), R(0),
  /* 2051 S> */ B(LdaConstant), U8(201),
                B(Star), R(0),
  /* 2061 S> */ B(LdaConstant), U8(202),
                B(Star), R(0),
  /* 2071 S> */ B(LdaConstant), U8(203),
                B(Star), R(0),
  /* 2081 S> */ B(LdaConstant), U8(204),
                B(Star), R(0),
  /* 2091 S> */ B(LdaConstant), U8(205),
                B(Star), R(0),
  /* 2101 S> */ B(LdaConstant), U8(206),
                B(Star), R(0),
  /* 2111 S> */ B(LdaConstant), U8(207),
                B(Star), R(0),
  /* 2121 S> */ B(LdaConstant), U8(208),
                B(Star), R(0),
  /* 2131 S> */ B(LdaConstant), U8(209),
                B(Star), R(0),
  /* 2141 S> */ B(LdaConstant), U8(210),
                B(Star), R(0),
  /* 2151 S> */ B(LdaConstant), U8(211),
                B(Star), R(0),
  /* 2161 S> */ B(LdaConstant), U8(212),
                B(Star), R(0),
  /* 2171 S> */ B(LdaConstant), U8(213),
                B(Star), R(0),
  /* 2181 S> */ B(LdaConstant), U8(214),
                B(Star), R(0),
  /* 2191 S> */ B(LdaConstant), U8(215),
                B(Star), R(0),
  /* 2201 S> */ B(LdaConstant), U8(216),
                B(Star), R(0),
  /* 2211 S> */ B(LdaConstant), U8(217),
                B(Star), R(0),
  /* 2221 S> */ B(LdaConstant), U8(218),
                B(Star), R(0),
  /* 2231 S> */ B(LdaConstant), U8(219),
                B(Star), R(0),
  /* 2241 S> */ B(LdaConstant), U8(220),
                B(Star), R(0),
  /* 2251 S> */ B(LdaConstant), U8(221),
                B(Star), R(0),
  /* 2261 S> */ B(LdaConstant), U8(222),
                B(Star), R(0),
  /* 2271 S> */ B(LdaConstant), U8(223),
                B(Star), R(0),
  /* 2281 S> */ B(LdaConstant), U8(224),
                B(Star), R(0),
  /* 2291 S> */ B(LdaConstant), U8(225),
                B(Star), R(0),
  /* 2301 S> */ B(LdaConstant), U8(226),
                B(Star), R(0),
  /* 2311 S> */ B(LdaConstant), U8(227),
                B(Star), R(0),
  /* 2321 S> */ B(LdaConstant), U8(228),
                B(Star), R(0),
  /* 2331 S> */ B(LdaConstant), U8(229),
                B(Star), R(0),
  /* 2341 S> */ B(LdaConstant), U8(230),
                B(Star), R(0),
  /* 2351 S> */ B(LdaConstant), U8(231),
                B(Star), R(0),
  /* 2361 S> */ B(LdaConstant), U8(232),
                B(Star), R(0),
  /* 2371 S> */ B(LdaConstant), U8(233),
                B(Star), R(0),
  /* 2381 S> */ B(LdaConstant), U8(234),
                B(Star), R(0),
  /* 2391 S> */ B(LdaConstant), U8(235),
                B(Star), R(0),
  /* 2401 S> */ B(LdaConstant), U8(236),
                B(Star), R(0),
  /* 2411 S> */ B(LdaConstant), U8(237),
                B(Star), R(0),
  /* 2421 S> */ B(LdaConstant), U8(238),
                B(Star), R(0),
  /* 2431 S> */ B(LdaConstant), U8(239),
                B(Star), R(0),
  /* 2441 S> */ B(LdaConstant), U8(240),
                B(Star), R(0),
  /* 2451 S> */ B(LdaConstant), U8(241),
                B(Star), R(0),
  /* 2461 S> */ B(LdaConstant), U8(242),
                B(Star), R(0),
  /* 2471 S> */ B(LdaConstant), U8(243),
                B(Star), R(0),
  /* 2481 S> */ B(LdaConstant), U8(244),
                B(Star), R(0),
  /* 2491 S> */ B(LdaConstant), U8(245),
                B(Star), R(0),
  /* 2501 S> */ B(LdaConstant), U8(246),
                B(Star), R(0),
  /* 2511 S> */ B(LdaConstant), U8(247),
                B(Star), R(0),
  /* 2521 S> */ B(LdaConstant), U8(248),
                B(Star), R(0),
  /* 2531 S> */ B(LdaConstant), U8(249),
                B(Star), R(0),
  /* 2541 S> */ B(LdaConstant), U8(250),
                B(Star), R(0),
  /* 2551 S> */ B(LdaConstant), U8(251),
                B(Star), R(0),
  /* 2561 S> */ B(LdaConstant), U8(252),
                B(Star), R(0),
  /* 2571 S> */ B(LdaConstant), U8(253),
                B(Star), R(0),
  /* 2581 S> */ B(LdaConstant), U8(254),
                B(Star), R(0),
  /* 2591 S> */ B(LdaConstant), U8(255),
                B(Star), R(0),
  /* 2601 S> */ B(Wide), B(CreateRegExpLiteral), U16(256), U16(4), U8(0),
  /* 2615 S> */ B(Return),
]
constant pool: [
  HEAP_NUMBER_TYPE [1.23],
  HEAP_NUMBER_TYPE [1.23],
  HEAP_NUMBER_TYPE [1.23],
  HEAP_NUMBER_TYPE [1.23],
  HEAP_NUMBER_TYPE [1.23],
  HEAP_NUMBER_TYPE [1.23],
  HEAP_NUMBER_TYPE [1.23],
  HEAP_NUMBER_TYPE [1.23],
  HEAP_NUMBER_TYPE [1.23],
  HEAP_NUMBER_TYPE [1.23],
  HEAP_NUMBER_TYPE [1.23],
  HEAP_NUMBER_TYPE [1.23],
  HEAP_NUMBER_TYPE [1.23],
  HEAP_NUMBER_TYPE [1.23],
  HEAP_NUMBER_TYPE [1.23],
  HEAP_NUMBER_TYPE [1.23],
  HEAP_NUMBER_TYPE [1.23],
  HEAP_NUMBER_TYPE [1.23],
  HEAP_NUMBER_TYPE [1.23],
  HEAP_NUMBER_TYPE [1.23],
  HEAP_NUMBER_TYPE [1.23],
  HEAP_NUMBER_TYPE [1.23],
  HEAP_NUMBER_TYPE [1.23],
  HEAP_NUMBER_TYPE [1.23],
  HEAP_NUMBER_TYPE [1.23],
  HEAP_NUMBER_TYPE [1.23],
  HEAP_NUMBER_TYPE [1.23],
  HEAP_NUMBER_TYPE [1.23],
  HEAP_NUMBER_TYPE [1.23],
  HEAP_NUMBER_TYPE [1.23],
  HEAP_NUMBER_TYPE [1.23],
  HEAP_NUMBER_TYPE [1.23],
  HEAP_NUMBER_TYPE [1.23],
  HEAP_NUMBER_TYPE [1.23],
  HEAP_NUMBER_TYPE [1.23],
  HEAP_NUMBER_TYPE [1.23],
  HEAP_NUMBER_TYPE [1.23],
  HEAP_NUMBER_TYPE [1.23],
  HEAP_NUMBER_TYPE [1.23],
  HEAP_NUMBER_TYPE [1.23],
  HEAP_NUMBER_TYPE [1.23],
  HEAP_NUMBER_TYPE [1.23],
  HEAP_NUMBER_TYPE [1.23],
  HEAP_NUMBER_TYPE [1.23],
  HEAP_NUMBER_TYPE [1.23],
  HEAP_NUMBER_TYPE [1.23],
  HEAP_NUMBER_TYPE [1.23],
  HEAP_NUMBER_TYPE [1.23],
  HEAP_NUMBER_TYPE [1.23],
  HEAP_NUMBER_TYPE [1.23],
  HEAP_NUMBER_TYPE [1.23],
  HEAP_NUMBER_TYPE [1.23],
  HEAP_NUMBER_TYPE [1.23],
  HEAP_NUMBER_TYPE [1.23],
  HEAP_NUMBER_TYPE [1.23],
  HEAP_NUMBER_TYPE [1.23],
  HEAP_NUMBER_TYPE [1.23],
  HEAP_NUMBER_TYPE [1.23],
  HEAP_NUMBER_TYPE [1.23],
  HEAP_NUMBER_TYPE [1.23],
  HEAP_NUMBER_TYPE [1.23],
  HEAP_NUMBER_TYPE [1.23],
  HEAP_NUMBER_TYPE [1.23],
  HEAP_NUMBER_TYPE [1.23],
  HEAP_NUMBER_TYPE [1.23],
  HEAP_NUMBER_TYPE [1.23],
  HEAP_NUMBER_TYPE [1.23],
  HEAP_NUMBER_TYPE [1.23],
  HEAP_NUMBER_TYPE [1.23],
  HEAP_NUMBER_TYPE [1.23],
  HEAP_NUMBER_TYPE [1.23],
  HEAP_NUMBER_TYPE [1.23],
  HEAP_NUMBER_TYPE [1.23],
  HEAP_NUMBER_TYPE [1.23],
  HEAP_NUMBER_TYPE [1.23],
  HEAP_NUMBER_TYPE [1.23],
  HEAP_NUMBER_TYPE [1.23],
  HEAP_NUMBER_TYPE [1.23],
  HEAP_NUMBER_TYPE [1.23],
  HEAP_NUMBER_TYPE [1.23],
  HEAP_NUMBER_TYPE [1.23],
  HEAP_NUMBER_TYPE [1.23],
  HEAP_NUMBER_TYPE [1.23],
  HEAP_NUMBER_TYPE [1.23],
  HEAP_NUMBER_TYPE [1.23],
  HEAP_NUMBER_TYPE [1.23],
  HEAP_NUMBER_TYPE [1.23],
  HEAP_NUMBER_TYPE [1.23],
  HEAP_NUMBER_TYPE [1.23],
  HEAP_NUMBER_TYPE [1.23],
  HEAP_NUMBER_TYPE [1.23],
  HEAP_NUMBER_TYPE [1.23],
  HEAP_NUMBER_TYPE [1.23],
  HEAP_NUMBER_TYPE [1.23],
  HEAP_NUMBER_TYPE [1.23],
  HEAP_NUMBER_TYPE [1.23],
  HEAP_NUMBER_TYPE [1.23],
  HEAP_NUMBER_TYPE [1.23],
  HEAP_NUMBER_TYPE [1.23],
  HEAP_NUMBER_TYPE [1.23],
  HEAP_NUMBER_TYPE [1.23],
  HEAP_NUMBER_TYPE [1.23],
  HEAP_NUMBER_TYPE [1.23],
  HEAP_NUMBER_TYPE [1.23],
  HEAP_NUMBER_TYPE [1.23],
  HEAP_NUMBER_TYPE [1.23],
  HEAP_NUMBER_TYPE [1.23],
  HEAP_NUMBER_TYPE [1.23],
  HEAP_NUMBER_TYPE [1.23],
  HEAP_NUMBER_TYPE [1.23],
  HEAP_NUMBER_TYPE [1.23],
  HEAP_NUMBER_TYPE [1.23],
  HEAP_NUMBER_TYPE [1.23],
  HEAP_NUMBER_TYPE [1.23],
  HEAP_NUMBER_TYPE [1.23],
  HEAP_NUMBER_TYPE [1.23],
  HEAP_NUMBER_TYPE [1.23],
  HEAP_NUMBER_TYPE [1.23],
  HEAP_NUMBER_TYPE [1.23],
  HEAP_NUMBER_TYPE [1.23],
  HEAP_NUMBER_TYPE [1.23],
  HEAP_NUMBER_TYPE [1.23],
  HEAP_NUMBER_TYPE [1.23],
  HEAP_NUMBER_TYPE [1.23],
  HEAP_NUMBER_TYPE [1.23],
  HEAP_NUMBER_TYPE [1.23],
  HEAP_NUMBER_TYPE [1.23],
  HEAP_NUMBER_TYPE [1.23],
  HEAP_NUMBER_TYPE [1.23],
  HEAP_NUMBER_TYPE [1.23],
  HEAP_NUMBER_TYPE [1.23],
  HEAP_NUMBER_TYPE [1.23],
  HEAP_NUMBER_TYPE [1.23],
  HEAP_NUMBER_TYPE [1.23],
  HEAP_NUMBER_TYPE [1.23],
  HEAP_NUMBER_TYPE [1.23],
  HEAP_NUMBER_TYPE [1.23],
  HEAP_NUMBER_TYPE [1.23],
  HEAP_NUMBER_TYPE [1.23],
  HEAP_NUMBER_TYPE [1.23],
  HEAP_NUMBER_TYPE [1.23],
  HEAP_NUMBER_TYPE [1.23],
  HEAP_NUMBER_TYPE [1.23],
  HEAP_NUMBER_TYPE [1.23],
  HEAP_NUMBER_TYPE [1.23],
  HEAP_NUMBER_TYPE [1.23],
  HEAP_NUMBER_TYPE [1.23],
  HEAP_NUMBER_TYPE [1.23],
  HEAP_NUMBER_TYPE [1.23],
  HEAP_NUMBER_TYPE [1.23],
  HEAP_NUMBER_TYPE [1.23],
  HEAP_NUMBER_TYPE [1.23],
  HEAP_NUMBER_TYPE [1.23],
  HEAP_NUMBER_TYPE [1.23],
  HEAP_NUMBER_TYPE [1.23],
  HEAP_NUMBER_TYPE [1.23],
  HEAP_NUMBER_TYPE [1.23],
  HEAP_NUMBER_TYPE [1.23],
  HEAP_NUMBER_TYPE [1.23],
  HEAP_NUMBER_TYPE [1.23],
  HEAP_NUMBER_TYPE [1.23],
  HEAP_NUMBER_TYPE [1.23],
  HEAP_NUMBER_TYPE [1.23],
  HEAP_NUMBER_TYPE [1.23],
  HEAP_NUMBER_TYPE [1.23],
  HEAP_NUMBER_TYPE [1.23],
  HEAP_NUMBER_TYPE [1.23],
  HEAP_NUMBER_TYPE [1.23],
  HEAP_NUMBER_TYPE [1.23],
  HEAP_NUMBER_TYPE [1.23],
  HEAP_NUMBER_TYPE [1.23],
  HEAP_NUMBER_TYPE [1.23],
  HEAP_NUMBER_TYPE [1.23],
  HEAP_NUMBER_TYPE [1.23],
  HEAP_NUMBER_TYPE [1.23],
  HEAP_NUMBER_TYPE [1.23],
  HEAP_NUMBER_TYPE [1.23],
  HEAP_NUMBER_TYPE [1.23],
  HEAP_NUMBER_TYPE [1.23],
  HEAP_NUMBER_TYPE [1.23],
  HEAP_NUMBER_TYPE [1.23],
  HEAP_NUMBER_TYPE [1.23],
  HEAP_NUMBER_TYPE [1.23],
  HEAP_NUMBER_TYPE [1.23],
  HEAP_NUMBER_TYPE [1.23],
  HEAP_NUMBER_TYPE [1.23],
  HEAP_NUMBER_TYPE [1.23],
  HEAP_NUMBER_TYPE [1.23],
  HEAP_NUMBER_TYPE [1.23],
  HEAP_NUMBER_TYPE [1.23],
  HEAP_NUMBER_TYPE [1.23],
  HEAP_NUMBER_TYPE [1.23],
  HEAP_NUMBER_TYPE [1.23],
  HEAP_NUMBER_TYPE [1.23],
  HEAP_NUMBER_TYPE [1.23],
  HEAP_NUMBER_TYPE [1.23],
  HEAP_NUMBER_TYPE [1.23],
  HEAP_NUMBER_TYPE [1.23],
  HEAP_NUMBER_TYPE [1.23],
  HEAP_NUMBER_TYPE [1.23],
  HEAP_NUMBER_TYPE [1.23],
  HEAP_NUMBER_TYPE [1.23],
  HEAP_NUMBER_TYPE [1.23],
  HEAP_NUMBER_TYPE [1.23],
  HEAP_NUMBER_TYPE [1.23],
  HEAP_NUMBER_TYPE [1.23],
  HEAP_NUMBER_TYPE [1.23],
  HEAP_NUMBER_TYPE [1.23],
  HEAP_NUMBER_TYPE [1.23],
  HEAP_NUMBER_TYPE [1.23],
  HEAP_NUMBER_TYPE [1.23],
  HEAP_NUMBER_TYPE [1.23],
  HEAP_NUMBER_TYPE [1.23],
  HEAP_NUMBER_TYPE [1.23],
  HEAP_NUMBER_TYPE [1.23],
  HEAP_NUMBER_TYPE [1.23],
  HEAP_NUMBER_TYPE [1.23],
  HEAP_NUMBER_TYPE [1.23],
  HEAP_NUMBER_TYPE [1.23],
  HEAP_NUMBER_TYPE [1.23],
  HEAP_NUMBER_TYPE [1.23],
  HEAP_NUMBER_TYPE [1.23],
  HEAP_NUMBER_TYPE [1.23],
  HEAP_NUMBER_TYPE [1.23],
  HEAP_NUMBER_TYPE [1.23],
  HEAP_NUMBER_TYPE [1.23],
  HEAP_NUMBER_TYPE [1.23],
  HEAP_NUMBER_TYPE [1.23],
  HEAP_NUMBER_TYPE [1.23],
  HEAP_NUMBER_TYPE [1.23],
  HEAP_NUMBER_TYPE [1.23],
  HEAP_NUMBER_TYPE [1.23],
  HEAP_NUMBER_TYPE [1.23],
  HEAP_NUMBER_TYPE [1.23],
  HEAP_NUMBER_TYPE [1.23],
  HEAP_NUMBER_TYPE [1.23],
  HEAP_NUMBER_TYPE [1.23],
  HEAP_NUMBER_TYPE [1.23],
  HEAP_NUMBER_TYPE [1.23],
  HEAP_NUMBER_TYPE [1.23],
  HEAP_NUMBER_TYPE [1.23],
  HEAP_NUMBER_TYPE [1.23],
  HEAP_NUMBER_TYPE [1.23],
  HEAP_NUMBER_TYPE [1.23],
  HEAP_NUMBER_TYPE [1.23],
  HEAP_NUMBER_TYPE [1.23],
  HEAP_NUMBER_TYPE [1.23],
  HEAP_NUMBER_TYPE [1.23],
  HEAP_NUMBER_TYPE [1.23],
  HEAP_NUMBER_TYPE [1.23],
  HEAP_NUMBER_TYPE [1.23],
  HEAP_NUMBER_TYPE [1.23],
  HEAP_NUMBER_TYPE [1.23],
  HEAP_NUMBER_TYPE [1.23],
  HEAP_NUMBER_TYPE [1.23],
  HEAP_NUMBER_TYPE [1.23],
  ONE_BYTE_INTERNALIZED_STRING_TYPE ["ab+d"],
]
handlers: [
]

