#
# Autogenerated by generate-bytecode-expectations.
#

---
wrap: no
test function name: f

---
snippet: "
  var a = 1;
  function f() { a = 2; }
  f();
"
frame size: 0
parameter count: 1
bytecode array length: 8
bytecodes: [
  /*   21 E> */ B(StackCheck),
  /*   26 S> */ B(LdaSmi), I8(2),
  /*   28 E> */ B(StaGlobalSloppy), U8(0), U8(4),
                B(LdaUndefined),
  /*   33 S> */ B(Return),
]
constant pool: [
  ONE_BYTE_INTERNALIZED_STRING_TYPE ["a"],
]
handlers: [
]

---
snippet: "
  var a = \"test\"; function f(b) { a = b; }
  f(\"global\");
"
frame size: 0
parameter count: 2
bytecode array length: 8
bytecodes: [
  /*   26 E> */ B(StackCheck),
  /*   32 S> */ B(Ldar), R(arg0),
  /*   34 E> */ B(StaGlobalSloppy), U8(0), U8(4),
                B(LdaUndefined),
  /*   39 S> */ B(Return),
]
constant pool: [
  ONE_BYTE_INTERNALIZED_STRING_TYPE ["a"],
]
handlers: [
]

---
snippet: "
  'use strict'; var a = 1;
  function f() { a = 2; }
  f();
"
frame size: 0
parameter count: 1
bytecode array length: 8
bytecodes: [
  /*   35 E> */ B(StackCheck),
  /*   40 S> */ B(LdaSmi), I8(2),
  /*   42 E> */ B(StaGlobalStrict), U8(0), U8(4),
                B(LdaUndefined),
  /*   47 S> */ B(Return),
]
constant pool: [
  ONE_BYTE_INTERNALIZED_STRING_TYPE ["a"],
]
handlers: [
]

---
snippet: "
  a = 1;
  function f() { a = 2; }
  f();
"
frame size: 0
parameter count: 1
bytecode array length: 8
bytecodes: [
  /*   17 E> */ B(StackCheck),
  /*   22 S> */ B(LdaSmi), I8(2),
  /*   24 E> */ B(StaGlobalSloppy), U8(0), U8(4),
                B(LdaUndefined),
  /*   29 S> */ B(Return),
]
constant pool: [
  ONE_BYTE_INTERNALIZED_STRING_TYPE ["a"],
]
handlers: [
]

---
snippet: "
  a = 1;
  function f(b) {
    b.name;
    b.name;
    b.name;
    b.name;
    b.name;
    b.name;
    b.name;
    b.name;
    b.name;
    b.name;
    b.name;
    b.name;
    b.name;
    b.name;
    b.name;
    b.name;
    b.name;
    b.name;
    b.name;
    b.name;
    b.name;
    b.name;
    b.name;
    b.name;
    b.name;
    b.name;
    b.name;
    b.name;
    b.name;
    b.name;
    b.name;
    b.name;
    b.name;
    b.name;
    b.name;
    b.name;
    b.name;
    b.name;
    b.name;
    b.name;
    b.name;
    b.name;
    b.name;
    b.name;
    b.name;
    b.name;
    b.name;
    b.name;
    b.name;
    b.name;
    b.name;
    b.name;
    b.name;
    b.name;
    b.name;
    b.name;
    b.name;
    b.name;
    b.name;
    b.name;
    b.name;
    b.name;
    b.name;
    b.name;
    b.name;
    b.name;
    b.name;
    b.name;
    b.name;
    b.name;
    b.name;
    b.name;
    b.name;
    b.name;
    b.name;
    b.name;
    b.name;
    b.name;
    b.name;
    b.name;
    b.name;
    b.name;
    b.name;
    b.name;
    b.name;
    b.name;
    b.name;
    b.name;
    b.name;
    b.name;
    b.name;
    b.name;
    b.name;
    b.name;
    b.name;
    b.name;
    b.name;
    b.name;
    b.name;
    b.name;
    b.name;
    b.name;
    b.name;
    b.name;
    b.name;
    b.name;
    b.name;
    b.name;
    b.name;
    b.name;
    b.name;
    b.name;
    b.name;
    b.name;
    b.name;
    b.name;
    b.name;
    b.name;
    b.name;
    b.name;
    b.name;
    b.name;
    b.name;
    b.name;
    b.name;
    b.name;
    b.name;
    b.name;
    a = 2;
  }
  f({name: 1});
"
frame size: 0
parameter count: 2
bytecode array length: 531
bytecodes: [
  /*   17 E> */ B(StackCheck),
  /*   27 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(4),
  /*   37 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(6),
  /*   47 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(8),
  /*   57 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(10),
  /*   67 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(12),
  /*   77 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(14),
  /*   87 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(16),
  /*   97 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(18),
  /*  107 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(20),
  /*  117 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(22),
  /*  127 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(24),
  /*  137 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(26),
  /*  147 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(28),
  /*  157 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(30),
  /*  167 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(32),
  /*  177 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(34),
  /*  187 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(36),
  /*  197 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(38),
  /*  207 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(40),
  /*  217 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(42),
  /*  227 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(44),
  /*  237 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(46),
  /*  247 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(48),
  /*  257 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(50),
  /*  267 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(52),
  /*  277 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(54),
  /*  287 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(56),
  /*  297 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(58),
  /*  307 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(60),
  /*  317 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(62),
  /*  327 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(64),
  /*  337 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(66),
  /*  347 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(68),
  /*  357 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(70),
  /*  367 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(72),
  /*  377 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(74),
  /*  387 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(76),
  /*  397 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(78),
  /*  407 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(80),
  /*  417 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(82),
  /*  427 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(84),
  /*  437 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(86),
  /*  447 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(88),
  /*  457 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(90),
  /*  467 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(92),
  /*  477 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(94),
  /*  487 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(96),
  /*  497 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(98),
  /*  507 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(100),
  /*  517 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(102),
  /*  527 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(104),
  /*  537 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(106),
  /*  547 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(108),
  /*  557 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(110),
  /*  567 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(112),
  /*  577 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(114),
  /*  587 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(116),
  /*  597 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(118),
  /*  607 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(120),
  /*  617 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(122),
  /*  627 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(124),
  /*  637 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(126),
  /*  647 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(128),
  /*  657 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(130),
  /*  667 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(132),
  /*  677 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(134),
  /*  687 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(136),
  /*  697 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(138),
  /*  707 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(140),
  /*  717 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(142),
  /*  727 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(144),
  /*  737 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(146),
  /*  747 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(148),
  /*  757 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(150),
  /*  767 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(152),
  /*  777 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(154),
  /*  787 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(156),
  /*  797 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(158),
  /*  807 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(160),
  /*  817 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(162),
  /*  827 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(164),
  /*  837 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(166),
  /*  847 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(168),
  /*  857 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(170),
  /*  867 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(172),
  /*  877 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(174),
  /*  887 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(176),
  /*  897 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(178),
  /*  907 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(180),
  /*  917 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(182),
  /*  927 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(184),
  /*  937 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(186),
  /*  947 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(188),
  /*  957 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(190),
  /*  967 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(192),
  /*  977 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(194),
  /*  987 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(196),
  /*  997 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(198),
  /* 1007 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(200),
  /* 1017 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(202),
  /* 1027 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(204),
  /* 1037 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(206),
  /* 1047 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(208),
  /* 1057 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(210),
  /* 1067 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(212),
  /* 1077 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(214),
  /* 1087 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(216),
  /* 1097 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(218),
  /* 1107 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(220),
  /* 1117 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(222),
  /* 1127 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(224),
  /* 1137 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(226),
  /* 1147 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(228),
  /* 1157 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(230),
  /* 1167 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(232),
  /* 1177 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(234),
  /* 1187 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(236),
  /* 1197 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(238),
  /* 1207 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(240),
  /* 1217 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(242),
  /* 1227 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(244),
  /* 1237 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(246),
  /* 1247 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(248),
  /* 1257 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(250),
  /* 1267 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(252),
  /* 1277 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(254),
  /* 1287 S> */ B(Wide), B(LdaNamedProperty), R16(arg0), U16(0), U16(256),
  /* 1297 S> */ B(Wide), B(LdaNamedProperty), R16(arg0), U16(0), U16(258),
  /* 1305 S> */ B(LdaSmi), I8(2),
  /* 1307 E> */ B(Wide), B(StaGlobalSloppy), U16(1), U16(260),
                B(LdaUndefined),
  /* 1312 S> */ B(Return),
]
constant pool: [
  ONE_BYTE_INTERNALIZED_STRING_TYPE ["name"],
  ONE_BYTE_INTERNALIZED_STRING_TYPE ["a"],
]
handlers: [
]

---
snippet: "
  a = 1;
  function f(b) {
    'use strict';
    b.name;
    b.name;
    b.name;
    b.name;
    b.name;
    b.name;
    b.name;
    b.name;
    b.name;
    b.name;
    b.name;
    b.name;
    b.name;
    b.name;
    b.name;
    b.name;
    b.name;
    b.name;
    b.name;
    b.name;
    b.name;
    b.name;
    b.name;
    b.name;
    b.name;
    b.name;
    b.name;
    b.name;
    b.name;
    b.name;
    b.name;
    b.name;
    b.name;
    b.name;
    b.name;
    b.name;
    b.name;
    b.name;
    b.name;
    b.name;
    b.name;
    b.name;
    b.name;
    b.name;
    b.name;
    b.name;
    b.name;
    b.name;
    b.name;
    b.name;
    b.name;
    b.name;
    b.name;
    b.name;
    b.name;
    b.name;
    b.name;
    b.name;
    b.name;
    b.name;
    b.name;
    b.name;
    b.name;
    b.name;
    b.name;
    b.name;
    b.name;
    b.name;
    b.name;
    b.name;
    b.name;
    b.name;
    b.name;
    b.name;
    b.name;
    b.name;
    b.name;
    b.name;
    b.name;
    b.name;
    b.name;
    b.name;
    b.name;
    b.name;
    b.name;
    b.name;
    b.name;
    b.name;
    b.name;
    b.name;
    b.name;
    b.name;
    b.name;
    b.name;
    b.name;
    b.name;
    b.name;
    b.name;
    b.name;
    b.name;
    b.name;
    b.name;
    b.name;
    b.name;
    b.name;
    b.name;
    b.name;
    b.name;
    b.name;
    b.name;
    b.name;
    b.name;
    b.name;
    b.name;
    b.name;
    b.name;
    b.name;
    b.name;
    b.name;
    b.name;
    b.name;
    b.name;
    b.name;
    b.name;
    b.name;
    b.name;
    b.name;
    b.name;
    a = 2;
  }
  f({name: 1});
"
frame size: 0
parameter count: 2
bytecode array length: 531
bytecodes: [
  /*   17 E> */ B(StackCheck),
  /*   43 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(4),
  /*   53 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(6),
  /*   63 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(8),
  /*   73 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(10),
  /*   83 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(12),
  /*   93 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(14),
  /*  103 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(16),
  /*  113 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(18),
  /*  123 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(20),
  /*  133 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(22),
  /*  143 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(24),
  /*  153 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(26),
  /*  163 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(28),
  /*  173 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(30),
  /*  183 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(32),
  /*  193 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(34),
  /*  203 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(36),
  /*  213 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(38),
  /*  223 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(40),
  /*  233 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(42),
  /*  243 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(44),
  /*  253 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(46),
  /*  263 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(48),
  /*  273 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(50),
  /*  283 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(52),
  /*  293 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(54),
  /*  303 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(56),
  /*  313 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(58),
  /*  323 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(60),
  /*  333 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(62),
  /*  343 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(64),
  /*  353 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(66),
  /*  363 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(68),
  /*  373 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(70),
  /*  383 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(72),
  /*  393 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(74),
  /*  403 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(76),
  /*  413 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(78),
  /*  423 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(80),
  /*  433 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(82),
  /*  443 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(84),
  /*  453 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(86),
  /*  463 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(88),
  /*  473 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(90),
  /*  483 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(92),
  /*  493 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(94),
  /*  503 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(96),
  /*  513 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(98),
  /*  523 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(100),
  /*  533 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(102),
  /*  543 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(104),
  /*  553 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(106),
  /*  563 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(108),
  /*  573 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(110),
  /*  583 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(112),
  /*  593 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(114),
  /*  603 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(116),
  /*  613 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(118),
  /*  623 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(120),
  /*  633 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(122),
  /*  643 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(124),
  /*  653 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(126),
  /*  663 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(128),
  /*  673 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(130),
  /*  683 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(132),
  /*  693 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(134),
  /*  703 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(136),
  /*  713 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(138),
  /*  723 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(140),
  /*  733 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(142),
  /*  743 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(144),
  /*  753 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(146),
  /*  763 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(148),
  /*  773 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(150),
  /*  783 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(152),
  /*  793 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(154),
  /*  803 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(156),
  /*  813 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(158),
  /*  823 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(160),
  /*  833 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(162),
  /*  843 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(164),
  /*  853 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(166),
  /*  863 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(168),
  /*  873 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(170),
  /*  883 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(172),
  /*  893 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(174),
  /*  903 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(176),
  /*  913 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(178),
  /*  923 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(180),
  /*  933 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(182),
  /*  943 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(184),
  /*  953 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(186),
  /*  963 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(188),
  /*  973 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(190),
  /*  983 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(192),
  /*  993 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(194),
  /* 1003 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(196),
  /* 1013 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(198),
  /* 1023 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(200),
  /* 1033 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(202),
  /* 1043 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(204),
  /* 1053 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(206),
  /* 1063 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(208),
  /* 1073 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(210),
  /* 1083 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(212),
  /* 1093 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(214),
  /* 1103 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(216),
  /* 1113 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(218),
  /* 1123 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(220),
  /* 1133 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(222),
  /* 1143 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(224),
  /* 1153 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(226),
  /* 1163 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(228),
  /* 1173 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(230),
  /* 1183 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(232),
  /* 1193 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(234),
  /* 1203 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(236),
  /* 1213 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(238),
  /* 1223 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(240),
  /* 1233 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(242),
  /* 1243 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(244),
  /* 1253 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(246),
  /* 1263 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(248),
  /* 1273 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(250),
  /* 1283 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(252),
  /* 1293 S> */ B(LdaNamedProperty), R(arg0), U8(0), U8(254),
  /* 1303 S> */ B(Wide), B(LdaNamedProperty), R16(arg0), U16(0), U16(256),
  /* 1313 S> */ B(Wide), B(LdaNamedProperty), R16(arg0), U16(0), U16(258),
  /* 1321 S> */ B(LdaSmi), I8(2),
  /* 1323 E> */ B(Wide), B(StaGlobalStrict), U16(1), U16(260),
                B(LdaUndefined),
  /* 1328 S> */ B(Return),
]
constant pool: [
  ONE_BYTE_INTERNALIZED_STRING_TYPE ["name"],
  ONE_BYTE_INTERNALIZED_STRING_TYPE ["a"],
]
handlers: [
]

