#
# Autogenerated by generate-bytecode-expectations.
#

---
wrap: yes

---
snippet: "
  try { return 1; } catch(e) { return 2; }
"
frame size: 2
parameter count: 1
bytecode array length: 28
bytecodes: [
  /*   30 E> */ B(StackCheck),
                B(Mov), R(context), R(0),
  /*   40 S> */ B(LdaSmi), I8(1),
  /*   49 S> */ B(Return),
                B(Jump), U8(19),
                B(Star), R(1),
                B(CreateCatchContext), R(1), U8(0), U8(1),
                B(Star), R(0),
                B(LdaTheHole),
                B(SetPendingMessage),
                B(Ldar), R(0),
                B(PushContext), R(1),
  /*   63 S> */ B(LdaSmi), I8(2),
  /*   72 S> */ B(Return),
                B(LdaUndefined),
  /*   75 S> */ B(Return),
]
constant pool: [
  ONE_BYTE_INTERNALIZED_STRING_TYPE ["e"],
  SCOPE_INFO_TYPE,
]
handlers: [
  [4, 7, 9],
]

---
snippet: "
  var a;
  try { a = 1 } catch(e1) {};
  try { a = 2 } catch(e2) { a = 3 }
"
frame size: 3
parameter count: 1
bytecode array length: 57
bytecodes: [
  /*   30 E> */ B(StackCheck),
                B(Mov), R(context), R(1),
  /*   47 S> */ B(LdaSmi), I8(1),
                B(Star), R(0),
                B(Jump), U8(18),
                B(Star), R(2),
  /*   49 E> */ B(CreateCatchContext), R(2), U8(0), U8(1),
                B(Star), R(1),
                B(LdaTheHole),
                B(SetPendingMessage),
                B(Ldar), R(1),
                B(PushContext), R(2),
                B(PopContext), R(2),
                B(Mov), R(context), R(1),
  /*   75 S> */ B(LdaSmi), I8(2),
                B(Star), R(0),
                B(Jump), U8(22),
                B(Star), R(2),
  /*   77 E> */ B(CreateCatchContext), R(2), U8(2), U8(3),
                B(Star), R(1),
                B(LdaTheHole),
                B(SetPendingMessage),
                B(Ldar), R(1),
                B(PushContext), R(2),
  /*   95 S> */ B(LdaSmi), I8(3),
                B(Star), R(0),
                B(PopContext), R(2),
                B(LdaUndefined),
  /*  103 S> */ B(Return),
]
constant pool: [
  ONE_BYTE_INTERNALIZED_STRING_TYPE ["e1"],
  SCOPE_INFO_TYPE,
  ONE_BYTE_INTERNALIZED_STRING_TYPE ["e2"],
  SCOPE_INFO_TYPE,
]
handlers: [
  [4, 8, 10],
  [29, 33, 35],
]

