// Copyright 2014 the V8 project authors. All rights reserved.
// AUTO-GENERATED BY tools/generate-runtime-tests.py, DO NOT MODIFY
// Flags: --allow-natives-syntax --harmony
var _object = new Object();
var arg1 = 10;
var _value = new Object();
var _unchecked_attributes = 1;
%AddPropertyForTemplate(_object, arg1, _value, _unchecked_attributes);
