// Copyright 2014 the V8 project authors. All rights reserved.
// AUTO-GENERATED BY tools/generate-runtime-tests.py, DO NOT MODIFY
// Flags: --allow-natives-syntax --harmony
var _error_object = new Object();
var _caller = new Object();
var _limit = 32;
%CollectStackTrace(_error_object, _caller, _limit);
