// Copyright 2014 the V8 project authors. All rights reserved.
// AUTO-GENERATED BY tools/generate-runtime-tests.py, DO NOT MODIFY
// Flags: --allow-natives-syntax --harmony
var _object = new Object();
var _name = "name";
var _value = new Object();
var _unchecked_value = 1;
%IgnoreAttributesAndSetProperty(_object, _name, _value, _unchecked_value);
