// Copyright 2014 the V8 project authors. All rights reserved.
// AUTO-GENERATED BY tools/generate-runtime-tests.py, DO NOT MODIFY
// Flags: --allow-natives-syntax --harmony
var _shared_array = new Array();
var _position_change_array = new Array();
try {
%LiveEditPatchFunctionPositions(_shared_array, _position_change_array);
} catch(e) {}
