// Copyright 2014 the V8 project authors. All rights reserved.
// AUTO-GENERATED BY tools/generate-runtime-tests.py, DO NOT MODIFY
// Flags: --allow-natives-syntax --harmony
var _new_compile_info = new Array();
var _shared_info = new Array();
try {
%LiveEditReplaceFunctionCode(_new_compile_info, _shared_info);
} catch(e) {}
