// Copyright 2014 the V8 project authors. All rights reserved.
// AUTO-GENERATED BY tools/generate-runtime-tests.py, DO NOT MODIFY
// Flags: --allow-natives-syntax --harmony
var _object_info = new Object();
var _change_type = "foo";
var _change_fn = function() {};
%ObjectNotifierPerformChangeInObjectContext(_object_info, _change_type, _change_fn);
