// Copyright 2014 the V8 project authors. All rights reserved.
// AUTO-GENERATED BY tools/generate-runtime-tests.py, DO NOT MODIFY
// Flags: --allow-natives-syntax --harmony
var _func = function() {};
var _num = 1;
%SetExpectedNumberOfProperties(_func, _num);
