// Copyright 2014 the V8 project authors. All rights reserved.
// AUTO-GENERATED BY tools/generate-runtime-tests.py, DO NOT MODIFY
// Flags: --allow-natives-syntax --harmony
var _object = new Object();
var _key = new Object();
var _value = new Object();
var _unchecked_attributes = 1;
var _strict_mode_arg = 1;
%SetProperty(_object, _key, _value, _unchecked_attributes, _strict_mode_arg);
