// Copyright 2014 the V8 project authors. All rights reserved.
// AUTO-GENERATED BY tools/generate-runtime-tests.py, DO NOT MODIFY
// Flags: --allow-natives-syntax --harmony
var _weak_collection = new WeakMap();
var _key = new Object();
%WeakCollectionHas(_weak_collection, _key);
