#!/bin/sh

tools_dir=$(dirname "$0")
d8_exec=$tools_dir/../d8

# compile d8 if it doesn't exist.
if [ ! -x $d8_exec ]
then
  scons -C $tools_dir/.. d8
fi

# nm spits out 'no symbols found' messages to stderr.
$d8_exec $tools_dir/splaytree.js $tools_dir/codemap.js \
  $tools_dir/csvparser.js $tools_dir/consarray.js \
  $tools_dir/profile.js $tools_dir/profile_view.js \
  $tools_dir/tickprocessor.js -- $@ 2>/dev/null
